### ISSUE TITLE
Trying to set NPC type to donkey

### ISSUE THREAD

**Issue by ABUDoctor** [CitizensDev/Citizens2#1004]
When i try to set an NPC to a donkey it deletes the NPC entity and error to console

```
[15:28:18] [Server thread/INFO]: ABUDoctor issued server command: /npc type donkey
[15:28:18] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[15:28:18] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:28:18] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:42)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.MobEntityController.createEntity(MobEntityController.java:27)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.HorseDonkeyController.spawn(HorseDonkeyController.java:41)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:196)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.setEntityController(CitizensNPC.java:174)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:161)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:1842)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[15:28:18] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:28:18] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:28:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:28:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[15:28:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[15:28:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:28:18] [Server thread/WARN]: Caused by: java.lang.ClassCastException: net.citizensnpcs.nms.v1_11_R1.entity.HorseDonkeyController$HorseDonkeyNPC cannot be cast to org.bukkit.entity.Horse
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.HorseDonkeyController$EntityHorseDonkeyNPC.<init>(HorseDonkeyController.java:56)
[15:28:18] [Server thread/WARN]: 	... 36 more
[15:28:18] [Server thread/WARN]: java.lang.NullPointerException
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.MobEntityController.createEntity(MobEntityController.java:29)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.HorseDonkeyController.spawn(HorseDonkeyController.java:41)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:196)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.setEntityController(CitizensNPC.java:174)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:161)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:1842)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[15:28:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[15:28:18] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[15:28:18] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:28:18] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:28:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:28:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[15:28:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[15:28:18] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[15:28:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fullwall** [comment]
Fixed
