### ISSUE TITLE
Npc skin weird crash

### ISSUE THREAD

**Issue by Wardraft** [CitizensDev/Citizens2#1009]
Hi, I got a weird issue on my server. When I  /reload, npc's duplicate and then the server crashes with this log report : 

`[18:20:52] [Server thread/ERROR]: Encountered an unexpected exception
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:106) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.citizensnpcs.npc.skin.SkinPacketTracker.scheduleRemovePacket(SkinPacketTracker.java:146) ~[?:?]
	at net.citizensnpcs.npc.skin.SkinPacketTracker.scheduleRemovePacket(SkinPacketTracker.java:161) ~[?:?]
	at net.citizensnpcs.npc.skin.SkinPacketTracker.updateViewer(SkinPacketTracker.java:221) ~[?:?]
	at net.citizensnpcs.nms.v1_10_R1.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:41) ~[?:?]
	at net.minecraft.server.v1_10_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:77) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.EntityTracker.updatePlayers(EntityTracker.java:178) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:816) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

I'm using Spigot for Minecraft 1.10.2 and the latest version of Citizen.
What could cause that ?

**Comment by mcmonkey4eva** [comment]
Don't EVER `/reload`!

**Comment by fullwall** [comment]
Fixed
