### ISSUE TITLE
Invalid Plugin.YML

### ISSUE THREAD

**Issue by Arctomium** [CitizensDev/Citizens2#1012]
I'm running the lastest Spigot 1.11 build and I even tried it with the last Spigot 1.10. When I try running the lastest Citizens 2 build I get this error:
```
[21:46:43] [Server thread/ERROR]: Could not load 'plugins\citizens-2.0.21-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-f950f8e-eb6c1bf]
	... 5 more
```

**Comment by mcmonkey4eva** [comment]
Corrupted .jar file, redownload - potentially from an alternate service (DBO, Spigot, Jenkins, ...) if you get consistent trouble from the same download.

**Comment by Arctomium** [comment]
I downloaded it straight from the Citizens Jenkins site.

**Comment by mcmonkey4eva** [comment]
Check your network functionality, try Spigot as a source, ...?
The Citizens2 file on the Jenkins page is not inherently corrupted, it's something on your end.

**Comment by Arctomium** [comment]
I've just built a brand new Spigot build and redownloaded the plugin from http://ci.citizensnpcs.co/job/Citizens2/ and I still get the same error.

**Comment by mcmonkey4eva** [comment]
When I say use an alternate source I mean use https://www.spigotmc.org/resources/citizens.13811/ or https://dev.bukkit.org/projects/citizens
If that doesn't work either, your connection has an error preventing you from downloading .jar files correctly.

**Comment by Arctomium** [comment]
The Bukkit one work perfectly, cheers.
