### ISSUE TITLE
1.11.1 & 1.11.2 support : ERRORS

### ISSUE THREAD

**Issue by TheIntelloBox** [CitizensDev/Citizens2#1018]
[22:31:00] [Server thread/WARN]: [Citizens] Task #457 for Citizens v2.0.21-SNAPSHOT (build 1426) generated an exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking player
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:881) ~[?:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:253) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.1.jar:git-Spigot-9deaa4c-8ea0c87]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_11_R1.World.g(Lnet/minecraft/server/v1_11_R1/Entity;)V
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:875) ~[?:?]
	... 9 more

I'm using the latest Spigot jar.

**Comment by AmazedMender16** [comment]
Same issue! please add support 1.11.1

**Comment by lucasordovas** [comment]
same here! 1.11.2 console spam

**Comment by AmazedMender16** [comment]
update to the latest version they updated! its fixed!
http://ci.citizensnpcs.co/job/Citizens2/1461/
this fixes it!
