### ISSUE TITLE
Citizens not creating

### ISSUE THREAD

**Issue by superkid6676** [CitizensDev/Citizens2#1020]
The citizens are not creating.

Here is the error

11:30:52 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[11:30:52 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[11:30:52 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[11:30:52 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[11:30:52 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
[11:30:52 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:30:52 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:30:52 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:30:52 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:30:52 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[11:30:52 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[11:30:52 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[11:30:52 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[11:30:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:30:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:30:52 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[11:30:52 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:30:52 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[11:30:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[11:30:52 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:30:52 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[11:30:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[11:30:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[11:30:52 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[11:30:52 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[11:30:52 WARN]:        ... 28 more
[11:31:02 INFO]: ghToxic issued server command: /npc create UHC uhc
[11:31:02 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[11:31:02 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[11:31:02 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[11:31:02 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[11:31:02 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
[11:31:02 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:31:02 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:31:02 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:31:02 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:31:02 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[11:31:02 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[11:31:02 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[11:31:02 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[11:31:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:31:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:31:02 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[11:31:02 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:31:02 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[11:31:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[11:31:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:31:02 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[11:31:02 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[11:31:02 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[11:31:02 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[11:31:02 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[11:31:02 WARN]:        ... 28 more

**Comment by Morphan1** [comment]
You're using a Citizens build for 1.8, but running a (most likely) 1.8.8 server.
Get the correct build from here https://wiki.citizensnpcs.co/Versions
