### ISSUE TITLE
/npc list 0 causes IndexOutOfBoundsException

### ISSUE THREAD

**Issue by javacraft** [CitizensDev/Citizens2#1024]
Type: Bug
Versions: Spigot 1.11.2 & Citizens 2.0.21
With a virgin install of Citizens and no NPC created

`/npc list`  & `/npc list 1` both return an empty list (i.e. ====[ NPC 0/1 ]=====)
`/npc list 2` returns The page {0} does not exist.
`/npc list -1` returns The page {0} does not exist.
`/npc list 0` results in IndexOutOfBoundException as shown below.

The conditional on net.citizensnpcs.api.util.Paginator:23 should read
   `( page <= 0 || page > pages )` instead of  `( page < 0 || page > pages )`

[04:05:15 WARN]: java.lang.IndexOutOfBoundsException: fromIndex = -9
[04:05:15 WARN]:        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1002)
[04:05:15 WARN]:        at java.util.ArrayList.subList(ArrayList.java:996)
[04:05:15 WARN]:        at net.citizensnpcs.api.util.Paginator.sendPage(Paginator.java:33)
[04:05:15 WARN]:        at net.citizensnpcs.commands.NPCCommands.list(NPCCommands.java:814)
[04:05:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:05:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:05:15 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:05:15 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[04:05:15 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[04:05:15 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[04:05:15 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[04:05:15 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[04:05:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)

**Comment by mcmonkey4eva** [comment]
Ah, the delightful error messages produced by Citizens when you type silly things...
