### ISSUE TITLE
citizens-2.0.21 can't load in spigot-1.11.2.jar

### ISSUE THREAD

**Issue by wadang** [CitizensDev/Citizens2#1028]
[15:42:28 INFO]: Starting Minecraft server on *:25565
[15:42:28 INFO]: Using default channel type
[15:42:28 ERROR]: Could not load 'plugins/citizens-2.0.21-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-7d78b81-f9e0440]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-7d78b81-f9e0440]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot.jar:git-Spigot-7d78b81-f9e0440]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-7d78b81-f9e0440]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot.jar:git-Spigot-7d78b81-f9e0440]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_112]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_112]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_112]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_112]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-7d78b81-f9e0440]
	... 5 more
[15:42:28 INFO]: Set PluginClassLoader as parallel capable
[15:42:28 ERROR]: ebean.properties not found

**Comment by mcmonkey4eva** [comment]
You have an error in your downloaded file, IE something was corrupted in the download process. Redownload, ideally from http://ci.citizensnpcs.co/job/Citizens2/
be careful when downloading, in case your OS mistakes the jar file for EG a zip file and mishandles it.

**Comment by wadang** [comment]
You're right, it is the file I downloaded is incomplete. Very emotional for your help.

**Comment by fullwall** [comment]
Where did you get the file from?
