### ISSUE TITLE
Client Crash with Humans npc types

### ISSUE THREAD

**Issue by tutur1004** [CitizensDev/Citizens2#1034]
Clients crash with npc player types.
https://cdn.discordapp.com/attachments/265480410186776577/265480527979610112/Capture.PNG

```
java.lang.NullPointerException
>       at com.pie.tlatoani.Tablist.TabListManager$1.onPacketSending(TabListManager.java:77) ~[MundoSK.jar:?]
>       at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.1.0-b325]
>       at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.1.0-b325]
>       at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:194) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.PlayerConnection.sendPacket(PlayerConnection.java:1097) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.citizensnpcs.nms.v1_10_R1.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:45) [citizens-2.0.21-SNAPSHOT.jar:?]
>       at net.minecraft.server.v1_10_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:77) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.EntityTracker.updatePlayers(EntityTracker.java:178) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:816) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:03:44 ERROR]: Parameters:
  net.minecraft.server.v1_10_R1.PacketPlayOutNamedEntitySpawn@37ebb885[
    a=34757
    b=14582172-c616-281c-a458-139229b9bd5b
    c=4.5826280463783435
    d=68.0
    e=288.06242991008867
    f=-21
    g=0
    h=net.minecraft.server.v1_10_R1.DataWatcher@2b72f5a
    i=<null>
  ]
>
[15:03:44 INFO]: tutur1004 lost connection: Disconnected
[15:03:44 INFO]: tutur1004 left the game

```

Citizens config = base config

Mc Version
```
>about
[15:02:39 INFO]: This server is running CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
>about Citizens
[15:02:42 INFO]: Citizens version 2.0.21-SNAPSHOT (build 1464)
```

**Comment by tutur1004** [comment]
I try to update protocolLib in 4.2.0 and same error :
```
java.lang.NullPointerException
>       at com.pie.tlatoani.Tablist.TabListManager$1.onPacketSending(TabListManager.java:77) ~[MundoSK.jar:?]
>       at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.0]
>       at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.0]
>       at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:194) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.PlayerConnection.sendPacket(PlayerConnection.java:1097) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:344) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.citizensnpcs.nms.v1_10_R1.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:45) [citizens-2.0.21-SNAPSHOT.jar:?]
>       at net.minecraft.server.v1_10_R1.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:441) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:77) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.EntityTracker.updatePlayers(EntityTracker.java:178) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:816) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:10:49 ERROR]: Parameters:
  net.minecraft.server.v1_10_R1.PacketPlayOutNamedEntitySpawn@2324d444[
    a=560
    b=14582172-c616-281c-a458-139229b9bd5b
    c=4.5826
    d=68.0
    e=288.0624
    f=-21
    g=0
    h=net.minecraft.server.v1_10_R1.DataWatcher@45ddb993
    i=<null>
  ]

```

**Comment by fullwall** [comment]
Can you upload the 'MundoSK' jar where the error is happening?

**Comment by tutur1004** [comment]
Yeap

**Comment by tutur1004** [comment]
http://mundosk.github.io/

**Comment by tutur1004** [comment]
Solved by using new version of MundoSk.

thank fullwall !
