### ISSUE TITLE
Ghost NPC spawned

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1042]
Environment: Spigot 1.11.2 latest, Citizens 2.0.21-b1465, Sentinel 1.0-b90, and a full range of up-to-date plugins, including WE/WG, PEX, MV, PWI, etc. Plugin list available on request.

I have four dog sentinels. They work great, chasing down and removing hostiles from a Factions safezone. However, when I restart the server (but not on **/citizens reload**) I get an ghost dog entity, located on the same spot as the fourth sentinel. The conviction that it is caused by Citizens is that if I change the Citizens type, I get an ghost entity of the new type. It is not a sentinel -- it doesn't chase zombies, for example -- and is not shown by **/npc list** nor in _Citizens/saves.yml_. No indication in the log that anything is amiss. If I push the ghost wolf sufficiently far from the NPCs, and kill it, the NPC with which it was co-located also dies, even though it is outside the kill range. So they are related somehow.

<blockquote><pre>
# Citizens Configuration
npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 4
      max-text-range: 50
    format:
      no-targets: '<npc> says: <text>'
      with-target-to-bystanders: <npc> says <text>
      to-target: '<npc> says: <text>'
      with-targets-to-bystanders: '<npc> says: <text>'
  pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  default:
    look-close:
      enabled: true
      range: 5
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: You <b>selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 3
    min-talk-cooldown: 3
    talk-item: '340'
  controllable:
    use-boat-controls: true
  teleport-delay: -1
  player-scoreboard-teams:
    enable: true
advanced:
  check-minecraft-version: true
general:
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
  debug-file: ''
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
</pre></blockquote>

Relevant portion of _Citizens/save.yml_
<blockquote><pre>
  '4':
    name: Butch
    uuid: 655b05fd-05ca-45ba-bc67-9b710b57d26d
    traits:
      spawned: true
      location:
        world: world
        x: '-87.1966'
        y: '69.0'
        z: '221.5714'
        yaw: '83.67118835449219'
        pitch: '0.0'
      type: WOLF
      lookclose:
        enabled: true
        range: '5.0'
        realisticlooking: false
      waypoints:
        linear:
          points:
            '0':
              location:
                world: world
                x: '-86.5'
                y: '69.0'
                z: '221.5'
                yaw: '-90.0'
                pitch: '0.0'
        provider: linear
      sentinel:
        stats_ticksSpawned: 22447061
        stats_timesSpawned: 1564
        stats_arrowsFired: 0
        stats_potionsThrow: 0
        stats_fireballsFired: 0
        stats_punches: 103
        stats_attackAttempts: 577
        stats_damageTaken: 7.497600088119507
        stats_damageGiven: 146.76800000667572
        range: 20.0
        damage: -1.0
        armor: -1.0
        health: 20.0
        ranged_chase: false
        close_chase: true
        invincible: false
        fightback: true
        attackRate: 30
        healRate: 30
        guardingUpper: 0
        guardingLower: 0
        needsAmmo: false
        safeShot: true
        respawnTime: 100
        chaseRange: 100.0
        enemyDrops: false
        enemyTargetTime: 0
        stats_snowballsThrown: 0
        stats_eggsThrown: 0
        stats_skullsThrown: 0
        stats_pearlsUsed: 0
        attackRateRanged: 30
        speed: 2.0
        greet_range: 10.0
        autoswitch: false
        accuracy: 0.0
        targets:
          '0': MONSTERS
        ignores:
          '0': OWNER
          '1': PLAYERS
      wolfmodifiers:
        angry: false
        collarColor: RED
        sitting: false
        tamed: true
      age:
        age: 0
        locked: true
      owner:
        owner: rambeau
        uuid: OBSCURED
    traitnames: type,owner,lookclose,age,sentinel,waypoints,wolfmodifiers,spawned,mounttrait,location,equipment
    navigator:
      stationaryticks: 100
      speedmodifier: '2.0'
      avoidwater: true
      usedefaultstuckaction: false
      pathfindingrange: '100.0'
    metadata:
      protected: false
</pre></blockquote>

**Comment by SlimeDog** [comment]
Any ideas?

**Comment by SlimeDog** [comment]
Sometimes when I kill the two entities, I get null pointer exception. Might be helpful.

> [12:33:51 ERROR]: Could not pass event EntityDeathEvent to Citizens v2.0.21-SNAPSHOT (build 1469)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityTameableAnimal.die(SourceFile:204) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityWolf.damageEntity(EntityWolf.java:232) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.EntityLiving.Q(EntityLiving.java:127) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.CommandKill.execute(SourceFile:41) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:94) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:38) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:581) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:38) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:581) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at ch.njol.skript.Skript.dispatchCommand(Skript.java:1081) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:54) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.command.Commands.handleCommand(Commands.java:270) [Skript-2.2-dev23.jar:?]
        at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) [Skript-2.2-dev23.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1336) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1260) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.chat(CraftPlayer.java:238) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.bendercraft.spigot.commandsigns.controller.CommandBlockExecutor.handleCommand(CommandBlockExecutor.java:175) [CommandSigns-1.5.5.jar:?]
        at net.bendercraft.spigot.commandsigns.controller.CommandBlockExecutor.execute(CommandBlockExecutor.java:144) [CommandSigns-1.5.5.jar:?]
        at net.bendercraft.spigot.commandsigns.controller.CommandSignListener.executeCommandBlock(CommandSignListener.java:189) [CommandSigns-1.5.5.jar:?]
        at net.bendercraft.spigot.commandsigns.controller.CommandSignListener.onInteractEvent(CommandSignListener.java:177) [CommandSigns-1.5.5.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:242) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar-2017-01-27-1804:git-Spigot-6de2fbc-c1aa859]
        ... 66 more

**Comment by fullwall** [comment]
The error is related to the extra wolf entity, but does not look like a logic error just the old entity has not been removed properly. I have not been able to reproduce this yet, still looking for a reliable way.

**Comment by SlimeDog** [comment]
No worries. I am happy to provide access to my test server to assist with debugging. It is 100% reproducible there.

**Comment by fullwall** [comment]
Does it have only citizens and sentinel and denizen enabled? Can you reproduce it then?

**Comment by SlimeDog** [comment]
No. I am running a multiverse, and the entities of interest are not in the default world. I could bring it down to a minimal set:

> Citizens
Multiverse-Core 
PermissionsEx 
Sentinel
Vault 
WorldEdit 
WorldGuard 

I will test that configuration and let you know.

**Comment by SlimeDog** [comment]
Environment: Spigot 1.11.2 latest.
The issue does not occur with this subset of plugins:
> citizens-2.0.21-b1469.jar
Multiverse-Core-2.5.0-b725.jar
PermissionsEx-1.23.4.jar
ProtocolLib-4.2.1-b346.jar
sentinel-1.0.jar
Vault-1.5.6-b49.jar
worldedit-bukkit-6.1.7-b3677.jar
worldguard-legacy-6.2.1-b1703.jar

If I add both (but not only one or the other):
> AAC-3.0.3.jar
BiomeFinder-1.2.4.jar

the extra entity is spawned. In no case were there errors or warnings in the log. So some interaction among these ten plugins is causing the problem. I cannot break it down further in multiverse. So next step is to change the server configuration to place the dogs in the default world and attempt to isolate without MV, WE, and WG. Any other ideas how to proceed?

**Comment by mcmonkey4eva** [comment]
AAC as in the (intentionally quoted) "Advanced" Anti Cheat plugin?
I wouldn't be the slightest bit shocked if that was the problem plugin.

I literally cannot find `BiomeFinder` as a Bukkit or Spigot plugin anywhere, so I can't comment on that one.

**Comment by SlimeDog** [comment]
[BiomeFinder](https://www.spigotmc.org/resources/biomefinder.30892/)

**Comment by mcmonkey4eva** [comment]
I can't see any reason that would cause issues that aren't lag issues
(from a quick glance through at least)

**Comment by SlimeDog** [comment]
I wouldn't think so, either. I can imagine AAC doing lots of things; maybe this is one of the ghosts. I'll raise the issue there.

**Comment by SlimeDog** [comment]
After a lot more testing, I cannot prove anything, but the feeling persists that Citizens/Sentinel are the prime suspects.

If I add a CustomName to the spare, and kill it solely and explicitly, the associated sentinel dies also. They are clearly linked. I cannot see how any other plugin would link them.

**Comment by mcmonkey4eva** [comment]
Well yeah it's a NPC being duplicated, Citizens is related... but Citizens is not the sole fault, something is triggering this happening externally most likely.

For reference, btw, the last time anything close to this happened, it was player duplication caused by Sentry not being friendly to `/citizens reload` - and that was replicable across any server that ran the two plugins.

**Comment by SlimeDog** [comment]
New wrinkle. Sometimes the ghost appears even with AAC not installed. So it's inconsistent. :(

Could this be caused by load order dependencies?

**Comment by SlimeDog** [comment]
More...
The dogs are NPCs 1-4. NPC 5 was type=VILLAGER with text chat. Yesterday, I changed NPC 5 to type=PLAYER. When I rebooted, the ghost dog was no longer present. I can no longer produce the ghost, confirmed through several reboots.

I have a backup of the Citizens/Sentinel configuration with the VILLAGER, which reliably reproduces the ghost, if anyone wants to debug on my test server.

**Comment by mcmonkey4eva** [comment]
If you can like... zip up a small but complete test server that replicates the issue, we could open that up - if we can replicate it on our own machines, we can diagnose and fix it for sure.

(Note: don't include the spigot jar, as it's illegal to distribute that - just make sure it replicates on approximately most recent spigot build)

**Comment by SlimeDog** [comment]
Bonus! I constructed a minimal reproduction set. There are now **two** ghosts produced, co-located with Spike and Butch. Good hunting!

A [gzipped tar file](https://whitedog.straight8.com/drops/sp-backup.gz) is available on my server for the next 24 hours. Please confirm here that you have downloaded it. As required, the Spigot JAR is not included. The INSTRUCTIONS are included in the tarball:

> ■ Make a clean Spigot JAR
■ Rename the new Spigot JAR to spigot.jar
■ Run ./sp-start

**Comment by mcmonkey4eva** [comment]
Pro-tip: don't give an HTTPS link if your server's HTTPS is misconfigured! Threw me off for a second.
(Also a "gzipped tar file" is called a tarball and is usually a `.tar.gz`)

Anyway, gonna play with it now that it's downloaded. Thanks for the files!
Will report back.

**Comment by mcmonkey4eva** [comment]
> boot it up with a 1.11.2 jar file
```
[00:12:59 WARN]: [Sentinel] Task #13 for Sentinel v1.0 (build 90) generated an exception
java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_11_R1.entity.MobEntityController.createEntity(MobEntityController.java:27) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:195) ~[?:?]
```

**Comment by SlimeDog** [comment]
Thanks for the ack. My server is self-certified. Since no one else uses it, it isn't essential that I do more.

"Tarball" is old-school, and not everyone knows what it means, so I went for explicit (I did use "tarball" later in the piece).

I will remove the files now.

**Comment by SlimeDog** [comment]
It does not generate NPE on my servers.

**Comment by mcmonkey4eva** [comment]
Oh, NPE was from you keep NPCs in the saves that are spawned in worlds that, er, don't exist.

**Comment by SlimeDog** [comment]
All the worlds exist in the tarball.

**Comment by mcmonkey4eva** [comment]
Oh I see. You were expecting me to somehow execute a Linux script to configure it to non-standard settings.
I didn't bother to figure out how to copy any of that to a batch start script.

**Comment by mcmonkey4eva** [comment]
Any simple recreation steps for recreating the bug locally, as I don't have your NPCs and world - or info on how to configure the worlds properly?

**Comment by SlimeDog** [comment]
Yes. Obtain a Linux server.  Do you want to debug on my test server? I offered access (within reasonable limitations) long ago.

**Comment by mcmonkey4eva** [comment]
I have server linux servers; I'm not going to put this on any of them.
If this can't be replicated in an LTS, it's going to end up being labeled as an environment issue.

**Comment by SlimeDog** [comment]
Suit yourself. It no longer occurs in my environment, since I changed the one NPC to a Player (formerly Villager).

**Comment by mcmonkey4eva** [comment]
I figured out what I needed to copy over (Literally just `--universe UNIVERSE` for some awful reason)

**Comment by SlimeDog** [comment]
That is standard procedure to uncluttered the root directory.

**Comment by mcmonkey4eva** [comment]
How would I replicate the ghosts? I see the 4 wolves

**Comment by SlimeDog** [comment]
No ghosts on two of them?

**Comment by mcmonkey4eva** [comment]
Nope.

**Comment by SlimeDog** [comment]
Then you cannot replicate. :(
Must be something I ate.

**Comment by mcmonkey4eva** [comment]
ooooooooooooooooooooooookay then.

**Comment by SlimeDog** [comment]
Please destroy the tarball. Much obliged. If anyone decides to debug on my test server,  I remain willing. Else, environment.

**Comment by SlimeDog** [comment]
Curious. When you said that you couldn't see the two ghosts, did you just look over there, or did you approach them? You might have to get a little closer to see the duplication. Just a thought.

**Comment by mcmonkey4eva** [comment]
I beat one of the actual NPCs to death, I selected each one with /npc sel, nothing happened at any point

**Comment by SlimeDog** [comment]
So, cannot be duplicated on your server. I've offered mine, but it sounds like there is no urgency. Feel free to close the issue, if that is the outcome.
