### ISSUE TITLE
Citizens Crash when I summon Wither monster (MC1.11)

### ISSUE THREAD

**Issue by NoblessHamster** [CitizensDev/Citizens2#1044]
Hmm.. What is this?

Is it a crash to think Normal mobs as NPCs in Citizens2?
I'm not create Wither Npc, but I just Create Wither mob!
but when I try to summon witherboss (use soulsand and skull) and apply /minecraft:particle command for witherBoss using via repeating_commandblock, Server is Crash down

http://ci.citizensnpcs.co/job/Citizens2/1465/
Build 1465 (Jenkins)

(Look at This Server Crash Report)

Time: 17. 1. 12 pm 8:46
Description: Ticking entity
java.lang.NullPointerException: Ticking entity
at net.citizensnpcs.nms.v1_11_R1.entity.WitherController$EntityWitherNPC.M(WitherController.java:151)
at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:662)
at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037)
at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24)
at net.minecraft.server.v1_11_R1.EntityWither.n(EntityWither.java:138)
at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893)
at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28)
at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
at net.minecraft.server.v1_11_R1.World.h(World.java:1604)
at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430)
at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617)
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806)
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Server thread
Stacktrace:
at net.citizensnpcs.nms.v1_11_R1.entity.WitherController$EntityWitherNPC.M(WitherController.java:151)
at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:662)
at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037)
at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24)
at net.minecraft.server.v1_11_R1.EntityWither.n(EntityWither.java:138)
at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893)
at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28)
at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
at net.minecraft.server.v1_11_R1.World.h(World.java:1604)
-- Entity being ticked --
Details:
**Entity Type: minecraft:wither (net.citizensnpcs.nms.v1_11_R1.entity.WitherController.EntityWitherNPC)**
>But This is not actually an NPC, but a mob.

Entity ID: 243157
Entity Name: ネクロマンサー
Entity's Exact location: 1776.50, 76.00, -1046.50
Entity's Block location: World: (1776,76,-1047), Chunk: (at 0,4,9 in 111,-66; contains blocks 1776,0,-1056 to 1791,255,-1041), Region: (3,-3; contains chunks 96,-96 to 127,-65, blocks 1536,0,-1536 to 2047,255,-1025)
Entity's Momentum: 0.00, -0.05, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430)
at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617)

**Comment by fullwall** [comment]
Fixed
