### ISSUE TITLE
Caused whenever a Citizen is spawned and exists

### ISSUE THREAD

**Issue by TheLimeGlass** [CitizensDev/Citizens2#1047]
Bug report:

Error that gets spammed:
```
[02:24:17] [Server thread/WARN]: [Citizens] Task #18 for Citizens v2.0.21-SNAPSHOT (build 1458) generated an exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking player
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:974) ~[?:?]
	at net.citizensnpcs.util.NMS.tick(NMS.java:265) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_11_R1.World.g(Lnet/minecraft/server/v1_11_R1/Entity;)V
	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:968) ~[?:?]
	... 9 more
```
Spigot version: 1.11.2-R0.1 (The lastest spigot version as of posting this)
Citizens version: Citizens 2.0.21 build 1458

**Comment by fullwall** [comment]
Update Citizens.
