### ISSUE TITLE
Skins do not work on their authorization system

### ISSUE THREAD

**Issue by SantaGitHub** [CitizensDev/Citizens2#1064]
- Why not set the skin on NPС?
- `[16:28:51] [Craft Scheduler Thread - 19/INFO]: Fetched profile 00ab55cf-9ffc-4f63-a122-fc42fa2a0c4c for player Skin3
[16:28:51] [Server thread/WARN]: [Citizens] Task #111 for Citizens v2.0.21-SNAPSHOT (build 1463) generated an exception
java.lang.NullPointerException: data cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at net.citizensnpcs.api.npc.SimpleMetadataStore.checkPrimitive(SimpleMetadataStore.java:16) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleMetadataStore.setPersistent(SimpleMetadataStore.java:88) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC$1.setPersistent(AbstractNPC.java:65) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.setNPCSkinData(Skin.java:315) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.apply(Skin.java:106) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:120) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:224) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:168) ~[?:?]
	at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`
- 1.10.2. - Citizens v2.0.21-SNAPSHOT

**Comment by i9hdkill** [comment]
Try latest. there has been 1 commit regarding skins.

**Comment by SantaGitHub** [comment]
`31.01 09:52:04 [Server] INFO JewishCat issued server command: /npc skin skin3
31.01 09:52:05 [Server] WARN [Citizens] Task #239 for Citizens v2.0.21-SNAPSHOT (build 1469) generated an exception
31.01 09:52:05 [Server] INFO java.lang.NullPointerException: data cannot be null
31.01 09:52:05 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.api.npc.SimpleMetadataStore.checkPrimitive(SimpleMetadataStore.java:16) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.api.npc.SimpleMetadataStore.setPersistent(SimpleMetadataStore.java:88) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.api.npc.AbstractNPC$1.setPersistent(AbstractNPC.java:65) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.skin.Skin.setNPCSkinData(Skin.java:360) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.skin.Skin.apply(Skin.java:106) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:120) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:270) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:168) ~[?:?]
31.01 09:52:05 [Server] INFO at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120) ~[?:?]
31.01 09:52:05 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
31.01 09:52:05 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by fullwall** [comment]
Try latest build
