### ISSUE TITLE
"Cannot measure distance between" - Navigator Error

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1071]
Hello!

If I set a mob to target me and I switch world. Then I get an error. Please check if the player is in the same world as the entity or cancel nagivation. @fullwall 

Running: Citizens version 2.0.21-SNAPSHOT (build 1469)

**Error:**
`[14:10:22 INFO]: [Citizens] Exception while updating 144: Cannot measure distance between NachtDerUntoten and Nuketown.
[14:10:22 WARN]: java.lang.IllegalArgumentException: Cannot measure distance between World and Worldtest
[14:10:22 WARN]:        at org.bukkit.Location.distanceSquared(Location.java:456)
[14:10:22 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:156)
[14:10:22 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274)
[14:10:22 WARN]:        at net.citizensnpcs.nms.v1_11_R1.entity.ZombieController$EntityZombieNPC.M(ZombieController.java:170)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:662)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityZombie.n(EntityZombie.java:155)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.World.h(World.java:1604)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[14:10:22 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[14:10:22 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by fullwall** [comment]
Fixed

**Comment by File14** [comment]
Thanks mate! @fullwall
