### ISSUE TITLE
Citizens2 - 1.9 Error

### ISSUE THREAD

**Issue by File14** [CitizensDev/Citizens2#1072]
Hello!

I'm a creator of a minigame, and I use Citizens2 as an API. One of my runs the minigame on 1.9 and sometimes he get's this error:

Do you know why? @fullwall 

`17:50:09] [Server thread/ERROR]: Could not pass event EntityDeathEvent to Citizens v2.0.18-SNAPSHOT (build 1371)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:391) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.die(EntityLiving.java:986) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityZombie.die(EntityZombie.java:552) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:903) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityMonster.damageEntity(EntityMonster.java:44) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityZombie.damageEntity(EntityZombie.java:180) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1002) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1134) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1576) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:238) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c6871e2-0cd0397]
	... 23 more`

**Comment by File14** [comment]
Because the guy wanted 1.9 > 1.11 support via Viaversion.

**Comment by i9hdkill** [comment]
Suggest him to use 1.11.2 + Protocolsupport to support 1.9-1.11.2 clients.
No point of sticking with 1.9.
As said above, it's the most unsupported version, for reasons.

**Comment by File14** [comment]
Okay thanks! I'll tell him that. :)
