### ISSUE TITLE
/npc rabbittype GOLD (any) - console error

### ISSUE THREAD

**Issue by BabelSolea** [CitizensDev/Citizens2#1124]
In this issue, please include:
- whether this is a bug description or a feature request
- Link to server log & Citizens config if relevant (using e.g. pastie.org) 
- Minecraft & Citizens version if relevant

```
[09:30:27 WARN]: java.lang.NullPointerException
[09:30:27 WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
[09:30:27 WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.getInt(UnsafeIntegerFieldAccessorImpl.java:56)
[09:30:27 WARN]: 	at sun.reflect.UnsafeIntegerFieldAccessorImpl.get(UnsafeIntegerFieldAccessorImpl.java:36)
[09:30:27 WARN]: 	at java.lang.reflect.Field.get(Field.java:393)
[09:30:27 WARN]: 	at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.getRabbitTypeField(NMSImpl.java:1318)
[09:30:27 WARN]: 	at net.citizensnpcs.nms.v1_11_R1.entity.RabbitController$EntityRabbitNPC.setRabbitType(RabbitController.java:208)
[09:30:27 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftRabbit.setRabbitType(CraftRabbit.java:49)
[09:30:27 WARN]: 	at net.citizensnpcs.trait.RabbitType.setType(RabbitType.java:28)
[09:30:27 WARN]: 	at net.citizensnpcs.commands.NPCCommands.rabbitType(NPCCommands.java:1251)
[09:30:27 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:30:27 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:30:27 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:30:27 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:30:27 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[09:30:27 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[09:30:27 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[09:30:27 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[09:30:27 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:30:27 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:30:27 WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:30:27 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:30:27 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[09:30:27 WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[09:30:27 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fullwall** [comment]
Fixed
