### ISSUE TITLE
A bug with /summon wither

### ISSUE THREAD

**Issue by DanielTravi** [CitizensDev/Citizens2#1144]
Error description: This error occurs when you run the / summon wither command or when a player is next to a wither that appears with the /summon command

Version: spigot 1.11.2

Plugin Version: Citizens Alpha #8 for MC 1.10-1.11.2

Log Error:
[22:48:57 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking entity
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_11_R1.entity.WitherController$EntityWitherNPC.M(WitherController.java:151) ~[?:?]
        at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:662) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityWither.n(EntityWither.java:138) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1604) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        ... 4 more
[22:48:57 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_11_R1.entity.WitherController$EntityWitherNPC.M(WitherController.java:151) ~[?:?]
        at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:662) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityWither.n(EntityWither.java:138) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.World.h(World.java:1604) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:617) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) ~[spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[22:48:57 ERROR]: This crash report has been saved to: B:\TravisUniverse\TravisUniverse\.\crash-reports\crash-2017-05-07_22.48.57-server.txt
[22:48:57 INFO]: Stopping server

Config:

# Citizens Configuration

general:
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  default:
    look-close:
      enabled: false
      range: 5
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest: true
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  teleport-delay: -1
  controllable:
    use-boat-controls: true
  player-scoreboard-teams:
    enable: true
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins

**Comment by mcmonkey4eva** [comment]
This was fixed in January: https://github.com/CitizensDev/Citizens2/commit/226470d743a5a505dea351ad019ff3c449e6cb63
Get the latest dev build: http://ci.citizensnpcs.co/job/Citizens2/
