### ISSUE TITLE
Citizens 2 Sentry /npc create test --trait sentry Error check console

### ISSUE THREAD

**Issue by BashtaTiEMaika** [CitizensDev/Citizens2#1156]
java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/World
[00:22:07 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[00:22:07 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[00:22:07 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:110)
[00:22:07 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
[00:22:07 WARN]:        at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[00:22:07 WARN]:        at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
[00:22:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:22:07 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:22:07 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:22:07 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[00:22:07 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[00:22:07 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[00:22:07 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[00:22:07 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[00:22:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:22:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:22:07 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[00:22:07 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:22:07 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[00:22:07 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[00:22:07 WARN]:        at java.lang.Thread.run(Thread.java:745)
[00:22:07 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
[00:22:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[00:22:07 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[00:22:07 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[00:22:07 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[00:22:07 WARN]:        ... 30 more

This is what I get when I try to create a npc with sentry trait. I'm on the latest version of everything Citizens and Sentry but idk why that is happening. Pls help. Thanks.

**Comment by mcmonkey4eva** [comment]
You want _Sentinel_ https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md

**Comment by BashtaTiEMaika** [comment]
Hi ! Thank you for responding. The plugin is all nice and stuff but there
is a little problem. When I make the npc it attacks me that's fine. However
it chases me around the whole place. I set its chaserange to 3 and it still
chases and targets me from like 20 blocks away. Is there a way you could
help ? Thanks.

2017-05-20 23:35 GMT+01:00 mcmonkey4eva <notifications@github.com>:

**Comment by mcmonkey4eva** [comment]
There are other range parameters you also have to set lower.

**Comment by BashtaTiEMaika** [comment]
What are they if you could tell me please ?

**Comment by mcmonkey4eva** [comment]
uh... the 'range' parameter in particular?

**Comment by BashtaTiEMaika** [comment]
Oh ok thanks ! :D sry for bothering you.

**Comment by BashtaTiEMaika** [comment]
Hi, sorry for bothering you again but once again... I have a problem. When
the NPC kills somebody it stays at the place the player was killed and
doesn't go back to his spawnpoint and also when I set the /sentinel
chaserange 5 it doesn't chase the player for 5 blocks only, but once again
around the whole place. Help please ! Thanks.

2017-05-21 8:36 GMT+01:00 InterstelGaming Nasko <pvpfriendnasko@gmail.com>:

> Oh ok thanks ! :D sry for bothering you.
>
