### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.npc.EntityControllers

### ISSUE THREAD

**Issue by BlackHatDark** [CitizensDev/Citizens2#1168]
at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:96)
[01:22:51 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[01:22:51 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[01:22:51 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:378)
[01:22:51 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:22:51 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:22:51 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:22:51 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:22:51 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[01:22:51 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[01:22:51 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[01:22:51 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[01:22:51 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:22:51 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:22:51 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[01:22:51 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:22:51 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[01:22:51 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[01:22:51 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
Do you have the correct _version_ of Citizens2? https://wiki.citizensnpcs.co/Versions

**Comment by BlackHatDark** [comment]
If I have the correct version of citizens2

**Comment by mcmonkey4eva** [comment]
... what?


Verify your version through that link, and if you feel sure,
post a full startup log (VIA PASTEBIN!!!) of your server

**Comment by BlackHatDark** [comment]
https://pastebin.com/YdimDmCN

**Comment by BlackHatDark** [comment]
https://pastebin.com/vu24Y2B6

**Comment by mcmonkey4eva** [comment]
You appear to be using some early build of 1.9 Spigot - please update to 1.9.4, 1.10.2, or 1.11.2
