### ISSUE TITLE
NPCs not loading into place at server startup.

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#1170]
Citizens dev 1476
Paper dev 1104 (Spigot 1.11.2)

I have 4 NPCs configured. I noticed after my server started up, two of them were invisible / not in place. I had to type ```/citizens reload``` for them to re-appear. So it seems sometimes citizens do not fully load in on server reboots / startup initialization. 

Despite it reporting;
```
[09:00:38] [Server thread/INFO]: [Citizens] Loaded 4 NPCs.
```

**Comment by mibby** [comment]
Still happening for me after restarts. Sometimes the npcs do not initialize in place, they are invisible until I ```/citizens reload```.

**Comment by mibby** [comment]
Still happening on Citizens dev 1481. Tested with a teleport-delay of -1 and 40. Higher teleport delay, npcs don't show up whatsoever on reload. No teleport delay, sometimes breaks skins and them not showing up on reload/initialization.

**Comment by mibby** [comment]
@fullwall @mcmonkey4eva Still occurring as of Citizens dev 1494. 

Is there anything I can do to force npcs to load / re-load a few seconds after startup? Perhaps citizens aren't appearing during restarts because of too many skin lookup requests in a short period of time due to other plugins requesting lookup (head database plugins). Since citizens is unable to get the skin data for an npc, it stops all loading?

**Comment by LeafyMitsuwa** [comment]
Are these npc's on worlds other than world, world_nether, or world_the_end by any chance?

**Comment by mibby** [comment]
When I initially created the ticket, they were only in ```world``` world. However I have recently moved all npcs to a separate void world that is used for my spawn.

**Comment by mcmonkey4eva** [comment]
Can you perhaps enable debug mode in your config, and see what the console says during restart sequences?

**Comment by mibby** [comment]
@mcmonkey4eva Here's the full start-up for Citizens with debug enabled.

```
[19:52:03] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.22-SNAPSHOT (build 1494)
[19:52:19] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.22-SNAPSHOT (build 1494)
[19:52:19] [Server thread/INFO]: Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes
[19:52:19] [Server thread/INFO]: [CommandNPC] Enabling CommandNPC v1.9.1
[19:52:19] [Server thread/INFO]: [CommandNPC] Vault compatible economy found! Economy support for CommandNPC has been enabled.
[19:52:19] [Server thread/INFO]: [CommandNPC] Initiating Database
[19:52:19] [Server thread/INFO]: [CommandNPC] Injecting command info into Citizens.
[19:52:19] [Server thread/INFO]: [CommandNPC] CommandNPC successfully loaded!
[19:52:19] [Thread-21/INFO]: [CommandNPC] Loading commands complete!
[19:52:25] [Server thread/INFO]: Done (19.315s)! For help, type "help" or "?"
[19:52:29] [Server thread/INFO]: Retrying spawn of 1 later due to chunk being unloaded. Util.isLoaded true
[19:52:29] [Server thread/INFO]: Stored 1 for respawn from NPCNeedsRespawnEvent
[19:52:29] [Server thread/INFO]: Retrying spawn of 6 later due to chunk being unloaded. Util.isLoaded true
[19:52:29] [Server thread/INFO]: Stored 6 for respawn from NPCNeedsRespawnEvent
[19:52:29] [Server thread/INFO]: Retrying spawn of 7 later due to chunk being unloaded. Util.isLoaded true
[19:52:29] [Server thread/INFO]: Stored 7 for respawn from NPCNeedsRespawnEvent
[19:52:29] [Server thread/INFO]: Retrying spawn of 8 later due to chunk being unloaded. Util.isLoaded true
[19:52:29] [Server thread/INFO]: Stored 8 for respawn from NPCNeedsRespawnEvent
[19:52:29] [Server thread/INFO]: [Citizens] Loaded 5 NPCs.
[19:52:29] [Craft Scheduler Thread - 11/INFO]: Fetched profile 70a5d798-479f-4cb0-9279-62d6956afd5c for player Angeleea
[19:52:30] [Craft Scheduler Thread - 11/INFO]: Fetched profile 291c2d6e-a25d-4179-a11e-3011f9a97b2b for player iMxAndyy
[19:52:30] [Craft Scheduler Thread - 11/INFO]: Fetched profile 0d6e7f2b-b16e-4e2e-9f47-4cbe8125cf07 for player Noby_Diver
[19:52:30] [Craft Scheduler Thread - 11/INFO]: Fetched profile fd3732f4-c293-4c3e-9bf4-a0ea4365af2b for player Wenger
[19:52:30] [Server thread/INFO]: Removing 4 from skin tracker due to DespawnReason.PENDING_RESPAWN
[19:52:30] [Server thread/INFO]: Despawned 4 DespawnReason. PENDING_RESPAWN
[19:52:30] [Craft Scheduler Thread - 11/INFO]: Fetched profile d32baf71-3c47-439e-be42-c630a481ddbc for player Cooper1990
[19:52:35] [Server thread/INFO]: Removing 4 from skin tracker due to DespawnReason.CHUNK_UNLOAD
[19:52:35] [Server thread/INFO]: Despawned 4 DespawnReason. CHUNK_UNLOAD
[19:52:35] [Server thread/INFO]: Despawned id 4 due to chunk unload at [-2,0]
[19:52:50] [Server thread/INFO]: Spawned id 8 due to chunk event at [1,0]
[19:52:50] [Server thread/INFO]: Spawned id 4 due to chunk event at [-2,0]
[19:52:50] [Server thread/INFO]: Spawned id 6 due to chunk event at [-2,-1]
[19:52:50] [Server thread/INFO]: Spawned id 7 due to chunk event at [-3,0]
[19:52:50] [Server thread/INFO]: Spawned id 1 due to chunk event at [-3,-1]
```

During restarts, I also force all connections to idle and reconnect on the BungeeCord proxy so players automatically rejoin the server after restarts. So perhaps with lots of players reconnecting at once, it stops citizens from fully loading when it tries to fetch skins?

**Comment by mibby** [comment]
@mcmonkey4eva Here is a restart with a confirmed occurrence of npcs disappearing. Caused by what I assumed, too many skin requests stopping npcs from loading. So perhaps load a blank steve skin with the npc so it still exists until the skin can be refetched?

```
[21:00:57] [Craft Scheduler Thread - 24/INFO]: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:300)
	at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:60)
	at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81)
	at com.destroystokyo.paper.event.profile.PreLookupProfileEvent$PreProfileLookupCallback.onProfileLookupSucceeded(PreLookupProfileEvent.java:162)
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63)
	at com.destroystokyo.paper.event.profile.PreLookupProfileEvent.lambda$wrapProfileRepository$0(PreLookupProfileEvent.java:143)
	at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
	at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79)
	... 18 more
```

http://paste.ubuntu.com/25730236/

**Comment by mibby** [comment]
Been an hour post server restart and the npcs haven't loaded /come back automatically. =/
![link](https://i.imgur.com/YXPSdo8.png)

Forcing a ```/citizens reload```, they load in.
![link2](https://i.imgur.com/4Oh4rgH.png)

Still think they should load default steve skins and keep retrying to fetch skins every defined amount of time until they actually can instead of not loading whatsoever.

**Comment by LeafyMitsuwa** [comment]
If they're using live-skins, then Mojang will block requests from IP's after a certain amount of requests has been met from said IP, an issue if your host is hosting multiple servers' on the same IP.

If they're using offline skins, (argumented with -p), why should the 1000th attempt to load a skin have any different result than the 4th attempt?

**Comment by mibby** [comment]
My dedicated box is only hosting a single server. The issue is with using a heads database plugin and if Citizens can't obtain the skin, it stops loading npcs entirely rather than using a steve skin until a skin can be refetched. 

Is offline skins something that Citizens supports?

**Comment by LeafyMitsuwa** [comment]
https://wiki.citizensnpcs.co/Skins

**Comment by mibby** [comment]
Interesting. This I presume will stop it from trying to fetch the skin online when attached to a specific player name? If so, that'll definitely help and will hopefully prevent the issue of npcs not loading at start-up.

**Comment by mibby** [comment]
It seems it still tries to fetch the skin of the npcs even with -p and prevents npcs from loading when it can't make a skin request on server restarts. So this issue will still need to be fixed.

**Comment by fullwall** [comment]
Apologies for the delay - I believe I have found the cause of this and will work on a fix tomorrow.

**Comment by fullwall** [comment]
Try latest build

**Comment by mibby** [comment]
@fullwall Doesn't seem to be fixed.

Citizens dev 1496

Post restart.
![link3](https://i.imgur.com/PZIwcYZ.jpg)

Reloading via ```/citizens reload```.
![link4](https://i.imgur.com/dSp4Fo9.jpg)

**Comment by BloodEko** [comment]
Is your error maybe related to this one ? https://github.com/CitizensDev/Citizens2/issues/1332

**Comment by mibby** [comment]
It is possible, but logging into the server post restart sometimes has them not showing as well. Even swapping worlds and back doesn't force them to re-show. Have to force it with ```/citizens reload```.

**Comment by mibby** [comment]
@fullwall Bump. ^^ :( It is quite frustrating to not have essential npcs loaded after restarts.

**Comment by mibby** [comment]
Any update to this issue? Still very frustrating for me. :(

**Comment by mibby** [comment]
Bump. ^^

**Comment by mibby** [comment]
Bump. 

Also experiencing a new issue recently where the skins of the loaded npcs disappear on your client until you switch worlds and back.

**Comment by mibby** [comment]
@mcmonkey4eva I'm not sure as I do not personally use many npcs outside of my spawn world and spawn location. I'd have to re-check but generally it is always spawn with missing npcs. I've just setup a script to reload citizens 5 minutes after a restart since this issue has existed forever.

**Comment by mcmonkey4eva** [comment]
If it's only spawn chunks, it's likely https://github.com/CitizensDev/Citizens2/issues/1332 as the basis of this (NPCs not loading in for chunks that are already loaded when Citizens fully starts up)

**Comment by mibby** [comment]
It's possible that's related or the actual symptom I'm experiencing. However I've had players login post-restart and claim citizens are missing - requiring a citizens reload to refresh.

**Comment by mibby** [comment]
Thus a fix would be to verify the integrity of the spawn location before spawning the entity, else force it or retry until succeeding? With a timeout in case the actual chunk is damaged so citizens doesn't just spam checks repeatedly?

**Comment by mibby** [comment]
Did a quick restart to check what npcs don't spawn in. It only seems to be the ones at spawn where half load in. The ones located in separate worlds loaded fine - though perhaps maybe I just got lucky in the load order based on when they were created.

**Comment by mcmonkey4eva** [comment]
I'm going to say this should be deferred to #1332 then
