### ISSUE TITLE
Invalid Plugin.yml

### ISSUE THREAD

**Issue by Arctomium** [CitizensDev/Citizens2#1183]
Running the latest version of Spigot 1.11.2 and downloaded the latest Citizens2 and removed my last configuration to generate a fresh one and got this error as soon as I started my server:
`[01:19:28] [Server thread/ERROR]: Could not load 'plugins/Citizens-2.0.22.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_60]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	... 5 more`

**Comment by mcmonkey4eva** [comment]
Redownload the jar, your download was corrupted.

**Comment by Arctomium** [comment]
Just downloaded it again and still the same thing.

**Comment by mcmonkey4eva** [comment]
0.o try a different version or from a different source (jenkins, spigot, bukkitdev, ...) ?

**Comment by Arctomium** [comment]
Well if I do it from Spigot I will have to buy it and I downloaded it from Jenkins.

**Comment by fullwall** [comment]
Are you sure you deleted the corrupted JAR? The one from Jenkins works for me...

**Comment by mcmonkey4eva** [comment]
Oh, this was resolved via sending a clean copy over Discord file transfer ( which was literally just me downloading off jenkins and reuploading )
