### ISSUE TITLE
error /npc create.... help-me

### ISSUE THREAD

**Issue by EduardoMGP** [CitizensDev/Citizens2#1187]
Hello, I have a problem with the plugin citizens a long time ago
And I do not find a solution
I've downloaded several versions until nowadays none worked
My server is tekkit
Use the jar thermos
version 1.7.10

When I use / npc create me returns this error

<a href="http://imgur.com/YDZ9EOU"><img src="http://i.imgur.com/YDZ9EOU.png" title="source: imgur.com" /></a>

LOGS

`[17:02:07] [Server thread/INFO]: EduardoMGP issued server command: /npc create teste
[17:02:07] [Server thread/INFO]: [Citizens] Could not fetch NMS field e: e.
[17:02:07] [Server thread/INFO]: [Citizens] Could not fetch NMS field j: j.
[17:02:07] [Server thread/INFO]: [Citizens] Could not fetch NMS field m: m.
[17:02:07] [Server thread/WARN]: java.lang.IllegalAccessError: tried to access field net.minecraft.pathfinding.PathNavigate.field_75521_i from class net.citizensnpcs.util.nms.PlayerNavigation
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:29)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:215)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:65)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:70)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:170)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:366)
[17:02:07] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:02:07] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:02:07] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:02:07] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[17:02:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[17:02:07] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:02:07] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[17:02:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[17:02:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[17:02:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
`

**Comment by mcmonkey4eva** [comment]
Unfortunately, we no longer have the .jar file to support 1.7.10 MCPC/Cauldron/etc. with :/
@bloodmc might have a copy somewhere (We used to just link his copy of it, but that got lost by the dropbox 'public folder' shutdown :/ )

**Comment by EduardoMGP** [comment]
Thank you so much for your answer
I did not know I had a citizens so for cauldron.
I managed to find one here if you want.

Https://www.dropbox.com/s/rs4n0i51mwxze9u/citizens-2.0.13-1.7.10-Cauldron-B1.jar

I found myself lost on the internet
Thank you even it worked.

**Comment by mcmonkey4eva** [comment]
Oh, thanks for the lost link!

**Comment by EduardoMGP** [comment]
Hmm
I downloaded that citizens ai, but when I use / npc skin miner for example it continues as steve
How to solve?
thank you

**Comment by mcmonkey4eva** [comment]
unfortunately skins are not available in Cauldron 1.7.10 Citizens :/
