### ISSUE TITLE
Skins Suddenly Stopped working

### ISSUE THREAD

**Issue by ELJESTER** [CitizensDev/Citizens2#1189]
#1480
Paper 1.11.2

Randomly i can no longer set Skins to NPC's. All the previous ones are still there but any new NPC's wont work with skins. I updated to build #1480 to see if it fixed the issue and it did not. Here is the Console error.

 `> [06:02:43 INFO]: Cutlett issued server command: /npc select
> [06:03:13 INFO]: Cutlett issued server command: /npc skin Cutlett
> [06:03:13 INFO]: Removing 15 from skin tracker due to DespawnReason.PENDING_RESPAWN
> [06:03:13 INFO]: Despawned 15 DespawnReason. PENDING_RESPAWN
> [06:03:15 INFO]: Profile lookup for player 'cutlett' failed2: null
> [06:03:15 INFO]: com.mojang.authlib.exceptions.AuthenticationException
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79)
    at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:54)
    at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
    at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by fullwall** [comment]
Duplicate - see https://github.com/CitizensDev/Citizens2/issues/1190
