### ISSUE TITLE
Can't create npcs

### ISSUE THREAD

**Issue by DashJavii03** [CitizensDev/Citizens2#1247]
Whenever i try to create an NPC  it shows me this error, i have tried with the example in the wiki:

[19:49:46 INFO]: DashJavii03 issued server command: /npc create Jimbo Stevenson --type PIG
[19:49:46 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.npc.EntityControllers
[19:49:46 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:361)
[19:49:46 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:49:46 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:49:46 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:49:46 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[19:49:46 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[19:49:46 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[19:49:46 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[19:49:46 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[19:49:46 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:49:46 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[19:49:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:624)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1250)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1110)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:37)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:9)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:49:46 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:49:46 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635)
[19:49:46 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539)
[19:49:46 WARN]:        at java.lang.Thread.run(Thread.java:745)

Any idea of why is this error appearing?

**Comment by DevIPv2** [comment]
Try updating to the latest version. - ArabCoder
"Time for a true display of skill"

**Comment by DevIPv2** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/b8d85097cb",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Sepp is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
