### ISSUE TITLE
ERROR Could not pass event ChunkLoadEvent

### ISSUE THREAD

**Issue by Enzo41814** [CitizensDev/Citizens2#1259]
I inform the following error in console:
https://pastebin.com/P7qPcdis
Minecraft 1.12.1 PaperSpigot b1173
Citizens v2.0.22-SNAPSHOT (build 1487)
IP: PotterWizard.tk 1.5.2 - 1.12.1

**Comment by fullwall** [comment]
Missing some exception info here - can you get the full log?

**Comment by Fabrimat** [comment]
Same here

Version: CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT
Citizens: Citizens v2.0.22-SNAPSHOT (build 1487)
`Could not pass event ChunkLoadEvent to Citizens v2.0.22-SNAPSHOT (build 1487)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:910) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:332) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:328) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.getTileEntity(World.java:1953) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.WorldServer.getTileEntity(WorldServer.java:136) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getTileEntityAt(CraftWorld.java:470) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftSign.<init>(CraftSign.java:20) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:270) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at com.minecraftmarket.minecraftmarket.bukkit.tasks.SignsTask.lambda$updateSigns$3(SignsTask.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalStateException: Asynchronous entity add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1016) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1112) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:228) ~[?:?]
        at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:42) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:199) ~[?:?]
        at net.citizensnpcs.EventListen.spawn(EventListen.java:572) ~[?:?]
        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:549) ~[?:?]
        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:139) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot112.jar:git-Spigot-596221b-9a1fc1e]
        ... 25 more
`

**Comment by fullwall** [comment]
Seems like a plugin conflict (Minecraft Market)
