### ISSUE TITLE
Exception for NPC respawning on chunk load

### ISSUE THREAD

**Issue by DanielTravi** [CitizensDev/Citizens2#1262]
SPIGOT 1.12.1
Citizens v2.0.22-SNAPSHOT (build 1479)
ERROR:
[15:44:44] [Server thread/INFO]: DanielTravi issued server command: /mv create Recursos normal -t LARGEBIOMES
[15:44:44] [Server thread/INFO]: [Multiverse-Core] Loading World & Settings - 'Recursos' - Env: NORMAL - Type: LARGE_BIOMES
[15:44:44] [Server thread/INFO]: -------- World Settings For [Recursos] --------
[15:44:44] [Server thread/INFO]: Mob Spawn Range: 8
[15:44:44] [Server thread/INFO]: Cactus Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Cane Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Melon Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Sapling Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Wheat Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Vine Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[15:44:44] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[15:44:44] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[15:44:44] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[15:44:44] [Server thread/INFO]: Random Lighting Updates: true
[15:44:44] [Server thread/INFO]: Structure Info Saving: true
[15:44:44] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[15:44:44] [Server thread/INFO]: Max TNT Explosions: 100
[15:44:44] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[15:44:44] [Server thread/INFO]: Item Despawn Rate: 6000
[15:44:44] [Server thread/INFO]: Item Merge Radius: 2.5
[15:44:44] [Server thread/INFO]: Arrow Despawn Rate: 1200
[15:44:44] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[15:44:44] [Server thread/INFO]: View Distance: 10
[15:44:44] [Server thread/INFO]: Experience Merge Radius: 3.0
[15:44:44] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[15:44:44] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[15:44:44] [Thread-172/INFO]: DanielTravi: Starting creation of world 'Recursos'...[m
[15:44:44] [Server thread/WARN]: Unable to find spawn biome
[15:44:44] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to Citizens v2.0.22-SNAPSHOT (build 1479)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:910) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:173) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:333) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.World.getChunkAtWorldCoords(World.java:329) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.World.getType(World.java:810) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.World.isEmpty(World.java:270) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.World.c(World.java:254) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.WorldProvider.canSpawn(SourceFile:86) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.WorldServer.canSpawn(WorldServer.java:259) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1000) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:922) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:905) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:454) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:466) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:268) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:278) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:142) [Multiverse-Core-2.5.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:92) [Multiverse-Core-2.5.jar:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:916) [Multiverse-Core-2.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_131]
	at java.util.ArrayList.remove(ArrayList.java:492) ~[?:1.8.0_131]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedList.remove(AbstractMapBasedMultimap.java:831) ~[TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:557) ~[Citizens.jar:?]
	at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:139) ~[Citizens.jar:?]
	at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[TravisWorld.jar:git-Spigot-edd0396-2a927e8]
	... 43 more

**Comment by fullwall** [comment]
Not sure what is causing this but I added a logging statement to help with the issue. Can you turn on debugging and tell me the output from the latest build if this is still a problem?
