### ISSUE TITLE
Bug - Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by KataLePanda** [CitizensDev/Citizens2#1271]
Hi, I took the plugin Citizen , everything was okay the first time I launched the plugin, ( so I don't think that that is a version problem), and, 
when I restarted my server, an error came.

[14:16:12] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Houses v1.9.1
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.Entity.checkBlockCollisions(Entity.java:903) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:486) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.EntityHuman.g(EntityHuman.java:1441) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.g(EntityHumanNPC.java:231) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:123) [Citizens.jar:?]
at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:969) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.tick(NMS.java:265) [Citizens.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens.jar:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
at com.hektropolis.houses.signs.SignListener.onPlayerInteract(SignListener.java:46) ~[?:?]
at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
... 25 more

I don't know what to do and I'm a bad dev 

I'm sorry for my english ^^'

" Help! "

**Comment by mergu** [comment]
This seems like an issue with Houses, not Citizens.
```
Caused by: java.lang.NullPointerException
at com.hektropolis.houses.signs.SignListener.onPlayerInteract(SignListener.java:46) ~[?:?]
```
Looks like it's caused by something stepping on a pressure plate/tripwire/redstone ore.

**Comment by KataLePanda** [comment]
What should I do ?

**Comment by mcmonkey4eva** [comment]
Speak to the developers of the `Houses` plugin?

**Comment by KataLePanda** [comment]
And, how can I contact him ?

**Comment by mcmonkey4eva** [comment]
Not really to our knowledge or power... figure out where you got the plugin from, and start looking for support pages from there...
