### ISSUE TITLE
Mounting npc's onto horses?

### ISSUE THREAD

**Issue by jamesol1** [CitizensDev/Citizens2#1274]
Hi I can't find the command to mount my npc's onto horses. I want to have npc mounted knights on my server.
Thanks

**Comment by mcmonkey4eva** [comment]
`/npc mount --onnpc <id>`

**Comment by jamesol1** [comment]
thanks for the response... 
I made an npc with the id 0. Then looked at him and entered:
''/npc mount --onnpc 0''
A red text error message came up saying '' null''.
Did i miss a step? Thanks.

**Comment by mcmonkey4eva** [comment]
I don't think you have made an NPC with ID 0 ... do you know what the ID is?

**Comment by jamesol1** [comment]
I typed /npc id and it listed 0

**Comment by jamesol1** [comment]
**Then again using james has given me this error... so maybe the npc's name is the id...**
[00:18:28 WARN]: java.lang.NumberFormatException: For input string: "james"
[00:18:28 WARN]:        at java.lang.NumberFormatException.forInputString(Unknow
n Source)
[00:18:28 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[00:18:28 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[00:18:28 WARN]:        at net.citizensnpcs.api.command.CommandContext.getFlagIn
teger(CommandContext.java:163)
[00:18:28 WARN]:        at net.citizensnpcs.commands.NPCCommands.mount(NPCComman
ds.java:882)
[00:18:28 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[00:18:28 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[00:18:28 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[00:18:28 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[00:18:28 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[00:18:28 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[00:18:28 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[00:18:28 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237
)
[00:18:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[00:18:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[00:18:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchC
ommand(CraftServer.java:644)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handle
Command(PlayerConnection.java:1385)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(Play
erConnection.java:1220)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:45)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:1)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1
.run(SourceFile:13)
[00:18:28 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[00:18:28 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFil
e:46)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(Minec
raftServer.java:747)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(Dedic
atedServer.java:405)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(Minec
raftServer.java:678)
[00:18:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min
ecraftServer.java:576)
[00:18:28 WARN]:        at java.lang.Thread.run(Unknown Source)
[00:18:33 INFO]: MineShaft87 issued server command: /npc mount --onnpc 0
[00:18:54 INFO]: MineShaft87 issued server command: /npc mount --onnpc James
[00:18:54 WARN]: java.lang.NumberFormatException: For input string: "James"
[00:18:54 WARN]:        at java.lang.NumberFormatException.forInputString(Unknow
n Source)
[00:18:54 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[00:18:54 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[00:18:54 WARN]:        at net.citizensnpcs.api.command.CommandContext.getFlagIn
teger(CommandContext.java:163)
[00:18:54 WARN]:        at net.citizensnpcs.commands.NPCCommands.mount(NPCComman
ds.java:882)
[00:18:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[00:18:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[00:18:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[00:18:54 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[00:18:54 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[00:18:54 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[00:18:54 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[00:18:54 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237
)
[00:18:54 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[00:18:54 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[00:18:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchC
ommand(CraftServer.java:644)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handle
Command(PlayerConnection.java:1385)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(Play
erConnection.java:1220)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:45)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:1)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1
.run(SourceFile:13)
[00:18:54 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[00:18:54 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFil
e:46)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(Minec
raftServer.java:747)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(Dedic
atedServer.java:405)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(Minec
raftServer.java:678)
[00:18:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min
ecraftServer.java:576)
[00:18:54 WARN]:        at java.lang.Thread.run(Unknown Source)
>

**Comment by mcmonkey4eva** [comment]
Eh... delete and remake it? `/npc` or `/npc list` ...? shouldn't have a 0, but it is a numbered ID...

**Comment by mcmonkey4eva** [comment]
ALso make sure you selected an NPC that isn't the NPC you're mounting onto

**Comment by jamesol1** [comment]
Hmm I made a new npc (deleted the old) this one has an ID of 1. 
Entered this:
/npc mount --onnpc 1
''null''

**Comment by jamesol1** [comment]
/npc list
Brings up this...
Key: ID  Name
1           Billy


Am i look at the right id?

**Comment by mcmonkey4eva** [comment]
yeah `1` would be the ID there

Make sure you have two involved NPCs and you have the right one selected...

**Comment by jamesol1** [comment]
Great I have it all working. The only issue I'm having is getting npc's to actually sit on horses correctly... currently mines sitting facing the right side of the horse instead of head on.
