### ISSUE TITLE
Citizens cannot work on spigot 1.12

### ISSUE THREAD

**Issue by SnUncle** [CitizensDev/Citizens2#1307]
[14:27:44] [Server thread/ERROR]: Could not load 'plugins\citizens-2.0.22-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	... 5 more
[14:27:44] [Server thread/ERROR]: Could not load 'plugins\FirstJoinPlus.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	... 5 more
[14:27:44] [Server thread/ERROR]: Could not load 'plugins\PlugMan.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	... 5 more
[14:27:44] [Server thread/ERROR]: Ambiguous plugin name `WorldEdit' for files `plugins\worldedit-bukkit-6.1.7.2.jar' and `plugins\worldedit-bukkit-6.1.2.jar' in `plugins'
[14:27:44] [Server thread/INFO]: Set PluginClassLoader as parallel capable

PLZ help me

**Comment by mcmonkey4eva** [comment]
Re-download the plugin.
From Spigot, Bukkit, or Jenkins CI.

If that fails, wait a day or so and try again!

**Comment by SnUncle** [comment]
I will try. thx
