### ISSUE TITLE
Couldn't look up profile properties 

### ISSUE THREAD

**Issue by SnUncle** [CitizensDev/Citizens2#1311]
Plz help me with the error
I running citizens2 on spigot 1.12 

[Head Conversion Thread - 0/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@45a3b9c3[id=a22cfb29-d360-45e7-815b-4029806430d9,name=Innkeeper,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:76) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:1) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.run(TileEntitySkull.java:201) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by mcmonkey4eva** [comment]
That's a tile entity (human skull) failing to load and has nothing to do with Citizens.
