### ISSUE TITLE
NPE after de-registering a NPC inside a NaviagtionEvent

### ISSUE THREAD

**Issue by NiklasEi** [CitizensDev/Citizens2#1316]
Using newest Citizens build #1494

The following NPE shows up everytime shortly after using NPCRegistry#deregister(NPC). I tried cancelling the navigation, but that didn't change anything. The same Error shows up on MC 1.10 and 1.12. Am I missing something that has to be done, bevore I can de-register the NPC? 

```
[23:45:10] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 241: null.
[23:45:10] [Server thread/WARN]: java.lang.NullPointerException
[23:45:10] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:276)
[23:45:10] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_10_R1.entity.ZombieController$EntityZombieNPC.M(ZombieController.java:170)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityInsentient.doTick(EntityInsentient.java:673)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:1961)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityInsentient.n(EntityInsentient.java:512)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityMonster.n(EntityMonster.java:28)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityZombie.n(EntityZombie.java:176)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1817)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:240)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.EntityZombie.m(EntityZombie.java:233)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.g(World.java:1604)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[23:45:10] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[23:45:10] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:45:17] [Server thread/INFO]: Arvindir issued server command: /tda test start
```

[Link to the method after which the Error shows up](https://github.com/NiklasEi/TowerDefense/blob/65cc997f3fa4aafc3a3c89dd2182e78625ecc38a/src/main/java/me/nikl/towerdefense/npc/TDnpc.java#L63-L71)

**Comment by NiklasEi** [comment]
I am deregistering the NPCs inside a NaviagationEvent. If I don't do that and use a command instead, this Error doesn't show up. Is there anything I can do to remove NPCs in a NaviagtionEvent without this?

**Comment by mcmonkey4eva** [comment]
Use the Bukkit scheduler to make it happen one tick later.

**Comment by NiklasEi** [comment]
That's what I am doing atm. I would prefere not to though. I'll make a quick PR fixing this, ok? Should be done with one null check...

**Comment by mcmonkey4eva** [comment]
No, not okay. That's not reasonable operation.

**Comment by NiklasEi** [comment]
Can I ask why? 
If the whole purpose of a NPC is to run from A to B, it is very reasonable to remove it when it reaches B in my opinion.

**Comment by mcmonkey4eva** [comment]
Bukkit events in general are designed in such a way that you cannot modify directly related variables within an event, except those provided by the event itself.
Any other modifications MUST be scheduled for later.
A simple example of this is inventory events: You can't edit an inventory while it's being modified in an event.

It's poor design on bukkit's part imo, but it's what we got here.
