### ISSUE TITLE
Error in the launch spigot 

### ISSUE THREAD

**Issue by Miyazaki1992** [CitizensDev/Citizens2#1317]
hello i have console error can help me please.

i let's see u, thx

[14:37:50 INFO]: [Citizens] Loaded 0 NPCs.
[14:37:50 WARN]: [Citizens] Task #73 for Citizens v2.0.22-SNAPSHOT (build 1479) generated an exception
java.lang.NullPointerException: null
        at net.citizensnpcs.Metrics$Plotter.hashCode(Metrics.java:640) ~[?:?]
        at java.util.HashMap.hash(Unknown Source) ~[?:1.8.0_144]
        at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_144]
        at java.util.HashSet.add(Unknown Source) ~[?:1.8.0_144]
        at net.citizensnpcs.Metrics$Graph.addPlotter(Metrics.java:530) ~[?:?]
        at net.citizensnpcs.npc.CitizensTraitFactory.addPlotters(CitizensTraitFactory.java:105) ~[?:?]
        at net.citizensnpcs.Citizens.startMetrics(Citizens.java:438) ~[?:?]
        at net.citizensnpcs.Citizens.access$300(Citizens.java:67) ~[?:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:307) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[14:37:50 INFO]: [Vault] You are running the latest version
[14:37:50 INFO]: [Quests] 4 Quest(s) loaded.
[14:37:50 INFO]: [Quests] 7 Event(s) loaded.
[14:37:50 INFO]: [Quests] 856 Phrase(s) loaded.
[14:37:55 INFO]: SignBoard will automatically check for and install updates.
[14:37:55 INFO]: You can control this behavior in config.yml, by changing 'updates:' to auto, check or off
[14:37:55 INFO]: You have the latest version: SignBoard version 1.3.1
[14:38:05 INFO]: [CE] Checking for updates...
[14:38:05 INFO]: [CE] You are using the latest Version of CE!
[14:38:45 INFO]: [dynmap] Loading default resource pack

**Comment by fullwall** [comment]
Fixed, but please update Citizens anyway
