### ISSUE TITLE
/npc not working?

### ISSUE THREAD

**Issue by UnrealPixel** [CitizensDev/Citizens2#1330]
Most recent version of Citizens
BUG!

/npc does not work. It does not give any error in-game or console.
It is not giving a response.

Yes I am on the right version.

I am using multiple worlds.

**Comment by UnrealPixel** [comment]
`org.bukkit.command.CommandException: Unhandled exception executing command 'npc' in plugin Citizens v2.0.18-SNAPSHOT (build 1371)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [server.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [server.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.npc.NPCSelector.getSelectedFromMetadatable(NPCSelector.java:60) ~[?:?]
        at net.citizensnpcs.npc.NPCSelector.getSelected(NPCSelector.java:45) ~[?:?]
        at net.citizensnpcs.Citizens.onCommand(Citizens.java:230) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-798f32d-0cd0397]
        ... 15 more
`
Got this error all of a sudden

**Comment by mcmonkey4eva** [comment]
Restart server, check saves file for unusual data, etc.

It'll be hard to give more full support to such an outdated build of Citizens :/

**Comment by maxi2004** [comment]
Bonjour Le plugin Citizen ne marche pas il n'y a aucun signe de vie ...
Aidez-moi plz ...
Quand je marque /npc create Rien ne se marque dans la barre de chat et dans la console. Il n'y a aucune erreur.

**Comment by fullwall** [comment]
Fixed in the latest build (which does not support 1.9).
