### ISSUE TITLE
use-new-finder crashes

### ISSUE THREAD

**Issue by Kurimatzu** [CitizensDev/Citizens2#1338]
[19:57:54 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:924) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper.jar:git-Paper-1244]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.OutOfMemoryError: Java heap space
        at net.citizensnpcs.api.astar.pathfinder.CachingChunkBlockSource.<init>(CachingChunkBlockSource.java:31) ~[?:?]
        at net.citizensnpcs.api.astar.pathfinder.CachingChunkBlockSource.<init>(CachingChunkBlockSource.java:22) ~[?:?]
        at net.citizensnpcs.api.astar.pathfinder.CachingChunkBlockSource.<init>(CachingChunkBlockSource.java:18) ~[?:?]
        at net.citizensnpcs.api.astar.pathfinder.ChunkBlockSource.<init>(ChunkBlockSource.java:9) ~[?:?]
        at net.citizensnpcs.npc.ai.AStarNavigationStrategy.update(AStarNavigationStrategy.java:84) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:164) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:158) ~[?:?]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1752) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1722) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:698) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1509) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913) ~[Paper.jar:git-Paper-1244]
        ... 4 more
[19:57:54 ERROR]:       Cause of unexpected exception was
java.lang.OutOfMemoryError: Java heap space
        at net.citizensnpcs.api.astar.pathfinder.CachingChunkBlockSource.<init>(CachingChunkBlockSource.java:31) ~[?:?]
        at net.citizensnpcs.api.astar.pathfinder.CachingChunkBlockSource.<init>(CachingChunkBlockSource.java:22) ~[?:?]
        at net.citizensnpcs.api.astar.pathfinder.CachingChunkBlockSource.<init>(CachingChunkBlockSource.java:18) ~[?:?]
        at net.citizensnpcs.api.astar.pathfinder.ChunkBlockSource.<init>(ChunkBlockSource.java:9) ~[?:?]
        at net.citizensnpcs.npc.ai.AStarNavigationStrategy.update(AStarNavigationStrategy.java:84) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:164) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:158) ~[?:?]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1752) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.World.h(World.java:1722) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.WorldServer.l(WorldServer.java:698) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1509) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:675) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:913) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[Paper.jar:git-Paper-1244]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper.jar:git-Paper-1244]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[19:57:54 ERROR]: This crash report has been saved to: C:\Users\DAVI\Desktop\Servidor\.\crash-reports\crash-2017-10-23_19.57.54-server.txt

Spigot 1.12.2 & latest Citizens version

**Comment by mcmonkey4eva** [comment]
...
`Caused by: java.lang.OutOfMemoryError: Java heap space`
Add more memory to your server to use heavier features and make room for more things loaded at once.

**Comment by Kurimatzu** [comment]
@mcmonkey4eva Using this code, observe:

if (npc.isSpawned()) {
			npc.getNavigator().getLocalParameters().range(Float.MAX_VALUE);
			npc.getNavigator().getDefaultParameters().range(Float.MAX_VALUE);
			npc.getNavigator().setTarget(new Location (Bukkit.getWorld("world") , 0 , 64 , 0));		
		}

The server does not respond and crash.

**Comment by mcmonkey4eva** [comment]
... oh
```

npc.getNavigator().getLocalParameters().range(Float.MAX_VALUE);
npc.getNavigator().getDefaultParameters().range(Float.MAX_VALUE);
```
... really?
That's nonsense code. Of course infinite range took all your RAM!
Make the range no higher than 100 under normal operation!

**Comment by Kurimatzu** [comment]
@mcmonkey4eva I didn't want him to be teleported to the location, I wanted him to walk there.

Is there another way?

**Comment by mcmonkey4eva** [comment]
Create a logical path via a plugin, and simple send points along the way... For example, every 25-or-so blocks apart, mark a point.
