### ISSUE TITLE
problem citizen skywars?

### ISSUE THREAD

**Issue by NightYuki** [CitizensDev/Citizens2#1354]
Hello in 1.9 when a npc slap a monster or i slap the npc (problem citizen / skywars)

```
[09:52:43] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to Skywars v3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:88) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:557) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:589) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1207) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity0(EntityHuman.java:839) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:816) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:763) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:512) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:120) [Citizens.jar:?]
	at net.minecraft.server.v1_9_R1.EntityMonster.B(EntityMonster.java:68) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityZombie.B(EntityZombie.java:236) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityInsentient.doTick(EntityInsentient.java:635) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.n(EntityLiving.java:1905) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityInsentient.n(EntityInsentient.java:480) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityMonster.n(EntityMonster.java:24) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityZombie.n(EntityZombie.java:175) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1761) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityMonster.m(EntityMonster.java:28) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityZombie.m(EntityZombie.java:232) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at be.isach.ultracosmetics.v1_9_R1.customentities.Pumpling.m(Pumpling.java:59) [UltraCosmetics-2.4.9-RELEASE.jar:?]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at me.wazup.skywars.SkywarsListener.onEntityDamageByEntity(SkywarsListener.java:979) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	... 37 more
[09:52:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to Skywars v3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:88) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:557) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:589) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1207) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity0(EntityHuman.java:839) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:816) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:763) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:512) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:120) [Citizens.jar:?]
	at net.minecraft.server.v1_9_R1.EntityMonster.B(EntityMonster.java:68) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityZombie.B(EntityZombie.java:236) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PathfinderGoalMeleeAttack.e(SourceFile:122) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityInsentient.doTick(EntityInsentient.java:635) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.n(EntityLiving.java:1905) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityInsentient.n(EntityInsentient.java:480) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityMonster.n(EntityMonster.java:24) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityZombie.n(EntityZombie.java:175) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1761) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityMonster.m(EntityMonster.java:28) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.EntityZombie.m(EntityZombie.java:232) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at be.isach.ultracosmetics.v1_9_R1.customentities.Pumpling.m(Pumpling.java:59) [UltraCosmetics-2.4.9-RELEASE.jar:?]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at me.wazup.skywars.SkywarsListener.onEntityDamageByEntity(SkywarsListener.java:979) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	... 37 more
```

**Comment by LoYungSum** [comment]
this is not a problem with npc, it is a problem with the skywar plugin
