### ISSUE TITLE
NPEs generated repeatedly after Sentinels attack Herobrine

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1371]
**Issue**
NPEs generated repeatedly after Sentinel NPCs attack Herobrine and associated bats and wolves.

Note that Sentinels have been working successfully and without errors for many months. This issue started with the introduction of Herobrine.

**Reproduction scenario**
* Install HB 1.7.2.
* Start server, stop server.
* Configure HB per attached config.yml (modified) and npc.yml (default).
* Start server. No startup errors.
* Connect as non-op player, in world_yellowdog (where HB is active per config.yml).
* Note that there are two wolf Sentinels nearby, Citizens ids 19 and 31. They have been configured to *ignore NPC*, but that doesn't seem to affect what follows. (In a previous test, they were configured to *ignore npc:NAME(Herobrine)*, with the same lack of positive effect).
* Note that player is position in a Factions Safe area, meaning that he cannot be harmed by mobs, although they may attack.
* Note initial **/hb position** = 0 -20 0 (which seems peculiar, since that location is below grade, but this has been repeated identically several times).
* Execute **/herobrine haunt *player*.**
* Based on the fact that multiple bats and wolf appear and are immediately attacked by the Sentinels, I assume that Herobrine is present as well, and is also under attack by the Sentinels.
* NPEs are generated immediately and continuously. Note that they are presented as WARN rather than ERROR (ERROR seems more appropriate).

**Versions**
* Spigot 1.12.2 latest build (2018-01-01)
* Herobrine 1.7.2
* Multiverse-Core 2.6.0-b734
* PermissionsEx 1.23.4
* Citizens 2.0.22-b1498
* Sentinel 1.4.5-b-155
* Factions 2.13.6
* MassiveCore 2.13.6 (required by Factions)
* 80 other plugins, all latest releases

**Errors**
```
[17:19:43] [Server thread/INFO]: [Herobrine] Herobrine is now haunting rambeau.
[17:19:51] [Server thread/INFO]: [Citizens] Exception while updating 31: null.
[17:19:51] [Server thread/WARN]: java.lang.NullPointerException
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.isTargeted(SentinelTrait.java:1656)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.shouldTarget(SentinelTrait.java:1531)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.findBestTarget(SentinelTrait.java:1733)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1855)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:2007)
[17:19:51] [Server thread/WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[17:19:51] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
[17:19:51] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_12_R1.entity.WolfController$EntityWolfNPC.M(WolfController.java:185)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:670)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2095)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityWolf.n(EntityWolf.java:152)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityWolf.B_(EntityWolf.java:167)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1601)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:19:51] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[17:19:51] [Server thread/INFO]: [Citizens] Exception while updating 19: null.
[17:19:51] [Server thread/WARN]: java.lang.NullPointerException
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.isTargeted(SentinelTrait.java:1656)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.shouldTarget(SentinelTrait.java:1531)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.findBestTarget(SentinelTrait.java:1733)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1855)
[17:19:51] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:2007)
[17:19:51] [Server thread/WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
[17:19:51] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
[17:19:51] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_12_R1.entity.WolfController$EntityWolfNPC.M(WolfController.java:185)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:670)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2095)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityAgeable.n(EntityAgeable.java:158)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityAnimal.n(EntityAnimal.java:27)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityWolf.n(EntityWolf.java:152)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1944)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.EntityWolf.B_(EntityWolf.java:167)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.World.h(World.java:1601)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[17:19:51] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[17:19:51] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
```

Cross-posted to [Sentinel](https://github.com/mcmonkey4eva/Sentinel/issues/222).

**Comment by fullwall** [comment]
Sentinel issue
