### ISSUE TITLE
Incompatibility with Paper 1.12

### ISSUE THREAD

**Issue by aikar** [CitizensDev/Citizens2#1392]
Using latest version of Citizens as of time of post.

See: https://github.com/PaperMC/Paper/issues/997#issuecomment-361128725

Can you please use the interface instead of force expecting Yggdrasril for Session Service, and can you please relay the .fillProfileProperties method to the MinecraftSessionService instead of re-implementing that logic.

By re-implementing the logic, it breaks Papers ability to fire an event for these operations.

```
[22:10:04 INFO]: Profile lookup for player 'Foo' failed: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService false
[22:10:04 INFO]: java.lang.ClassCastException: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:292)
        at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:60)
        at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81)
        at com.destroystokyo.paper.profile.WrappedGameProfileRepository$PreProfileLookupCallback.onProfileLookupSucceeded(WrappedGameProfileRepository.java:62)
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63)
        at com.destroystokyo.paper.profile.WrappedGameProfileRepository.findProfilesByNames(WrappedGameProfileRepository.java:47)
        at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
        at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Thank you.

**Comment by fullwall** [comment]
The reason we re-implement that logic is that Yggdrasil's default behaviour is to silently catch rate limiting exceptions, otherwise I'd just use the default methods.
