### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fortepsai** [CitizensDev/Citizens2#1399]
[00:19:30 ERROR]: Could not pass event EntityDamageByEntityEvent to Citizens v2.0.22-SNAPSHOT (build 1498)
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:631) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:617) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityFireball.damageEntity(EntityFireball.java:171) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:286) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-4bd94dc-c765646]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftLargeFireball cannot be cast to org.bukkit.entity.LivingEntity
at org.mcmonkey.sentinel.SentinelTrait.whenAttacksHappened(SentinelTrait.java:390) ~[?:?]
at sun.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-4bd94dc-c765646]
... 21 more

**Comment by mcmonkey4eva** [comment]
Defer to https://github.com/mcmonkey4eva/Sentinel/issues/226
