### ISSUE TITLE
Broken death animation

### ISSUE THREAD

**Issue by MrDienns** [CitizensDev/Citizens2#1403]
The death animation on an NPC when vulnerable seems to be somewhat broken.
See this GIF: https://gyazo.com/35058e156ba87abdcc521dc7d146ef94

For players it seems to be even worse:
https://gyazo.com/6aa865c464b0250dc8c7e2cfe2b45369

I'd love to see an actual full death animation like you see with normal players or monsters. Is this fixable? Using Citizens2 v2.0.22-SNAPSHOT (build 1485) and PaperSpigot 1.12 R0.1-SNAPSHOT.

Thank you.

**Comment by mcmonkey4eva** [comment]
Do you have any plugin or script that interacts with the death / combat events?

It looks like the NPC is being forcibly deleted or despawned upon receiving a fatal blow.

**Comment by MrDienns** [comment]
Thanks for the quick reply. I really appreciate it.

That was my first thought as well, however, I started up a server only with the Citizens2 (and Sentinel) plugin and the exact same behaviour occured, meaning there's no possibility of a different plugin forcefully deleting the entity right away.

**Comment by mcmonkey4eva** [comment]
There's totally a possibility there. And it does happen too! Sentinel does that. I don't remember why it does that specifically, but Sentinel listens to death and forces the NPC to despawn. I'd remove that part but I need to figure why that was added and what side effects it might cause to remove it...

**Comment by mcmonkey4eva** [comment]
... Well, nope. I removed the code in Sentinel that forcibly despawns the NPC and it just despawned instantly on death still. It also happens when Sentinel is not at all applied to an NPC.
So yeah I guess something went wrong in Citizens here... and also Sentinel reinforces it.

**Comment by oldquestman** [comment]
@MrDienns Sorry for off-topic but I just have to ask: Where can I get that awesome-looking pig-model? :o

**Comment by MrDienns** [comment]
@mcmonkey4eva Okay, thanks for taking a look at things. Saying you've removed the code that does it, does that mean this bug is confirmed? Would love to see this fixed.

@oldquestman it's from a resourcepack called Beyond the Lands.

**Comment by mcmonkey4eva** [comment]
Yes, the behavior is confirmed to be present within Citizens.
Specifically, it's right here: https://github.com/CitizensDev/Citizens2/blob/8bdadfb63589393b5c1bca7bef8cf5c0e3bfb6c5/main/src/main/java/net/citizensnpcs/EventListen.java#L245
Not sure why it's there. Likely to make it immediately respawnable after death (though that could be handled by the spawn function checking for a dead entity and removing it as a first step).
Might be other reasons for it, though.
@fullwall should know if there's any importance to that being there.

**Comment by fullwall** [comment]
This change was 5 years ago, so it's impossible to know what the motivations were as it was not commented (my bad). I have removed it now in the latest build - if there are any problems then let me know.

**Comment by MrDienns** [comment]
Awesome @fullwall! Thank you, really appreciate it. I am currently not available to test it right away. I assume you have done some basic testing to see if nothing crashes. I will let you know if it works asap.

**Comment by mcmonkey4eva** [comment]
For the sake of making that testing actually work I've committed+built the earlier experiment of removing Sentinel's death-despawn code as well.

**Comment by MrDienns** [comment]
Tested it out with the latest builds of Citizens2 and Sentinel. The actual animation is working without a hitch, however it does generate an exception in the console. See below:

```org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.die(EntityHumanNPC.java:212) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:186) [citizens-2.0.22-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:201) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at com.dyescape.DyescapeCharacters.characterclass.mage.skills.arcanist.models.ArcaneMissile.run(ArcaneMissile.java:64) [DyescapeCharacters-3.0.0-INDEV.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:243) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        ... 19 more```

**Comment by mcmonkey4eva** [comment]
A relevant fix was pushed, can you test latest build?

**Comment by MrDienns** [comment]
Apologies for the delay.

It's still causing errors on the latest build that I just downloaded.

```
[18:45:49 ERROR]: Could not pass event PlayerDeathEvent to Citizens v2.0.22-SNAPSHOT (build 1504)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.die(EntityHumanNPC.java:212) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:186) [citizens-2.0.22-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:201) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at com.dyescape.DyescapeCharacters.characterclass.mage.skills.arcanist.ArcaneBolt$1.run(ArcaneBolt.java:67) [DyescapeCharacters-3.0.0-INDEV.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.getVehicle(NMSImpl.java:554) ~[?:?]
        at net.citizensnpcs.util.NMS.getVehicle(NMS.java:151) ~[?:?]
        at net.citizensnpcs.trait.MountTrait.onDespawn(MountTrait.java:38) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:91) ~[?:?]
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:245) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        ... 19 more
```

**Comment by MrDienns** [comment]
Still getting this error on the latest build:

```[18:56:23 ERROR]: Could not pass event PlayerDeathEvent to Citizens v2.0.22-SNAPSHOT (build 1504)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:423) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.die(EntityHumanNPC.java:212) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:186) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:210) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.livingEntityBaseTick(EntityHumanNPC.java:349) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:135) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1027) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:293) [citizens-2.0.22-SNAPSHOT.jar:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [citizens-2.0.22-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.getVehicle(NMSImpl.java:554) ~[?:?]
        at net.citizensnpcs.util.NMS.getVehicle(NMS.java:151) ~[?:?]
        at net.citizensnpcs.trait.MountTrait.onDespawn(MountTrait.java:38) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:91) ~[?:?]
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:245) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-e3b4cf5]
        ... 24 more```

**Comment by fullwall** [comment]
@MrDienns latest build should fix the NPE. If there is a problem with the fix please open another issue.
