### ISSUE TITLE
Not working with 1.9.4...

### ISSUE THREAD

**Issue by TheColdEmeraldCODE** [CitizensDev/Citizens2#1420]
I downgraded I upgraded but almost nothing seems to work with Minecraft 1.9.4! I even have via version and it won't work! Whats the problem!?

**Comment by mcmonkey4eva** [comment]
Run latest versions of all plugins and software. Spigot 1.12.2 latest and everything to match

**Comment by TheColdEmeraldCODE** [comment]
Can I stay at 1.9.4?

**Comment by mcmonkey4eva** [comment]
Why would you?

**Comment by TheColdEmeraldCODE** [comment]
Because Via Version ([](https://www.spigotmc.org/resources/viaversion.19254/)) Makes all of it mostly compatible

**Comment by mcmonkey4eva** [comment]
... But why not just run 1.12.2 with ViaVersion and ViaBackwards?

**Comment by TheColdEmeraldCODE** [comment]
ViaBackwards seems to work but there's A TON of BIG problems! /plugins doesnt work /help doesnt work, almost nothing works...

**Comment by mergu** [comment]
I disagree. I run ViaBackwards from an always up-to-date server and everything works just fine. Players like that we're always running the latest version. You're missing out on a LOT of content by running 1.9.4

**Comment by TheColdEmeraldCODE** [comment]
Then can you give me some tips on why it's not working? (my server IP is 1.9.4)

**Comment by mergu** [comment]
It's not working because you're running an outdated server version

**Comment by TheColdEmeraldCODE** [comment]
No why ViaBackwards Is not working so well.. ERRORS:
`[04:14:14 ERROR]: Ambiguous plugin name `PixelPrinter' for files `plugins/PixelPrinter+v1.0.24.jar' and `plugins/PixelPrinter v1.0.24.jar' in `plugins' [04:14:14 ERROR]: Ambiguous plugin name `WorldGuard' for files `plugins/worldguard-6.1.2.jar' and `plugins/worldguard-6.2.1.jar' in `plugins' [04:14:24 ERROR]: false [04:14:24 ERROR]: Error occurred while enabling killStats v3.0 (Is it up to date?) [04:14:31 ERROR]: Error occurred while enabling WorldGuard v6.1.2;e38d98d (Is it up to date?) [04:14:49 ERROR]: Not successfull! Disabling ASkyBlock!`

**Comment by mcmonkey4eva** [comment]
Those errors you posted are incredibly simple to fix, apply some brain to it.

**Comment by TheColdEmeraldCODE** [comment]
I fixed the errors but the commands... saying an internal error occurred

**Comment by mcmonkey4eva** [comment]
... What's the actual error in console?

**Comment by TheColdEmeraldCODE** [comment]
`[17:59:54] [Server thread/INFO]: TheColdEmerald issued server command: /gmc
[17:59:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'gmc' in org.bukkit.command.PluginCommand(gamemode, Essentials vTeamCity)
	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:102) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/util/Java15Compat
	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
	... 14 more`

**Comment by mcmonkey4eva** [comment]
You're using horrendously outdated plugins. That error is from `me.incomprehendable.dev.pwp` which is broken from age.

**Comment by TheColdEmeraldCODE** [comment]
What plugin is it from?

**Comment by mcmonkey4eva** [comment]
If you google `me.incomprehendable.dev.pwp` you see a few mentions of Per-World-Plugins, which fits the `pwp` name, alongside many other reports of that and similar errors.

**Comment by TheColdEmeraldCODE** [comment]
Soo that's what it is, is there anything like PerWorldPlugins but up-to-date?

**Comment by mcmonkey4eva** [comment]
Probably. Search around Spigot plugin pages.

**Comment by TheColdEmeraldCODE** [comment]
thx i fixed it!
