### ISSUE TITLE
java.lang.NoSuchMethodError when issuing "/npc mount"

### ISSUE THREAD

**Issue by ChuckxxNorris** [CitizensDev/Citizens2#1430]
I want to use your awesome Citizens API to create a Plugin with an Enderdragon able to be used as a mount.

For this, I was testing around with the commands and when I issued "/npc" mount to get on the Dragon I got the following Crash (java.lang.NoSuchMethodError).

[22:36:04] [Server thread/INFO]: ChuckxxNorris issued server command: /npc mount
[22:36:04] [Server thread/WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_8_R1.EntityPlayer.setPassengerOf(Lnet/minecraft/server/v1_8_R1/Entity;)V
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.trait.Controllable.enterOrLeaveVehicle(Controllable.java:79)
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.trait.Controllable.mount(Controllable.java:129)
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.mount(NPCCommands.java:754)
[22:36:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:36:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:36:04] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:36:04] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[22:36:04] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[22:36:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:36:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:36:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[22:36:04] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:36:04] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[22:36:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[22:36:04] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

I am on Minecraft 1.8 using latest Citizens version for 1.8.1.

I hope someone can help me. I would have written this into a forum, but there is any working link on your site :D.

Greetings

**Comment by mcmonkey4eva** [comment]
Update your server. You're running an older version of Citizens for a version of Minecraft that is 4 years old.

Just run latest like a sane person.

**Comment by ChuckxxNorris** [comment]
So you mean I should use Minecraft 1.10 or above?
Is this not going to work for Minecraft 1.8?

I am sorry if I misunderstood you I am not a native speaker.

Anyways thank you for your reply! I hope you can also help me with my questions above. :)

**Comment by mcmonkey4eva** [comment]
Use 1.12.2 latest.

Minecraft 1.8 (especially the broken version you're using) is incredibly old and unsupported.

**Comment by ChuckxxNorris** [comment]
Ok, thank you very much for your help! 👍 :)

I thought it would be no problem because I do not think very good about the new Combat System.
