### ISSUE TITLE
New NPC Skins not loading

### ISSUE THREAD

**Issue by Matt5067** [CitizensDev/Citizens2#1436]
I cannot load skins for newly created NPCS. This is the error I get when I turn on debug mode:

`[04:45:51 INFO]: Profile lookup for player 'matt5067' failed2: null
[04:45:51 INFO]: com.mojang.authlib.exceptions.AuthenticationException
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenti|
cationService.java:79)                                                                              |
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(Yggdrasil
GameProfileRepository.java:54)
        at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
        at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

Is there any way to fix this? Is it a citizens issue or a mojang issue? Thanks.

MC Version: 1.12.2

**Comment by fullwall** [comment]
Seems like a mojang issue.

**Comment by mcmonkey4eva** [comment]
It looks like their server had an error (an NPE serverside).
