### ISSUE TITLE
Can't save npcs

### ISSUE THREAD

**Issue by nobodypromi** [CitizensDev/Citizens2#1441]
Everytime i want to save my created npcs there comes this error.
If i reload then it doesn't saves the npcs. :(

**LOG:**
[14:34:47 WARN]: java.lang.NullPointerException
[14:34:47 WARN]: 	at net.dandielo.core.items.dItem.serialize(dItem.java:94)
[14:34:47 WARN]: 	at net.dandielo.citizens.traders_v3.traders.stock.StockItem.toString(StockItem.java:86)
[14:34:47 WARN]: 	at net.dandielo.citizens.traders_v3.traders.stock.StockTrader.save(StockTrader.java:117)
[14:34:47 WARN]: 	at net.dandielo.citizens.traders_v3.traits.TraderTrait.save(TraderTrait.java:70)
[14:34:47 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:340)
[14:34:47 WARN]: 	at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:146)
[14:34:47 WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:80)
[14:34:47 WARN]: 	at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:438)
[14:34:47 WARN]: 	at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:443)
[14:34:47 WARN]: 	at net.citizensnpcs.commands.AdminCommands.save(AdminCommands.java:64)
[14:34:47 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:34:47 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:34:47 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:34:47 WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:34:47 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[14:34:47 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[14:34:47 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[14:34:47 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[14:34:47 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:34:47 WARN]: 	at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98)
[14:34:47 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[14:34:47 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:34:47 WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[14:34:47 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[14:34:47 WARN]: 	at java.lang.Thread.run(Unknown Source)

Citizens: 2.0.17 (alpha 1 for MC 1.9)
MC-Server: Spigot 1.9

**Comment by fullwall** [comment]
net.dandielo
