### ISSUE TITLE
Skins not loading

### ISSUE THREAD

**Issue by DarkObscurity** [CitizensDev/Citizens2#1445]
Hello!

Since yesterday for some reason the skins from new NPC's arren't  loaded. I have tried to reset Citizens and stuff, but it didn't help. I also looked it up, but the error I got from the debug file was different then from what I could find.

My citizens version is: 2.0.22-SNAPSHOT
Minecraft version 1.12.2

Debug Log:
2018-03-17 18:32:56 [INFO] Fetched profile c138890d-b483-4629-9924-ec2f6717c6ca for player Fortist
2018-03-17 18:32:56 [INFO] Profile lookup for player 'Fortist' failed: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService false
2018-03-17 18:32:56 [INFO] java.lang.ClassCastException: com.destroystokyo.paper.profile.WrappedMinecraftSessionService cannot be cast to com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService
	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.fillProfileProperties(NMSImpl.java:292)
	at net.citizensnpcs.util.NMS.fillProfileProperties(NMS.java:60)
	at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupSucceeded(ProfileFetcher.java:81)
	at com.destroystokyo.paper.profile.WrappedGameProfileRepository$PreProfileLookupCallback.onProfileLookupSucceeded(WrappedGameProfileRepository.java:62)
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:63)
	at com.destroystokyo.paper.profile.WrappedGameProfileRepository.findProfilesByNames(WrappedGameProfileRepository.java:47)
	at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
	at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Is there maybe any idea what is causing this?

**Comment by mcmonkey4eva** [comment]
Run Spigot, not Paper.

**Comment by DarkObscurity** [comment]
Why would that be a problem all of a sudden? it worked and suddenly it doesn't anymore...

**Comment by mcmonkey4eva** [comment]
Running paper has always been a problem, it's just not always immediately breaking.
In this case it's related as they broke skin lookup code a bit.

The most immediate fix for your issue is to update server and all plugins to latest dev releases, but it's worthwhile to note that you should switch to Spigot instead of Paper for more consistent support and functionality.

**Comment by Baktus79** [comment]
I am experience the same problem @DarkObscurity is talking about. And Citizen har always worked perfectly on my Paper server. This has never before been an issue. The issue started at the same time Mojang changed the way for a server to download skins from a third party plugin.

At that time more plugins broke because of this, but they all fixed it and works perfectly fine with Paper. Running Paper for me has always been the best choice cuz of many things, and I will not change my server to Spigot.

**Comment by Baktus79** [comment]
I want to add that the issue is solved with the latest snapshot :)

**Comment by mcmonkey4eva** [comment]
It was solved in a semi-recent Citizens patch by adding a special case handler for Paper breaking API contracts and general assumptions. This error only ever existed on Paper, because of Paper breaking things intentionally and refusing to fix them.
The ideal solution is for nobody to ever use Paper.
