### ISSUE TITLE
NPC Path triggers

### ISSUE THREAD

**Issue by STiCory** [CitizensDev/Citizens2#145]
CraftBukkit version git-Spigot-fef4168 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Citizens 2.0.14-SNAPSHOT (build 1190)

What I am attempting to create is an NPC that will randomly announce "Follow me to the Blackmsith" and then when left or right clicked will walk a path leading to the blacksmith, announcing a different text at each chosen waypoint, then when he reaches the final waypoint, he should say "bye" or something, and then return to his station at the start and wait until the next person clicks him.

Here is a sequence of events that I feel should start with what I need, I already have the random announcement of chat "Follow me to the blacksmith!" working fine, but I can't get any of the actual path to work correctly:

/npc select
/npc path
*left click bock in front of him*
*left click block 5 blocks away*
triggers
add
animation
ARM_SWING
finish
Console error:
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:
213) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at com.google.common.collect.Lists.newArrayList(Lists.java:127) ~[spigot
-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at net.citizensnpcs.trait.waypoint.triggers.AnimationTrigger.<init>(Anim
ationTrigger.java:25) ~[?:?]
        at net.citizensnpcs.trait.waypoint.triggers.AnimationTriggerPrompt.accep
tInput(AnimationTriggerPrompt.java:26) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:2
29) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at org.bukkit.craftbukkit.v1_8_R1.conversations.ConversationTracker.acce
ptConversationInput(ConversationTracker.java:58) [spigot-1.8-R0.1-SNAPSHOT.jar:g
it-Spigot-fef4168]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.acceptConversationI
nput(CraftPlayer.java:1031) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at net.minecraft.server.v1_8_R1.PlayerConnection$2.evaluate(PlayerConnec
tion.java:932) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at org.bukkit.craftbukkit.v1_8_R1.util.Waitable.run(Waitable.java:24) [s
pigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:7
03) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
16) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
27) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:530) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-fef4168]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

then the only way to get out of this is to hit /npc path then /npc path again, and then "clear" to get him to stop running around, then /npc path again to exit.

**Comment by fullwall** [comment]
Fixed, sorry for the delay.
