### ISSUE TITLE
Citizens Error After NPC is Right Clicked (after updating from Spigot 1.12 to 1.12.2)

### ISSUE THREAD

**Issue by Tiago1098** [CitizensDev/Citizens2#1491]
On Citizens after updating from Spigot 1.12 to 1.12.2 every time I rigth click an NPC the following 
error happens.

Spigot Version: CraftBukkit version git-Spigot-2086bb0-ca057a3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Citizens Version: Citizens v2.0.22-SNAPSHOT (build 1541)

Plugins Installed: Plugins (33): TitleMotd, Languages, PlaceholderAPI, Scoreboard, FireBalls, Multiverse-Core, VoidSpawn, Friends3_0, FastAsyncWorldEdit, VoidGenerator, Multiverse-Inventories, LobbyBow, PermissionsEx, ViaVersion, LobbyCompass, Vault, ViaBackwards, ViaRewind, WorldEdit, Essentials, UltraCosmetics, pvparena, ProtocolLib, WorldGuard, NoCheatPlus, KitAdder, Citizens, EditableSign, EssentialsChat, HolographicDisplays, BetterNick, CitizensCMD, Skywars

The error:
```
15:33:43 [ERROR] Could not pass event PlayerInteractAtEntityEvent to WorldGuard v6.2.1;84bc322
15:33:43 org.bukkit.event.EventException: null
15:33:43 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
15:33:43 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
15:33:43 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
15:33:43 Caused by: java.lang.NullPointerException
15:33:43 at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at com.sk89q.worldguard.bukkit.event.inventory.UseItemEvent.<init>(UseItemEvent.java:48) ~[?:?]
15:33:43 at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteractEntity(EventAbstractionListener.java:684) ~[?:?]
15:33:43 at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener$SpigotCompatListener.onPlayerInteractAtEntity(EventAbstractionListener.java:1007) ~[?:?]
15:33:43 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
15:33:43 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 ... 15 more
15:33:43 [ERROR] Could not pass event PlayerInteractEntityEvent to WorldGuard v6.2.1;84bc322
15:33:43 org.bukkit.event.EventException: null
15:33:43 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
15:33:43 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
15:33:43 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
15:33:43 Caused by: java.lang.NullPointerException
15:33:43 at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at com.sk89q.worldguard.bukkit.event.inventory.UseItemEvent.<init>(UseItemEvent.java:48) ~[?:?]
15:33:43 at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteractEntity(EventAbstractionListener.java:684) ~[?:?]
15:33:43 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
15:33:43 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 ... 15 more
15:33:43 [ERROR] Could not pass event NPCRightClickEvent to Citizens v2.0.22-SNAPSHOT (build 1541)
15:33:43 org.bukkit.event.EventException: null
15:33:43 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:416) [citizens-2.0.22-SNAPSHOT.jar:?]
15:33:43 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
15:33:43 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:43 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:43 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
15:33:44 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
15:33:44 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
15:33:44 Caused by: java.lang.NullPointerException
15:33:44 at net.citizensnpcs.util.Util.matchesItemInHand(Util.java:181) ~[?:?]
15:33:44 at net.citizensnpcs.npc.NPCSelector.onNPCRightClick(NPCSelector.java:98) ~[?:?]
15:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
15:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 ... 24 more
15:33:44 [INFO] TheGameratorT issued server command: /lobbycompass
15:33:44 [ERROR] Could not pass event PlayerInteractAtEntityEvent to WorldGuard v6.2.1;84bc322
15:33:44 org.bukkit.event.EventException: null
15:33:44 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
15:33:44 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
15:33:44 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
15:33:44 Caused by: java.lang.NullPointerException
15:33:44 at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at com.sk89q.worldguard.bukkit.event.inventory.UseItemEvent.<init>(UseItemEvent.java:48) ~[?:?]
15:33:44 at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteractEntity(EventAbstractionListener.java:684) ~[?:?]
15:33:44 at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener$SpigotCompatListener.onPlayerInteractAtEntity(EventAbstractionListener.java:1007) ~[?:?]
15:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
15:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 ... 15 more
15:33:44 [ERROR] Could not pass event PlayerInteractEntityEvent to WorldGuard v6.2.1;84bc322
15:33:44 org.bukkit.event.EventException: null
15:33:44 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1580) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
15:33:44 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
15:33:44 at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
15:33:44 Caused by: java.lang.NullPointerException
15:33:44 at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 at com.sk89q.worldguard.bukkit.event.inventory.UseItemEvent.<init>(UseItemEvent.java:48) ~[?:?]
15:33:44 at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onPlayerInteractEntity(EventAbstractionListener.java:684) ~[?:?]
15:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
15:33:44 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
15:33:44 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
15:33:44 ... 15 more

```

**Comment by mcmonkey4eva** [comment]
As far as I can tell, you somehow managed to have a null item in hand... an issue that has nothing to do with Citizens in particular.

**Comment by Tiago1098** [comment]
So clearing inventory will fix that?

**Comment by mcmonkey4eva** [comment]
You might try to figure out how you managed to have a null item in hand ... perhaps your inventory was modified by a broken item managing plugin?

**Comment by Tiago1098** [comment]
I dunno if I have a sword in hand everything works fine but if I have nothing it bugs, maybe its Multiverse-Inventories, I will check it

**Comment by Tiago1098** [comment]
nope, i removed the plugin and still bugging maybe the world got a bit corrupted

**Comment by Tiago1098** [comment]
thx for the help I will now close the thread
