### ISSUE TITLE
Option to delay skin fetching at start-up.

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#1497]
Paper dev 1462 (Spigot 1.12.2)
Citizens v2.0.22-SNAPSHOT (build 1543)

Despite ``` use-latest-by-default: false``` being set in the main config to disable skin fetching, Citizens _still_ seems to fetch skins every time they are loaded. As I get this profile look-up error due to too many requests every single time I restart my server, always after citizens being loaded.

Would it be possible to have an option to delay skin look-up a bit at start-up?
```
[04:53:05] [Server thread/INFO]: [Citizens] Loaded 62 NPCs.
[04:53:06] [Head Conversion Thread - 2/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3e3be0ca[id=0d6e7f2b-b16e-4e2e-9f47-uuidcensored,name=player,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.12.2.jar:git-Paper-1424]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [patched_1.12.2.jar:git-Paper-1424]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) [patched_1.12.2.jar:git-Paper-1424]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [patched_1.12.2.jar:git-Paper-1424]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:79) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:46) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [patched_1.12.2.jar:git-Paper-1424]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:206) [patched_1.12.2.jar:git-Paper-1424]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:203) [patched_1.12.2.jar:git-Paper-1424]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by mibby** [comment]
That's what I thought but I was told it was a plugin issue. :( It always occurs after Citizens loads npcs and I do have an npc with the skin of the player being looked up, so I thought it was perhaps a Citizens cause.
https://github.com/PaperMC/Paper/issues/1126

**Comment by mcmonkey4eva** [comment]
They specifically exclude Citizens as a potential issue in that reply there.
`for skulls improperly generated using a command or from skulls actively being updated by a plugin.`
