### ISSUE TITLE
NPC Sit animation sends uncontainable error messages

### ISSUE THREAD

**Issue by CortesiRaccoon** [CitizensDev/Citizens2#1523]
Hello,
what I did on my server was enabling npc path to try it, and what I did was:
- /npc create <name>
- /npc path
- triggers
- animation
- sit
- (I selected a block where i wanted the npc to sit)
- finish
- (then I set another waypoint next to number one)
The npc follows waypoint Nr. 2, then goes back, sits and I get all of these error messages that will not go away even if i remove the npc:
`INFO 06/17/2018 09:01:38
09:01:38[Citizens] Exception while updating 555: null.
WARN 06/17/2018 09:01:38
09:01:38java.lang.NullPointerException
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:464)
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:461)
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$5.update(NMSImpl.java:518)
at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:77)
at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:164)
at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:274)
at net.citizensnpcs.nms.v1_12_R1.entity.nonliving.ArmorStandController$EntityArmorStandNPC.B_(ArmorStandController.java:77)
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1777)
at net.minecraft.server.v1_12_R1.World.h(World.java:1747)
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1562)
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:678)
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:914)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
at java.lang.Thread.run(Thread.java:745)`
I have no idea what triggers it, I even tried removing plugins that could conflict with it like ArmourStandTools and Chairs. My full plugin list is: ArmourStandTools, BetterChairs, Citizens, CoreProtect, DiscordSRV, dynmap, EasyElevator, Essentials, Lift, Lottery, LuckPerms, Multiverse, MyWarp, PlaceholderAPI, ProtocolLib, pvparena, TimeIsMoney, uCars, VanishNoPacket, Vault, VentureChat, VPNGuard, WorldBorder, WorldEdit, WorldGuard.
Server version is: Paper Spigot 1.12.2-R0.1-SNAPSHOT
Citizens version is 2.0.22-SNAPSHOT (build 1487)
I'm using the default config file for citizens.

Thank you and have a great day.

**Comment by CortesiRaccoon** [comment]
also,
I tried this with the latest version of citizens too and it still doesn't work

**Comment by mcmonkey4eva** [comment]
Can you post the error output as given by latest build from http://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
Please reply below with that error output when you have it, will reopen the issue then
