### ISSUE TITLE
1.13 Update

### ISSUE THREAD

**Issue by mcmonkey4eva** [CitizensDev/Citizens2#1534]
Hey! The latest dev builds of Citizens (version 2.0.23) at http://ci.citizensnpcs.co/job/Citizens2/ now have initial support for Minecraft 1.13!

The final build before this update started is http://ci.citizensnpcs.co/job/Citizens2/1552/ 

Since this is a rather major Minecraft update (a lot of internals have been changed) I'm posting this to give notice to be extra careful with these builds for the moment, and test them with care before putting them anywhere near a live server.

Anyone interested, it would be very helpful to test the latest builds on both 1.13 spigot (to test the new version's functionality), and 1.12.2 spigot (to ensure that the updates made to Citizens don't damage older versions).

If you encounter any issues while testing, please post them as a reply to this post, or as a new issue post (in which case, please link to the new post in a reply here). Please also read through any current issues posted below before posting (to avoid duplicate posts).

**Comment by mcmonkey4eva** [comment]
I believe https://github.com/CitizensDev/Citizens2/issues/1535 from @mibby is an issue to be tracked here (1.13 builds not compatible in 1.12 due to `Material.matchMaterial(String)` call usage at `net.citizensnpcs.util.Util.matchesItemInHand(Util.java:181)`

**Comment by mcmonkey4eva** [comment]
Needed fix for 1.13 to even work: https://github.com/CitizensDev/Citizens2/pull/1536

**Comment by TheIntelloBox** [comment]
Hi ! Does 1.13 work well with the latest dev build of Citizens ?

**Comment by mcmonkey4eva** [comment]
@TheIntelloBox I'm... not sure why you're posting that question. Read the post at the top of the thread?

**Comment by Capri205** [comment]
Seeing this in the log:

[22:11:46] [Server thread/INFO]: [Citizens] Could not fetch NMS field b: [[b.

If you figure out the new NMS mappings from 1.12 to 1.13 let me know as I need these also for an NPC shop plugin I maintain!

Also seeing traits not get loaded, but not sure if that's because all plugins aren't back yet:

[22:04:23] [Server thread/ERROR]: [Citizens] The trait skeletontype failed to load for NPC ID: 30.
[22:04:23] [Server thread/ERROR]: [Citizens] The trait sneaking failed to load for NPC ID: 156.
[22:04:24] [Server thread/ERROR]: [Citizens] The trait sitting failed to load for NPC ID: 374.
[22:04:24] [Server thread/INFO]: [Citizens] Loaded 257 NPCs.

**Comment by mcmonkey4eva** [comment]
Need support for new 1.13 items: https://github.com/CitizensDev/Citizens2/issues/1550

**Comment by fullwall** [comment]
@Capri205 I don't get this error. Are you on 1.12 by mistake?

**Comment by Capri205** [comment]
I should have included versions. My apologies:

[07:29:44] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1503de9-200b239 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[07:29:50] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.23-SNAPSHOT (build 1562)
[07:29:50] [Server thread/INFO]: [Sentinel] Loading Sentinel v1.6.0 (build 173)
[07:29:57] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.23-SNAPSHOT (build 1562)
[07:30:23] [Server thread/ERROR]: [Citizens] The trait skeletontype failed to load for NPC ID: 30.
[07:30:24] [Server thread/ERROR]: [Citizens] The trait sneaking failed to load for NPC ID: 156.
 . hundreds of these .
[07:30:25] [Server thread/INFO]: [Citizens] Loaded 257 NPCs.
[07:32:36] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.23-SNAPSHOT (build 1562)
[07:32:38] [Server thread/INFO]: [Citizens] Could not fetch NMS field b: [[b.

Looks to be during the disable plugin cycle

**Comment by fullwall** [comment]
Can you please turn debug mode on for the loading error?

**Comment by Capri205** [comment]
The only thing in the log that matches the timing of trait errors are these:

2018-08-08 08:10:44 [INFO] Retrying spawn of 60 later due to chunk being unloaded. Util.isLoaded false
2018-08-08 08:10:44 [INFO] Stored 60 for respawn from NPCNeedsRespawnEvent
2018-08-08 08:10:44 [INFO] Retrying spawn of 75 later due to chunk being unloaded. Util.isLoaded false
2018-08-08 08:10:44 [INFO] Stored 75 for respawn from NPCNeedsRespawnEvent

Some exceptions due to missing profiles for some NPC's, but nothing else of note.

**Comment by fullwall** [comment]
Wait those aren't Citizens2 traits... @mcmonkey4eva ?

**Comment by Capri205** [comment]
Ah. I missed one link. I was still pointing to 1.0.2 snapshot for the player server. Sorry for wasting your time.

All good except for the one trait which I will ask the user to fix.

[10:45:46] [Server thread/ERROR]: [Citizens] The trait skeletontype failed to load for NPC ID: 30.
[10:45:48] [Server thread/INFO]: [Citizens] Loaded 257 NPCs.

Thanks a lot, and a big thanks for the speedy updates to 1.13.

**Comment by mcmonkey4eva** [comment]
Likely 1.13 error (reported by Discord user `Reemik#7489`: https://pastebin.com/ZewdU7vH
`/citizens save` error, likely from item handling changes:
```
[22:58:40] [Server thread/WARN]: java.lang.NullPointerException
[22:58:40] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:33)
[22:58:40] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.load(CraftBanner.java:1)
[22:58:40] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:39)
[22:58:40] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R1.block.CraftBanner.<init>(CraftBanner.java:26)
[22:58:40] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_13_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:374)
[22:58:40] [Server thread/WARN]:    at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:446)
[22:58:40] [Server thread/WARN]:    at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:279)
[22:58:40] [Server thread/WARN]:    at net.citizensnpcs.api.trait.trait.Inventory.save(Inventory.java:143)
[22:58:40] [Server thread/WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:339)
[22:58:40] [Server thread/WARN]:    at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:154)
```

**Comment by mcmonkey4eva** [comment]
Phantom entity handling error in 1.13: https://github.com/CitizensDev/Citizens2/issues/1554

**Comment by mcmonkey4eva** [comment]
1.13 material handling has back-compat issues with 1.12.2 (and older versions):
https://github.com/CitizensDev/Citizens2/issues/1534
```

java.lang.NoSuchFieldError: TURTLE_HELMET
at net.citizensnpcs.editor.GenericEquipper.(GenericEquipper.java:82) ~[?:?]
at net.citizensnpcs.editor.EquipmentEditor.onPlayerInteractEntity(EquipmentEditor.java:99) ~[?:?]
```

**Comment by IvIurdoc** [comment]
Looks like there's an issue with trying to equip a playerhead onto an NPC using the npc equip/right click feature. Saying "helmet" while holding the playerhead works, however.

**Comment by mcmonkey4eva** [comment]
1.13 Citizens builds are relatively stable at this point - please open any 1.13 issue as regular issues.

**Comment by rentexfamily** [comment]
I have a this problem on my server. 

> [22:54:48 INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1591)
> [22:54:48 INFO]: Creating file: config.yml
> [22:54:48 ERROR]: [Citizens] v2.0.24-SNAPSHOT (build 1591) is not compatible with Minecraft v1_13_R1 - try upgrading or downgrading Citizens. Disabling.
> [22:54:48 INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1591)
> [22:54:48 INFO]: [ColoredTags] Enabling ColoredTags v2.1.3
> [22:54:48 INFO]: [Quests] Enabling Quests v3.4.0-b493
> [22:54:48 ERROR]: Error occurred while enabling Quests v3.4.0-b493 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensPlugin
at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:398) ~[?:?]
at me.blackvein.quests.Quests.onEnable(Quests.java:183) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.reload(CraftServer.java:799) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.Bukkit.reload(Bukkit.java:528) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensPlugin
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-fe3ab0d-162bda9]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
... 25 more



**HELP PLEASE!**

**Comment by mcmonkey4eva** [comment]
@rentexfamily update your server.

1.13 (flat) and 1.13.1 are irrelevant/unsupported server builds. You need 1.13.2

**Comment by rentexfamily** [comment]
can i get the link for download please?

pet, 16. stu 2018. 23:16 mcmonkey4eva <notifications@github.com> je napisao:

**Comment by mcmonkey4eva** [comment]
http://ci.citizensnpcs.co/job/Citizens2/

**Comment by rentexfamily** [comment]
Now i installed Spigot-1.13.2.jar and Citizens not working..
In Console says *java version "1.8.0_181"*
*Java(TM) SE Runtime Environment (build 1.8.0_181-b13)*
*Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)*
*:/home/container$ java -Xms128M -Xmx2069M -jar spigot.jar*
**** Error, this build is outdated ****
**** Please download a new build as per instructions from
https://www.spigotmc.org/ <https://www.spigotmc.org/> ****
**** Server will start in 20 seconds ****
*Loading libraries, please wait...*

Plugin Quest is not working now...

pet, 16. stu 2018. u 23:56 mcmonkey4eva <notifications@github.com> napisao
je:

**Comment by rentexfamily** [comment]
Can you send link of jar file spigot for stable 1.13.2?


sub, 17. stu 2018. u 11:16 Rentex <rentexfamily@gmail.com> napisao je:

**Comment by Joakimbeijer** [comment]
I have Citizens-2.0.24-b1612 and running latest 1.13.2 Spigot.
But Citizens is red in my pluginlist and not working.
What is wrong?

**Comment by mcmonkey4eva** [comment]
@Joakimbeijer look in your server log for an error - when you find one, post a _new_ issue (not on this one) with the error message
