### ISSUE TITLE
Could not pass event NPCRightClickEvent to Citizens

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#1535]
Paper dev 1504 (Spigot 1.12.2)
Citizens dev 1555
Denizens dev 395
Sentinels dev 170

```
[06:37:19] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.23-SNAPSHOT (build 1555)
java.lang.NoSuchMethodError: org.bukkit.Material.matchMaterial(Ljava/lang/String;Z)Lorg/bukkit/Material;
	at net.citizensnpcs.util.Util.matchesItemInHand(Util.java:181) ~[?:?]
	at net.citizensnpcs.npc.NPCSelector.onNPCRightClick(NPCSelector.java:98) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor319.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1504]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1504]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1504]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1504]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:418) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor340.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1504]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1504]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1504]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1504]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1663) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1504]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1504]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1504]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by mcmonkey4eva** [comment]
Should be fixed in https://github.com/CitizensDev/Citizens2/commit/9adf755b8ba59f78a4eaf57b40664a808d1abf23 (dev build 1556)
