### ISSUE TITLE
NPE on start-up with missing worlds

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1538]
```
>version
[09:07:36 INFO]: This server is running CraftBukkit version git-Spigot-a85f7ec-5870145 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[09:07:36 INFO]: You are running the latest version
>version Citizens
[09:07:39 INFO]: Citizens version 2.0.23-SNAPSHOT (build 1560)
[09:07:39 INFO]: Website: http://www.citizensnpcs.co
[09:07:39 INFO]: Authors: aPunch and fullwall
>version Sentinel
[09:07:45 INFO]: Sentinel version 1.6.0 (build 172)
[09:07:45 INFO]: Author: mcmonkey
```
```
[09:03:44] [Server thread/WARN]: [Sentinel] Task #14 for Sentinel v1.6.0 (build 172) generated an exception
java.lang.NullPointerException: null
        at net.citizensnpcs.nms.v1_13_R1.entity.MobEntityController.createEntity(MobEntityController.java:27) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:198) ~[?:?]
        at org.mcmonkey.sentinel.SentinelPlugin$1.run(SentinelPlugin.java:104) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar-2018-07-23-0652:git-Spigot-a85f7ec-5870145]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar-2018-07-23-0652:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar-2018-07-23-0652:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar-2018-07-23-0652:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar-2018-07-23-0652:git-Spigot-a85f7ec-5870145]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar-2018-07-23-0652:git-Spigot-a85f7ec-5870145]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

I am engaged in 1.13 plugin testing, so most worlds are not present (hidden safely away). Citizens got the NPE when attempting to reference a missing world. With the references (temporarily) removed from Citizens/saves.yml, there is no error. So basically a user error, but still...

Obviously, the priority of this issue is very small.

**Comment by fullwall** [comment]
Latest build should fail silently now.

**Comment by SlimeDog** [comment]
Thanks.
