### ISSUE TITLE
Error after /npc tp

### ISSUE THREAD

**Issue by NetyTV** [CitizensDev/Citizens2#1547]
Hello, it probably started by command /npc tp and then there was a much of these errors:

```
[11:00:48] [Server thread/INFO]: Nety issued server command: /npc tp
[11:00:48] [Server thread/INFO]: [Citizens] Exception while updating 73: yaw must be finite.
[11:00:48] [Server thread/WARN]: java.lang.IllegalArgumentException: yaw must be finite
[11:00:48] [Server thread/WARN]: at org.bukkit.Location.checkFiniteFloat(Location.java:613)
[11:00:48] [Server thread/WARN]: at org.bukkit.Location.setYaw(Location.java:191)
[11:00:48] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.getLocation(CraftEntity.java:193)
[11:00:48] [Server thread/WARN]: at net.citizensnpcs.trait.CurrentLocation.run(CurrentLocation.java:24)
[11:00:48] [Server thread/WARN]: at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:425)
[11:00:48] [Server thread/WARN]: at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:225)
[11:00:48] [Server thread/WARN]: at net.citizensnpcs.npc.entity.EntityHumanNPC.s_(EntityHumanNPC.java:244)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1374)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.World.g(World.java:1352)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1222)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:539)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)
[11:00:48] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517)
[11:00:48] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
```

The output of command `/version` on my server is: 

`This server is running CraftBukkit version git-Bukkit-ee6d0fa (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
You are 1035 version(s) behind`

The output of command `/version citizens` on my server is: 

`Citizens version 2.0.14-SNAPSHOT (build 1195)Website: http://www.citizensnpcs.coAuthors: aPunch and fullwall`

**Comment by mcmonkey4eva** [comment]
Update your server. 1.8 is absolutely not a valid Spigot version.
