### ISSUE TITLE
Error on Server start

### ISSUE THREAD

**Issue by ApertureDevelopment** [CitizensDev/Citizens2#1548]
After a while the Console shows this:

```
could not pass event PlayerTeleportEvent to Lobby v1.2.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:514) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:216) [Citizens.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:142) [Citizens.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens.jar:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:306) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at me.BukkitPVP.Lobby.Language.Messages.getPlayer(Messages.java:69) ~[?:?]
	at me.BukkitPVP.Lobby.Language.Messages.msg(Messages.java:19) ~[?:?]
	at me.BukkitPVP.Lobby.Module.LobbyAPI.fix(LobbyAPI.java:532) ~[?:?]
	at me.BukkitPVP.Lobby.Module.LobbyAPI.reset(LobbyAPI.java:357) ~[?:?]
	at me.BukkitPVP.Lobby.Module.LobbyAPI.performSpawn(LobbyAPI.java:281) ~[?:?]
	at me.BukkitPVP.Lobby.Listener.TeleportListener.onEvent(TeleportListener.java:27) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-642f6d2-57ab4cf]
	... 16 more
```

The NPCs show ingame, but this error on every startup is unnecessary.

The output of command `/version` on my server is: **git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.23-SNAPSHOT (build 1562)**

**Comment by mcmonkey4eva** [comment]
That error is the fault of plugin `me.BukkitPVP.Lobby`, not Citizens.
