### ISSUE TITLE
/npc equip doesn't work

### ISSUE THREAD

**Issue by Momonche** [CitizensDev/Citizens2#1559]
Test on the latest dev build 1567
I can use /npc equip but i can't equip

[23:44:41] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to Citizens v2.0.24-SNAPSHOT (build 1567)
java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.editor.GenericEquipper
	at net.citizensnpcs.editor.EquipmentEditor.onPlayerInteractEntity(EquipmentEditor.java:99) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1045.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1230]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1649) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1230]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by mcmonkey4eva** [comment]
Could you post the rest of the error?

Check your logs file. It's likely the firstmost instance of a stacktrace appearing in the logs that is relevant.

**Comment by mcmonkey4eva** [comment]
Should be resolved by build 1568+ on http://ci.citizensnpcs.co/job/Citizens2/
Let me know if there's any further trouble!
