### ISSUE TITLE
console error: invalid plugin.yml

### ISSUE THREAD

**Issue by comonier** [CitizensDev/Citizens2#1573]
[14:08:42] [Server thread/ERROR]: Could not load 'plugins\citizensapi-2.0.24-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot.jar:git-Spigot-68acb93-65bb2d0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-68acb93-65bb2d0]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:317) [spigot.jar:git-Spigot-68acb93-65bb2d0]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot.jar:git-Spigot-68acb93-65bb2d0]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-68acb93-65bb2d0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by comonier** [comment]
[14:08:41] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-68acb93-65bb2d0 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by yzimroni** [comment]
You are using a citizensapi jar instead of a citizens2 jar (the actual plugin), you can download the latest citizens 2 build from [here](http://ci.citizensnpcs.co/job/Citizens2/)

**Comment by comonier** [comment]
![using](https://user-images.githubusercontent.com/19571541/45931205-13c11300-bf41-11e8-8955-035bcd235b54.jpg)
ALREADY last update

**Comment by mcmonkey4eva** [comment]
@comonier Don't download the API jar. Remove that. It's not a plugin, it's an internal developer API

**Comment by comonier** [comment]
ah ok sorry - ty
