### ISSUE TITLE
NPC Deletes it self.

### ISSUE THREAD

**Issue by WizardPlays** [CitizensDev/Citizens2#1575]
<--
** DO NOT IGNORE **
Issue posts that fail to follow the instructions here will be automatically closed!
Please include:
- I have recently had the problem that my NPC's which I create after the / citizens reload or a restart are 
   gone. I can create the NPCs but only until reload / restart. I do not use Entity Manager plugins like 
   ClearLagg. If I create an NPC this is indeed there but without skin and it is not registered in the 
   saves.yml. I've already tried every Citizen version available for the 1.12.2 but nothing works.
- Console LOG:       https://pastebin.com/QMEPpxRQ
  Server Version:     https://pastebin.com/dBG7Ted2
- **Spigot and Citizens version!**
  Spigot Version:    http://prntscr.com/ky6kha 
  Citizens version:   http://prntscr.com/ky6kxw
- Server Specifications: http://prntscr.com/ky6lmk
   saves.yml:                  http://prntscr.com/ky6ld4 
-->

The output of command `/version` on my server is: **(Craftbukkit version git-Spigot-7754231- 
94b0980(MC.1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.24-SNAPSHOT (build1568))**

**Comment by mcmonkey4eva** [comment]
What exactly is the actual issue?

**Comment by WizardPlays** [comment]
I cant post it
it doesnt post the completely one

**Comment by mcmonkey4eva** [comment]
Can you format your post less nonsensically? You've broken the issue notice header and randomly inserted log links / etc into the middle of it, instead of posting them in the issue body...

**Comment by WizardPlays** [comment]
I Hope this is better

**Comment by mcmonkey4eva** [comment]
Do not use ` /citizens reload` unless you have a very specific reason to.

**ABSOLUTELY DO NOT EVER** use `/reload` (Spigot reload) or "PlugMan". These are unsupportable systems that **WILL BREAK YOUR SERVER**.

Your server log is literally flooded with error messages - `[19:04:09] [Server thread/WARN]: java.lang.NullPointerException` all over. There's no visible context to that error message, so either you've damaged the Java VM with too many errors *or* you have a horrifically broken plugin dying all over your logs.

**Comment by WizardPlays** [comment]
How can i rescue my Java VM? 

I had never reloaded plugins with Plugman. I use Plugman just for unload and disable. I reload Citizens only with /citizens reload or Server Restart

**Comment by mcmonkey4eva** [comment]
Citizens reload, again, should not be used.

PlugMan by nature will break things and should be entirely removed.

The error message being contextless is more likely some broken plugin outputting sloppily than a Java VM issue. I can't really say what plugin is cause those messages but a spam of internal exception messages in logs is definitely something that needs fixing.

The first error message in your logs:
```

[18:13:31] [Thread-13/WARN]: java.lang.NullPointerException
[18:13:31] [Thread-13/WARN]:    at com.gmail.filoghost.holographicdisplays.SimpleUpdater$1.run(SimpleUpdater.java:59)
[18:13:31] [Thread-13/WARN]:    at java.lang.Thread.run(Thread.java:745)
```
Seems to be an error from the plugin HolographicDisplays.

The second error message in your logs:
```

[18:13:33] [Thread-18/WARN]: java.lang.NullPointerException
[18:13:33] [Thread-18/WARN]:    at java.io.StringReader.<init>(StringReader.java:50)
[18:13:33] [Thread-18/WARN]:    at org.json.simple.JSONValue.parse(JSONValue.java:50)
[18:13:33] [Thread-18/WARN]:    at de.czymm.serversigns.Updater.read(Updater.java:494)
```
Has context - it appears to be a JSON configuration issue with the plugin 'serversigns' owned by 'de.czymm'

There's a lot of warnings all over that appear to be network connectivity / database handling errors.

In all 3 of those cases, you should contact relevant parties (the two plugin developers) and/or check that your server's network is properly configured.

**Comment by WizardPlays** [comment]
I thank u for ur fast reply. I will try to fix this. But there is still the Problem with the Deleting npc after restart. The NPC's do not even create themselves in the saves yml.

**Comment by mcmonkey4eva** [comment]
We can't provide direct support for an issue when there's serious errors in the logs.
The reason for this is that the majority of the time, fixing the error messages in the logs results in the actual issue being fixed as well, even if it doesn't immediately appear that they're linked.

**Comment by WizardPlays** [comment]
Okay I'll try to sort out all the bad plugins and then report back to them if the error persists. Thanks for your help :)
