### ISSUE TITLE
Guided waypoint issue

### ISSUE THREAD

**Issue by shawngiese** [CitizensDev/Citizens2#1578]
The output of command `/version` on my server is: This server is running CraftBukkit version git-Spigot-f823ac5-c1ecaa2 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is:  [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1571)

Trying to remove guided waypoints, could not figure it out. So finally decided to just remove NPC and received the null pointer.

[16:54:41] [Server thread/INFO]: [Citizens] Exception while updating 108: null.
[16:54:41] [Server thread/WARN]: java.lang.NullPointerException
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.trait.waypoint.GuidedWaypointProvider$GuidedAIGoal$1.onCompletion(GuidedWaypointProvider.java:263)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:293)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:180)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:289)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.tick(NMSImpl.java:1041)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:302)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[16:54:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[16:54:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[16:54:41] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

[16:54:41] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1571)
[16:54:41] [Server thread/WARN]: java.lang.NullPointerException
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.trait.waypoint.GuidedWaypointProvider$GuidedAIGoal$1.onCompletion(GuidedWaypointProvider.java:263)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:293)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.onDespawn(CitizensNavigator.java:135)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:87)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.Citizens.despawnNPCs(Citizens.java:111)
[16:54:41] [Server thread/WARN]:        at net.citizensnpcs.Citizens.onDisable(Citizens.java:249)
[16:54:41] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[16:54:41] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363)
[16:54:41] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[16:54:41] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[16:54:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:365)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:625)
[16:54:41] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:770)
[16:54:41] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by shawngiese** [comment]
Also while trying to delete an NPC and then stopping the server to avoid the spam (I also updated the spigot jar)
This server is running CraftBukkit version git-Spigot-f6a273b-1a7f2d1 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)


[21:33:33] [Server thread/INFO]: [Citizens] Exception while updating 109: null.
[21:33:33] [Server thread/WARN]: java.lang.NullPointerException

[21:37:58] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.24-SNAPSHOT (build 1571) (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register MobType{PLAYER} while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:522) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:107) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:226) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.getFullName(AbstractNPC.java:197) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:332) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:154) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91) ~[?:?]
        at net.citizensnpcs.Citizens.onDisable(Citizens.java:247) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) [spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:365) [spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:625) [spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:770) [spigot-1.13.1.jar:git-Spigot-f6a273b-1a7f2d1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
