### ISSUE TITLE
java.lang.NoSuchFieldError: field_711109_bG error when trying to create an NPC

### ISSUE THREAD

**Issue by ExplodingC** [CitizensDev/Citizens2#1584]
- Hello I get this issue when I do /npc create test

[13:05:15] [Server thread/INFO]: FireIsH0t issued server command: /npc create test
[13:05:15] [Server thread/WARN]: java.lang.NoSuchFieldError: field_71109_bG
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:67)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.nms.v1_10_R1.entity.HumanController.createEntity(HumanController.java:81)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:195)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:454)
[13:05:15] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:05:15] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:05:15] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:05:15] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[13:05:15] [Server thread/WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[13:05:15] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:05:15] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[13:05:15] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:719)
[13:05:15] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1427)
[13:05:15] [Server thread/WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1263)
[13:05:15] [Server thread/WARN]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[13:05:15] [Server thread/WARN]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[13:05:15] [Server thread/WARN]: at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[13:05:15] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:05:15] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:05:15] [Server thread/WARN]: at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[13:05:15] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:769)
[13:05:15] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:465)
[13:05:15] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:702)
[13:05:15] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
[13:05:15] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
- https://pastebin.com/C0cX3kEC
- Server Jar: http://prntscr.com/l3o0o8 (Custom Jar for mods and plugins at the same time)
- Premium Citizens Jar (Paid the 10 USD) 2.0.22 (1.12 ALPHA #2)
- Server Specs: 8 GB Ram but forgot the cpu which should be an issue. 

The output of command `/version` on my server is: http://prntscr.com/l3o1kp
The output of command `/version citizens` on my server is: http://prntscr.com/l3o1h9

**Comment by mergu** [comment]
I just wanted to point out that there is no 'premium' version of Citizens - it has been, and will always be free and open source. The Citizens plugin you are using is no different than the one the rest of us are.

I should also mention your Citizens build is quite out of date (current build is #1581 - http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/)

Has this been tested on spigot instead of a custom jar? That might be the problem

**Comment by mcmonkey4eva** [comment]
You're trying to run Citizens on an entirely unsupported platform. "CatServer" appears to be an obscure non-English-produced Forge+Bukkit combo jar, which is entirely outside of the range of things we can or do support at all. Citizens is built specifically against the underlying NMS structure used by Spigot, and is not compatible with the Forge structure at all.
