### ISSUE TITLE
Minecraft 1.13.2 issue

### ISSUE THREAD

**Issue by Rocologo** [CitizensDev/Citizens2#1597]
Tonight I tried to update my server to Spigot 1.13.2, but the server crashed while doing something with Citizens2. 

```
[20:49:22] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:983) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchFieldError: b
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerPathfinderNormal.b(PlayerPathfinderNormal.java:402) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerPathfinder.a(PlayerPathfinder.java:38) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerPathfinder.a(PlayerPathfinder.java:30) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.superb(PlayerNavigation.java:471) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.b(PlayerNavigation.java:270) ~[?:?]
	at net.minecraft.server.v1_13_R2.NavigationAbstract.a(SourceFile:107) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.a(PlayerNavigation.java:82) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$4.apply(NMSImpl.java:460) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$4.apply(NMSImpl.java:457) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$5.update(NMSImpl.java:514) ~[?:?]
	at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:77) ~[?:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:289) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437) ~[?:?]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1347) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:624) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1149) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	... 4 more
[20:49:22] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoSuchFieldError: b
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerPathfinderNormal.b(PlayerPathfinderNormal.java:402) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerPathfinder.a(PlayerPathfinder.java:38) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerPathfinder.a(PlayerPathfinder.java:30) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.superb(PlayerNavigation.java:471) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.b(PlayerNavigation.java:270) ~[?:?]
	at net.minecraft.server.v1_13_R2.NavigationAbstract.a(SourceFile:107) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.a(PlayerNavigation.java:82) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$4.apply(NMSImpl.java:460) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$4.apply(NMSImpl.java:457) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$5.update(NMSImpl.java:514) ~[?:?]
	at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:77) ~[?:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:289) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437) ~[?:?]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1347) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:624) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1149) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

Spigot Version: This server is running CraftBukkit version git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Citizens Version: Loading Citizens v2.0.24-SNAPSHOT (build 1583)

**Comment by Rocologo** [comment]
I had to rollback to Spigot 1.13.1 to make my server run again. 

Here is the complete server.log from start to crash 

https://pastebin.com/kZVUzZHm

**Comment by fullwall** [comment]
Try latest build

**Comment by mart-r** [comment]
> Try latest build

Had the same issue with 1583, but 1584 seems to have fixed it. Thanks! :)

**Comment by Rocologo** [comment]
Build 1584 solved my problem to. I have now upgraded to 1.13.2

Thank you for a very fast fix!!!
