### ISSUE TITLE
issue saving

### ISSUE THREAD

**Issue by WHiZSTA** [CitizensDev/Citizens2#1603]
29.10 08:26:49 [Server] INFO This server is running Paper version git-Paper-405 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

29.10 08:20:03 [Server] WARN [Citizens] Task #226 for Citizens v2.0.24-SNAPSHOT (build 1586) generated an exception 
29.10 08:20:03 [Server] INFO java.lang.IndexOutOfBoundsException: No group 3 
29.10 08:20:03 [Server] INFO at java.util.regex.Matcher.start(Matcher.java:375) ~[?:1.8.0_161] 
29.10 08:20:03 [Server] INFO at java.util.regex.Matcher.appendReplacement(Matcher.java:880) ~[?:1.8.0_161] 
29.10 08:20:03 [Server] INFO at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_161] 
29.10 08:20:03 [Server] INFO at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_161] 
29.10 08:20:03 [Server] INFO at net.livecar.nuttyworks.npc_destinations.messages.Messages_Manager.buildMessage(Messages_Manager.java:106) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.livecar.nuttyworks.npc_destinations.messages.Messages_Manager.consoleMessage(Messages_Manager.java:54) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.save(Citizens_Processing.java:1465) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.trait_saveSettings(Citizens_Processing.java:66) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.livecar.nuttyworks.npc_destinations.citizens.NPCDestinationsTrait.save(NPCDestinationsTrait.java:176) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:339) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:154) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:441) ~[?:?] 
29.10 08:20:03 [Server] INFO at net.citizensnpcs.Citizens$3.run(Citizens.java:376) ~[?:?] 
29.10 08:20:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-405] 
29.10 08:20:03 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-405] 
29.10 08:20:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-405] 
29.10 08:20:03 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-405] 
29.10 08:20:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-405] 
29.10 08:20:03 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-405] 
29.10 08:20:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by mcmonkey4eva** [comment]
I reformatted your post for you (bit messy there).

The issue is entirely from the plugin `npc_destinations`, please report to that plugin's developer.
