### ISSUE TITLE
NPC Path not working for Player type NPCs

### ISSUE THREAD

**Issue by Haden88** [CitizensDev/Citizens2#1609]
Using the path command on a player type NPC throws errors while on all other types it works fine. 
       
[22:47:50 WARN]: [Citizens] Task #60 for Citizens v2.0.24-SNAPSHOT (build 1574) generated an exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.tick(NMSImpl.java:1047) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:302) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoSuchFieldError: b
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerControllerMove.a(PlayerControllerMove.java:38) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.updateAI(EntityHumanNPC.java:441) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.updateAI(NMSImpl.java:1565) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:431) ~[?:?]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) ~[spigot-1.13.2.jar:git-Spigot-e4d0c66-f3f2fe5]
        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.tick(NMSImpl.java:1041) ~[?:?]
        ... 9 more

**Comment by mergu** [comment]
Hello,

Make sure to follow the issue template. Please also update before making an issue:
http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/

If the update solves your issue, feel free to close this. Always update before posting.
