### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1635]
Spigot 1.13.2 latest (today) = CraftBukkit version git-Spigot-140f654-c64fe50 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens 2.0.24-b1601
```
java.lang.NoSuchFieldError: ae
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:31)
        at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:254)
        at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(SourceFile:123)
        at net.minecraft.server.v1_13_R2.PlayerChunk.a(SourceFile:63)
        at net.minecraft.server.v1_13_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:257)
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:287)
        at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:385)
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163)
        at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150)
        at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:54)
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231)
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120)
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998)
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
        at java.lang.Thread.run(Thread.java:748)
```
With previous Spigot build (three days ago) = CraftBukkit version git-Spigot-078a7f5-7fa173e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
no issues

**Comment by SlimeDog** [comment]
Verified build 1603 produced no errors with latest Spigot build.
