### ISSUE TITLE
Crash at the start of the server

### ISSUE THREAD

**Issue by Musicalink** [CitizensDev/Citizens2#1647]
The output of command `/version` on my server is: **(PLEASE FILL IN)**
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**

Here's the crash issue : 
[21:24:00 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:978) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot.jar:git-Spigot-82e117e-2b2d084]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.MethodProfiler.a(Ljava/lang/String;)V
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.superb(PlayerNavigation.java:467) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.b(PlayerNavigation.java:271) ~[?:?]
        at net.minecraft.server.v1_13_R2.NavigationAbstract.a(SourceFile:107) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerNavigation.a(PlayerNavigation.java:83) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$4.apply(NMSImpl.java:461) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$4.apply(NMSImpl.java:458) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl$5.update(NMSImpl.java:515) ~[?:?]
        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:77) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:289) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437) ~[?:?]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1326) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1293) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:606) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1095) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:967) ~[spigot.jar:git-Spigot-82e117e-2b2d084]
        ... 4 more

I can't give the version, the server don't want to start up anymore

**Comment by mergu** [comment]
Make sure you're using the most recent versions of Spigot and Citizens.

Spigot should be built using BuildTools: https://www.spigotmc.org/wiki/buildtools/
Latest Citizens can be found here: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

**Comment by Musicalink** [comment]
That was that, thank you !
