### ISSUE TITLE
Missing preferred location bundle.

### ISSUE THREAD

**Issue by mistek131995** [CitizensDev/Citizens2#1648]
[02:57:13] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1604)
[02:57:13] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.
[02:57:13] [Server thread/WARN]: java.lang.NoSuchMethodException: com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)
[02:57:13] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[02:57:13] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.<clinit>(NMSImpl.java:1544)
[02:57:13] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[02:57:13] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[02:57:13] [Server thread/WARN]: 	at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189)
[02:57:13] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onEnable(Citizens.java:266)
[02:57:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:57:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[02:57:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[02:57:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[02:57:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[02:57:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[02:57:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[02:57:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[02:57:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[02:57:13] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[02:57:14] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:57:14] [Server thread/INFO]: [Spleef] Enabling Spleef v1.3.0

**Comment by mistek131995** [comment]
Citizens version - 2.0.24-b1605
[09:30:19] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-93e20b3-31d3159 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)[m

**Comment by mergu** [comment]
You're using a 1.12.2 build from Oct 6, 2017. Please update to the latest 1.12.2 build and re-post the output of /version.

**Comment by mcmonkey4eva** [comment]
The `Missing preferred location bundle.` is separate from the rest of that error.
`Missing preferred location bundle.` indicates that your server is configured to a locale that Citizens doesn't have a language pack for (Citizens attempts to translate to the local language automatically). You can just ignore that message if you're fine with English output (and build your own language file if you'd prefer it be translated).

The rest of that post is an exception that most likely is just an outdated copy of Spigot 1.12.2 as mentioned

**Comment by TheEeveeLovers** [comment]
"
> The `Missing preferred location bundle.` is separate from the rest of that error.
> `Missing preferred location bundle.` indicates that your server is configured to a locale that Citizens doesn't have a language pack for (Citizens attempts to translate to the local language automatically). You can just ignore that message if you're fine with English output (and build your own language file if you'd prefer it be translated).
> 
> The rest of that post is an exception that most likely is just an outdated copy of Spigot 1.12.2 as mentioned
"

So citizens is not compatible with bukkit 1.13.2 English?
Since I got the same error on my 1.13.2 bukkit server?
So Bukkit 1.13.2 is an outdated copy of Spigot 1.12.2

**Comment by mergu** [comment]
You should never be running a bukkit server. Only use spigot. If you have a new issue, open a post with your new console logs.

**Comment by TheEeveeLovers** [comment]
then why is it on the page for bukkit plugins?

**Comment by mergu** [comment]
Bukkit development was stopped with the DMCA in 2014. Since then, Spigot is the actively developed server version you should use.

**Comment by mcmonkey4eva** [comment]
Bukkit is a plugin API.
"a bukkit server" refers to a server based on CraftBukkit.jar, which was the server jar made by the Bukkit team. After the Bukkit team was shut down, Spigot took over. You can still technically run "a bukkit server" using the internal tooling Spigot includes, but it is not recommended - instead run the actual Spigot server (Spigot.jar).

If you have an error message you can't resolve, please create a new issue and include the exact text of the message as it appears on your server.
Even if an error _looks_ the same it isn't necessarily the same - they're quite long messages and include a lot of details.
If you have an error message that says `net.minecraft.server.v1_12_R1.MinecraftServer` in it then yes you're running 1.12, and not 1.13.2.
If your error message says `v1_13_R2` instead, then you're probably running 1.13.2
