### ISSUE TITLE
Citizens2 can't work.

### ISSUE THREAD

**Issue by FAWKESX** [CitizensDev/Citizens2#1653]
[16:59:26] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:59:26] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:59:26] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:59:26] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[16:59:26] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[16:59:26] [main/INFO]: Loaded 0 recipes
[16:59:26] [Server thread/INFO]: Starting minecraft server version 1.13
[16:59:26] [Server thread/INFO]: Loading properties
[16:59:26] [Server thread/INFO]: Default game type: SURVIVAL
[16:59:26] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[16:59:26] [Server thread/INFO]: Debug logging is disabled
[16:59:26] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:59:26] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:59:26] [Server thread/INFO]: Generating keypair
[16:59:27] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:59:27] [Server thread/INFO]: Using default channel type
[16:59:28] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[16:59:28] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.24-SNAPSHOT (build 1604)
[16:59:28] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[16:59:28] [Server thread/INFO]: Preparing level "world"
[16:59:28] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[16:59:29] [Server thread/INFO]: Loaded 524 recipes
[16:59:29] [Server thread/INFO]: -------- World Settings For [world] --------
[16:59:29] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:59:29] [Server thread/INFO]: Arrow Despawn Rate: 1200
[16:59:29] [Server thread/INFO]: View Distance: 10
[16:59:29] [Server thread/INFO]: Item Despawn Rate: 6000
[16:59:29] [Server thread/INFO]: Item Merge Radius: 2.5
[16:59:29] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:59:29] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:59:29] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[16:59:29] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:59:29] [Server thread/INFO]: Mob Spawn Range: 6
[16:59:29] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Random Lighting Updates: false
[16:59:29] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:59:29] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:59:29] [Server thread/INFO]: Max TNT Explosions: 100
[16:59:29] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:59:29] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[16:59:29] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[16:59:29] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:59:29] [Server thread/INFO]: Arrow Despawn Rate: 1200
[16:59:29] [Server thread/INFO]: View Distance: 10
[16:59:29] [Server thread/INFO]: Item Despawn Rate: 6000
[16:59:29] [Server thread/INFO]: Item Merge Radius: 2.5
[16:59:29] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:59:29] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:59:29] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[16:59:29] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:59:29] [Server thread/INFO]: Mob Spawn Range: 6
[16:59:29] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Random Lighting Updates: false
[16:59:29] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:59:29] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:59:29] [Server thread/INFO]: Max TNT Explosions: 100
[16:59:29] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:59:29] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[16:59:29] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[16:59:29] [Server thread/INFO]: Experience Merge Radius: 3.0
[16:59:29] [Server thread/INFO]: Arrow Despawn Rate: 1200
[16:59:29] [Server thread/INFO]: View Distance: 10
[16:59:29] [Server thread/INFO]: Item Despawn Rate: 6000
[16:59:29] [Server thread/INFO]: Item Merge Radius: 2.5
[16:59:29] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[16:59:29] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[16:59:29] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[16:59:29] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[16:59:29] [Server thread/INFO]: Mob Spawn Range: 6
[16:59:29] [Server thread/INFO]: Cactus Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Cane Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Melon Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Sapling Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Wheat Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Vine Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[16:59:29] [Server thread/INFO]: Random Lighting Updates: false
[16:59:29] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[16:59:29] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[16:59:29] [Server thread/INFO]: Max TNT Explosions: 100
[16:59:29] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[16:59:29] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[16:59:29] [Server thread/INFO]: Preparing start region for level 0 (Seed: -1407715470521421555)
[16:59:29] [Server thread/INFO]: Preparing spawn area: 4%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 8%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 12%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 16%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 20%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 24%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 28%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 32%
[16:59:29] [Server thread/INFO]: Preparing spawn area: 36%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 40%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 44%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 48%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 52%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 56%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 60%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 64%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 68%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 72%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 76%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 80%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 84%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 88%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 92%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 96%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 100%
[16:59:30] [Server thread/INFO]: Preparing start region for level 1 (Seed: -1407715470521421555)
[16:59:30] [Server thread/INFO]: Preparing spawn area: 4%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 8%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 12%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 16%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 20%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 24%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 28%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 32%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 36%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 40%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 44%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 48%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 52%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 56%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 60%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 64%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 68%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 72%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 76%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 80%
[16:59:30] [Server thread/INFO]: Preparing spawn area: 84%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 88%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 92%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 96%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 100%
[16:59:31] [Server thread/INFO]: Preparing start region for level 2 (Seed: -1407715470521421555)
[16:59:31] [Server thread/INFO]: Preparing spawn area: 4%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 8%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 12%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 16%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 20%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 24%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 28%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 32%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 36%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 40%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 44%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 48%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 52%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 56%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 60%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 64%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 68%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 72%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 76%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 80%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 84%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 88%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 92%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 96%
[16:59:31] [Server thread/INFO]: Preparing spawn area: 100%
[16:59:31] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1604)
[16:59:31] [Server thread/INFO]: Creating file: config.yml
[16:59:31] [Server thread/ERROR]: [Citizens] Missing preferred location bundle.
[16:59:31] [Server thread/ERROR]: [Citizens] v2.0.24-SNAPSHOT (build 1604) is not compatible with Minecraft v1_13_R1 - try upgrading or downgrading Citizens. Disabling.
[16:59:31] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1604)
[16:59:31] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:59:31] [Server thread/INFO]: Time elapsed: 1602 ms
[16:59:31] [Server thread/INFO]: Done (2.399s)! For help, type "help"
[16:59:43] [Server thread/WARN]: Unexpected exception while parsing console command "npc"
org.bukkit.command.CommandException: Cannot execute command 'npc' in plugin Citizens v2.0.24-SNAPSHOT (build 1604) - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:679) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.aW(DedicatedServer.java:453) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:412) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[16:59:57] [Server thread/INFO]: Stopping the server
[16:59:57] [Server thread/INFO]: Stopping server
[16:59:57] [Server thread/INFO]: Saving players
[16:59:57] [Server thread/INFO]: Saving worlds
[16:59:57] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[16:59:57] [Server thread/INFO]: Saving chunks for level 'world_nether'/the_nether
[16:59:57] [Server thread/INFO]: Saving chunks for level 'world_the_end'/the_end

**Comment by FAWKESX** [comment]
My server is Spigot 1.13
Citizens version is b1605
