### ISSUE TITLE
Citizens finally activated in Spigot 1.13.2

### ISSUE THREAD

**Issue by MrKiller01** [CitizensDev/Citizens2#1658]
The output of command `/version` on my server is: **(>version 
[16:04:30 INFO]: This server is running CraftBukkit version git-Spigot-19c3c5a-5
932f8a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:04:30 INFO]: Checking version, please wait...
[16:04:30 INFO]: You are running the latest version)**
The output of command `/version citizens` on my server is: **(>version citizens
[16:05:11 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1591)
[16:05:11 INFO]: Website: http://www.citizensnpcs.co
[16:05:11 INFO]: Authors: aPunch and fullwall)**

**Comment by mergu** [comment]
What's the issue? You didn't provide any details.

Please also update Citizens: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

**Comment by mcmonkey4eva** [comment]
@MrKiller01 I edited your post to make what you wrote visible (you typed it in the wrong spot originally)

The issue you are having is caused by running an outdated copy of Citizens on a not-outdated copy of Spigot. Update: http://ci.citizensnpcs.co/job/Citizens2/

**Comment by mergu** [comment]
Update as recommended (twice) then re-post the output of /version Citizens. If your problem still occurs after updating, then we can continue.

**Comment by MrKiller01** [comment]
[01:37:54 ERROR]: Could not pass event NPCLeftClickEvent to Citizens v2.0.24-SNA
PSHOT (build 1605)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:309) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.citizensnpcs.EventListen.onEntityDamage(EventListen.java:228) ~[?
:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(Cra
ftEventFactory.java:101) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDam
ageEvent(CraftEventFactory.java:757) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932
f8a]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityD
amageEvent(CraftEventFactory.java:656) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-59
32f8a]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingE
ntityDamageEvent(CraftEventFactory.java:789) ~[spigot-1.13.2.jar:git-Spigot-19c3
c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving
.java:1445) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.j
ava:879) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.
java:967) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.ja
va:792) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.
java:625) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.damageEntity(Enti
tyHumanNPC.java:152) ~[?:?]
        at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:104
4) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1
336) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.jav
a:1855) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69)
~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13)
~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1
.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
896) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
831) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:729) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
        at nl.thewgbbroz.dtltraders.adminguis.ShopEditService.selectShop(ShopEdi
tService.java:913) ~[?:?]
        at nl.thewgbbroz.dtltraders.citizens.CitizensHook.openGUISelectGUI(Citiz
ensHook.java:29) ~[?:?]
        at nl.thewgbbroz.dtltraders.citizens.TraderTrait.onClick(TraderTrait.jav
a:78) ~[?:?]
        at nl.thewgbbroz.dtltraders.citizens.TraderTrait.onNPCLeftClickEvent(Tra
derTrait.java:56) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        ... 36 more
[01:39:22 INFO]: [PreciousStones] [New Player]: ºeBuyer ºaSally UUID: f3739fd8-1
006-2035-bfe5-5d8cb7c931e0
[01:39:22 INFO]: [PreciousStones] [New Player]: ºeBUYER ºaSam UUID: 30b2aaea-ffc
e-2c65-b4b2-594970fb62c0
[01:39:22 INFO]: [PreciousStones] [New Player]: ºeSELLER ºaBrian UUID: 498db209-
9d0d-2da6-88b5-a07f638d9e08
[01:39:37 INFO]: [PreciousStones] [New Player]: NO KILLS UUID: 719a727e-c5c3-238
9-b0f1-fe3fc4992dad
[01:39:37 INFO]: [MobHunting] Citizens MobType 43 was inserted to mh_Mobs
[01:39:38 INFO]: [PreciousStones] [New Player]: Nelsonkamiel UUID: be73bcaa-d270
-243f-88f2-9ffcaaebd033
[01:39:46 INFO]: [PreciousStones] [New Player]: stagemaster UUID: c71efc6c-6831-
2aed-a807-6b92afc6614c

>version citizens
[01:51:54 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1605)
[01:51:54 INFO]: Website: http://www.citizensnpcs.co
[01:51:54 INFO]: Authors: aPunch and fullwall
>

**Comment by mergu** [comment]
Seems to be an issue with dtltraders:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
at nl.thewgbbroz.dtltraders.adminguis.ShopEditService.selectShop(ShopEdi
tService.java:913) ~[?:?]
```

Have you been in contact with them?

**Comment by samyratchet** [comment]
Hey MrKiller01,

Could it be possible to send the **saves.yml that is located in your citizens folder** and the **guis.yml located in dtlTraders folder** so we can take a look and locate the bugg.


Thanks, samyratchet (dtlTraders)

**Comment by MrKiller01** [comment]
[guis - Copy.yml.txt](https://github.com/CitizensDev/Citizens2/files/2730607/guis.-.Copy.yml.txt)

Here it is, I hope it is helpfull.....

Thank you very much....

**Comment by MrKiller01** [comment]
Sorry @mcmonkey4eva, forgot to page refresh, read your message after I sent it in......
