### ISSUE TITLE
Following up #1658

### ISSUE THREAD

**Issue by MrKiller01** [CitizensDev/Citizens2#1660]
Could not pass event NPCLeftClickEvent to Citizens v2.0.24-SNAPSHOT (build 1605)

This is because the issue is I think not completely related to DtlTraders. If that plugin is faulty, why do I get this errormessage when I click on that specific NPC?

[12:51:11 ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.24-SN
APSHOT (build 1605)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:309) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:
431) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.jav
a:1809) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69)
~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13)
~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1
.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
896) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
831) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:729) [spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
        at nl.thewgbbroz.dtltraders.adminguis.ShopEditService.selectShop(ShopEdi
tService.java:913) ~[?:?]
        at nl.thewgbbroz.dtltraders.citizens.CitizensHook.openGUISelectGUI(Citiz
ensHook.java:29) ~[?:?]
        at nl.thewgbbroz.dtltraders.citizens.TraderTrait.onClick(TraderTrait.jav
a:78) ~[?:?]
        at nl.thewgbbroz.dtltraders.citizens.TraderTrait.onNPCRightClickEvent(Tr
aderTrait.java:49) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[spigot-1.13.2.jar:git-Spigot-19c3c5a-5932f8a]
        ... 23 more

I am trying to understand when where how this occurs, just for me to understand, not to nag you!
Thanks...

**Comment by MrKiller01** [comment]
oh, and yes, I am now in contact with DtlTraders on spigot..
https://www.spigotmc.org/threads/dtltraders.215471/page-22

**Comment by mcmonkey4eva** [comment]
```

Caused by: java.lang.ArrayIndexOutOfBoundsException: 27
at nl.thewgbbroz.dtltraders.adminguis.ShopEditService.selectShop(ShopEdi
tService.java:913) ~[?:?]
```
^ caused by dtltraders.
