### ISSUE TITLE
plugin disabled

### ISSUE THREAD

**Issue by linhus** [CitizensDev/Citizens2#1664]
Hi this is my log.
In the log are also the command and version.

[15:42:59] [Server thread/INFO]: DosePlay issued server command: /npc
[15:42:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'npc' in plugin Citizens v2.0.24-SNAPSHOT (build 1604) - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-fe3ab0d-162bda9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by mergu** [comment]
You need to be on 1.13.2. Previous versions of 1.13 have some serious bugs.
