### ISSUE TITLE
Newest Version (1.13.2) Crashing

### ISSUE THREAD

**Issue by ShadowAngel25** [CitizensDev/Citizens2#1669]
I'm new to making servers and i've asked some of my friends what plugins (besides the basics i.e. permissionsex, world edit, etc.) and one suggest citizens2. 
I downloaded the newest version 2.0.24(1.10-1.13.2) and also I have the newest versions of spigot and java. But this came up when I tried to create a new NPC; I typed "/create npc noah" then the server was closed from crashing.

Here is the error message in the server prompt: 

 Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:978) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchFieldError: ae
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:31) ~[?:?]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:449) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:207) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityLiving.tickPotionEffects(EntityLiving.java:616) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.livingEntityBaseTick(EntityHumanNPC.java:318) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:414) ~[?:?]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1326) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1293) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:606) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1095) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:967) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        ... 4 more
[01:45:59 ERROR]:       Cause of unexpected exception was
java.lang.NoSuchFieldError: ae
        at net.citizensnpcs.nms.v1_13_R2.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:31) ~[?:?]
        at net.minecraft.server.v1_13_R2.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:449) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:207) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityLiving.tickPotionEffects(EntityLiving.java:616) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.livingEntityBaseTick(EntityHumanNPC.java:318) ~[?:?]
        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:414) ~[?:?]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1326) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1293) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:606) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1095) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:967) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[01:45:59 ERROR]: This crash report has been saved to: C:\Users\Ramir\Desktop\Spigot 1.13.2 Server\.\crash-reports\crash-2019-01-15_01.45.59-server.txt

Help please.
![2019-01-15_01 44 38](https://user-images.githubusercontent.com/46704592/51199254-ef0bf500-18bb-11e9-8331-659c8433f6fa.png)

![2019-01-15_01 45 00](https://user-images.githubusercontent.com/46704592/51199259-f0d5b880-18bb-11e9-9009-8b3872aec138.png)

![2019-01-15_01 45 56](https://user-images.githubusercontent.com/46704592/51199264-f3381280-18bb-11e9-8a7c-3b079fc7c342.png)

![2019-01-15_01 46 02](https://user-images.githubusercontent.com/46704592/51199269-f59a6c80-18bb-11e9-9dae-cb27a4a344d1.png)

**Comment by mergu** [comment]
You aren't running the latest versions of Spigot or Citizens. Both are outdated according to the output you've posted.

Update -
Spigot: https://www.spigotmc.org/wiki/buildtools/
Citizens: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild

Feel free to close this issue if updating solves the problem

**Comment by ShadowAngel25** [comment]
> You aren't running the latest versions of Spigot or Citizens. Both are outdated according to the output you've posted.
> 
> Update -
> Spigot: https://www.spigotmc.org/wiki/buildtools/
> Citizens: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild
> 
> Feel free to close this issue if updating solves the problem

I couldn't figure out the tool builder thing all day because for some reason it was just confusing, so I switched to downloading and running the latest Citizens2(which for some reason I couldn't originally find for some reason) and it worked! Thank you for your help!

**Comment by Nupper** [comment]
i am using the latest Citizens2 required 1.13.2 and it crashes

**Comment by mergu** [comment]
Update using the links I provided. If that doesn't work, make a new github issue with all requested info and a startup log.
