### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by dianlemel** [CitizensDev/Citizens2#1680]
`[10:58:06 ERROR]: Could not pass event ChunkLoadEvent to Citizens v2.0.24-SNAPSHOT (build 1604)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.Chunk.addEntities(Chunk.java:816) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:1556) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.postToMainThread(MinecraftServer.java:1565) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:103) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PlayerChunk.<init>(SourceFile:43) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PlayerChunkMap.c(PlayerChunkMap.java:198) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PlayerChunkMap.movePlayer(PlayerChunkMap.java:327) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PlayerList.updateChunks(PlayerList.java:391) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:976) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: yaw not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:121) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.Location.checkFinite(Location.java:572) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:575) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:295) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:190) ~[?:?]
        at net.citizensnpcs.EventListen.spawn(EventListen.java:608) ~[?:?]
        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:578) ~[?:?]
        at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:144) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
        ... 24 more`

Server version:  **1.13.2-R0.1-SNAPSHOT  git-Spigot-f56e2e7-0c715b3**
Citizens version:  **v2.0.24-SNAPSHOT (build 1604)**

**Comment by mcmonkey4eva** [comment]
```
Caused by: java.lang.IllegalArgumentException: yaw not finite at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:121) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3] at org.bukkit.Location.checkFinite(Location.java:572) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3] at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:575) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3] at
net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?] at 
```
Seems like an NPC was trying to spawn in (per normal autospawning) but is corrupt (has an infinity value for its yaw angle)
You can probably patch this by looking in the `Citizens/saves.yml` file and locating the infinite yaw value, and editing it to just be `0`

**Comment by dianlemel** [comment]
> ```
> Caused by: java.lang.IllegalArgumentException: yaw not finite
> at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:121) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
> at org.bukkit.Location.checkFinite(Location.java:572) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
> at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:575) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-0c715b3]
> at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:233) ~[?:?]
> ```
> Seems like an NPC was trying to spawn in (per normal autospawning) but is corrupt (has an infinity value for its yaw angle)
> You can probably patch this by looking in the `Citizens/saves.yml` file and locating the infinite yaw value, and editing it to just be `0`

OK Thank's
