### ISSUE TITLE
Paper 516 citizens error Entity#remove

### ISSUE THREAD

**Issue by x1p** [CitizensDev/Citizens2#1692]
Paper build 516 causes an error.
```
[08:30:14] [Server thread/WARN]: [Citizens] Task #283 for Citizens v2.0.24-SNAPSHOT (build 1613) generated an exception
java.lang.UnsupportedOperationException: Calling Entity#remove on players produces undefined (bad) behavior
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.remove(CraftPlayer.java:1943) ~[patched_1.13.2.jar:git-Paper-516]
	at net.citizensnpcs.npc.AbstractEntityController.remove(AbstractEntityController.java:35) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.HumanController.remove(HumanController.java:120) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:228) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:306) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-516]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-516]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-516]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
Paper build 515 does not causes the error.
Citizens config: https://pastebin.com/Y84tKFTB
Server log: https://pastebin.com/A5jHMnHm

The output of command `/version` on my server is: Paper version git-Paper-516 (MC: 1.13.2)
The output of command `/version citizens` on my server is: Citizens version 2.0.24-SNAPSHOT (build 1613)

**Comment by digital-r** [comment]
Have this issue too. Same versions of Paper and Citizens

**Comment by mcmonkey4eva** [comment]
Issue is caused by Paper, not Citizens.
Sourced from this Paper commit: https://github.com/PaperMC/Paper/commit/28cf2696d4078643774b896fb6a9dcda0a35a8fd by @zachbr

**Comment by x1p** [comment]
With all due respect, I don't think Paper will not make an exception only for Citizens easily

**Comment by mcmonkey4eva** [comment]
Paper has an obligation to remain compatible with Spigot plugins.

The commit description also specifically says that if the commit breaks plugins they'll be happy to fix that.

**Comment by MiniDigger** [comment]
Shouldn't NPCs be HumanEntities rather than players?

**Comment by mcmonkey4eva** [comment]
I believe NPC entity types explicitly have to override actual entity types (HumanEntity isn't an entity type, it's just a base class).
Also a variety of internal code works best using Player entities, rather than just overriding from the base Human.
And either way, that's not really changeable - quite a lot of code (both inside Citizens and in various plugins that interact with Citizens) relies on the assumption that humanoid NPCs are Players, and at minimum implement the Bukkit `Player` interface (and in some cases further than they are based on CraftPlayer).

**Comment by MiniDigger** [comment]
fixed in https://github.com/PaperMC/Paper/commit/8211569c9a6d14c56d67bed2e0f024d9bb8f5033
paper build 517+
