### ISSUE TITLE
NoClassDefFoundError on start-up

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1704]
Spigot 1.13.2 latest = git-Spigot-e5e5c7c-c24abab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens 2.0.24-SNAPSHOT (build 1618)

[20:58:41] [Server thread/WARN]: [Citizens] Task #54 for Citizens v2.0.24-SNAPSHOT (build 1618) generated an exception
java.lang.NoClassDefFoundError: net/citizensnpcs/util/metrics/bukkit/Metrics$1
        at net.citizensnpcs.Citizens.startMetrics(Citizens.java:457) ~[?:?]
        at net.citizensnpcs.Citizens.access$300(Citizens.java:73) ~[?:?]
        at net.citizensnpcs.Citizens$3.run(Citizens.java:333) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.util.metrics.bukkit.Metrics$1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar-2019-02-19-0717:git-Spigot-e5e5c7c-c24abab]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 10 more
```

**Comment by mcmonkey4eva** [comment]
I'm pretty confused about this error.
Can't replicate it and can't think of any reason it would happen... maybe something like accidentally duplicated jar files?

**Comment by SlimeDog** [comment]
No duplicates. I did update Denizen and Depenizen at the same time. When I have a few minutes, I'll back those out and see if they are causing the issue.
Denizen-1.0.3-b630.jar
DepenizenBukkit-1.0.0-b436.jar

**Comment by mcmonkey4eva** [comment]
There appears to be a compiling error, the current version of bStats requires Java 8+ but Citizens is compiling against Java 6, and the shading is missing a single subclass.

**Comment by mcmonkey4eva** [comment]
Should be fixed in build 1619+
via updated shade plugin

**Comment by SlimeDog** [comment]
Fixed with Citizens 2.0.24-SNAPSHOT (build 1619). Thanks.

**Comment by SlimeDog** [comment]
Java 6 ??? :)

**Comment by mcmonkey4eva** [comment]
Minecraft prior to 1.12 was on Java 6 (and I think farther back, Java 5?)

Citizens is cross-compatible back to Minecraft 1.8, and for some reason some servers still run really old Java versions, so we've left Java 6 as the compile target to avoid trouble with those servers .-.
