### ISSUE TITLE
NoClassDef

### ISSUE THREAD

**Issue by Aster0** [CitizensDev/Citizens2#1705]
I have a similar issue with SlimeDog, using the latest build, except, mine is task #84.

[14:52:05 WARN]: [Citizens] Task #82 for Citizens v2.0.24-SNAPSHOT (build 1618) generated an exception
java.lang.NoClassDefFoundError: net/citizensnpcs/util/metrics/bukkit/Metrics$1
at net.citizensnpcs.Citizens.startMetrics(Citizens.java:457) ~[?:?]
at net.citizensnpcs.Citizens.access$300(Citizens.java:73) ~[?:?]
at net.citizensnpcs.Citizens$3.run(Citizens.java:333) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-524]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-524]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.util.metrics.bukkit.Metrics$1
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_192]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-524]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-524]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_192]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_192]
... 10 more

**Comment by mcmonkey4eva** [comment]
Duplicate, post any additional info (if any) you have to the original issue #1704

**Comment by Aster0** [comment]
Different task though. Thought I'd post an new one.

**Comment by mcmonkey4eva** [comment]
The task number is irrelevant.

**Comment by Aster0** [comment]
Gotcha :)
