### ISSUE TITLE
[Bug] Cannot load Citizens with latest Spigot 1.13.2 nightly build.

### ISSUE THREAD

**Issue by mrfloris** [CitizensDev/Citizens2#1714]
```
>ver
[18:47:38 INFO]: This server is running CraftBukkit version git-Spigot-cf694d8-8d8475f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:47:38 INFO]: Checking version, please wait...
[18:47:39 INFO]: You are 6 version(s) behind
>
```
any newer build of Spigot 1.13.2 causes Citizens to fail to load
```
>about Citizens
[18:47:00 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1624)
[18:47:00 INFO]: Website: http://www.citizensnpcs.co
[18:47:00 INFO]: Authors: aPunch and fullwall
>
```

error during startup:
```
[18:44:04 INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1624)
[18:44:04 ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1624) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 15 more
```

**Comment by mergu** [comment]
Hello, thanks for opening an issue! Try updating to both the latest builds of spigot and citizens, and let us know if the issue persists

https://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
That was fixed in Citizens build 1626

If you use the latest dev release of Spigot, you should get the latest dev release of any and all plugins, including Citizens.
