### ISSUE TITLE
can't load

### ISSUE THREAD

**Issue by p82183645** [CitizensDev/Citizens2#1716]
`[08:11:45] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1626)
[08:11:45] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1626) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$PooledBlockPosition
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_191]
	at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$PooledBlockPosition
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot.jar:git-Spigot-3cb9dcb-8b1588e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	... 15 more`

The output of command `/version` on my server is: **(PLEASE FILL IN)** 1.13.2
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)** (build 1626)

**Comment by mcmonkey4eva** [comment]
If you run latest Citizens, you must also run latest Spigot.
You have there latest Citizens and outdated Spigot.

**Comment by p82183645** [comment]
yes i have
