### ISSUE TITLE
Error while enabeling

### ISSUE THREAD

**Issue by xXSchrandXx** [CitizensDev/Citizens2#1719]
``` LOG
[19:03:31] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1626)
[19:03:31] [Server thread/INFO]: Creating file: config.yml
[19:03:31] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1626) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$PooledBlockPosition
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_191]
	at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$PooledBlockPosition
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	... 15 more
```

The output of command `/version` on my server is:
``` LOG
19:06:03 [INFO] Lobby > This server is running Paper version git-Paper-525 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
19:06:03 [INFO] Lobby > Previous version: git-Paper-509 (MC: 1.13.2)
19:06:03 [INFO] Lobby > Checking version, please wait...
19:06:03 [INFO] Lobby > You are 45 version(s) behind
```
The output of command `/version citizens` on my server is:
``` LOG
19:06:42 [INFO] Lobby > Citizens version 2.0.24-SNAPSHOT (build 1626)
19:06:42 [INFO] Lobby > Website: http://www.citizensnpcs.co
19:06:42 [INFO] Lobby > Authors: aPunch and fullwall
```

**Comment by mergu** [comment]
Update Paper, this has already been solved.
