### ISSUE TITLE
Violation error

### ISSUE THREAD

**Issue by FlashLight34** [CitizensDev/Citizens2#1722]
[01:45:53] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.24-SNAPSHOT (build 1613) (Is it up to date?)
java.lang.NullPointerException: null
	at net.citizensnpcs.Citizens.onDisable(Citizens.java:247) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:371) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:419) [PlugMan.jar:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:379) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[01:45:53] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "net.citizensnpcs.Citizens.createAnonymousNPCRegistry(Lnet/citizensnpcs/api/npc/NPCDataStore;)Lnet/citizensnpcs/api/npc/NPCRegistry;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/Citizens, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for interface net/citizensnpcs/api/CitizensPlugin have different Class objects for the type net/citizensnpcs/api/npc/NPCRegistry used in the signature

**Comment by FlashLight34** [comment]
spigot version: This server is running CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[23:06:09 INFO]: Checking version, please wait...

[23:06:09 INFO]: You are 1 version(s) behind

**Comment by mergu** [comment]
Do not use Plugman. It breaks **many** plugins and we are at no obligation to fix that. If you need to make plugin changes, do a full server restart.
