### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#1728]
Random error keeps popping up in console (A horse, i just deleted it now but sent you the error just incase its needed):
```
[07:41:02] [Server thread/ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 226.
[07:41:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 2
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:192)
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:90)
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:258)
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:190)
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.spawn(EventListen.java:610)
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:580)
[07:41:02] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:144)
[07:41:02] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor692.execute(Unknown Source)
[07:41:02] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[07:41:02] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[07:41:02] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[07:41:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.Chunk.addEntities(Chunk.java:981)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:535)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:116)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:110)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:105)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1068)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:939)
[07:41:02] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[07:41:02] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
The output of command `/version` on my server is: **paper 1.13.2 build 591**
The output of command `/version citizens` on my server is: **2.0.24 build 1627**

**Comment by mcmonkey4eva** [comment]
Patched via https://github.com/CitizensDev/CitizensAPI/commit/7aab5e7024646646281b21ce89a8e6ee6c5fa5c2
Patch is in Citizens build 1628+ from https://ci.citizensnpcs.co/job/Citizens2/
