### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by 1192720503** [CitizensDev/Citizens2#1732]
[14:19:48 ERROR]: [Citizens] Missing preferred location bundle.
[14:19:48 ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1626) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$PooledBlockPosition
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
        at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-529]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$PooledBlockPosition
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-529]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 15 more
[14:19:48 INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1626)
[14:19:48 ERROR]: Error occurred while disabling Citizens v2.0.24-SNAPSHOT (build 1626) (Is it up to date?)
java.lang.NullPointerException: null
        at net.citizensnpcs.Citizens.onDisable(Citizens.java:272) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:406) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-529]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-529]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by mergu** [comment]
Update Paper
