### ISSUE TITLE
NPC skins not loading

### ISSUE THREAD

**Issue by Bobbyperson12** [CitizensDev/Citizens2#1734]
The output of command `/version` on my server is: https://i.imgur.com/AdqlRCW.png
The output of command `/version citizens` on my server is: https://i.imgur.com/Qxfl3UF.png
Conifg: https://pastebin.com/QJCAHAfT
Log too long for pastebin so: https://mega.nz/#!DkdVUAxB!JFPFLsvTrFzDTm3GuzSldPEPrDXdvB-ezLp7yujS3V8
Plugins: https://i.imgur.com/cllSpvt.png

After I downloaded the most recent update to Citizens2 yesterday, skins will not load on new NPCS. Previous NPCs have their skins, but I'm afraid to test changing them. 

Any suggestions?

**Comment by mcmonkey4eva** [comment]
- Read through https://wiki.citizensnpcs.co/Skins for information about common skin handling issues.
- Your server log is filled to the brim with error messages from a plugin.
```

[18:05:40] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to TrollCommandsPlusPlus v7.29.56
java.lang.NoClassDefFoundError: me/dpohvar/powernbt/PowerNBT
	at me.egg82.tcpp.lib.ninja.egg82.nbt.reflection.powernbt.PowerNBTCompound.<init>(PowerNBTCompound.java:24) ~[?:?]
	at me.egg82.tcpp.lib.ninja.egg82.nbt.reflection.PowerNBTHelper.getCompound(PowerNBTHelper.java:32) ~[?:?]
	at me.egg82.tcpp.events.block.blockPlace.LuckyBlockEventCommand.onExecute(LuckyBlockEventCommand.java:33) ~[?:?]
	at me.egg82.tcpp.lib.ninja.egg82.patterns.Command.start(Command.java:32) ~[?:?]
	at me.egg82.tcpp.lib.ninja.egg82.bukkit.core.CoreEventHandler.onAnyEvent(CoreEventHandler.java:113) ~[?:?]
``
Please remove that plugin or get the errors fixed.

- Please remove plugin `SkinsRestorer`, that doesn't belong there at all.

**Comment by KraftLegos** [comment]
I am experiencing the same issue.

**Comment by mergu** [comment]
Post the same required output as well as a startup log and your plugin list. Also fully describe the issue you are having as well as replication steps.

**Comment by Bobbyperson12** [comment]
Even after removing both plugins I am still having the same issue.

**Comment by SXRWahrheit** [comment]
Does the issue occur if you *only* have Citizens installed?

**Comment by mcmonkey4eva** [comment]
Again,
Read through https://wiki.citizensnpcs.co/Skins for information about common skin handling issues.

**Comment by Bobbyperson12** [comment]
Update: Updating from paper-605 fixed the issue. It did not only break NPC skins, it broke skins with every plugin that used skins in some way.
