### ISSUE TITLE
Citizens does not enable because of supervanish hook.

### ISSUE THREAD

**Issue by DePianoman** [CitizensDev/Citizens2#1747]
When the server opens, the Citizens plugin refuses to enable, with the error message:
```[08:51:10] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1631)
[08:51:10] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader Citizens v2.0.24-SNAPSHOT (build 1631)
[08:51:10] [Server thread/ERROR]: [Citizens] Citizens implementation changed, disabling plugin.
[08:51:10] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1631)
[08:51:10] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.24-SNAPSHOT (build 1631) (Is it up to date?)
java.lang.NullPointerException: null
	at net.citizensnpcs.Citizens.onDisable(Citizens.java:272) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.citizensnpcs.Citizens.onImplementationChanged(Citizens.java:349) [Citizens.jar:?]
	at net.citizensnpcs.api.CitizensAPI.setImplementation(CitizensAPI.java:185) [Citizens.jar:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:284) [Citizens.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at me.codercloud.installer.manager.PluginOverview.onDoubleClick(PluginOverview.java:45) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask$Click.invoke(MenuTask.java:398) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.click(MenuTask.java:611) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.access$10(MenuTask.java:562) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask.inventoryClick(MenuTask.java:223) [Installer.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[08:51:10] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1631) (Is it up to date?)
java.lang.IllegalArgumentException: Invalid plugin passed to EventRegistrar. Is it enabled?
	at net.citizensnpcs.api.scripting.EventRegistrar.<init>(EventRegistrar.java:24) ~[?:?]
	at net.citizensnpcs.Citizens.registerScriptHelpers(Citizens.java:374) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:301) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at me.codercloud.installer.manager.PluginOverview.onDoubleClick(PluginOverview.java:45) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask$Click.invoke(MenuTask.java:398) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.click(MenuTask.java:611) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.access$10(MenuTask.java:562) [Installer.jar:?]
	at me.codercloud.installer.util.tasks.MenuTask.inventoryClick(MenuTask.java:223) [Installer.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[08:51:10] [Server thread/WARN]: [SuperVanish] Unknown exception occurred!
[08:51:10] [Server thread/WARN]: [SuperVanish] Please report this issue!
[08:51:10] [Server thread/WARN]: [SuperVanish] Message: 
[08:51:10] [Server thread/WARN]: [SuperVanish]   org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register de.myzelyam.supervanish.hooks.CitizensHook@3d75104e while not enabled
[08:51:10] [Server thread/WARN]: [SuperVanish] General information: 
[08:51:10] [Server thread/WARN]: [SuperVanish]   ServerVersion: git-Spigot-596221b-9a1fc1e (MC: 1.12)
[08:51:10] [Server thread/WARN]: [SuperVanish]   PluginVersion: 6.1.0
[08:51:10] [Server thread/WARN]: [SuperVanish]   ServerPlugins: Renamer v1.3, SignManager v2.0.1, PluginConstructorAPI v1.0.51, WelcomeMessage v1.0, GroupManager v2.0.1-b332, PlaceholderAPI v2.9.2, AlwaysDay v2.2.8, DeluxeTags v1.7.1, VoxelSniper v5.171.0-SNAPSHOT, ViaVersion v1.6.0, ChatColor v6.2, Installer v2.4.1, ParkourPlugin v1.12.2, Skript v2.3.2, QuickBoard v4.2.1, GroupChat v2.1, EasyBackup v2.1.1, ProtocolLib v4.4.0, AutoSaveWorld v4.15, VPNGuard v3.1, FastAsyncWorldEdit v19.03.02-14f3b91-1254-22.0.11, UberEnchant v7.7, PixelPrinter v1.0.43, Rename v1.0, Vault v1.7.1-b91, BKCommonLib v1.13.2-v2, HolographicDisplays v2.3.2, GUIPlus v1.11, WorldEdit v6.1.7;dd00bb1, Essentials v2.16.0.3, LightCleaner v1.13.1-v1, HeadDatabase v4.3.6, EssentialsChat v2.16.0.3, TAB v2.3.4, JoinMessagePlus v3.0, PlotSquared v3.5.0-SNAPSHOT-95f8aaa, WorldGuard v6.2.2-SNAPSHOT;8eeab68, EssentialsProtect v2.16.0.3, EssentialsGeoIP v2.16.0.3, AddLight v4.3.2, ServerSigns v4.5.1, EssentialsSpawn v2.16.0.3, Multiverse-Core v2.5.0-b727, LunaChat v2.8.9, Multiverse-Inventories v2.5.0-SNAPSHOT-b444, SimpleAlias v1.6.2, ItemJoin v5.0.2, Citizens v2.0.24-SNAPSHOT (build 1631), CommandNPC v1.9.1,
[08:51:10] [Server thread/WARN]: [SuperVanish] Settings:
[08:51:10] [Server thread/WARN]: [SuperVanish]   MsgsVersion: 6.1.0
[08:51:10] [Server thread/WARN]: [SuperVanish]   Settings: ||InvisibilityFeatures.NightVisionEffect>true||InvisibilityFeatures.DisableDamage>true||InvisibilityFeatures.DisableHunger>true||InvisibilityFeatures.DisableMobTarget>true||InvisibilityFeatures.OpenChestsSilently>true||InvisibilityFeatures.DisablePressurePlates>true||InvisibilityFeatures.DisablePush>false||InvisibilityFeatures.DefaultPickUpItemsOption>false||InvisibilityFeatures.Fly.Enable>true||InvisibilityFeatures.Fly.DisableOnReappear>true||VanishStateFeatures.AutoVanishOnJoin>false||VanishStateFeatures.ReappearOnWorldChange>false||VanishStateFeatures.ReappearOnQuit>false||VanishStateFeatures.CheckPermissionOnWorldChange>false||VanishStateFeatures.CheckPermissionOnQuit>false||VanishStateFeatures.CheckPermissionOnLogin>false||IndicationFeatures.LayeredPermissions.EnableSeePermission>true||IndicationFeatures.LayeredPermissions.LayeredSeeAndUsePermissions>false||IndicationFeatures.LayeredPermissions.MaxLevel>100||IndicationFeatures.MarkVanishedPlayersAsSpectators>true||MessageOptions.FakeJoinQuitMessages.BroadcastFakeQuitOnVanish>true||MessageOptions.FakeJoinQuitMessages.BroadcastFakeJoinOnReappear>true||MessageOptions.FakeJoinQuitMessages.AnnounceVanishReappearToAdmins>true||MessageOptions.FakeJoinQuitMessages.SendMessageOnlyToAdmins>false||MessageOptions.FakeJoinQuitMessages.SendMessageOnlyToUsers>false||MessageOptions.HideRealJoinQuitMessages>true||MessageOptions.ReappearOnQuitHideLeaveMsg>true||MessageOptions.AnnounceRealJoinQuitToAdmins>true||MessageOptions.RemindVanishedOnJoin>true||MessageOptions.DisplayActionBar>true||RestrictiveOptions.PreventBlockBreaking>false||RestrictiveOptions.PreventBlockPlacing>false||RestrictiveOptions.PreventHittingEntities>false||ExternalInvisibility.ServerList.AdjustAmountOfOnlinePlayers>true||ExternalInvisibility.ServerList.AdjustListOfLoggedInPlayers>true||HookOptions.EnableEssentialsHook>true||HookOptions.EnableDynmapHook>true||HookOptions.DynmapSendJoinLeaveMessages>true||HookOptions.EnableTrailGUIHook>true||HookOptions.EnableSuperTrailsHook>true||HookOptions.EnablePlaceholderAPIHook>true||HookOptions.EnableMVdWPlaceholderAPIHook>true||HookOptions.EnableCitizensHook>true||CompatibilityOptions.PlayerJoinEventPriority>HIGH||CompatibilityOptions.PlayerQuitEventPriority>HIGH||MiscellaneousOptions.UpdateChecker.Enable>true||MiscellaneousOptions.UpdateChecker.NotifyAdmins>true||ConfigVersion>6.1.0||
[08:51:10] [Server thread/WARN]: [SuperVanish] StackTrace: 
[08:51:10] [Server thread/WARN]: de.myzelyam.supervanish.hooks.InvalidPluginHookException: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register de.myzelyam.supervanish.hooks.CitizensHook@3d75104e while not enabled
[08:51:10] [Server thread/WARN]: 	at de.myzelyam.supervanish.hooks.PluginHookMgr.onPluginEnable(PluginHookMgr.java:83)
[08:51:10] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:51:10] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[08:51:10] [Server thread/WARN]: 	at me.codercloud.installer.manager.PluginOverview.onDoubleClick(PluginOverview.java:45)
[08:51:10] [Server thread/WARN]: 	at me.codercloud.installer.util.tasks.MenuTask$Click.invoke(MenuTask.java:398)
[08:51:10] [Server thread/WARN]: 	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.click(MenuTask.java:611)
[08:51:10] [Server thread/WARN]: 	at me.codercloud.installer.util.tasks.MenuTask$MenuPoint.access$10(MenuTask.java:562)
[08:51:10] [Server thread/WARN]: 	at me.codercloud.installer.util.tasks.MenuTask.inventoryClick(MenuTask.java:223)
[08:51:10] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:51:10] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[08:51:10] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[08:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[08:51:10] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:51:10] [Server thread/WARN]: Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register de.myzelyam.supervanish.hooks.CitizensHook@3d75104e while not enabled
[08:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:521)
[08:51:10] [Server thread/WARN]: 	at de.myzelyam.supervanish.hooks.PluginHookMgr.onPluginEnable(PluginHookMgr.java:60)
[08:51:10] [Server thread/WARN]: 	... 35 more
[08:51:10] [Server thread/WARN]: [SuperVanish] Please include this information
[08:51:10] [Server thread/WARN]: [SuperVanish] if you report the issue.
[08:51:10] [Server thread/WARN]: [SuperVanish] Affected by this error is only the Citizens-Hook, all other hooks and features aren't affected.
```

I am also posting this as an issue on SuperVanish, although as it is the Citizens plugin that isn't loading (the SuperVanish plugin works just fine) I feel like it would work here better.

[latest.log](https://github.com/CitizensDev/Citizens2/files/3099626/latest.log.txt)
[config.yml](https://github.com/CitizensDev/Citizens2/files/3099627/config.yml.txt)

The output of command `/version` on my server is: **
This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
You are 642 version(s) behind** (It's a 1.12 server, so it's not using the latest craftbukkit version)

The output of command `/version citizens` on my server is: **
Citizens version 2.0.24-SNAPSHOT (build 1631)
Website: http://www.citizensnpcs.co
Authors: aPunch and fullwall**

**Comment by mergu** [comment]
The fault is yours / one of your player's for using a plugin such as Installer to change plugins at runtime. Plugin changes must be done via a full restart. Any sufficiently advanced plugin will break if you start to flip it on and off like a lightswitch (especially if other plugins rely on it). You should strongly consider uninstalling Installer:

```
[08:51:05] [Server thread/INFO]: DevExit issued server command: /inst pm
...
[08:51:10] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1631)
[08:51:10] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader Citizens v2.0.24-SNAPSHOT (build 1631)
[08:51:10] [Server thread/ERROR]: [Citizens] Citizens implementation changed, disabling plugin.
[08:51:10] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.24-SNAPSHOT (build 1631)
[08:51:10] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.24-SNAPSHOT (build 1631) (Is it up to date?)
java.lang.NullPointerException: null
	at net.citizensnpcs.Citizens.onDisable(Citizens.java:272) ~[?:?]
...
```

**Comment by DePianoman** [comment]
Is there any way to fix it? I've uninstalled Installer and Citizens, then reinstalled Citizens to no avail, shutting the server down both times. It still won't enable.

**Comment by mergu** [comment]
Can you post a full startup log now that you've done that?

**Comment by DePianoman** [comment]
[The new startup after that](https://github.com/CitizensDev/Citizens2/files/3100188/startup.log.txt)

**Comment by mcmonkey4eva** [comment]
- You have several plugins failing to load at startup (please fix or remove them)
- `(It's a 1.12 server, so it's not using the latest craftbukkit version)` 1.12 flat is not a supported version. Use 1.12.2 latest or 1.13.2 latest.
- You have some plugin (an outdated Essentials?) spamming your logs file with thousands of lines of nonsense output. You might want to fix, replace, update, or remove that.
