### ISSUE TITLE
Crash while reloading server plugins

### ISSUE THREAD

**Issue by Sago92** [CitizensDev/Citizens2#1758]
The output of command `/version` on my server is: 
![Screenshot1](https://i.ibb.co/4ZtGhFH/2.png)
The output of command `/version citizens` on my server is:
![Screenshot2](https://i.ibb.co/kmkD37g/1.png)
Citizens configuration & latest server log file: [click](https://www.file-upload.net/download-13584802/data.zip.html)

Dear Development-Team,

when I reload my server and have NPCs from Citizens on it, the reload command crashs the server every time I use the command with the following exception.

[22:13:12 INFO]: [RightOfConquest] Disabling RightOfConquest v0.1.0
[22:13:12 INFO]: [RightOfConquest] ---------------false---------------
[22:13:12 INFO]: [Citizens] Disabling Citizens v2.0.25-SNAPSHOT (build 1661)
[22:13:12 INFO]: [RightOfConquestSecurity] Disabling RightOfConquestSecurity v0.0.1
[22:13:12 INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.3.3-SNAPSHOT
[22:13:12 INFO]: [WorldEdit] Disabling WorldEdit v7.0.0-beta-01;8975469
[22:13:12 INFO]: [SimpleBackup] Disabling SimpleBackup v1.8
[22:13:12 INFO]: [SimpleBackup] Disabled SimpleBackup
[22:13:12 INFO]: [ArmorStandEditor] Disabling ArmorStandEditor v1.13-21
[22:13:12 INFO]: Loaded 524 recipes
[22:13:12 INFO]: Reloading ResourceManager: Default, bukkit
[22:13:12 INFO]: Loaded 524 recipes
[22:13:13 INFO]: [ArmorStandEditor] Loading ArmorStandEditor v1.13-21
[22:13:13 INFO]: [SimpleBackup] Loading SimpleBackup v1.8
[22:13:13 INFO]: [WorldEdit] Loading WorldEdit v7.0.0-beta-01;8975469
[22:13:13 INFO]: [HolographicDisplays] Loading HolographicDisplays v2.3.3-SNAPSHOT
[22:13:13 INFO]: [RightOfConquestSecurity] Loading RightOfConquestSecurity v0.0.1
[22:13:13 INFO]: [Citizens] Loading Citizens v2.0.25-SNAPSHOT (build 1661)
[22:13:13 INFO]: [RightOfConquest] Loading RightOfConquest v0.1.0
[22:13:13 INFO]: [ArmorStandEditor] Enabling ArmorStandEditor v1.13-21
[22:13:13 INFO]: [SimpleBackup] Enabling SimpleBackup v1.8
[22:13:13 INFO]: [SimpleBackup] Worlds [CraftWorld{name=world}, CraftWorld{name=world_the_end}] scheduled for backup.
[22:13:13 INFO]: [SimpleBackup] Backup scheduled starting in 1.0 hours, repeat interval: 1.0 hours
[22:13:13 INFO]: [SimpleBackup] Enabled.
[22:13:13 INFO]: [WorldEdit] Enabling WorldEdit v7.0.0-beta-01;8975469
[22:13:13 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R2 as the Bukkit adapter
[22:13:14 INFO]: WEPIF: Using the Bukkit Permissions API.
[22:13:14 INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.3.3-SNAPSHOT
[22:13:14 INFO]: [HolographicDisplays] Please do not use /reload or plugin reloaders. Use the command "/holograms reload" instead. You will receive no support for doing this operation.
[22:13:14 INFO]: [RightOfConquestSecurity] Enabling RightOfConquestSecurity v0.0.1
[22:13:14 INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1661)
[22:13:14 INFO]: [Citizens] Unable to use economy handling. Has Vault been enabled?
[22:13:14 INFO]: [RightOfConquest] Enabling RightOfConquest v0.1.0
[22:13:15 INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:13:15 INFO]: DarkRykid: Reload complete.
[22:13:15 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking entity
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:979) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalStateException: no implementation set
at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:65) ~[?:?]
at net.citizensnpcs.api.CitizensAPI.getTraitFactory(CitizensAPI.java:144) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.getTraitFor(AbstractNPC.java:234) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:227) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.updateFlyableState(CitizensNPC.java:379) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.isFlyable(CitizensNPC.java:132) ~[?:?]
at net.citizensnpcs.nms.v1_13_R2.entity.SheepController$EntitySheepNPC.a(SheepController.java:70) ~[?:?]
at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2283) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:510) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityAgeable.movementTick(EntityAgeable.java:145) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityAnimal.movementTick(EntityAnimal.java:27) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntitySheep.movementTick(EntitySheep.java:95) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2098) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:248) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.World.g(World.java:1298) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
... 4 more
[22:13:15 ERROR]: 	Cause of unexpected exception was
java.lang.IllegalStateException: no implementation set
at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:65) ~[?:?]
at net.citizensnpcs.api.CitizensAPI.getTraitFactory(CitizensAPI.java:144) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.getTraitFor(AbstractNPC.java:234) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:227) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.updateFlyableState(CitizensNPC.java:379) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.isFlyable(CitizensNPC.java:132) ~[?:?]
at net.citizensnpcs.nms.v1_13_R2.entity.SheepController$EntitySheepNPC.a(SheepController.java:70) ~[?:?]
at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2283) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:510) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityAgeable.movementTick(EntityAgeable.java:145) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityAnimal.movementTick(EntityAnimal.java:27) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntitySheep.movementTick(EntitySheep.java:95) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2098) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:248) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.World.g(World.java:1298) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) ~[craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [craftbukkit.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[22:13:15 ERROR]: This crash report has been saved to: /mnt/./crash-reports/crash-2019-04-26_22.13.15-server.txt
[22:13:15 INFO]: Stopping server

I attached the log aswell the citizens configuration.

Regards
Sascha

**Comment by mcmonkey4eva** [comment]
**NEVER** use `/reload`.
Always restart the server in full.
