### ISSUE TITLE
NPE on /npc inventory with Horse

### ISSUE THREAD

**Issue by adamlaughlin** [CitizensDev/Citizens2#1760]
Ofc /npc equip worked fine, but it asked me "please report" so here is the error for your reading pleasure:
```
28.04 14:24:58 [Server] INFO smellyonionman issued server command: /npc inventory
28.04 14:24:58 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 2
28.04 14:24:58 [Server] WARN at net.citizensnpcs.api.trait.trait.Inventory.openInventory(Inventory.java:109)
28.04 14:24:58 [Server] WARN at net.citizensnpcs.commands.NPCCommands.inventory(NPCCommands.java:683)
28.04 14:24:58 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.04 14:24:58 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
28.04 14:24:58 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28.04 14:24:58 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
28.04 14:24:58 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
28.04 14:24:58 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
28.04 14:24:58 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
28.04 14:24:58 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
28.04 14:24:58 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
28.04 14:24:58 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
28.04 14:24:58 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
28.04 14:24:58 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
28.04 14:24:58 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
28.04 14:24:58 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
28.04 14:24:58 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

The output of command `/version` on my server is: **git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.24-SNAPSHOT (build 1626)**

**Comment by mcmonkey4eva** [comment]
This issue was previously fixed.
Please update to latest stable Citizens build for 1.13: https://ci.citizensnpcs.co/job/Citizens2/1636/
Or to the latest build (which is in-dev 1.14 compat, semi-stable)
