### ISSUE TITLE
noclassdeffounderror for modded server

### ISSUE THREAD

**Issue by TheNoobBoi** [CitizensDev/Citizens2#1763]
well im trying to make a modded forge server to play with my friends and i keep getting this error for the server. can someone help me? 
here's the crash report

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/28/19 5:32 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at DamageIndicatorsMod.server.DIProxy.register(DIProxy.java:11)
	at DamageIndicatorsMod.DIMod.load(DIMod.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 33 more
Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 35 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 58352664 bytes (55 MB) / 190783488 bytes (181 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (Twilight-Forest-Mod-1.7.10.jar) 
	UCHI	chisel{2.9.5.11} [Chisel] (Chisel-Mod-1.7.10.jar) 
	UCHI	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-1.7.10.jar) 
	UCHE	DamageIndicatorsMod{3.3.2} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHI	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHI	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHI	llibrary{1.5.1} [LLibrary] (LLibrary-1.7.10.jar) 
	UCHI	Morph{0.9.2} [Morph] (Morphing-Mod-1.7.10.jar) 
	UCHI	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	UCHI	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (Myths-and-Monsters-Mod-1.7.10.jar) 
	UCHI	oreexcavation{1.1.134} [OreExcavation] (Ore-Excavation-Mod-1.7.10.jar) 
	UCHI	OreSpawn{1.7.10.20.3} [OreSpawn] (Ore-Spawn-Mod-1.7.10.zip) 
	UCHI	PortalGun{4.0.0-beta-6} [PortalGun] (Portal-Gun-Mod-1.7.10.jar) 
	UCHI	Techguns{0.1.0} [Techguns] (Techguns-Mod-1.7.10.jar) 
	CoFHCore: -[1.7.10]3.1.3-327
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by mcmonkey4eva** [comment]
Did you put this issue in entirely the wrong place?
Citizens is a spigot plugin, not a forge mod, and has no relation to whatever you're doing.
