### ISSUE TITLE
idk what to do

### ISSUE THREAD

**Issue by SorrowMage** [CitizensDev/Citizens2#1766]
[10:00:50 ERROR]: Error occurred while disabling Citizens v2.0.24-SNAPSHOT (build 1605) (Is it up to date?)
java.lang.NullPointerException: null
at net.citizensnpcs.Citizens.onDisable(Citizens.java:247) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> [10:00:50 INFO]: [Sentinel] Enabling Sentinel v1.9.1 (build 253)
> [10:00:50 INFO]: [Sentinel] Sentinel loading...

**Comment by mcmonkey4eva** [comment]
Update to latest Citizens: https://ci.citizensnpcs.co/job/Citizens2/
