### ISSUE TITLE
Server Crash [1.7.10 Spigot]

### ISSUE THREAD

**Issue by Obly** [CitizensDev/Citizens2#177]
Hello whoever is reading this and hopefully will help me, I received a error in citizens that caused the server to crash.. The following was found in the console when the server crashed:

[16:20:26 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking entity
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
        at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        ... 4 more
[16:20:26 ERROR]:       Cause of unexpected exception was
java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
        at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]

If you need anymore then let me know :P.

**Comment by mcmonkey4eva** [comment]
You're running the wrong version of Citizens, get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by Obly** [comment]
O... It seems I didn't see the 1.8 protocol hack option....  It works perfectly fine now! Thanks
