### ISSUE TITLE
NoClassDefFoundError 1.14.1

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1777]
Spigot 1.14.1 (Jenkins 2295)
Citizens 2.0.25-b1689
```
>version
[18:29:27] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-8043ebc-89c52b7 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
[18:29:27] [Server thread/INFO]: You are running the latest version
>version citizens
[18:29:31] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1689)
```

On server start-up
```
[18:26:46] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1689)
[18:26:46] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.25-SNAPSHOT (build 1689) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/EntityLLamaTrader
        at net.citizensnpcs.nms.v1_14_R1.util.CustomEntityRegistry.<clinit>(CustomEntityRegistry.java:184) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.<clinit>(NMSImpl.java:1695) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at net.citizensnpcs.util.NMS.loadBridge(NMS.java:254) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.EntityLLamaTrader
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.1.jar-2019-05-13-1809:git-Spigot-8043ebc-89c52b7]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 15 more
```

**Comment by cdmvirt** [comment]
I get this also... can confirm

**Comment by Blueeyestar** [comment]
the same with me

**Comment by fullwall** [comment]
Fixed

**Comment by Blueeyestar** [comment]
it is not possible to download the version

https://ci.citizensnpcs.co/job/Citizens2/

**Comment by mcmonkey4eva** [comment]
It is quite possible to download

**Comment by SlimeDog** [comment]
Confirmed fixed with
1.14.1 (Jenkins 2294) git-Spigot-8043ebc-dd99c5b
Citizens Citizens-2.0.25-b1691

Thanks.
