### ISSUE TITLE
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#1778]
Vers.  CraftBukkit version git-Spigot-8043ebc-dd99c5b (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
citizen: Citizens-2.0.25-b1691.jar

[14:56:41] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: net.minecraft.server.v1_14_R1.ChunkCache cannot be cast to net.minecraft.server.v1_14_R1.World.
[14:56:41] [Server thread/WARN]: java.lang.ClassCastException: net.minecraft.server.v1_14_R1.ChunkCache cannot be cast to net.minecraft.server.v1_14_R1.World
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerPathfinderNormal.a(PlayerPathfinderNormal.java:301)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerPathfinderNormal.a(PlayerPathfinderNormal.java:398)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:93)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:36)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.a(PlayerNavigation.java:90)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.superb(PlayerNavigation.java:557)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.b(PlayerNavigation.java:320)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.NavigationAbstract.a(SourceFile:103)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.a(PlayerNavigation.java:108)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl$4.apply(NMSImpl.java:476)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl$4.apply(NMSImpl.java:1)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl$5.update(NMSImpl.java:537)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:77)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:161)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:290)
[14:56:41] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.World.a(World.java:745)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
[14:56:41] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
[14:56:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:44] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:44] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:44] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:44] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:44] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:44] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:44] [Server thread/WARN]: java.lang.ClassCastException
[15:57:45] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:45] [Server thread/WARN]: java.lang.ClassCastException
[15:57:45] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:45] [Server thread/WARN]: java.lang.ClassCastException
[15:57:45] [Server thread/INFO]: [Citizens] Schwerwiegender Fehler während Update von 5: null.
[15:57:45] [Server thread/WARN]: java.lang.ClassCastException

**Comment by cdmvirt** [comment]
[07:05:24 WARN]: java.lang.ClassCastException
[07:05:24 INFO]: [Citizens] Exception while updating 6: null.

mine is 6

**Comment by Blueeyestar** [comment]
Please fix quickly, my logs will be full forever..in 1/2 hour 21 mb !!

**Comment by fullwall** [comment]
Fixed
