### ISSUE TITLE
Getting this error in the console, plugin fails to load

### ISSUE THREAD

**Issue by clayvi** [CitizensDev/Citizens2#1781]
Getting this error in the console, plugin fails to load

[00:34:12] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1692)
[00:34:12] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.25-SNAPSHOT (build 1692) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/EntityLlamaTrader
        at net.citizensnpcs.nms.v1_14_R1.util.CustomEntityRegistry.<clinit>(CustomEntityRegistry.java:184) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.<clinit>(NMSImpl.java:1695) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
        at net.citizensnpcs.util.NMS.loadBridge(NMS.java:254) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.EntityLlamaTrader
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-7d29eb5]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 15 more

**Comment by mcmonkey4eva** [comment]
Please update to Spigot or Paper 1.14.1
1.14 flat is unsupported.

**Comment by clayvi** [comment]
Oh okay.. yeah I would however protocolLib hasnt been updated to 1.14.1 yet and it would break the rest of my plugins.. :c Thanks for your support
