### ISSUE TITLE
Getting this error when using the newest build of citizens

### ISSUE THREAD

**Issue by clayvi** [CitizensDev/Citizens2#1782]
[03:14:22] [Server thread/ERROR]: [GadgetsMenu] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:67) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:78) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:170) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1419) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1392) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.broadcast(PlayerChunkMap.java:1054) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:349) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:317) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:165) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:920) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:372) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:264) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 242.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        ... 35 more
Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        ... 35 more
Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Field.get(Unknown Source) ~[?:1.8.0_201]
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        ... 35 more
[03:14:40] [Server thread/ERROR]: [GadgetsMenu] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for GadgetsMenu
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:67) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:78) ~[?:?]
        at com.yapzhenyie.GadgetsMenu.hook.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:170) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1419) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1392) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.broadcast(PlayerChunkMap.java:1054) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:349) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.c(EntityTrackerEntry.java:317) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:165) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:920) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:372) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:264) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:257) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.1.jar:git-Spigot-8043ebc-dd99c5b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 242.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        ... 35 more
Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        ... 35 more
Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Field.get(Unknown Source) ~[?:1.8.0_201]
        at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
        ... 35 more

**Comment by mcmonkey4eva** [comment]
Issue is caused by GadgetsMenu.
That plugin is known to be broken.

**Comment by clayvi** [comment]
Well, removing citizens from my plugins folder gets rid of the error.

**Comment by clayvi** [comment]
Do you know why that is

**Comment by mcmonkey4eva** [comment]
The plugin is caused by GadgetsMenu.
It only happens when Citizens is present.
It is still the fault of GadgetsMenu. If you get rid of GadgetsMenu, the error will be gone then too as well.
