### ISSUE TITLE
Cannot spawn NPC using API due to `Skin applyAndRespawn Error`

### ISSUE THREAD

**Issue by SirBlobman** [CitizensDev/Citizens2#1803]
**Citizens Version:** 2.0.25-SNAPSHOT (build 1700)
**Server Version:** 1.12.2 (git-Paper-1613)
**Current Plugins:** CombatLogX (my plugin), Citizens

I am trying to use the API to spawn NPCs. Whenever I spawn an NPC for a player for the first time, this error always shows up and instantly kills the NPC. 
**Error Log**: https://pastebin.com/raw/gCRu32kH

My current code for spawning NPCs is in this pastebin: 
**Code:** https://pastebin.com/raw/quVbL4fj

**Comment by SirBlobman** [comment]
Still an issue in build 1701:

```
[11:11:30 INFO]: SirBlobman lost connection: Disconnected
[11:11:30 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Created NPC and set protected to 'false'.
[11:11:30 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Attempting to spawn NPC for player 'SirBlobman'...
[11:11:30 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Spawned NPC, checking if sentinel settings are enabled...
[11:11:30 INFO]: [CombatLogX] [Debug] [Flight Re-Enable] Checking flight re-enable for 'SirBlobman'.
[11:11:30 INFO]: [CombatLogX] [Debug] [Flight Re-Enable] Untag Reason is not expire, ignoring player.
[11:11:30 INFO]: SirBlobman left the game
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Checking if NPC is still spawned after 5 ticks...
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] NPC is spawned, running other tasks...
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Set npc health to match player health
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] NPC ID 'SirBlobman:11' has been set to a CombatLogX NPC.
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Extending time on NPC 'SirBlobman:11'.
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Added CombatLogX trait and set owner/enemy for NPC
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Stored inventory of 'SirBlobman' in NPC
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Set npc to be targetable by mobs
[11:11:31 INFO]: [CombatLogX] [Debug] [Citizens Compatibility] NPC successfully created!
[11:11:32 WARN]: [Citizens] Task #21 for Citizens v2.0.25-SNAPSHOT (build 1701) generated an exception
java.lang.NullPointerException: location cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:215) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:135) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:280) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:33) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:177) ~[?:?]
        at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1613]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1613]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1613]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**Comment by SirBlobman** [comment]
Still confirmed for 1702 (I even updated Spigot, still a bug)

```
[18:22:39] [Server thread/INFO]: SirBlobman lost connection: Disconnected
[18:22:39] [Netty Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_14_R1.NetworkManager@58f3fa7f to net.minecraft.server.v1_14_R1.HandshakeListener@63b57de7
[18:22:39] [Netty Server IO #2/DEBUG]: Enabled auto read
[18:22:39] [Netty Server IO #2/DEBUG]: Enabled auto read
[18:22:39] [Netty Server IO #2/DEBUG]: Set listener of net.minecraft.server.v1_14_R1.NetworkManager@58f3fa7f to net.minecraft.server.v1_14_R1.PacketStatusListener@633eee80
[18:22:39] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Created NPC and set protected to 'false'.
[18:22:39] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Attempting to spawn NPC for player 'SirBlobman'...
[18:22:39] [Server thread/DEBUG]: Set listener of net.citizensnpcs.nms.v1_14_R1.network.EmptyNetworkManager@5f4a7dcd to net.citizensnpcs.nms.v1_14_R1.network.EmptyNetHandler@3a5f6311
[18:22:39] [Server thread/DEBUG]: Set listener of net.citizensnpcs.nms.v1_14_R1.network.EmptyNetworkManager@5f4a7dcd to net.citizensnpcs.nms.v1_14_R1.network.EmptyNetHandler@3a5f6311
[18:22:39] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Spawned NPC, checking if sentinel settings are enabled...
[18:22:39] [Server thread/INFO]: [CombatLogX] [Debug] [Flight Re-Enable] Checking flight re-enable for 'SirBlobman'.
[18:22:39] [Server thread/INFO]: [CombatLogX] [Debug] [Flight Re-Enable] Untag Reason is not expire, ignoring player.
[18:22:40] [Server thread/INFO]: SirBlobman left the game
[18:22:40] [Craft Scheduler Thread - 4/DEBUG]: Opening connection to https://api.mojang.com/profiles/minecraft
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Checking if NPC is still spawned after 5 ticks...
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] NPC is spawned, running other tasks...
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Set npc health to match player health
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] NPC ID 'SirBlobman:10' has been set to a CombatLogX NPC.
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Extending time on NPC 'SirBlobman:10'.
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Added CombatLogX trait and set owner/enemy for NPC
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Stored inventory of 'SirBlobman' in NPC
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] Set npc to be targetable by mobs
[18:22:41] [Server thread/INFO]: [CombatLogX] [Debug] [Citizens Compatibility] NPC successfully created!
[18:22:41] [Craft Scheduler Thread - 4/DEBUG]: Writing POST data to https://api.mojang.com/profiles/minecraft: ["sirblobman"]
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Reading data from https://api.mojang.com/profiles/minecraft
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Successful read, server response was 200
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Response: [{"id":"5ba03c6cad4c44758ec98bc8a15a9ebe","name":"SirBlobman"}]
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Page 0 returned 1 results, parsing
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Successfully looked up profile com.mojang.authlib.GameProfile@21636160[id=5ba03c6c-ad4c-4475-8ec9-8bc8a15a9ebe,name=SirBlobman,properties={},legacy=false]
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Opening connection to https://sessionserver.mojang.com/session/minecraft/profile/5ba03c6cad4c44758ec98bc8a15a9ebe?unsigned=false
[18:22:42] [Craft Scheduler Thread - 4/DEBUG]: Reading data from https://sessionserver.mojang.com/session/minecraft/profile/5ba03c6cad4c44758ec98bc8a15a9ebe?unsigned=false
[18:22:43] [Craft Scheduler Thread - 4/DEBUG]: Successful read, server response was 200
[18:22:43] [Craft Scheduler Thread - 4/DEBUG]: Response: {"id":"5ba03c6cad4c44758ec98bc8a15a9ebe","name":"SirBlobman","properties":[{"name":"textures","value":"eyJ0aW1lc3RhbXAiOjE1NTk1MTQxNjA3ODEsInByb2ZpbGVJZCI6IjViYTAzYzZjYWQ0YzQ0NzU4ZWM5OGJjOGExNWE5ZWJlIiwicHJvZmlsZU5hbWUiOiJTaXJCbG9ibWFuIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jOTNjYTFiYmY4ODcwZmFkNTRjMTMzMTFmZmRhMWUwZTI5Zjc2NjE2YjE0M2FkY2JkMjEwMWI2YTA1MGIwZmFiIn19fQ==","signature":"nESJWN6Jxqp3TrwLFmYPrdIuuykVwCla/2g803oWc3c+EAhw4BGXCbIucwuiifSMVQD3i5c2TQTkEImUKfXvbm3XzuDxn9vuZBwV77ff0yFIpKNF54CNkpHe9nIybfFyH7WtdEGUTX+Srs86gJrdjMDZmKXabineoFAi+qTMbUla9zAlD0OiCuIAen+KBe6MRYbT8V7MkTdmj21BumC9XhX9WXTyMfZSEpGbnj4rBd9xJ4uMzStt0MTULtxGoSUvZ+bjX8vEnZco60UyA/wpj0Ze9PyA2QWMfmDpkYjAFub5p+BP21ZKAXLywJyp+1qP+lMnnrXHrIcTOF/rnId9/VW5Jm3zMLAwBg3vkOdQEzN7wYYLazl+yt9fX0Ngis+1b9ydGY0+B4q6+cvp4DaeSb4OHYyfTO7tf0Z7KyWkpRLo/iCC0B2OK7Bvamvc4nB0EAm60b4/DAB480GeNuyHpWVLj95BAR0SQpWgG3yuYFXaZ67g8Kpb4V6QN1oMd9l+/0NUbQqdQHH8gYypLAGr8OobBit0UChPRcP7dVIXwjl2VqWfpRLWioEGSXYzveF5qYDmrEjg7spZiNB/Xbem5YyuUTGc4OhAj/Y/1YDQH3WQ9FWum2/owQOUXvu/5UtkEFGpnLJ36XxO6VeIC7wHbsTH2NXT1nAa8N3LWbvMzNo="}]}
[18:22:43] [Server thread/WARN]: [Citizens] Task #241 for Citizens v2.0.25-SNAPSHOT (build 1702) generated an exception
java.lang.NullPointerException: location cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[patched_1.14.2.jar:git-Paper-59]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:215) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:135) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:280) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:33) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:177) ~[?:?]
	at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-59]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-59]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114) ~[patched_1.14.2.jar:git-Paper-59]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-59]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-59]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-59]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**Comment by mcmonkey4eva** [comment]
Neither of those updates were meant to address your issue.

Your issue is likely in some way related to your API code usage, rather than an issue in Citizens itself, making it difficult to provide any helpful response.

Generally speaking, in the case where you're writing your own code, the task is on you to know and follow debugging procedures to locate the source of the issue, or at least simplify it down to the smallest possible replication path.

We don't have access to your full codebase, and the issue is more likely to be in `TraitCombatLogX` or somewhere else in your project than the code you posted.

**Comment by SirBlobman** [comment]
@mcmonkey4eva All of my code can be accessed here, so if you can point out what I did wrong and what i can fix it would be nice:
https://github.com/SirBlobman/CombatLogX/tree/master/expansion/CompatCitizens/src/main

**Comment by mcmonkey4eva** [comment]
https://github.com/SirBlobman/CombatLogX/blob/master/expansion/CompatCitizens/src/main/java/com/SirBlobman/expansion/compatcitizens/trait/TraitCombatLogX.java#L93-L121
^ that's why
You remove the NPC when it despawns.
In general, the NPC despawns before it respawns.
In Citizens, the NPC needs to respawn to apply a skin change.

**Comment by SirBlobman** [comment]
Thank you for the help, its always good to have a second eye on your code :)

This seems to have fixed it
