### ISSUE TITLE
New console eror in latest paper 1.14.2

### ISSUE THREAD

**Issue by successed** [CitizensDev/Citizens2#1808]
https://hastebin.com/lujecuyaca.sql

**Comment by successed** [comment]
[11:43:43 WARN]: java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_14_R1.Entity.bukkitEntity from class net.citizensnpcs.nms.v1_14_R1.entity.VillagerController$EntityVillagerNPC
[11:43:43 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.VillagerController$EntityVillagerNPC.getBukkitEntity(VillagerController.java:179)
[11:43:43 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:42)
[11:43:43 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[11:43:43 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:230)
[11:43:43 WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:152)
[11:43:43 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[11:43:43 WARN]:        at net.citizensnpcs.Citizens.reload(Citizens.java:387)
[11:43:43 WARN]:        at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:45)
[11:43:43 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:43:43 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:43:43 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:43:43 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[11:43:43 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[11:43:43 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[11:43:43 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[11:43:43 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[11:43:43 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:43:43 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:43:43 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1832)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1640)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974)
[11:43:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[11:43:43 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by successed** [comment]
[11:45:20 INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1702)
[11:45:20 ERROR]: Error occurred while enabling Citizens v2.0.25-SNAPSHOT (build 1702) (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method "net.citizensnpcs.api.CitizensAPI.setImplementation(Lnet/citizensnpcs/api/CitizensPlugin;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/Citizens, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, net/citizensnpcs/api/CitizensAPI, have different Class objects for the type net/citizensnpcs/api/CitizensPlugin used in the signature
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:284) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-65]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:698) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:457) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by mcmonkey4eva** [comment]
Issue invalid; please follow the issue template.

Also: **DO NOT EVER** use plugman.

**Comment by successed** [comment]
> Issue invalid; please follow the issue template.
> 
> Also: **DO NOT EVER** use plugman.

even the server's version is written in the console , what is invalid? PLEASE FİX THİS PROBLEM STOP FLAME ME!

**Comment by mcmonkey4eva** [comment]
Follow the issue template.
And don't use PlugMan.

**Comment by successed** [comment]
> Follow the issue template.
> And don't use PlugMan.
Oke, can you check the problem ? #1809
