### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by 666rucio666** [CitizensDev/Citizens2#1814]
when I set up the npc server is crashing
Server version : spigot 1.13.2 
plugin version : 2.0.24 (MC 1.10-1.13.2)
command /npc create test                 <----- and booom crash 
Pls help me bro :D Thanks 

log : 
[17:15:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_13_R2.ReportedException: Ticking player
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:978) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchFieldError: ae
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:31) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:449) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:207) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityLiving.tickPotionEffects(EntityLiving.java:616) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.livingEntityBaseTick(EntityHumanNPC.java:318) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:414) ~[?:?]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1326) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1293) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:606) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1095) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:967) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	... 4 more
[17:15:50] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoSuchFieldError: ae
	at net.citizensnpcs.nms.v1_13_R2.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:31) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityTrackerEntry.scanPlayers(EntityTrackerEntry.java:449) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:207) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityLiving.tickPotionEffects(EntityLiving.java:616) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:307) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.livingEntityBaseTick(EntityHumanNPC.java:318) ~[?:?]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:414) ~[?:?]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1326) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1293) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.WorldServer.p_(WorldServer.java:606) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1095) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:967) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830) ~[spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [spigot-1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[17:15:50] [Server thread/ERROR]: This crash report has been saved to: /home/data/serwertrickpl/744025.wom/./crash-reports/crash-2019-06-06_17.15.50-server.txt
[17:15:50] [Server thread/INFO]: Stopping server

**Comment by mcmonkey4eva** [comment]
Did not follow issue template instructions.

Also, update Citizens: https://ci.citizensnpcs.co/job/Citizens2/
And Spigot: https://www.spigotmc.org/wiki/buildtools/
