### ISSUE TITLE
Citizens 1.14.3pre4  -  Encountered an unexpected exception net.minecraft.server.v1_14_R1.ReportedException

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#1837]
Citizens:Citizens-2.0.25-b1704

Spigot: CraftBukkit version git-Spigot-f16400e-8a3d3f4 (MC: 1.14.3 Pre-Release 4) (Implementing API version 1.14.3-pre4-SNAPSHOT)

It is only a pre-release version but you can read critical bugs there. 

I hope they can be fixed. Maybe the 1.14.3 will work then without further 

[14:50:58] [Server thread/INFO]: [Citizens] 45 NPCs geladen.
[14:50:59] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Ticking entity
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1066) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:955) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:800) [minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.at()Z
	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104) ~[?:?]
	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096) ~[?:?]
	at net.citizensnpcs.util.NMS.trySwim(NMS.java:421) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314) ~[?:?]
	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439) ~[?:?]
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.World.a(World.java:745) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1053) ~[minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	... 4 more

https://pastebin.com/uqCp26uy

**Comment by mcmonkey4eva** [comment]
Citizens is compatible with 1.14.2, not prereleases

**Comment by mcmonkey4eva** [comment]
Update: latest builds (1705+) now target 1.14.3-pre4.
