### ISSUE TITLE
Unexpected exception and crash

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1839]
Cannot run /version commands since the server crashed on start-up, but:
```
[06:27:20] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-df0eb25-da071ec (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
[06:28:40] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1706)
```
```
[06:29:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Ticking entity
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1070) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.ay()Z
        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096) ~[?:?]
        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439) ~[?:?]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.World.a(World.java:745) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        ... 4 more
[06:29:07] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.Entity.ay()Z
        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1104) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.trySwim(NMSImpl.java:1096) ~[?:?]
        at net.citizensnpcs.util.NMS.trySwim(NMS.java:421) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:314) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439) ~[?:?]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.World.a(World.java:745) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) ~[spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar-2019-06-21-0650:git-Spigot-df0eb25-da071ec]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Crash report available if needed.

**Comment by mcmonkey4eva** [comment]
dev builds starting at build 1705+ are compatible with Spigot 1.14.3-pre4.
Build 1704 is the last one that targets 1.14.2

**Comment by SlimeDog** [comment]
Oh. I run dev builds for testing, whenever and wherever possible. Note that b1706 runs without error on Spigot 1.13.2 !!

**Comment by mcmonkey4eva** [comment]
Yes, only 1.14.2 compatibility was dropped, as it was replaced by 1.14.3-pre4.
Older minecraft version support remains as-is, targeting the latest sub-releases (1.13.2, but not 1.13.1 or 1.13.0).

**Comment by SlimeDog** [comment]
Thanks.
