### ISSUE TITLE
Npc glowing issue

### ISSUE THREAD

**Issue by Sean1472** [CitizensDev/Citizens2#1852]
Hello, I've recently been using your citizen's plugin and the glow effect returns null whenever I type anything after "/npc glowing -- color [COLOR]". Whatever colour I try, RED, &4, 4, it always says "null".

I have found a solution (Temporary).

You can create a team, add the villagers to it and modify the glow colour which works. The only downside is citizens resets the glow colour on server restart so the team won't work properly and goes back to white.

Is there a way to possibly save the glowing colour / team issue?

The output of command `/version` on my server is: git paper-624 1.13.2
The output of command `/version citizens` on my server is:  2.0.25-Snapshot build 1717

**Comment by mcmonkey4eva** [comment]
Please post the exact command(s) that you tried in full, and the details of what NPC you were trying them on (third line indicates it may be specifically villagers?). Have you tried on other entity types (like player-type NPCs?)

**Comment by Sean1472** [comment]
Thanks for the reply.

I've tried the command /npc glowing --color RED, returns null, older versions actually return the correct colour in chat but doesn't change the NPC colour.

Tested with villagers and normal player NPCs.

This was also tested on a clean server, no other plugins

Tried respawning the NPC and that did not help either.

**Comment by Sean1472** [comment]
Also, a side note;
When I type /npc glowing --color red, while the player NPC is selected, it modifys the config properly but the glow in-game doesn't visually change despite the config changing.

Also, I reloaded citizens and restarted the server during testing with multiple different config changes to test.

**Comment by mcmonkey4eva** [comment]
Do you have any other plugins or settings that may alter your server's scoreboards?
Citizens glowing functionality (alongside longer name functionality and some other stuff) does require that Citizens be able to control the scoreboard - this most often gets broken when plugins like sidebars and tablist changers and such choose to irrelevantize the main server scoreboard

**Comment by Sean1472** [comment]
Just to reiterate, it was tested on a clean server with just Citizens on it. 

The command to change the glow color only runs properly on PLAYER type NPC's. On all other mob types, it just returns null in the chat with no config changes. Even though the config has a glowing-color option set, the visual glow around the NPC remains white no matter what. I've even tested this on a 1.9 server running citizens 2.0.18 to see if maybe going far back would do anything and the same results. The in-game color doesn't change despite /citizens reload and server restarts.

**Comment by fullwall** [comment]
Try the latest build. When you say it returns "null" usually that means you need to delete the lang folder in the plugins folder.

**Comment by Sean1472** [comment]
Thanks for the reply. I just downloaded the latest build (build 1727) and the same issue occurs.
Screenshot here for player and villager types;
https://imgur.com/ug7YjOH
As you can see, setting it to a villager and changing colour returns null, setting it to a player and changing colours returns the right colour but the glow colour still stays white in-game.

I also got this error when changing an NPC from a villager to a player type.
`[18:05:36 ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 0.
[18:05:36 WARN]: java.lang.ArrayIndexOutOfBoundsException: 8
[18:05:36 WARN]:        at net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:195)
[18:05:36 WARN]:        at net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:90)
[18:05:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:281)
[18:05:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.setEntityController(CitizensNPC.java:196)
[18:05:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:183)
[18:05:36 WARN]:        at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:1998)
[18:05:36 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:05:36 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:05:36 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:05:36 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[18:05:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[18:05:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[18:05:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[18:05:36 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[18:05:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[18:05:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:05:36 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[18:05:36 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:05:36 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[18:05:36 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[18:05:36 WARN]:        at java.lang.Thread.run(Unknown Source)`

As a side note: This was a fresh install of Citizens. No previous files were used.

**Comment by fullwall** [comment]
Fixed
