### ISSUE TITLE
Incompatibility with HolographicDisplays?

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#1858]
Paper dev 124 (Spigot 1.14.3)
Citizens2 dev 1719
HolographicDisplay dev 84
ProtocolLib Gradle dev 9

Full error spam in log.
https://paste.ubuntu.com/p/r5NYBNMzrh/

```
[05:12:41] [Server thread/ERROR]: [HolographicDisplays] Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for HolographicDisplays
java.lang.RuntimeException: Cannot retrieve entity from ID.
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:65) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityMetadata.getEntity(WrapperPlayServerEntityMetadata.java:74) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:173) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1552) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1525) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.broadcast(PlayerChunkMap.java:1206) ~[patched_1.14.3.jar:git-Paper-124]
	at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.broadcastIncludingSelf(SpigotEntityTrackerEntry.java:282) ~[?:?]
	at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.updateMetadataAndAttributes(SpigotEntityTrackerEntry.java:254) ~[?:?]
	at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.a(SpigotEntityTrackerEntry.java:144) ~[?:?]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.g(PlayerChunkMap.java:1065) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:474) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:368) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-124]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 649.
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 35 more
Caused by: java.lang.RuntimeException: Cannot read  private final net.minecraft.server.v1_14_R1.Entity net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:17) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 35 more
Caused by: java.lang.IllegalArgumentException: Can not set final net.minecraft.server.v1_14_R1.Entity field net.citizensnpcs.nms.v1_14_R1.util.PlayerlistTracker.tracker to net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_212]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_212]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:1.8.0_212]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_212]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_212]
	at com.comphenix.protocol.reflect.accessors.DefaultFieldAccessor.get(DefaultFieldAccessor.java:15) ~[?:?]
	at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:216) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
	at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
	... 35 more
```

**Comment by mcmonkey4eva** [comment]
This is probably one to report to HolographicsDisplays rather than here. Might be something we can work with them to fix together, but they'll have to start that process, as the error is in some weird reflection they're doing.

**Comment by mibby** [comment]
@mcmonkey4eva https://github.com/filoghost/HolographicDisplays/issues/135#issuecomment-510850671

**Comment by mcmonkey4eva** [comment]
Apparently the issue was in ProtocolLib, interesting. I replied to that thread with details on what went wrong and how to fix it.
