### ISSUE TITLE
spigot 1.14.4 inkompatibel

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#1875]
Spigot-Ver: CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

The latest version of Citizens is unfortunately incompatible

[02:46:10] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[02:46:10] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:46:10] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[02:46:10] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[02:46:10] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:47)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:150)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$3.run(Citizens.java:331)
[02:46:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[02:46:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816)
[02:46:10] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:46:10] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.Entity.<init>(Entity.java:199)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.<init>(EntityLiving.java:144)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.<init>(EntityInsentient.java:56)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityCreature.<init>(EntityCreature.java:10)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityMonster.<init>(SourceFile:26)
[02:46:10] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityEnderman.<init>(EntityEnderman.java:23)
[02:46:10] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EndermanController$EntityEndermanNPC.<init>(EndermanController.java:59)
[02:46:10] [Server thread/WARN]: 	... 18 more
[02:46:10] [Server thread/WARN]: [Citizens] Task #400 for Citizens v2.0.25-SNAPSHOT (build 1731) generated an exception
java.lang.NullPointerException: null
	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:150) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by successed** [comment]
[09:15:10] [Server thread/WARN]: [Citizens] Task #345 for Citizens v2.0.25-SNAPSHOT (build 1708) generated an exception
java.lang.NullPointerException: null
	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:234) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:152) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[patched_1.14.4.jar:git-Paper-135]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[patched_1.14.4.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by mcmonkey4eva** [comment]
No need to report the same error again. We'll update to 1.14.4 soon (probably by tomorrow).

**Comment by Blueeyestar** [comment]
Have major changes been made to 1.14.4 again? As in other versions? 

Because otherwise the update from Citizens was faster.  Do you already know when the update to 1.14.4 will be released?

**Comment by mcmonkey4eva** [comment]
Build 1733+ now targets 1.14.4 https://ci.citizensnpcs.co/job/Citizens2/
