### ISSUE TITLE
InvocationTargetException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#1876]
The output of command `/version` on my server is: 
```
>version
[06:12:06] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9de398a-8b09d98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[06:12:06] [Server thread/INFO]: You are running the latest version
```
The output of command /version citizens on my server is:
```
>version citizens
[06:12:43] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1731)
[06:12:43] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[06:12:43] [Server thread/INFO]: Author: fullwall
[06:12:43] [Server thread/INFO]: CitizensCMD version 2.3.2
[06:12:43] [Server thread/INFO]: Author: Mateus Moreira
```

Citizens/config.yml (comments elided) is:
```
general:
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  pathfinding:
    default-distance-margin: 2
    default-path-distance-margin: 1
    update-path-rate: 20
    maximum-new-pathfinder-iterations: 50000
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  default:
    look-close:
      enabled: false
      range: 5
      random-look-enabled: false
      random-look-delay: 60
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: stick
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: book
  teleport-delay: -1
  controllable:
    use-boat-controls: true
  player-scoreboard-teams:
    enable: true
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
```

On server start-up:
```
[05:44:50] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[05:44:50] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:44:50] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:44:50] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:44:50] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:47)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:150)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$3.run(Citizens.java:331)
[05:44:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[05:44:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816)
[05:44:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[05:44:50] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.Entity.<init>(Entity.java:199)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.<init>(EntityLiving.java:144)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.<init>(EntityInsentient.java:56)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityCreature.<init>(EntityCreature.java:10)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityAgeable.<init>(EntityAgeable.java:14)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityAnimal.<init>(EntityAnimal.java:14)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityTameableAnimal.<init>(SourceFile:32)
[05:44:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityWolf.<init>(EntityWolf.java:30)
[05:44:50] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.WolfController$EntityWolfNPC.<init>(WolfController.java:50)
[05:44:50] [Server thread/WARN]: 	... 18 more
[05:44:50] [Server thread/WARN]: [Citizens] Task #71 for Citizens v2.0.25-SNAPSHOT (build 1731) generated an exception
```

**Comment by mcmonkey4eva** [comment]
I... you... why? Why did you post this?
I have no response other than the one already given at https://github.com/mcmonkeyprojects/Sentinel/issues/301

**Comment by SlimeDog** [comment]
because one was Citizens and other was Sentinel. I did not want to assume that they were the same cause.

**Comment by SlimeDog** [comment]
Confirmed fixed by Citizens b1733. Thanks.
