### ISSUE TITLE
Missing NPCS | Script Refusing NPC Spawn during /npc create (user)

### ISSUE THREAD

**Issue by MrRbman** [CitizensDev/Citizens2#1884]
So, when I was attempting to create an npc using /npc create (user), I received an error warning me to head to console, which was preventing the spawn of the player NPC:

`[19:31:02] [Server thread/INFO]: MrRbman issued server command: /npc create MrRbman
[19:31:02] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
[19:31:02] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:31:02] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:31:02] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:31:02] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[19:31:02] [Server thread/WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[19:31:02] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:31:02] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:31:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1676)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1516)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875)
[19:31:02] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808)
[19:31:02] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[19:31:02] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
[19:31:02] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[19:31:02] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[19:31:02] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[19:31:02] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[19:31:02] [Server thread/WARN]:        ... 33 more`

The output of command `/version` on my server is: [19:26:32] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9a643a6-a77ba00 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
[19:26:32] [Server thread/INFO]: You are 17 version(s) behind

The output of command `/version citizens` on my server is: 
[19:29:04] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1737)
[19:29:04] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[19:29:04] [Server thread/INFO]: Author: fullwall

**Comment by fullwall** [comment]
Update to 1.14.4.
