### ISSUE TITLE
I know the issue... but i cant do nothing

### ISSUE THREAD

**Issue by EndeBy** [CitizensDev/Citizens2#1886]
i need to start the server on 1.14.X i know... i tried 1.14, 1.14.1, 1.14.2, 1.14.3 and no ones work. Give me that error on ALL 1.14.X versions...

[09:21:39] [Server thread/INFO]: EndeSP issued server command: /npc create k
[09:21:39] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
[09:21:39] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:21:39] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:21:39] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:21:39] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[09:21:39] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[09:21:39] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:21:39] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[09:21:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872)
[09:21:39] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805)
[09:21:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:21:39] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
[09:21:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[09:21:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[09:21:39] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:21:39] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:21:39] [Server thread/WARN]: 	... 33 more

**Comment by fullwall** [comment]
Try 1.14.4 and latest Citizens.
