### ISSUE TITLE
Npc's dont spawn after server restart

### ISSUE THREAD

**Issue by vox4455** [CitizensDev/Citizens2#1893]
Using the defaut config I have 6 npc's that just /npc look and i use /cmi ic to assign commands to them so my players click on the npc and they warp to diff locations.

https://pastebin.com/6TR0BJtM

AdvancedEnchantments*, Citizens2.0.25 (1.14.4 BUILD #1), CMI, CMIEInjector*, CoreProtect, DeluxeChat, DiscordSRV, dynmap*, IllegalStack, LuckPerms, mcMMO, PlaceholderAPI*, QuickShop, StackMob, Vault, WorldEdit, WorldGuard

Running paper 1.14.3 and all plugings are updated

The output of command `/version` on my server is:
[00:39:22 INFO]: This server is running Paper version git-Paper-132 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
[00:39:22 INFO]: Checking version, please wait...
[00:39:22 INFO]: Previous version: git-Paper-131 (MC: 1.14.3)
[00:39:22 INFO]: You are 2 version(s) behind

The output of command `/version citizens` on my server is: 
[00:40:05 INFO]: Citizens version 2.0.25-SNAPSHOT (build 1732)
[00:40:05 INFO]: Website: http://www.citizensnpcs.co
[00:40:05 INFO]: Author: fullwall

**Comment by vox4455** [comment]
now nothing works. I tryed /npc create and i got 

[00:43:52 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
[00:43:52 WARN]:        at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
[00:43:52 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
[00:43:52 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
[00:43:52 WARN]:        at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
[00:43:52 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[00:43:52 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[00:43:52 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
[00:43:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:43:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:43:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:43:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[00:43:52 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[00:43:52 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[00:43:52 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[00:43:52 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[00:43:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:43:52 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:43:52 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1837)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1645)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979)
[00:43:52 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912)
[00:43:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[00:43:52 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
[00:43:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
[00:43:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[00:43:52 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[00:43:52 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[00:43:52 WARN]:        ... 33 more

**Comment by vox4455** [comment]
Updated to 1.14.4 and it all works now.
