### ISSUE TITLE
Incompatible NMS with 1.14.2

### ISSUE THREAD

**Issue by Azarexs** [CitizensDev/Citizens2#1895]
The output of command `/version` on my server is: **1.14.2-R0.1-SNAPSHOT**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1702)**

I'm getting the following error, and I believe this to be some sort of NMS issue.
`java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
        at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91) ~[?:?]
        at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:150) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
        at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1011) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-a77ba00]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 16 more`

**Comment by mcmonkey4eva** [comment]
Update to latest Citizens build (not that one) and Spigot 1.14.4 (1.14 flat, .1, .2, and .3 are all unsupported Minecraft versions. Unsupported by Minecraft itself, I mean... they were replaced by patches, thus the sub-release versions)
