### ISSUE TITLE
cant create npc's

### ISSUE THREAD

**Issue by realFaiden** [CitizensDev/Citizens2#1905]
i got a spigot 1.14.2 server with the latest citizens 2 version

if i write: /npc create Test (or somthing like that)

thats the consol output:

[15:46:32] [Server thread/INFO]: TTTobi issued server command: /npc create teo
[15:46:32] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
[15:46:32] [Server thread/WARN]: at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.(PlayerNavigation.java:68)
[15:46:32] [Server thread/WARN]: at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292) [15:46:32] [Server thread/WARN]: at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.(EntityHumanNPC.java:91)
[15:46:32] [Server thread/WARN]: at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
[15:46:32] [Server thread/WARN]: at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[15:46:32] [Server thread/WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[15:46:32] [Server thread/WARN]: at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:426)
[15:46:32] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:46:32] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
rate limit exceeded

Thank you

**Comment by mcmonkey4eva** [comment]
Update to 1.14.4

**Comment by realFaiden** [comment]
is there a way, that it work for 1.14.2, because the server has to be on this version?

best regards

**Comment by mcmonkey4eva** [comment]
Your server does **not** have to be on 1.14.2, I can just about guarantee it. Update to 1.14.4
