### ISSUE TITLE
Error loading NPCs

### ISSUE THREAD

**Issue by masterstreamer** [CitizensDev/Citizens2#1908]
Issue posts that fail to follow the instructions here will be automatically closed!
Please include:
- A detailed description of your issue or feature request
- Link to server log & Citizens config (using e.g. pastebin.com) ESPECIALLY if it's a pathfinding issue
- **Spigot and Citizens versions!** Use in-game commands "/version" and "/version citizens" and screenshot or copy/paste the EXACT output of BOTH commands!
- FOR LAG RELATED ISSUES: please include server specs, number of NPCs, saves.yml and timings from WarmRoast or other profiler (NOT just Spigot timings, though that can be included as well)
-->

The output of command `/version` on my server is: **git-Spigot-e5b1b5d-1ec1b05**
The output of command `/version citizens` on my server is: **2.0.25-SNAPSHOT (build 1706)**

After upgrading from Citizens 2.0.25-SNAPSHOT (build 1675) to Citizens 2.0.25-SNAPSHOT (build 1706) all NPCs are despawned. 
Before the upgrade, the server was git-Spigot-1a3504a-dfa7583.
This are the Citizens-related errors:
``
[20:22:43] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:22:43] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:22:43] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:22:43] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:22:43] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[20:22:43] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:47)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:234)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:152)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$3.run(Citizens.java:331)
[20:22:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[20:22:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1021)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:969)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:814)
[20:22:43] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)
[20:22:43] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.Entity.<init>(Entity.java:199)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.<init>(EntityLiving.java:144)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.<init>(EntityInsentient.java:56)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityCreature.<init>(EntityCreature.java:10)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityMonster.<init>(SourceFile:26)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityMonsterPatrolling.<init>(SourceFile:31)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityRaider.<init>(EntityRaider.java:25)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityIllagerAbstract.<init>(SourceFile:21)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityIllagerWizard.<init>(SourceFile:26)
[20:22:43] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityEvoker.<init>(SourceFile:44)
[20:22:43] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EvokerController$EntityEvokerNPC.<init>(EvokerController.java:46)
[20:22:43] [Server thread/WARN]: 	... 19 more
[20:22:43] [Server thread/WARN]: [Citizens] Task #74 for Citizens v2.0.25-SNAPSHOT (build 1706) generated an exception
java.lang.NullPointerException: null
	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[Citizens-2.0.25-b1706.jar:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[Citizens-2.0.25-b1706.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:234) ~[Citizens-2.0.25-b1706.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:152) ~[Citizens-2.0.25-b1706.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[Citizens-2.0.25-b1706.jar:?]
	at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[Citizens-2.0.25-b1706.jar:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot_server.jar:git-Spigot-1981d55-3e7b386]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot_server.jar:git-Spigot-1981d55-3e7b386]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1021) [spigot_server.jar:git-Spigot-1981d55-3e7b386]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot_server.jar:git-Spigot-1981d55-3e7b386]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:969) [spigot_server.jar:git-Spigot-1981d55-3e7b386]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:814) [spigot_server.jar:git-Spigot-1981d55-3e7b386]
	at java.lang.Thread.run(Thread.java:835) [?:?]
``

**Comment by Ph4i1ur3** [comment]
Try the latest build from Jenkins:
https://ci.citizensnpcs.co/job/Citizens2/1738/
