### ISSUE TITLE
NPC connected with each other with no reason.

### ISSUE THREAD

**Issue by BrainRTP** [CitizensDev/Citizens2#1912]
Bug: https://youtu.be/NtQhXFbDgh8
Citizens version 2.0.25-SNAPSHOT (build 1742)
git-Paper-631 (MC: 1.13.2)
error with 22 character. (example from video: "&6Кузнец &7[Уровень 1]")
If name > 22 or name <22 then everything is ok.

> @mcmonkey4eva 
>This is a base name vs. long name issue.
>Player entity names are 16 characters long... Citizens has a system to let you add longer names, but this uses scoreboard extensions to the base name.
>If two NPCs have the same name, they automatically have the same scoreboard extension text.

>To combat this, you can add a stray color code in the middle.
>For example, instead of &6Big Old NPC Guy Thing &5#1 you do &6Big Old&1 &6NPC Guy Thing &5#1.
>That &1 &6 in the middle makes no visual difference but makes the names be technically different (and thus not conflict).

Sometimes It doesn't work. (bug: https://youtu.be/hwB09HFMANM)
And i found new problem:
<img width="1440" alt="Снимок экрана 2019-08-10 в 22 45 02" src="https://user-images.githubusercontent.com/22731705/62825367-d64e8e00-bbc3-11e9-9d7c-c8d713291328.png">

**Comment by BrainRTP** [comment]
This error occures when executing command `/npc rename &eBlacksmith &7[Level 01]`:
```
[21:24:26 INFO]: Profile lookup for player 'ith [level 0' failed2: Server did not find the requested profile
[21:24:26 INFO]: com.mojang.authlib.yggdrasil.ProfileNotFoundException: Server did not find the requested profile
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:69)
        at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:45)
        at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:48)
        at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:121)
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
"F1" mode:
![2019-08-10_23 25 19](https://user-images.githubusercontent.com/22731705/62825511-54ac2f80-bbc6-11e9-908e-4c070394e520.png)
without "F1" mode:
![2019-08-10_23 25 18](https://user-images.githubusercontent.com/22731705/62825512-54ac2f80-bbc6-11e9-8ec0-4d515bab3990.png)

**Comment by mcmonkey4eva** [comment]
- Please don't open multiple issues for the same thing, just reply to your existing issue #1860 if it's the same.
- My answer to that issue still applies to part of your current trouble.
You have to actual make the names distinct through hidden colors (notice how in my example, I made a space be colored completely different from everything else... you can't visually see it but it internally makes a difference. Simple duplicate color codes are liable to be autoremoved internally).
- That error message is a normal one when you have debug enabled, you can ignore it (or turn debug off to get rid of it).
- The 7 that appeared out of nowhere is something that can happen if the 16 character split is right in the middle of a color code (ie it put the `&` in the prefix and the `7` in the next part, so it got borked).
