### ISSUE TITLE
Crashing Error

### ISSUE THREAD

**Issue by MothGirlMusic** [CitizensDev/Citizens2#1960]
** DO NOT IGNORE **
Issue posts that fail to follow the instructions here will be automatically closed!
Please include:
- A detailed description of your issue or feature request
There's an error that crashes the server every so often. theres nothing wrong in game just every so often the server just shuts down. i have no real way of knowing whats wrong.

- Link to server log & Citizens config (using e.g. pastebin.com) ESPECIALLY if it's a pathfinding issue
will be provided if its asked for/needed

- **Spigot and Citizens versions!** Use in-game commands "/version" and "/version citizens" and screenshot or copy/paste the EXACT output of BOTH commands!
[04:37:29] [Server thread/INFO]: Server version: Spigot 1.14.4-R0.1-SNAPSHOT
[04:38:13] [Server thread/INFO]: =====[ Citizens v2.0.25-SNAPSHOT (build 1762) ]=====

- FOR LAG RELATED ISSUES: please include server specs, number of NPCs, saves.yml and timings from WarmRoast or other profiler (NOT just Spigot timings, though that can be included as well)
its not lag. its just full on immediate crashing.

The output of command `/version` on my server is: **(PLEASE FILL IN)**
its posted above
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
its posted above.

this is the error [i guess theres no spacei n the template to give errors]
```
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register net.citizensnpcs.trait.Gravity@6b05eb5c while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:552)
	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
	at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:228)
	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:419)
	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568)
	at net.minecraft.server.v1_14_R1.World.a(World.java:745)
	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344)
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068)
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcmonkey4eva** [comment]
- Please post the actual output of the two commands as requested. What you posted was not that.

- Please post a pastebin link to your FULL `logs/latest.log` containing the error. The error you posted is not complete.

**Comment by mcmonkey4eva** [comment]
Closing due to lack of reply. Will reopen when the requested information is posted.
