### ISSUE TITLE
Citizens Navigator Error In 1.15.x

### ISSUE THREAD

**Issue by TheLastBlockbender** [CitizensDev/Citizens2#1995]
Not sure how to describe this issue, was told to post this here by mcmonkey. Thanks for all your help man.
Here's the pastebin of my latest server log:
https://pastebin.com/epATF97g

Versions:
Citizens v2.0.26-SNAPSHOT (build 1790) -- (Current build)
Denizen v1.1.2-SNAPSHOT (build 4471-DEV) -- (Current build)
Depenizen v2.0.0 (build 580) -- (Current build)
Sentinel v2.0.1-SNAPSHOT (build 328) -- (Current build)
Server: Paper version git-Paper-22 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by mcmonkey4eva** [comment]
Navigator error in 1.15.x
```
[01:37:17] [Server thread/WARN]: java.lang.NullPointerException
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:145)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:98)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:95)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_15_R1.util.PlayerNavigation.a(PlayerNavigation.java:103)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.NavigationAbstract.a(NavigationAbstract.java:84)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_15_R1.util.PlayerNavigation.a(PlayerNavigation.java:124)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl$4.apply(NMSImpl.java:533)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl$4.apply(NMSImpl.java:1)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl$5.update(NMSImpl.java:594)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:73)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:319)
[01:37:17] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:713)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.World.a(World.java:878)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:479)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1238)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106)
[01:37:17] [Server thread/WARN]:    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933)
[01:37:17] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:748)
```
Similar errors have been posted by other users as well recently.

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/20892253210f141b81017a4392adbc6c9af641fd in build 1793+ on https://ci.citizensnpcs.co/job/Citizens2/
