### ISSUE TITLE
Repo problem with betonquest

### ISSUE THREAD

**Issue by BijuuKrunos** [CitizensDev/Citizens2#2008]
repo is down?

```
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://repo.citizensnpcs.co/pl/betoncraft/betonquest/BetonQuest-bootstrap/1.12-SNAPSHOT/BetonQuest-bootstrap-1.12-SNAPSHOT.pom. Return code is: 502 , ReasonPhrase:Bad Gateway.
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1021)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
        ... 41 more

```

I want to build with maven.

**Comment by fullwall** [comment]
Can you post your pom.xml?

**Comment by BijuuKrunos** [comment]
I didnot edit anything here..

```
        <!-- CitizenNPC Repo -->
        <repository>
            <id>everything</id>
            <url>http://repo.citizensnpcs.co/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```

```
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizensapi</artifactId>
            <version>2.0.24-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```

Denizen same problem... links do not work is the Jenkins down or something?

**Comment by BijuuKrunos** [comment]
https://ci.citizensnpcs.co/job/Citizens2/
down as well.

**Comment by mcmonkey4eva** [comment]
Jenkins (and the repo, which is hosted by Jenkins)
It's scheduled to self-restart every 2 hours, due to the never-ending DDoS attack it seems to be receiving. If it goes down, just wait an hour or two and it'll be back on its own.
I'm hoping to find more ways to mitigate the attack and allow it to stay online more stably, but it's a whole experimentation process...

We have CloudFlare as a caching layer, but even that is only able to do so much.
