### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Blox61** [CitizensDev/Citizens2#2009]
```
[17:24:47] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.26-SNAPSHOT (build 1801) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Villager$Type
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_222]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_222]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_222]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_222]
	at net.citizensnpcs.api.command.Injector.getInstance(Injector.java:22) ~[?:?]
	at net.citizensnpcs.api.command.CommandManager.registerMethods(CommandManager.java:412) ~[?:?]
	at net.citizensnpcs.api.command.CommandManager.register(CommandManager.java:389) ~[?:?]
	at net.citizensnpcs.nms.v1_14_R1.util.NMSImpl.load(NMSImpl.java:670) ~[?:?]
	at net.citizensnpcs.util.NMS.load(NMS.java:285) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:324) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Villager$Type
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
	... 19 more
```

**Comment by mcmonkey4eva** [comment]
You need 1.14.4, not 1.14 flat.
Alternately, run 1.13.2 or 1.15.1
