### ISSUE TITLE
[1.13.2] Is it up to date problem

### ISSUE THREAD

**Issue by Vitowt** [CitizensDev/Citizens2#2013]
Please include:
- A detailed description of your issue or feature request:
All versions matched as "...-1.13.2" on minecraft spigot 1.13.2 dont work. There is log from console

[22:43:12 INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1605)
[22:43:12 INFO]: Creating file: config.yml
[22:43:12 ERROR]: [Citizens] Missing preferred location bundle.
[22:43:12 ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1605) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_152]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_152]
        at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:266) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_152]
        ... 15 more

The output of command `/version` on my server is: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
The output of command `/version citizens` on my server is:  Citizens version 2.0.24-SNAPSHOT (build 1605)

**Comment by mcmonkey4eva** [comment]
That is a very old build. You need the latest build of Citizens which can be found at https://ci.citizensnpcs.co/job/Citizens2/
