### ISSUE TITLE
 Plugin attempted to register net.citizensnpcs.trait.Gravity

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#2019]
Spigot-Ver:CraftBukkit version git-Spigot-492a779-b98e2de (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

Citizens-Build: 1804

**I had a crash on the server and in the crash report it is because of Citizens. I have attached the report**

org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register net.citizensnpcs.trait.Gravity@5e58e8be while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:552)
	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
	at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:234)
	at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:419)
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:623)
	at net.minecraft.server.v1_15_R1.World.a(World.java:718)
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395)
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076)
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Ph4i1ur3** [comment]
The above is not indicative of a crash caused by Citizens at all.

Please paste your full log to pastebin and put the link here.
