### ISSUE TITLE
[Bug] Can't perform the command /citizens save without error

### ISSUE THREAD

**Issue by Tiplish** [CitizensDev/Citizens2#2027]
Hi,

When i'm doing the command /citizens save, i'm having this on console : 

[13:13:35] [Server thread/INFO]: Tiplish issued server command: /citizens save
[13:13:35] [Server thread/WARN]: java.lang.NullPointerException

no more informations :s 
In game, i've just the same error as in the console and instruction about looking at the console for more informations. 

The output of command `/version` on my server is: 
**This server is running CraftBukkit version git-Spigot-492a779-fde78ef (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
**
The output of command `/version citizens` on my server is: 
** Citizens version 2.0.26-SNAPSHOT (build 1792)**

**Comment by Tiplish** [comment]
New message to add : 

[13:57:10] [Server thread/WARN]: java.lang.NullPointerException
[13:57:10] [Server thread/WARN]:        at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.save(Citizens_Processing.java:1407)
[13:57:10] [Server thread/WARN]:        at net.livecar.nuttyworks.npc_destinations.citizens.Citizens_Processing.trait_saveSettings(Citizens_Processing.java:70)
[13:57:10] [Server thread/WARN]:        at net.livecar.nuttyworks.npc_destinations.citizens.NPCDestinationsTrait.save(NPCDestinationsTrait.java:184)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:336)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:177)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:480)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:484)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.commands.AdminCommands.save(AdminCommands.java:64)
[13:57:10] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:57:10] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:57:10] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:57:10] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[13:57:10] [Server thread/WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[13:57:10] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:57:10] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[13:57:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:893)
[13:57:10] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827)
[13:57:10] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by Ph4i1ur3** [comment]
The errors seems to be from a plugin called "NPC Destinations", and is not a Citizens issue.

**Comment by mcmonkey4eva** [comment]
Yep, contact the developer of that plugin.
