### ISSUE TITLE
Having trouble with Citizends

### ISSUE THREAD

**Issue by KotypeyPyEdition** [CitizensDev/Citizens2#2033]
Cant load plugin(when updated paper spigot version)
except:
`[02:36:04 ERROR]: Error occurred while enabling Citizens v2.0.24-SNAPSHOT (build 1591) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$b
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_232]
at net.citizensnpcs.util.NMS.loadBridge(NMS.java:189) ~[?:?]
at net.citizensnpcs.Citizens.onEnable(Citizens.java:266) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Paper-624]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[server.jar:git-Paper-624]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[server.jar:git-Paper-624]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[server.jar:git-Paper-624]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[server.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[server.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[server.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[server.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[server.jar:git-Paper-624]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[server.jar:git-Paper-624]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$b
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Paper-624]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Paper-624]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
... 15 more`

Version:
`version Citizens
[02:39:14 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1591)
[02:39:14 INFO]: Website: http://www.citizensnpcs.co
[02:39:14 INFO]: Authors: aPunch and fullwall
version
[02:39:17 INFO]: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[02:39:17 INFO]: Previous version: git-Paper-1574 (MC: 1.12.2)
[02:39:17 INFO]: Checking version, please wait...
[02:39:17 INFO]: You are 31 version(s) behind`

i hope you can help i tried another version but it still not working :(

**Comment by KotypeyPyEdition** [comment]
version Citizens
[02:39:14 INFO]: Citizens version 2.0.24-SNAPSHOT (build 1591)
[02:39:14 INFO]: Website: http://www.citizensnpcs.co
[02:39:14 INFO]: Authors: aPunch and fullwall
version
[02:39:17 INFO]: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[02:39:17 INFO]: Previous version: git-Paper-1574 (MC: 1.12.2)
[02:39:17 INFO]: Checking version, please wait...
[02:39:17 INFO]: You are 31 version(s) behind

**Comment by SXRWahrheit** [comment]
That version of Paper is not updated, neither is your Citizens version updated. Your version of Citizens is about 300 builds out-of-date. Please update before opening an issue.

**Comment by mcmonkey4eva** [comment]
^ Ye https://papermc.io/legacy + https://ci.citizensnpcs.co/job/Citizens2/
Though: strongly consider updating to MC 1.15.2 as soon as possible. 1.13.2 support was already dropped by the Paper team.
