### ISSUE TITLE
Do not use `teleport` in pathfinder

### ISSUE THREAD

**Issue by Luluno01** [CitizensDev/Citizens2#2051]
I made a plugin that equips an NPC an elytra then makes it fly toward some target using built-in navigator (`npc.getNavigator().setTarget(location)`). The NPC flies well on its own, but once it has a passenger, it will drop the passenger during navigation. If the passenger is a player, that will sometimes crash the server (log shown below). I have looked into the [code](https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/ai/FlyingAStarNavigationStrategy.java) and found that it is teleporting the NPC all the time, which leads to dropping of passengers.

I am currently using `NMS.look` and `entity.setVelocity` as workaround. They seem to be working well.

Server log:

```
[16:20:33] [Server thread/WARN]: Entity threw exception at world:-161.10431677383428,76.74307803992303,49.70227815682517
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: java.lang.OutOfMemoryError: Java heap space
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1896)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2114)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:159)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[16:20:33] [Log4j2-TF-1-AsyncLogger[AsyncContext@6d06d69c]-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:830)
[16:20:33] [Server thread/WARN]: java.lang.OutOfMemoryError: Java heap space
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayOutLightUpdate.<init>(SourceFile:50)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1561)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:1050)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1323)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1460)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityPlayer.stopRiding(EntityPlayer.java:1093)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityPlayer.stopRiding(EntityPlayer.java:1077)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Entity.ejectPassengers(Entity.java:2052)
[16:20:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.eject(CraftEntity.java:653)
[16:20:33] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:385)
[16:20:33] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:416)
[16:20:33] [Server thread/WARN]: 	at net.citizensnpcs.npc.ai.FlyingAStarNavigationStrategy.update(FlyingAStarNavigationStrategy.java:164)
[16:20:33] [Server thread/WARN]: 	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:158)
[16:20:33] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:319)
[16:20:33] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer$$Lambda$3191/0x0000000801738840.accept(Unknown Source)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.a(World.java:856)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[16:20:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[16:20:33] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:830)
[16:20:33] [Server thread/ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC} did not stopTiming)
java.lang.Throwable: null
	at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.15.2.jar:git-Paper-105]
	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:511) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-105]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-105]
	at java.lang.Thread.run(Thread.java:830) [?:?]
```

*It's probably not a bug of paper because the reason of crashing should be teleporting an entity with passenger(s).*

The output of command `/version` on my server is: **This server is running Paper version git-Paper-105 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1822)**

**Comment by mcmonkey4eva** [comment]
That crash is an Out Of Memory error...

**Comment by Luluno01** [comment]
@mcmonkey4eva Yeah, the issue template asked me to show some server logs so I pasted it here... The actual problem will not be seen in logs but in game. If you ride on the NPC and it starts navigating, you will firstly get on and off the NPC at a high frequency, then falling into void and disconnect because of server's running out of memory (for unknown reason).

**Comment by mcmonkey4eva** [comment]
Issue should be resolved by commit https://github.com/CitizensDev/Citizens2/commit/225ede02cecb1470a6ef5462c6e9063ce19c2642 from fullwall, available in build 1829+ from https://ci.citizensnpcs.co/job/Citizens2/

**Comment by Luluno01** [comment]
@mcmonkey4eva Oh, great! But have you tested? I have tried using `NMS.setYaw` and `entity.setVelocity` previously, the animation looks normal only when flying toward one direction, say from location A to B (I mean gliding with elytra). If back from B to A, the NPC will fly upside down, facing the sky (which is funny). I am currently using `NMS.look`, which seems to fix the problem.

**Comment by Luluno01** [comment]
And some other pathfinding-related functions are still using teleport without checking passengers to move NPCs. Here is the call stack:

```
[15:23:56 WARN]: java.lang.OutOfMemoryError: Java heap space
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayOutLightUpdate.<init>(SourceFile:42)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1561)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.sendChunk(PlayerChunkMap.java:1050)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1323)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:1460)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.EntityPlayer.stopRiding(EntityPlayer.java:1093)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.EntityPlayer.stopRiding(EntityPlayer.java:1077)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.Entity.ejectPassengers(Entity.java:2052)
[15:23:56 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.eject(CraftEntity.java:653)
[15:23:56 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:385)
[15:23:56 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:416)
[15:23:56 WARN]:        at net.citizensnpcs.api.ai.TeleportStuckAction.run(TeleportStuckAction.java:38)
[15:23:56 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:312)
[15:23:56 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:152)
[15:23:56 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:319)
[15:23:56 WARN]:        at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.WorldServer$$Lambda$2993/0x00000008016b0c40.accept(Unknown Source)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.World.a(World.java:856)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[15:23:56 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[15:23:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:830)
```

(Build 1829, controllable and flyable NPC equiped with elytra, waypoints added using `/npc path` command)

**Comment by mcmonkey4eva** [comment]
That's the TeleportStuckAction - ie the default setting to teleport when no valid path can be found (this can be changed via commands or API options to instead do nothing when stuck)

**Comment by fullwall** [comment]
The point of npc.teleport is that it does check passengers and teleports them with the NPC by ejecting and then re-mounting (https://github.com/CitizensDev/CitizensAPI/blob/master/src/main/java/net/citizensnpcs/api/npc/AbstractNPC.java#L383)

**Comment by Luluno01** [comment]
Thank you for replying. So why would `teleport` eat up all the memory? That's frustrating :(. Besides, the NPC that glides toward a waypoint is still glitching (looks really funny lol).

**Comment by Luluno01** [comment]
I am not sure whether the glitch and OutOfMemory are caused by one single `teleport` call or multiple calls. So weird :(
