### ISSUE TITLE
NPC command is not saved

### ISSUE THREAD

**Issue by benr233** [CitizensDev/Citizens2#2061]
When the server is turned off, the NPC command will not be saved in the file. When the server is turned on, the NPC no longer has the command.

**Comment by fullwall** [comment]
Server logs? Remember to use /stop if you want to be sure every thing is saved.

**Comment by benr233** [comment]
Yes, I use / stop, but the command is not saved normally, and the server has no errors.

**Comment by benr233** [comment]
server version : 1.15.2 paper-121

**Comment by fullwall** [comment]
Can you pastebin your log please?

**Comment by benr233** [comment]
[Citizens] Disabling Citizens v2.0.26-SNAPSHOT (build 1840)
[11:44:49] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.26-SNAPSHOT (build 1840) (Is it up to date?)
java.lang.ClassCastException: java.util.UUID cannot be cast to java.lang.String
	at net.citizensnpcs.api.persistence.PersistenceLoader.serialise(PersistenceLoader.java:431) ~[?:?]
	at net.citizensnpcs.api.persistence.PersistenceLoader.save(PersistenceLoader.java:408) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:342) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:178) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91) ~[?:?]
	at net.citizensnpcs.Citizens.onDisable(Citizens.java:272) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:468) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:454) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:447) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:404) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:742) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by fullwall** [comment]
Can you try the latest build?

**Comment by benr233** [comment]
Okay, I'll try

**Comment by benr233** [comment]
[Citizens] Disabling Citizens v2.0.26-SNAPSHOT (build 1841)
[11:59:05] [Server thread/ERROR]: Error occurred while disabling Citizens v2.0.26-SNAPSHOT (build 1841) (Is it up to date?)
java.lang.ClassCastException: java.util.UUID cannot be cast to java.lang.String
	at net.citizensnpcs.api.persistence.PersistenceLoader.serialise(PersistenceLoader.java:434) ~[?:?]
	at net.citizensnpcs.api.persistence.PersistenceLoader.save(PersistenceLoader.java:411) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:342) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:178) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91) ~[?:?]
	at net.citizensnpcs.Citizens.onDisable(Citizens.java:272) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:468) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:454) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:447) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:404) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:742) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[Paper-1.15.2-b121.jar:git-Paper-120]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by fullwall** [comment]
1842 should fix this.
