### ISSUE TITLE
Unhandled error with /npc select

### ISSUE THREAD

**Issue by Vekseid** [CitizensDev/Citizens2#207]
From the log (tried to select NPC by id)

[22:21:11] [Server thread/INFO]: Vekseid issued server command: /npc select 4
[22:21:11] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/conversations/NumericPrompt
[22:21:11] [Server thread/WARN]:        at java.lang.ClassLoader.defineClass1(Native Method)
[22:21:11] [Server thread/WARN]:        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[22:21:11] [Server thread/WARN]:        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[22:21:11] [Server thread/WARN]:        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[22:21:11] [Server thread/WARN]:        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[22:21:11] [Server thread/WARN]:        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[22:21:11] [Server thread/WARN]:        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[22:21:11] [Server thread/WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[22:21:11] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[22:21:11] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)

**Comment by Vekseid** [comment]
Scratch this, I didn't actually have the latest dev build.
