### ISSUE TITLE
Error executing task on Client - java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#2072]
The output of command `/version` on my server is: **This server is running Purpur version git-Purpur-508 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1852)**

Purpur dev 508 (Paper Fork for Spigot 1.15.2)
Citizens2 dev 1852
BungeeTabListPlus dev 937
NametagEdit dev 69

Citizens config.yml
https://paste.ubuntu.com/p/kwJK35RbgG/

This client error seems to occur whenever NPCs are unloaded and loaded back into chunk view (i.e. flying away and back). It seems to occur for as many NPCs that are in the area that unload and reload.

```
[04:06:37] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at dnp.a(SourceFile:565) ~[dnp.class:?]
	at mc.a(SourceFile:57) ~[mc.class:?]
	at mc.a(SourceFile:11) ~[mc.class:?]
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[lv.class:?]
	at lv$$Lambda$2387/1274735625.run(Unknown Source) ~[?:?]
	at ais.c(ThreadTaskExecutor.java:173) [ais.class:?]
	at aiw.c(SourceFile:23) [aiw.class:?]
	at ais.w(ThreadTaskExecutor.java:135) [ais.class:?]
	at ais.bk(ThreadTaskExecutor.java:115) [ais.class:?]
	at dbn.d(SourceFile:956) [dbn.class:?]
	at dbn.d(SourceFile:619) [dbn.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]
```

**Comment by mcmonkey4eva** [comment]
Can you replicate this on a vanilla 1.15.2 client on a Spigot 1.15.2 server?

If so, please reply with with a full pastebin of `logs/latest.log` of that server, and a new copy of the clientside error message.

**Comment by mibby** [comment]
@mcmonkey4eva Apologies, you seem to be correct. Reproducing with Spigot 1.15.2 does not have the issue occurring. It seems to be isolated to a patch incompatibility with tuinity and has been forwarded that direction.
