### ISSUE TITLE
1.15 Console Spam - sendPacketsNearby

### ISSUE THREAD

**Issue by cursedgerbil** [CitizensDev/Citizens2#2078]
/version: CraftBukkit version git-Spigot-a03b1fd-fc318cc (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT) - latest version, I was on an older version and switched to the latest version to see if it would fix the issue, with no luck

/version citizens: 2.0.26-SNAPSHOT (build 1856)

I'm using Citizens on a 1.15.2 server and created an NPC. While I have an NPC active on the server, I constantly receive an error message in console:

```
 Exception while updating 3: null.
[22:32:00] [Server thread/WARN]: java.lang.NullPointerException
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1640)
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.sendPacketNearby(NMSImpl.java:1635)
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.sendPacketNearby(NMSImpl.java:1629)
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.sendPositionUpdate(NMSImpl.java:960)
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.util.NMS.sendPositionUpdate(NMS.java:346)
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:354)
[22:32:00] [Server thread/WARN]:        at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:439)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:626)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.World.a(World.java:692)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[22:32:00] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[22:32:00] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
```

I've checked my Citizens configs and no null values or otherwise odd things seem to be present at a glance. I also don't believe any of my other plugins would cause conflicts with Citizens, though I will list them below:

ChatControl, CoreProtect, CustomCrafting, EssentialsX, EpicWorldGenerator, FastChunkPregenerator, GroupManager, Harbor, MobArena, MyPet, MythicMobs, Shopkeepers, Towny, Vault, WorldEdit, WorldGuard

To be clear, I'm NOT running Paper (EpicWorldGenerator doesn't support it).

Any idea what this issue is? I've scrounged the internet and this issue tracker with little findings and have no idea how to rectify this issue.
Thanks for your help.

**Comment by mergu** [comment]
Update - https://ci.citizensnpcs.co/job/Citizens2/

**Comment by cursedgerbil** [comment]
Thanks! This issue is fixed in the latest build. I'll close this issue!
