### ISSUE TITLE
NPC despawn error

### ISSUE THREAD

**Issue by Nick-kel** [CitizensDev/Citizens2#2109]
A detailed description of my issue:
I try to despawn a NPC when it reaches a specified location.

Server log:
```
[15:25:36] [Server thread/ERROR]: Could not pass event NavigationCompleteEvent to [...] v1.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:178) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:332) ~[?:?]
	at net.citizensnpcs.nms.v1_15_R1.entity.BatController$EntityBatNPC.mobTick(BatController.java:169) ~[?:?]
	at net.minecraft.server.v1_15_R1.EntityInsentient.doTick(EntityInsentient.java:661) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2521) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:504) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2353) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.EntityBat.tick(EntityBat.java:86) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:626) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.World.a(World.java:718) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-800b93f-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-800b93f-8160e29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1169) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.removeFromWorld(NMSImpl.java:943) ~[?:?]
	at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:334) ~[?:?]
	at net.citizensnpcs.nms.v1_15_R1.entity.HumanController.remove(HumanController.java:116) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:101) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC.despawn(AbstractNPC.java:148) ~[?:?]
	at [...].listeners.NPCListener.onNavigatorFinished(NPCListener.java:35) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-800b93f-8160e29]
	... 20 more
```

Citiziens config:
https://pastebin.com/i27Znsks

The output of command `/version` and `/version Citiziens`on my server is: 
![image](https://user-images.githubusercontent.com/42046014/79464330-3a9ada80-7ffa-11ea-8732-2ed6f2603370.png)

Code in plugin:
`NPC present = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, " ");
                            present.data().setPersistent(NPC.PLAYER_SKIN_UUID_METADATA, "KaNickkel");
                            present.data().setPersistent(NPC.PLAYER_SKIN_USE_LATEST, false);
                            present.spawn(loc);
                            getNpcManager().present.put(npc, present);
[...].getInstance().getNpcManager().present.get(event.getNPC()).despawn();`

**Comment by fullwall** [comment]
You need to remove the entity in a Bukkit scheduled task not instantly.
