### ISSUE TITLE
Could not pass event ChunkUnloadEvent to Citizens

### ISSUE THREAD

**Issue by mibby** [CitizensDev/Citizens2#2116]
Paper dev 201 (Spigot 1.15.2)
Citizens2 dev 1883

```
[10:07:32] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Citizens v2.0.26-SNAPSHOT (build 1883)
java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1517) ~[patched_1.15.2.jar:git-Paper-201]
	at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.removeFromWorld(NMSImpl.java:943) ~[?:?]
	at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:334) ~[?:?]
	at net.citizensnpcs.nms.v1_15_R1.entity.HumanController.remove(HumanController.java:116) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:101) ~[?:?]
	at net.citizensnpcs.EventListen.onChunkUnload(EventListen.java:168) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor360.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-201]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.Chunk.unloadCallback(Chunk.java:843) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:497) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:106) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:507) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:100) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:603) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1040) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:484) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.getType(World.java:649) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:84) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.EntityPlayer.tick(EntityPlayer.java:377) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:794) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.a(World.java:863) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:516) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1152) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-201]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[10:07:32] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Citizens v2.0.26-SNAPSHOT (build 1883)
java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1517) ~[patched_1.15.2.jar:git-Paper-201]
	at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.removeFromWorld(NMSImpl.java:943) ~[?:?]
	at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:334) ~[?:?]
	at net.citizensnpcs.nms.v1_15_R1.entity.HumanController.remove(HumanController.java:116) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:101) ~[?:?]
	at net.citizensnpcs.EventListen.onChunkUnload(EventListen.java:168) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor360.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-201]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-201]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.Chunk.unloadCallback(Chunk.java:843) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:497) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:106) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:507) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:100) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:603) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1040) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:484) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:325) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.IWorldReader.getChunkAt(IWorldReader.java:87) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.getChunkAt(World.java:270) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.getType(World.java:649) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:84) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.EntityPlayer.tick(EntityPlayer.java:377) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:794) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.World.a(World.java:863) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:516) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1152) ~[patched_1.15.2.jar:git-Paper-201]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-201]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by fullwall** [comment]
Should be fixed in latest build.
