### ISSUE TITLE
NPCDeathEvent null entity

### ISSUE THREAD

**Issue by SkytAsul** [CitizensDev/Citizens2#2124]
The output of command `/version` on my server is: **Latest Paper 1.14 build**
The output of command `/version citizens` on my server is: **Citizens-2.0.26-b1895**

In a plugin of mine I'm listening to NPCDeathEvent. However, when trying to retrieve NPC's entity, I only get a null object (with `event.getNPC().getEntity()`.
My code is the following:
```java
@EventHandler
public void onNPCKilled(NPCDeathEvent e) {
	LivingEntity en = (LivingEntity) e.getNPC().getEntity();
	if (en.getKiller() == null) return; // <-- I get a NullPointerException here
	callEvent(e.getNPC(), en, en.getKiller());
}
```
How should I retrieve the NPC's entity here?

EDIT: here is the error, if it can help:
```
Could not pass event NPCDeathEvent to BeautyQuests v0.17_BUILD79
java.lang.NullPointerException: null
at fr.skytasul.quests.utils.compatibility.mobs.CitizensFactory.onNPCKilled(CitizensFactory.java:60) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1274.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:289) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor492.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:775) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.EntityPlayer.die(EntityPlayer.java:586) ~[patched_1.14.4.jar:git-Paper-243]
at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.die(EntityHumanNPC.java:168) ~[?:?]
at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:786) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:757) ~[patched_1.14.4.jar:git-Paper-243]
at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:142) ~[?:?]
at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1047) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1691) ~[patched_1.14.4.jar:git-Paper-243] at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by mcmonkey4eva** [comment]
Most likely something is removing the entity (aka despawning the npc) during the death event. You'd have to figure what's doing that and correct it.

If that's not the case, and you can replicate this on a server running only Spigot 1.15.2, Citizens latest dev, and a test plugin comprising only an NPCDeathEvent -> check for null, please reply below with details regarding that confirmation.
