### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Doublejin1201** [CitizensDev/Citizens2#2130]
[10:00:20] [Server thread/INFO]: Double_jin issued server command: /NPC CREATE ARX
[10:00:20] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_14_R1/PathDestination
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.util.PlayerNavigation.<init>(PlayerNavigation.java:68)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:292)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:91)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.HumanController.createEntity(HumanController.java:54)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:238)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:477)
[10:00:20] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:00:20] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:00:20] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:00:20] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[10:00:20] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[10:00:20] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:00:20] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[10:00:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:892)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:885)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:869)
[10:00:20] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:802)
[10:00:20] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:00:20] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_14_R1.PathDestination
[10:00:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[10:00:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81)
[10:00:20] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:00:20] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:00:20] [Server thread/WARN]: 	... 33 more

Spigot version : 1.14

Mod version : from offical site,latest modification

Tried to install another versions, but did not help anyway (

[latest.log](https://github.com/CitizensDev/Citizens2/files/4563614/latest.log)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
