### ISSUE TITLE
Error: Removing entity while ticking

### ISSUE THREAD

**Issue by Pugabyte** [CitizensDev/Citizens2#2136]
Citizens build 1926
Spigot: `CraftBukkit version git-Spigot-2040c4c-1872231 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

Trying to update a NPC via API ([Code](https://github.com/Pugabyte/BNCore/blob/master/src/main/java/me/pugabyte/bncore/utils/CitizensUtils.java))
Error: https://paste.bnn.gg/azefe.css

**Comment by mcmonkey4eva** [comment]
Exception copy/pasted to not a temporary link:
```
[Citizens] Exception while updating 2,707: Removing entity while ticking!.
java.lang.IllegalStateException: Removing entity while ticking!
       at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1169)
       at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.removeFromWorld(NMSImpl.java:954)
       at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:342)
       at net.citizensnpcs.nms.v1_15_R1.entity.HumanController.remove(HumanController.java:122)
       at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:105)
       at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:140)
       at net.citizensnpcs.npc.skin.SkinPacketTracker.notifySkinChange(SkinPacketTracker.java:99)
       at net.citizensnpcs.trait.SkinTrait.onSkinChange(SkinTrait.java:96)
       at net.citizensnpcs.trait.SkinTrait.migrate(SkinTrait.java:90)
       at net.citizensnpcs.trait.SkinTrait.run(SkinTrait.java:102)
       at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:435)
       at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:330)
       at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:426)
       at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:626)
       at net.minecraft.server.v1_15_R1.World.a(World.java:694)
       at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395)
       at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082)
       at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
       at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
       at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
       at java.lang.Thread.run(Thread.java:748)
```
