### ISSUE TITLE
cannot remove an sit npc the first time

### ISSUE THREAD

**Issue by Noiknez** [CitizensDev/Citizens2#2157]
The output of command `/version` on my server is: **( Paper version git-Paper-301 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.26-SNAPSHOT (build 1967)**

When we try to remove a sit npc, we need to run the command two times. The first time the npc goes into the side of the chair and standup and give an error, and we need to do the command a second time to really remove the npc
```
[23:58:41 INFO]: Naeliks issued server command: /npc select
[23:58:44 INFO]: Naeliks issued server command: /npc remove
[00:07:12 WARN]: [Citizens] Task #2168 for Citizens v2.0.26-SNAPSHOT (build 1967) generated an exception
java.lang.NullPointerException: null
        at net.citizensnpcs.nms.v1_15_R1.util.NMSImpl.getPassengers(NMSImpl.java:458) ~[?:?]
        at net.citizensnpcs.util.NMS.getPassengers(NMS.java:221) ~[?:?]
        at net.citizensnpcs.nms.v1_15_R1.util.PlayerAnimationImpl$1.run(PlayerAnimationImpl.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-301]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-301]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-301]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[23:58:49 INFO]: Naeliks issued server command: /npc select
[23:59:33 INFO]: Naeliks issued server command: /npc remove

```

**Comment by fullwall** [comment]
I added an extra null check for you.

**Comment by Noiknez** [comment]
I confirm that this is fixed now
