### ISSUE TITLE
Server Crash Spigot 1.15.2 Plugin attempted to register

### ISSUE THREAD

**Issue by JamesVengeance** [CitizensDev/Citizens2#2160]
This problem occurs since we enter the plugin to our server, the server stops loading and then closes and sends the following message in console:

**org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register net.citizensnpcs.trait.Gravity@5e6f7583 while not enabled
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:552)
	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:109)
	at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:234)
	at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:406)
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:626)
	at net.minecraft.server.v1_15_R1.World.a(World.java:718)
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:395)
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1082)
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
	at java.lang.Thread.run(Thread.java:748)**

https://tawk.link/5a69160e4b401e45400c5ef7/a/5cccd77f433ba42754b7d085/d06f54d215cae21e515869587f6879e16c69c6f8/crash-2020-05-20_17.42.59-server.txt

The output of command `/version` on my server is: git-Spigot-800b93f-8160e29 1.15.2
The output of command `/version citizens` on my server is: 2.0.26-SNAPSHOT build 1951

**Comment by Ph4i1ur3** [comment]
This issue is a by product of another issue, and not caused by Citizens itself.

**Comment by mcmonkey4eva** [comment]
That link goes nowhere btw. In the future use https://pastebin.com/ or https://one.denizenscript.com/haste
