### ISSUE TITLE
Citizens is not running in Spigot 1.16.1

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#2196]
The thread sais it, it gets disabled on launch of server

Infos from console:
```
[13:34:04] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.27-SNAPSHOT (build 2002)
[13:34:04] [Server thread/ERROR]: [Citizens] v2.0.27-SNAPSHOT (build 2002) ist nicht kompatibel mit Minecraft v1_16_R1. Deaktivere Citizens.
[13:34:04] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.27-SNAPSHOT (build 2002)
```

![image](https://user-images.githubusercontent.com/12080017/85712478-a7aca980-b6e8-11ea-8d3c-fa99e6c80772.png)

**Comment by fullwall** [comment]
Download build 2003

**Comment by Blueeyestar** [comment]
I also reported the same thing. But was blocked for no apparent reason !!

https://github.com/CitizensDev/Citizens2/issues/2193

**Comment by fullwall** [comment]
@Blueeyestar you made an issue a few hours after Spigot released 1.16 and before Citizens had even started to update. Please read Spigot's post on 1.16 entitlement. Of course, you are welcome to download build 2003 as well.

**Comment by YaRkOsHaRkO** [comment]
I have the same problem, I tried using 2003 But I got this (looks like there is no plugin.yml):
`[10:00:59] [Server thread/ERROR]: Could not load 'plugins/Citizens-2.0.27-b2190.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:380) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:871) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.Bukkit.reload(Bukkit.java:642) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:755) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:740) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:386) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
`

**Comment by SXRWahrheit** [comment]
Citizens only supports the latest minor revisions. Update your server to 1.16.4.

**Comment by CloudeLecaw** [comment]
We run latest citisenz n our spigot 1.16.4. works fine.
