### ISSUE TITLE
Exception for saves in Paper 1.16.1 running worlds from 1.15.2

### ISSUE THREAD

**Issue by themonomers** [CitizensDev/Citizens2#2211]
### The server throws an exception when Citizens is:
1.  Auto-saving or when a
2.  'citizens save' command is manually executed:

**1. server log** 
[20:04:04] [Server thread/WARN]: [Citizens] Task #110 for Citizens v2.0.27-SNAPSHOT (build 2016) generated an exception
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:301) ~[patched_1.16.1.jar:git-Paper-19]
        at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:547) ~[?:?]
        at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:342) ~[?:?]
        at net.citizensnpcs.api.trait.trait.Inventory.save(Inventory.java:154) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:351) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:183) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91) ~[?:?]
        at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:484) ~[?:?]
        at net.citizensnpcs.Citizens$4.run(Citizens.java:401) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-19]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-19]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-19]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**2. server log**
[20:11:10] [Server thread/INFO]: Saving Citizens...
[20:11:10] [Server thread/WARN]: java.lang.NullPointerException
[20:11:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:301)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:547)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:342)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.trait.trait.Inventory.save(Inventory.java:154)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:351)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:183)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:484)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:488)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.commands.AdminCommands.save(AdminCommands.java:64)
[20:11:10] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:11:10] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:11:10] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:11:10] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[20:11:10] [Server thread/WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[20:11:10] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:11:10] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:11:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[20:11:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:754)
[20:11:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[20:11:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[20:11:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[20:11:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[20:11:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[20:11:10] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

### Citizens config:
# Citizens Configuration
npc:
  pathfinding:
    new-finder:
      iterations-per-tick: 25000
    default-distance-margin: 2
    default-path-distance-margin: 1
    update-path-rate: 20
    disable-mc-fallback-navigation: true
    maximum-new-pathfinder-iterations: 50000
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  controllable:
    ground-direction-modifier: 1.0
    max-ground-speed: 0.5
    use-boat-controls: true
  default:
    waypoints:
      cache-paths: false
    look-close:
      enabled: false
      range: 5
      random-look-enabled: false
      random-look-delay: 60
      disable-while-navigating: true
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: stick
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '*'
  teleport-delay: -1
  player-scoreboard-teams:
    enable: true
general:
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-error: <c>
    message-highlight: <e>
    message: <a>
  translation:
    locale: ''
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins

### The output of command `/version` on my server is: 
> version
[20:44:19 INFO]: This server is running Paper version git-Paper-19 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[20:44:19 INFO]: Checking version, please wait...
[20:44:21 INFO]: Previous version: git-Paper-372 (MC: 1.15.2)
[20:44:21 INFO]: You are running the latest version

### The output of command `/version citizens` on my server is: 
> version citizens
[20:45:01 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2016)
[20:45:01 INFO]: Website: http://www.citizensnpcs.co
[20:45:01 INFO]: Author: fullwall

**Comment by fullwall** [comment]
Seems like a Paper or Spigot issue. Finding it a bit hard to look at the relevant code so I'll leave it to those teams to figure out.

**Comment by fullwall** [comment]
To give you more context: there's an item in one of the inventories (maybe a sign or something?) that is not being serialised properly.

**Comment by themonomers** [comment]
Ok thanks, I'll check out the NPC equipment or inventory.
