### ISSUE TITLE
ERROR WHEN RIGHT CLICKING CITIZENS THAT HAVE COMMANDS 

### ISSUE THREAD

**Issue by slvlr** [CitizensDev/Citizens2#2237]
>.... [13:37:03 ERROR]: Could not pass event EntityDamageByEntityEvent to Citizens v2.0.27-SNAPSHOT (build 2019)
java.lang.NoClassDefFoundError: net/citizensnpcs/trait/CommandTrait$1
at net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:105) ~[?:?]
at net.citizensnpcs.EventListen.onEntityDamage(EventListen.java:269) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor708.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-86]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:246) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1034) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:921) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:877) ~[patched_1.16.1.jar:git-Paper-86]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1066) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1826) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1159) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:833) ~[patched_1.16.1.jar:git-Paper-86]
at net.citizensnpcs.nms.v1_16_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:155) ~[?:?]
at net.minecraft.server.v1_16_R1.EntityHuman.attack(EntityHuman.java:1092) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.EntityPlayer.attack(EntityPlayer.java:1861) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2135) ~[?:git-Paper-86]
at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-86]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by mcmonkey4eva** [comment]
NEVER use `/reload`. It breaks stuff like that.
