### ISSUE TITLE
Server crashes when Citizens saves

### ISSUE THREAD

**Issue by Ferocimo** [CitizensDev/Citizens2#2239]
The output of command `/version` on my server is: **(git-Paper-378 (MC:1.15.2)**
The output of command `/version citizens` on my server is: **Citizens 2.0.27 build 2058**

Hello,

When performing a /citizens save (which also sometimes occur automatically), the server crashes and the following error is spammed (and by spammed I mean "thousands of pages of the same repeated error"-kind of spamming) : 

```
[17:10:39 ERROR]: [Citizens] Spigot error when saving item meta
[17:10:39 WARN]: java.lang.NullPointerException
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.NBTTagCompound.a(NBTTagCompound.java:427)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.NBTTagCompound.write(NBTTagCompound.java:81)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:104)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:97)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
[17:10:39 WARN]: at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1426)
[17:10:39 WARN]: at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:239)
[17:10:39 WARN]: at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1352)
[17:10:39 WARN]: at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16)
[17:10:39 WARN]: at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48)
[17:10:39 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144)
[17:10:39 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[17:10:39 WARN]: at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:381)
[17:10:39 WARN]: at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:361)
[17:10:39 WARN]: at net.citizensnpcs.api.trait.trait.Equipment.saveOrRemove(Equipment.java:150)
[17:10:39 WARN]: at net.citizensnpcs.api.trait.trait.Equipment.save(Equipment.java:141)
[17:10:39 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:363)
[17:10:39 WARN]: at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:184)
[17:10:39 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[17:10:39 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[17:10:39 WARN]: at net.citizensnpcs.Citizens.onDisable(Citizens.java:271)
[17:10:39 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[17:10:39 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[17:10:39 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[17:10:39 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[17:10:39 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[17:10:39 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:749)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:753)
[17:10:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1016)
[17:10:39 WARN]: at java.lang.Thread.run(Thread.java:748)
```

Config seems to be irrelevant. I suspect it to be a Citizen that has an item with NBT equipped, but I can't know which one or how to fix it.

Thank you for looking into this.

**Comment by mcmonkey4eva** [comment]
That's a Spigot bug, not a Citizens one. Spigot serializes **skull items (player heads)** incorrectly, and modern Citizens builds rely on Spigot to serialize items.
That error message in and of itself doesn't cause a crash, though if you get thousands it might just be slowing the server til it timeout's.
The ideal fix is for Spigot to fix the bug, but the workaround available is to get rid of player heads. You can also download an older build of Citizens from back when Citizens tried to handle item serialization itself rather than letting Spigot do it (has its own problems, but doesn't have this particular problem).

**Comment by Ferocimo** [comment]
Okay, we'll try on Spigot side, but just so you know this means that Citizens/Spigot will necessarly cause a server crash in 1.16 servers since they won't be able to downgrade.

Unfortunately NPCs with heads can't be replaced, it's very important in a number of instances.
