### ISSUE TITLE
save error

### ISSUE THREAD

**Issue by arts7493** [CitizensDev/Citizens2#2246]
[08:29:10] [Server thread/ERROR]: [Citizens] Spigot error when saving item meta
[08:29:10] [Server thread/WARN]: java.lang.NullPointerException
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NBTTagCompound.a(NBTTagCompound.java:427)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NBTTagCompound.write(NBTTagCompound.java:81)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:104)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:97)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1426)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:239)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1352)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48)
[08:29:10] [Server thread/WARN]: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144)
[08:29:10] [Server thread/WARN]: 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:381)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:361)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Equipment.saveOrRemove(Equipment.java:150)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Equipment.save(Equipment.java:141)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:363)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:184)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:485)
[08:29:10] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$4.run(Citizens.java:402)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[08:29:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[08:29:10] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[08:29:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

The output of command `/version` on my server is: **(PLEASE FILL IN)**
[21:29:52] [Server thread/INFO]: This server is running Paper version git-Paper-379 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:29:52] [Server thread/INFO]: Checking version, please wait...
[21:29:53] [Thread-1343/INFO]: Previous version: git-Paper-378 (MC: 1.15.2)
[21:29:53] [Thread-1343/INFO]: You are running the latest version
The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
[21:29:32] [Server thread/INFO]: Citizens version 2.0.27-SNAPSHOT (build 2064)
[21:29:32] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[21:29:32] [Server thread/INFO]: Author: fullwall

**Comment by mcmonkey4eva** [comment]
Refer to https://github.com/CitizensDev/Citizens2/issues/2239#issuecomment-657332830
