### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [CitizensDev/Citizens2#2271]
Error (im not sure the case as it happened after an admin typed /npc type player but also happened without any command usage):
1) the error that happened after `/npc type player`
```
{player} issued server command: /npc type player
ERROR 22:19:08
Could not pass event NPCDespawnEvent to Citizens v2.0.27-SNAPSHOT (build 2083)
Console 22:19:08
java.lang.ClassCastException: class net.citizensnpcs.nms.v1_15_R1.entity.FoxController$FoxNPC cannot be cast to class org.bukkit.entity.Player (net.citizensnpcs.nms.v1_15_R1.entity.FoxController$FoxNPC is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @25f3c03e; org.bukkit.entity.Player is in unnamed module of loader 'app')
at net.citizensnpcs.EventListen.onNPCDespawn(EventListen.java:432) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor234.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-385]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:82) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.setEntityController(CitizensNPC.java:210) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:201) ~[?:?]
at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:2239) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187) ~[?:?]
at net.citizensnpcs.Citizens.onCommand(Citizens.java:269) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[?:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[?:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1233) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-385]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
2) the error that was caused by `/npc type zombie`: 
```
{player} issued server command: /npc type zombie
ERROR 22:13:44
Could not pass event NPCDespawnEvent to Citizens v2.0.27-SNAPSHOT (build 2083)
Console 22:13:44
java.lang.ClassCastException: class net.citizensnpcs.nms.v1_15_R1.entity.EndermanController$EndermanNPC cannot be cast to class org.bukkit.entity.Player (net.citizensnpcs.nms.v1_15_R1.entity.EndermanController$EndermanNPC is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @25f3c03e; org.bukkit.entity.Player is in unnamed module of loader 'app')
at net.citizensnpcs.EventListen.onNPCDespawn(EventListen.java:432) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor234.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-385]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:82) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.setEntityController(CitizensNPC.java:210) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:201) ~[?:?]
at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:2239) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187) ~[?:?]
at net.citizensnpcs.Citizens.onCommand(Citizens.java:269) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[?:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[?:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-385]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
3) the errors that randomly showed up in chat:
```
ERROR 22:18:35
Could not pass event NPCDespawnEvent to Citizens v2.0.27-SNAPSHOT (build 2083)
Console 22:18:35
java.lang.ClassCastException: class net.citizensnpcs.nms.v1_15_R1.entity.ZombieController$ZombieNPC cannot be cast to class org.bukkit.entity.Player (net.citizensnpcs.nms.v1_15_R1.entity.ZombieController$ZombieNPC is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @25f3c03e; org.bukkit.entity.Player is in unnamed module of loader 'app')
at net.citizensnpcs.EventListen.onNPCDespawn(EventListen.java:432) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor234.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-385]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:82) ~[?:?]
at net.citizensnpcs.npc.CitizensNPCRegistry.deregister(CitizensNPCRegistry.java:78) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.destroy(AbstractNPC.java:165) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.destroy(CitizensNPC.java:113) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.destroy(AbstractNPC.java:172) ~[?:?]
at net.citizensnpcs.commands.NPCCommands.remove(NPCCommands.java:1594) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91) ~[?:?]
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187) ~[?:?]
at net.citizensnpcs.Citizens.onCommand(Citizens.java:269) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[?:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[?:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-385]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

The output of command `/version` on my server is: **Paper 1.15.2 build 385**
The output of command `/version citizens` on my server is: **Citizens v2.0.27-SNAPSHOT (build 2083)**

**Comment by fullwall** [comment]
Fixed
