### ISSUE TITLE
"Could not pass event EntityPortalEvent to Citizens" cause server crash when enter the end portal

### ISSUE THREAD

**Issue by mechcalvin** [CitizensDev/Citizens2#2295]
When I use the latest Citizen snapshot, the server will crash whenever a player enter the end port with the errors below, disable Citizen works fine.

`[Server thread/ERROR]: Could not pass event EntityPortalEvent to Citizens v2.0.27-SNAPSHOT (build 2100)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityPortalEvent(CraftEventFactory.java:1618) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.Entity.a(Entity.java:2483) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityPlayer.a(EntityPlayer.java:734) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityPlayer.b(EntityPlayer.java:785) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.BlockEnderPortal.a(BlockEnderPortal.java:41) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:547) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.Entity.checkBlockCollisions(Entity.java:909) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.Entity.move(Entity.java:643) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.a(EntityLiving.java:2273) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.g(EntityLiving.java:2232) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityHuman.g(EntityHuman.java:1405) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.movementTick(EntityLiving.java:2696) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityHuman.movementTick(EntityHuman.java:397) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2386) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityHuman.tick(EntityHuman.java:153) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:443) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:143) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:223) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at net.citizensnpcs.EventListen.onEntityPortal(EventListen.java:317) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	... 28 more
[19:45:17] [Server thread/WARN]: Failed to handle packet for /192.168.2.53:32955
net.minecraft.server.v1_16_R2.ReportedException: Colliding entity with block
	at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:525) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:143) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:223) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_16_R2.EntityPlayer.b(EntityPlayer.java:799) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.BlockEnderPortal.a(BlockEnderPortal.java:41) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.a(BlockBase.java:547) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.Entity.checkBlockCollisions(Entity.java:909) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.Entity.move(Entity.java:643) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.a(EntityLiving.java:2273) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.g(EntityLiving.java:2232) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityHuman.g(EntityHuman.java:1405) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.movementTick(EntityLiving.java:2696) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityHuman.movementTick(EntityHuman.java:397) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2386) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityHuman.tick(EntityHuman.java:153) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:443) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	... 9 more
[19:45:17] [Server thread/INFO]: MECHCalvin lost connection: Internal server error`

**Comment by veltrium** [comment]
@mechcalvin can you help me with this please?

**Comment by mechcalvin** [comment]
> @mechcalvin can you help me with this please?

are you running on linux or ubuntu? follow the wiki link to use buildtools through terminal or download papermc directly.
