### ISSUE TITLE
Works on Spigot 1.16.2, fails on Spigot 1.16.3

### ISSUE THREAD

**Issue by Mintaka3a** [CitizensDev/Citizens2#2320]
The output of command `/version` on my server is: Spigot 1.16.3
The output of command `/version citizens` on my server is: Citizens version 2.0.27-SNAPSHOT (build 2110)

Citizens working great on 1.16.2, but generates the following error on startup in 1.16.3:

[Server thread/WARN]: [Citizens] Task #41 for Citizens v2.0.27-SNAPSHOT (build 2110) generated an exception
java.lang.NoSuchFieldError: a
        at net.citizensnpcs.nms.v1_16_R2.util.PlayerNavigation.<init>(PlayerNavigation.java:43) ~[?:?]
        at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:318) ~[?:?]
        at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:97) ~[?:?]
        at net.citizensnpcs.nms.v1_16_R2.entity.HumanController.createEntity(HumanController.java:52) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:249) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:162) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
[snip]

**Comment by mcmonkey4eva** [comment]
You need the latest dev build from https://ci.citizensnpcs.co/job/Citizens2/ for 1.16.3.
