### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gary81013** [CitizensDev/Citizens2#2323]
[14:46:35] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.27-SNAPSHOT (build 2113)
[14:46:35] [Server thread/ERROR]: [Citizens] Spigot error when saving item meta
[14:46:35] [Server thread/WARN]: java.lang.NullPointerException
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.a(NBTTagCompound.java:451)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.write(NBTTagCompound.java:92)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:163)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:156)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:112)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1462)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:239)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1388)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48)
[14:46:35] [Server thread/WARN]: 	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
[14:46:35] [Server thread/WARN]: 	at java.io.ObjectOutputStream.writeObject(Unknown Source)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:381)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:361)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Equipment.saveOrRemove(Equipment.java:150)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Equipment.save(Equipment.java:141)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:363)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:190)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[14:46:35] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onDisable(Citizens.java:278)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[14:46:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.disablePlugins(CraftServer.java:433)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.stop(MinecraftServer.java:773)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.stop(DedicatedServer.java:702)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1046)
[14:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[14:46:35] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
That is a Spigot error. Report it to Spigot.
Longer description here: https://github.com/CitizensDev/Citizens2/issues/2239#issuecomment-657332830

See also https://github.com/CitizensDev/Citizens2/issues/2310 or https://github.com/CitizensDev/Citizens2/issues/2300 or https://github.com/CitizensDev/Citizens2/issues/2246
