### ISSUE TITLE
ERROR IN THE CONSOLE

### ISSUE THREAD

**Issue by LokiTheGod123** [CitizensDev/Citizens2#2337]
1.16.2
latest version of citizens
I can't see my citizens:

[10:36:13] [Server thread/INFO]: Norbik1004 issued server command: /citizens reload
[10:36:13] [Server thread/WARN]: java.lang.NoSuchFieldError: ORIGIN
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.util.PlayerNavigation.<init>(PlayerNavigation.java:43)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:318)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:97)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.entity.HumanController.createEntity(HumanController.java:52)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:249)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:162)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.reload(Citizens.java:393)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:49)
[10:36:13] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:36:13] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:36:13] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:36:13] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[10:36:13] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
[10:36:13] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:36:13] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[10:36:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
[10:36:13] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:36:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by mcmonkey4eva** [comment]
Update to 1.16.3

if you need the old 1.16.2 build, it's here https://ci.citizensnpcs.co/job/Citizens2/2094/
But... update, asap!
