### ISSUE TITLE
npc create exception

### ISSUE THREAD

**Issue by OOTW-CLYHE** [CitizensDev/Citizens2#2348]
/version 
This server is running Akarin version git-Akarin-"70f0094" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
Previous version: git-Akarin-"df7efd2" (MC: 1.16.1)
 Error obtaining version information
/version Citizens
Citizens version 2.0.27-SNAPSHOT (build 2125)
[17:35:52 INFO]: Website: http://www.citizensnpcs.co
[17:35:52 INFO]: Author: fullwall
/npc create [name]
 java.lang.NoSuchFieldError: ORIGIN
[17:29:10 WARN]:        at net.citizensnpcs.nms.v1_16_R2.util.PlayerNavigation.<init>(PlayerNavigation.java:43)
[17:29:10 WARN]:        at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:318)
[17:29:10 WARN]:        at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:97)
[17:29:10 WARN]:        at net.citizensnpcs.nms.v1_16_R2.entity.HumanController.createEntity(HumanController.java:52)
[17:29:10 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[17:29:10 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:249)
[17:29:10 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:508)
[17:29:10 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:29:10 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:29:10 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:29:10 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:29:10 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[17:29:10 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[17:29:10 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[17:29:10 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
[17:29:10 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:29:10 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:29:10 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:793)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1917)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1728)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1190)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1183)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1159)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[17:29:10 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[17:29:10 WARN]:        at java.lang.Thread.run(Thread.java:748)

also,the npc didn't show up.

**Comment by mcmonkey4eva** [comment]
- Run Spigot or Paper, not whatever that is
- Use 1.16.3, not .2

**Comment by OOTW-CLYHE** [comment]
> * Run Spigot or Paper, not whatever that is
> * Use 1.16.3, not .2

would you please tell me which version runs on 1.16.2
