### ISSUE TITLE
Can't save item with NBT

### ISSUE THREAD

**Issue by HexedHero** [CitizensDev/Citizens2#2349]
I gave an NPC a few items like a player head colored armor and axe and after I added that only NPC it now cant "save" the items when given to the NPC, it does persist and work as normal but throws the error below.

> [11:33:39 ERROR]: [Citizens] Spigot error when saving item meta
[11:33:39 WARN]: java.lang.NullPointerException
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.a(NBTTagCompound.java:451)
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.write(NBTTagCompound.java:92)
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:163)
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:156)
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:112)
[11:33:39 WARN]: at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1462)
[11:33:39 WARN]: at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:247)
[11:33:39 WARN]: at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1388)
[11:33:39 WARN]: at org.bukkit.util.io.Wrapper.newWrapper(Wrapper.java:16)
[11:33:39 WARN]: at org.bukkit.util.io.BukkitObjectOutputStream.replaceObject(BukkitObjectOutputStream.java:48)
[11:33:39 WARN]: at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144)
[11:33:39 WARN]: at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[11:33:39 WARN]: at net.citizensnpcs.api.util.ItemStorage.serialiseMeta(ItemStorage.java:381)
[11:33:39 WARN]: at net.citizensnpcs.api.util.ItemStorage.saveItem(ItemStorage.java:361)
[11:33:39 WARN]: at net.citizensnpcs.api.trait.trait.Equipment.saveOrRemove(Equipment.java:150)
[11:33:39 WARN]: at net.citizensnpcs.api.trait.trait.Equipment.save(Equipment.java:141)
[11:33:39 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:363)
[11:33:39 WARN]: at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:190)
[11:33:39 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:85)
[11:33:39 WARN]: at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:91)
[11:33:39 WARN]: at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:490)
[11:33:39 WARN]: at net.citizensnpcs.Citizens$4.run(Citizens.java:407)
[11:33:39 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[11:33:39 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[11:33:39 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)

The output of command `/version` on my server is: **(PLEASE FILL IN)**
[11:36:26 INFO]: This server is running Paper version git-Paper-214 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
[11:36:37 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2113)

**Comment by mcmonkey4eva** [comment]
That is a spigot error from the player head item. Report it to the spigot bug tracker.

Longer description here: https://github.com/CitizensDev/Citizens2/issues/2239#issuecomment-657332830

See also https://github.com/CitizensDev/Citizens2/issues/2310 or https://github.com/CitizensDev/Citizens2/issues/2300 or https://github.com/CitizensDev/Citizens2/issues/2246 or https://github.com/CitizensDev/Citizens2/issues/2323 or https://github.com/CitizensDev/Citizens2/issues/2340
