### ISSUE TITLE
Error Pls Help

### ISSUE THREAD

**Issue by Rytexs** [CitizensDev/Citizens2#2363]
Here is the error...

[17:43:23] [Server thread/WARN]: java.lang.NoSuchFieldError: a
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.util.PlayerNavigation.<init>(PlayerNavigation.java:43)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:318)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:97)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R2.entity.HumanController.createEntity(HumanController.java:50)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:249)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:509)
[17:43:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:43:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:43:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:43:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[17:43:23] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
[17:43:23] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:43:23] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:43:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[17:43:23] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[17:43:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by fullwall** [comment]
Use Minecraft 1.16.3 with the latest build please.

**Comment by Rytexs** [comment]
I have
