### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dinobossytnew** [CitizensDev/Citizens2#2386]
[18:43:31] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CTF vR-0.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:251) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:966) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:853) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:809) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:998) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1755) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:828) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1139) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:745) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:719) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:154) ~[?:?]
at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1068) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1632) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2001) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at com.jakubson.ctf.listeners.EntityDamage.onEntityDamage(EntityDamage.java:22) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
... 31 more
[18:43:31] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CTF vR-0.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:251) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:966) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:853) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:809) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:998) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1755) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:828) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1139) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:745) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:719) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:154) ~[?:?]
at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1068) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1632) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2001) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at com.jakubson.ctf.listeners.EntityDamageByEntity.check(EntityDamageByEntity.java:52) ~[?:?]
at com.jakubson.ctf.listeners.EntityDamageByEntity.onEntityDamageByEntity(EntityDamageByEntity.java:26) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-a19903d-23618b2]
... 31 more

1.16.3

Spigot 

Premium

**Comment by mcmonkey4eva** [comment]
This is an error in the plugin `CTF vR-0.10`, not Citizens.
