### ISSUE TITLE
Conflicts with @e in commands

### ISSUE THREAD

**Issue by Kloudy** [CitizensDev/Citizens2#239]
Any command that uses the @e selector causes this exception if Citizens is loaded on the server:

[06:09:24 WARN]: CommandBlock at (-421,14,367) failed to handle command
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String
        at net.minecraft.server.v1_8_R1.EntityTypes.b(SourceFile:240) ~[spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.EntityTypes.b(SourceFile:262) ~[spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.PlayerSelector.b(PlayerSelector.java:110) ~[spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.PlayerSelector.getPlayers(PlayerSelector.java:60) ~[spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at org.bukkit.craftbukkit.v1_8_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:65) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.CommandBlockListenerAbstract.executeCommand(CommandBlockListenerAbstract.java:149) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:92) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.BlockCommand.b(BlockCommand.java:48) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:632) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:236) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:741) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-b1e6da1-1092acb]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by mcmonkey4eva** [comment]
That looks to me more like a Spigot code error that Citizens just happens to trigger.

**Comment by Bastikeks** [comment]
it seems that citizens is the cause. Have the same issue and a developers of spigot says that either an npc or pet plugin (which modifies entities) causes the error (https://hub.spigotmc.org/jira/browse/SPIGOT-437)

**Comment by mcmonkey4eva** [comment]
Does this fix the issue -> https://dl.dropboxusercontent.com/u/54130586/citizens-2.0.14-SNAPSHOT.jar ?

**Comment by Bastikeks** [comment]
i'll try and give report later (today)

**Comment by Bastikeks** [comment]
doesnt work:
```
[21:25:10 WARN]: Unknown CommandBlock failed to handle command
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String
        at net.minecraft.server.v1_8_R1.EntityTypes.b(SourceFile:240) ~[spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.EntityTypes.b(SourceFile:262) ~[spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerSelector.b(PlayerSelector.java:110) ~[spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerSelector.getPlayers(PlayerSelector.java:60) ~[spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:68) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_65]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_65]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot18.jar:git-Spigot-ed3e3af-ee6d0fa]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
>

```
used command: /minecraft:kill @e[r=3,type=Item]

**Comment by Bastikeks** [comment]
is it possible to fix this asap? this bug destroys a big part of vanilla functionality

**Comment by Bastikeks** [comment]
any progress here?

**Comment by Bastikeks** [comment]
still an issue in versions for spigot 1.8.3

**Comment by sawine** [comment]
Bumping this, I have the same issue on 1.8.3 as well.

**Comment by sawine** [comment]
Bumping this, I have the same issue on 1.8.3 as well.

**Comment by fullwall** [comment]
Closing this, it doesn't seem like a Citizens issue. I checked the method causing the error, which is casting the result from the d Map in EntityTypes. Citizens doesn't touch this Map at all so it must be a pet plugin or something.

**Comment by Bastikeks** [comment]
This IS a Citizens Bug!
I installed it on a spigot-server without anything beside. Just Server + Citizens and it fails. Citizens-versions like 1195 worked well.

**Comment by Bastikeks** [comment]
investigated a bit more: only when the type=xxx parameter inside the @e[] is given it runs into issues.

**Comment by Bastikeks** [comment]
digged deeper: we had one irongolem-npc-type which caused the issue. when removing him everything was good. So to fix this issue i recommend to look into your npc-types classes which seem to conflict with entity - vanilla - commands

**Comment by mcmonkey4eva** [comment]
Does any irongolem cause it, or just that one?

**Comment by Bastikeks** [comment]
i only had one irongolem npc. every other npc was a player-type. but i quess @e will also fail on the other mob-npc-types.

**Comment by fullwall** [comment]
I'm still not seeing how Citizens could cause this issue at all.... @mcmonkey4eva ?

**Comment by mcmonkey4eva** [comment]
Yup, any iron golem. I just tested myself. Definitely Citizens-induced somehow. Not sure ... how exactly...

**Comment by Bastikeks** [comment]
im curious if other mobtype npcs are affected as well?

**Comment by mcmonkey4eva** [comment]
Yup, it appears to be any mob-type npc.

**Comment by mcmonkey4eva** [comment]
@fullwall @Bastikeks Fixed :) https://github.com/CitizensDev/Citizens2/pull/320

Darn NMS reflection, always messing us up!
