### ISSUE TITLE
Citizens says the plugin is disabled

### ISSUE THREAD

**Issue by Endergamer312** [CitizensDev/Citizens2#2401]
org.bukkit.command.CommandException: Cannot execute command 'npc' in plugin Citizens v2.0.24-SNAPSHOT (build 1605) - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:737) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1738) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1595) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1548) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(SourceFile:36) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(SourceFile:9) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:899) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:892) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:876) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:815) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[craftbukkit-1.16.4%20(1).jar:git-Bukkit-3eb7236]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by mcmonkey4eva** [comment]
- You need Spigot or Paper, not craftbukkit
- You need a Citizens build from the current decade, not the previous decade https://ci.citizensnpcs.co/job/Citizens2/
