### ISSUE TITLE
Cannot create NPCs on legacy mc version

### ISSUE THREAD

**Issue by isXander** [CitizensDev/Citizens2#2408]
The output of the command `/version` on my server is: This server is running CraftBukkit version git-PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
The output of the command `/version citizens` on my server is: Citizens version 2.0.13-SNAPSHOT (build 1166)

Hey! Basically, I am having an issue with finding the correct version of Citizens that works with my server version. Before you give me the "uhhh 1.7.10 is so old just use 1.16 or 1.8" then you are really no help at all. My server is 1.7 and will stay 1.7. I have finally got b1166 to even enable after searching through the wiki and jenkins but now, when I try to create an npc, it flashes up in game with a broken skin then disappears with the console message:
[16:31:39 WARN]: Entity threw exception at world:129.90879904086967,133.87901799436185,365.1763479511192
[16:31:39 WARN]: java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
[16:31:39 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277)
[16:31:39 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1676)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1643)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1491)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:511)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:766)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549)
[16:31:39 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by BehrRiley** [comment]
We cannot reasonably support your server version. Additionally, the latest Citizens build is the only supported build.

**Comment by isXander** [comment]
> We cannot reasonably support your server version. Additionally, the latest Citizens build is the only supported build.

I have seen so many spigot threads about v 2.0.13 working fine yet mine doesn't! It just seems a bit weird why mine isn't working
