### ISSUE TITLE
/npc create doesn't work

### ISSUE THREAD

**Issue by mawkingg** [CitizensDev/Citizens2#2425]
I'm using 2.0.24 (MC 1.10-1.13.2) version of citizens downloaded from spigot.mc
running on Magma server 

[05:43:22] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: mawkingg issued server command: /npc create Bob --type PLAYER
[05:43:22] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@3e7fa6f3:
 java.lang.NullPointerException: null
        at journeymap.common.network.impl.MessageProcessor.sendToPlayer(MessageProcessor.java:240) ~[MessageProcessor.class:1.12.2-5.5.6]
        at journeymap.server.events.ForgeEvents.sendConfigsToPlayer(ForgeEvents.java:82) ~[ForgeEvents.class:1.12.2-5.5.6]
        at journeymap.server.events.ForgeEvents.onEntityJoinWorldEvent(ForgeEvents.java:64) ~[ForgeEvents.class:1.12.2-5.5.6]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_354_ForgeEvents_onEntityJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:bb50f45]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:bb50f45]
        at net.minecraft.world.World.spawnEntity(World.java:1491) ~[amu.class:?]
        at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1375) ~[oo.class:?]
        at net.minecraft.world.World.addEntity(World.java:1414) ~[amu.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:240) ~[?:?]
        at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:48) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:261) ~[?:?]
        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:527) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159) ~[?:?]
        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91) ~[?:?]
        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187) ~[?:?]
        at net.citizensnpcs.Citizens.onCommand(Citizens.java:269) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:bb50f45]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) ~[SimpleCommandMap.class:bb50f45]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) ~[CraftServer.class:bb50f45]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1604) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1452) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) ~[la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) ~[la.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[05:43:22] [Server thread/ERROR] [FML]: Index: 11 Listeners:
[05:43:22] [Server thread/ERROR] [FML]: 0: HIGHEST
[05:43:22] [Server thread/ERROR] [FML]: 1: ASM: net.minecraftforge.common.ForgeInternalHandler@355702ba onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 2: HIGH
[05:43:22] [Server thread/ERROR] [FML]: 3: ASM: tschipp.carryon.common.event.ItemEvents@10ca59e9 onItemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 4: ASM: tschipp.carryon.common.event.ItemEntityEvents@6a1746bb onItemDropped(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 5: NORMAL
[05:43:22] [Server thread/ERROR] [FML]: 6: ASM: lumien.bloodmoon.handler.BloodmoonEventHandler@25de25f playerJoinedWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 7: ASM: com.rwtema.extrautils2.items.DemonicIngotHandler@18bdfea5 onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 8: ASM: com.rwtema.extrautils2.blocks.BlockCursedEarth$EventHandler@55411bdb spawnInWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 9: ASM: futurepack.common.FPMain@14457ff4 onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 10: ASM: futurepack.common.ManagerGleiter@6139f62 onPlayerLogin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 11: ASM: journeymap.server.events.ForgeEvents@7d00085e onEntityJoinWorldEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 12: ASM: net.geforcemods.securitycraft.SCEventHandler@6461c644 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 13: ASM: com.rwtema.extrautils2.villagers.EntityAINinjaPoof$Handler@3aa824e3 a(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/ERROR] [FML]: 14: ASM: class com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim onJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
[05:43:22] [Server thread/WARN] []: java.lang.NullPointerException
[05:43:22] [Server thread/WARN] []:     at journeymap.common.network.impl.MessageProcessor.sendToPlayer(MessageProcessor.java:240)
[05:43:22] [Server thread/WARN] []:     at journeymap.server.events.ForgeEvents.sendConfigsToPlayer(ForgeEvents.java:82)
[05:43:22] [Server thread/WARN] []:     at journeymap.server.events.ForgeEvents.onEntityJoinWorldEvent(ForgeEvents.java:64)
[05:43:22] [Server thread/WARN] []:     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_354_ForgeEvents_onEntityJoinWorldEvent_EntityJoinWorldEvent.invoke(.dynamic)
[05:43:22] [Server thread/WARN] []:     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[05:43:22] [Server thread/WARN] []:     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.world.World.spawnEntity(World.java:1491)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1375)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.world.World.addEntity(World.java:1414)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.addEntityToWorld(NMSImpl.java:240)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.util.NMS.addEntityToWorld(NMS.java:48)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:261)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:527)
[05:43:22] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:43:22] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05:43:22] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05:43:22] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Method.java:498)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[05:43:22] [Server thread/WARN] []:     at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
[05:43:22] [Server thread/WARN] []:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:43:22] [Server thread/WARN] []:     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)
[05:43:22] [Server thread/WARN] []:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1604)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1452)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14)
[05:43:22] [Server thread/WARN] []:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:43:22] [Server thread/WARN] []:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[05:43:22] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[05:43:22] [Server thread/WARN] []:     at java.lang.Thread.run(Thread.java:748)

**Comment by Camotoy** [comment]
`at journeymap.common.network.impl.MessageProcessor.sendToPlayer(MessageProcessor.java:240) `

This does not appear to be a Citizens issue.

Additionally, I'm sure that Magma is not supported by the Citizens developers.

**Comment by mcmonkey4eva** [comment]
Magma/Forge is entirely unsupported and unsupportable. Citizens does not work on Forge, at all... there are unofficial compatibility builds made by third parties, but they are entirely separate.
