### ISSUE TITLE
Error message~I don't know how to solve it.

### ISSUE THREAD

**Issue by michaeljrgame** [CitizensDev/Citizens2#2453]
[00:13:21 WARN]: [Citizens] Plugin Citizens v2.0.27-SNAPSHOT (build 2217) generated an exception whilst handling conversation input
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
        at java.text.MessageFormat.applyPattern(MessageFormat.java:520) ~[?:?]
        at java.text.MessageFormat.<init>(MessageFormat.java:370) ~[?:?]
        at net.citizensnpcs.api.util.Translator.getFormatter(Translator.java:71) ~[?:?]
        at net.citizensnpcs.api.util.Translator.format(Translator.java:50) ~[?:?]
        at net.citizensnpcs.api.util.Translator.translate(Translator.java:312) ~[?:?]
        at net.citizensnpcs.api.util.Translator.translate(Translator.java:316) ~[?:?]
        at net.citizensnpcs.api.util.Messaging.sendTr(Messaging.java:139) ~[?:?]
        at net.citizensnpcs.trait.text.TextEditPrompt.acceptInput(TextEditPrompt.java:23) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[patched_1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[patched_1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1522) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerConnection$2.run(PlayerConnection.java:1843) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1308) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[00:13:37 WARN]: [Citizens] Plugin Citizens v2.0.27-SNAPSHOT (build 2217) generated an exception whilst handling conversation input
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
        at java.text.MessageFormat.applyPattern(MessageFormat.java:520) ~[?:?]
        at java.text.MessageFormat.<init>(MessageFormat.java:370) ~[?:?]
        at net.citizensnpcs.api.util.Translator.getFormatter(Translator.java:71) ~[?:?]
        at net.citizensnpcs.api.util.Translator.format(Translator.java:50) ~[?:?]
        at net.citizensnpcs.api.util.Translator.translate(Translator.java:312) ~[?:?]
        at net.citizensnpcs.api.util.Translator.translate(Translator.java:316) ~[?:?]
        at net.citizensnpcs.api.util.Messaging.sendTr(Messaging.java:139) ~[?:?]
        at net.citizensnpcs.trait.text.TextEditPrompt.acceptInput(TextEditPrompt.java:23) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[patched_1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[patched_1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1522) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerConnection$2.run(PlayerConnection.java:1843) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1308) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[00:13:59 WARN]: [Citizens] Plugin Citizens v2.0.27-SNAPSHOT (build 2217) generated an exception whilst handling conversation input
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
        at java.text.MessageFormat.applyPattern(MessageFormat.java:520) ~[?:?]
        at java.text.MessageFormat.<init>(MessageFormat.java:370) ~[?:?]
        at net.citizensnpcs.api.util.Translator.getFormatter(Translator.java:71) ~[?:?]
        at net.citizensnpcs.api.util.Translator.format(Translator.java:50) ~[?:?]
        at net.citizensnpcs.api.util.Translator.translate(Translator.java:312) ~[?:?]
        at net.citizensnpcs.api.util.Translator.translate(Translator.java:316) ~[?:?]
        at net.citizensnpcs.api.util.Messaging.sendTr(Messaging.java:139) ~[?:?]
        at net.citizensnpcs.trait.text.TextEditPrompt.acceptInput(TextEditPrompt.java:23) ~[?:?]
        at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[patched_1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[patched_1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1522) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.PlayerConnection$2.run(PlayerConnection.java:1843) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1308) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-414]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by mcmonkey4eva** [comment]
First, try updating to a newer build: https://ci.citizensnpcs.co/job/Citizens2/ and Paper 1.16.5

**Comment by michaeljrgame** [comment]
THANK YOU!
