### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by RickyLaChow** [CitizensDev/Citizens2#2456]
Hi i receive this error in my console when i click on NPC
```
[14:10:42 ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.27-SNAPSHOT (build 2237)
java.lang.NullPointerException: null
        at net.citizensnpcs.npc.ai.speech.CitizensSpeechFactory.isRegistered(CitizensSpeechFactory.java:59) ~[?:?]
        at net.citizensnpcs.npc.ai.speech.CitizensSpeechFactory.getVocalChord(CitizensSpeechFactory.java:35) ~[?:?]
        at net.citizensnpcs.api.ai.speech.SimpleSpeechController.speak(SimpleSpeechController.java:33) ~[?:?]
        at net.citizensnpcs.api.ai.speech.SimpleSpeechController.speak(SimpleSpeechController.java:23) ~[?:?]
        at net.citizensnpcs.trait.text.Text.sendText(Text.java:224) ~[?:?]
        at net.citizensnpcs.trait.text.Text.onRightClick(Text.java:142) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[server.jar:git-Paper-438]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-438]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-438]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[server.jar:git-Paper-438]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:504) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor746.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[server.jar:git-Paper-438]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[server.jar:git-Paper-438]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Paper-438]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2196) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[server.jar:git-Paper-438]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[server.jar:git-Paper-438]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
The output of command `/version` on my server is: Version 1.16-R0.1-SNAPSHOT Paper 
The output of command `/version citizens` on my server is: Build 2237
More details:
command /version: 
[14:14:57 INFO]: This server is running Paper version git-Paper-438 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[14:14:57 INFO]: Previous version: git-Paper-344 (MC: 1.16.4)
[14:14:57 INFO]: You are 6 version(s) behind

command /version citizens:
[14:16:05 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2237)
[14:16:05 INFO]: Website: http://www.citizensnpcs.co
[14:16:05 INFO]: Author: fullwall

**Comment by fullwall** [comment]
Your saves file may have an error in it - can you post it please?

**Comment by RickyLaChow** [comment]
https://www.dropbox.com/s/5qk7ruo8xztw2gv/saves.yml?dl=0

**Comment by mcmonkey4eva** [comment]
There are a few NPCs with `speech: chat` in that saves file, which seems relevant.

This commit: https://github.com/CitizensDev/Citizens2/commit/ac106a6c5080b202d552b35e5a5af16fd2299836 seems to be adding better error checks for this issue, so please try to replicate the error on a newer build: https://ci.citizensnpcs.co/job/Citizens2/
and if you can replicate it, post a newer log file.
