### ISSUE TITLE
1.16.4 error report 

### ISSUE THREAD

**Issue by 3269199948** [CitizensDev/Citizens2#2459]
my server version is: **(Arclight 1.16.4)**
citizens version is: **(Citizens-2.0.27-b2247)**

Spring issued server command: /npc create 星之守护者
[19:05:49] [Server thread/INFO] [n.m.c.C.astralsorcery/COREMODLOG]: Adding 'reach_set_server_entity_interact' ASM patch...
[19:05:49] [Server thread/INFO] [n.m.c.C.astralsorcery/COREMODLOG]: Added 'reach_set_server_entity_interact' ASM patch!
[19:05:49] [Server thread/INFO] [n.m.c.C.astralsorcery/COREMODLOG]: Adding 'allow_entity_interaction' ASM patch...
[19:05:49] [Server thread/INFO] [n.m.c.C.astralsorcery/COREMODLOG]: Added 'allow_entity_interaction' ASM patch!
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]: java.lang.reflect.GenericSignatureFormatError: Signature Parse error: Expected Field Type Signature
        Remaining input: 
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:297)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:485)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:52)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:42)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.repository.FieldRepository.<init>(FieldRepository.java:48)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.generics.repository.FieldRepository.make(FieldRepository.java:66)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at java.lang.reflect.Field.getGenericInfo(Field.java:105)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at java.lang.reflect.Field.getGenericType(Field.java:247)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.checkFieldTypes(ClassLoaderRemapper.java:147)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.tryGetFields(ClassLoaderRemapper.java:126)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.lambda$getFields$1(ClassLoaderRemapper.java:119)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.getFields(ClassLoaderRemapper.java:119)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at io.izzel.arclight.common.mod.util.remapper.ClassLoaderRemapper.tryMapDecFieldToSrg(ClassLoaderRemapper.java:185)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at io.izzel.arclight.common.mod.util.remapper.generated.ArclightReflectionHandler_14.redirectGetDeclaredField(ArclightReflectionHandler.java:99)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.util.NMS.getField(NMS.java:92)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.util.NMS.getGetter(NMS.java:177)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.util.NMS.getGetter(NMS.java:172)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<clinit>(EntityHumanNPC.java:589)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:527)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at java.lang.reflect.Method.invoke(Method.java:498)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:763)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapperMixin.java:44)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.command.Commands.func_197059_a(CommandsMixin.java:217)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2535)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2388)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.network.PacketThreadUtil.md5fe4d0$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:733)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:716)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:710)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232)
[19:05:49] [Server thread/INFO] [STDERR/]: [net.citizensnpcs.api.command.CommandManager:executeSafe:205]:       at java.lang.Thread.run(Thread.java:748)

**Comment by mcmonkey4eva** [comment]
Citizens only supports Spigot and derivative forks like Paper, not Forge or other platforms.
