### ISSUE TITLE
/npc equip breaks in 1.8.9

### ISSUE THREAD

**Issue by skbeh** [CitizensDev/Citizens2#2464]
The output of command `/version` on my server is: **This server is running CraftBukkit version git-TacoSpigot-"c80c1e5" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2253)**

The comment [8e31baf](https://github.com/CitizensDev/Citizens2/commit/8e31baf2022fd2a1ecdcf027448f3c827b04fc6d) breaks `/npc equip` in 1.8.9
```
[22:34:49] [Server thread/INFO]: issued server command: /npc equip
[22:34:49] [Server thread/WARN]: java.lang.EnumConstantNotPresentException: org.bukkit.Material.ELYTRA
[22:34:49] [Server thread/WARN]: 	at sun.reflect.annotation.EnumConstantNotPresentExceptionProxy.generateException(EnumConstantNotPresentExceptionProxy.java:46)
[22:34:49] [Server thread/WARN]: 	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84)
[22:34:49] [Server thread/WARN]: 	at com.sun.proxy.$Proxy44.material(Unknown Source)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenuSlot.initialise(InventoryMenuSlot.java:69)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.createSlot(InventoryMenu.java:96)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.transition(InventoryMenu.java:389)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.<init>(InventoryMenu.java:71)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.createWithContext(InventoryMenu.java:632)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.editor.EquipmentEditor.begin(EquipmentEditor.java:40)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.editor.Editor.enter(Editor.java:20)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.editor.Editor.enterOrLeave(Editor.java:31)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.commands.EditorCommands.equip(EditorCommands.java:39)
[22:34:49] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:34:49] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:34:49] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:34:49] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[22:34:49] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:269)
[22:34:49] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:34:49] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[22:34:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:34:49] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:34:49] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[22:34:49] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[22:34:49] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by skbeh** [comment]
The old one also do not open GUI when I right click the NPC,but it don't throw out error.

**Comment by fullwall** [comment]
Fixed

**Comment by skbeh** [comment]
There is still a problem.

```
[19:14:26] [Server thread/INFO]: issued server command: /npc equip
[19:14:26] [Server thread/WARN]: java.lang.NullPointerException
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenuSlot.initialise(InventoryMenuSlot.java:82)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.createSlot(InventoryMenu.java:96)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.transition(InventoryMenu.java:389)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.<init>(InventoryMenu.java:71)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.createWithContext(InventoryMenu.java:632)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.editor.EquipmentEditor.begin(EquipmentEditor.java:40)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.editor.Editor.enter(Editor.java:20)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.editor.Editor.enterOrLeave(Editor.java:31)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.commands.EditorCommands.equip(EditorCommands.java:39)
[19:14:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:14:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:14:26] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:14:26] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[19:14:26] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[19:14:26] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:14:26] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[19:14:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[19:14:26] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:14:26] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[19:14:26] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[19:14:26] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Loneattic** [comment]
I have the same trouble with latest Paper and Citizens.

**Comment by skbeh** [comment]
New problem.
```
[15:43:13] [Server thread/INFO]: issued server command: /npc equip
[15:43:13] [Server thread/WARN]: java.lang.EnumConstantNotPresentException: org.bukkit.Material.GLASS_PANE
[15:43:13] [Server thread/WARN]: 	at sun.reflect.annotation.EnumConstantNotPresentExceptionProxy.generateException(EnumConstantNotPresentExceptionProxy.java:46)
[15:43:13] [Server thread/WARN]: 	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84)
[15:43:13] [Server thread/WARN]: 	at com.sun.proxy.$Proxy50.material(Unknown Source)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenuSlot.initialise(InventoryMenuSlot.java:95)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.createSlot(InventoryMenu.java:102)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.parsePattern(InventoryMenu.java:319)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.transition(InventoryMenu.java:413)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.<init>(InventoryMenu.java:73)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.gui.InventoryMenu.createWithContext(InventoryMenu.java:666)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.editor.EquipmentEditor.begin(EquipmentEditor.java:40)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.editor.Editor.enter(Editor.java:20)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.editor.Editor.enterOrLeave(Editor.java:31)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.commands.EditorCommands.equip(EditorCommands.java:39)
[15:43:13] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:43:13] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:43:13] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:43:13] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[15:43:13] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[15:43:13] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:43:13] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[15:43:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:43:13] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:43:13] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:43:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:43:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```
