### ISSUE TITLE
Utterly nonsensical ClassCastException with NPC commands?!

### ISSUE THREAD

**Issue by bluelhf** [CitizensDev/Citizens2#2494]
The output of command `/version` on my server is: **git-Paper-496 (MC: 1.16.5)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.27-SNAPSHOT (build 2260)**
The output of `java --version` on my server is:
```
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

I'm getting a `ClassCastException` when I **right-click on a citizen that has commands attached to it, preventing any of the commands from running.** The stack-trace is this:
```
[21:10:25 ERROR]: Could not pass event PlayerInteractEntityEvent to Citizens v2.0.27-SNAPSHOT (build 2260)
java.lang.ClassCastException: class java.lang.String cannot be cast to class net.citizensnpcs.trait.CommandTrait$PlayerNPCCommand (java.lang.String is in module java.base of loader 'bootstrap'; net.citizensnpcs.trait.CommandTrait$PlayerNPCCommand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1163f265)
        at net.citizensnpcs.trait.CommandTrait$1$3.run(CommandTrait.java:223) ~[?:?]
        at net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:242) ~[?:?]
        at net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:212) ~[?:?]
        at net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:249) ~[?:?]
        at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:509) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor335.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-496]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2203) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.5.jar:git-Paper-496]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

Honestly, I'm quite stumped. [The line that the trace points to](https://github.com/CitizensDev/Citizens2/blob/0b41b24425a9678507a2a0c8af0067117882b837/main/src/main/java/net/citizensnpcs/trait/CommandTrait.java#L223) is `PlayerNPCCommand info = cooldowns.get(player.getUniqueId().toString());`, but the failure of the cast makes zero sense, because cooldowns is a `String, PlayerNPCCommand` map, so a call to cooldowns.get(String) should (obviously) result in a PlayerNPCCommand... What!?

The commands on the NPC are as follows:
```
Commands to run on right click:
     - [0]: tellraw @s {"text":"You can\'t remember anything. Perhaps walking around will freshen your memory","color":"gray","italic":"true"} [0s] -o -p
     - [1]: effect give @s minecraft:slowness 7 5 true [7s] -o -p
```

Any help / workarounds would be appreciated :)

**Comment by MetooMango** [comment]
I think im going to attempt deleting the config for the citizens plugin and restarting it all over from scratch again

**Comment by SXRWahrheit** [comment]
Please post your full latest log file here, thanks:

https://paste.denizenscript.com/New/Log

**Comment by bluelhf** [comment]
Duplicate of Confirmed Bug #2472
