### ISSUE TITLE
IllegalArgumentException on right click npc

### ISSUE THREAD

**Issue by eUipKh** [CitizensDev/Citizens2#2529]
Having this error when players spam the right click on npc with this command:
`/npc command add -p --cooldown 1 "coins"`

```
[18:52:01] [Server thread/ERROR]: Could not pass event PlayerInteractEntityEvent to Citizens v2.0.27-SNAPSHOT (build 2286)
java.lang.IllegalArgumentException: can't parse argument number: minutes
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1429) ~[?:1.8.0_272]
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479) ~[?:1.8.0_272]
	at java.text.MessageFormat.<init>(MessageFormat.java:362) ~[?:1.8.0_272]
	at net.citizensnpcs.api.util.Translator.getFormatter(Translator.java:71) ~[?:?]
	at net.citizensnpcs.api.util.Translator.format(Translator.java:221) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait.sendErrorMessage(CommandTrait.java:295) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait.access$900(CommandTrait.java:56) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait$PlayerNPCCommand.canUse(CommandTrait.java:571) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait$1$3.run(CommandTrait.java:231) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:245) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:215) ~[?:?]
	at net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:252) ~[?:?]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:515) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor533.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-582]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-582]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-582]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2343) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-582]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NumberFormatException: For input string: "minutes"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_272]
	at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_272]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_272]
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1427) ~[?:1.8.0_272]
	... 32 more
```

The output of command `/version` on my server is: **(PLEASE FILL IN)**
```
This server is running Paper version git-Paper-582 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind
Previous version: git-Paper-468 (MC: 1.16.5)
```

The output of command `/version citizens` on my server is: **(PLEASE FILL IN)**
```
Citizens version 2.0.27-SNAPSHOT (build 2286)
Website: http://www.citizensnpcs.co
Author: fullwall
```

**Comment by mcmonkey4eva** [comment]
Confirmed and replicated, most likely caused by this commit: https://github.com/CitizensDev/Citizens2/commit/643e42f4ba76b97e55bdcd720c7b8640a917b161
Only applicable to up-to-date `config.yml` files.
