### ISSUE TITLE
Flocker produces infinite velocities

### ISSUE THREAD

**Issue by gayakps** [CitizensDev/Citizens2#2548]
version : This server is running Paper version git-Paper-557 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

https://pastebin.com/dQBR1an9

Info :
1. NPC is spawned
2. Add trait to npc ( flocking isn't work / and navigator.settarget() was working )
3. /npc follow command is working that flocking and follow specific player
                   
                   
Why using flocking ? => avoid npc's overlappaed

if flock.run() method execute, occur this errors:
```
[11:41:54 INFO]: [Citizens] Exception while updating 16: x not finite.
[11:41:54 WARN]: java.lang.IllegalArgumentException: x not finite
[11:41:54 WARN]:        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118)
[11:41:54 WARN]:        at org.bukkit.util.Vector.checkFinite(Vector.java:814)
[11:41:54 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.setVelocity(CraftEntity.java:430)
[11:41:54 WARN]:        at net.citizensnpcs.api.ai.flocking.Flocker.run(Flocker.java:43)
[11:41:54 WARN]:        at gaya.pe.kr.traits.PlayerFollowing.run(PlayerFollowing.java:45)
[11:41:54 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:480)
[11:41:54 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:350)
```

**Comment by fullwall** [comment]
Update to latest Citizens. Also if you are using compile scope in maven - use scope provided instead.

**Comment by gayakps** [comment]
<dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizensapi</artifactId>
            <version>2.0.27-SNAPSHOT</version>
            <type>jar</type>
            <scope>provided</scope>
        </dependency>
        
        i'm using this

**Comment by fullwall** [comment]
OK and still getting error in build 2310?

**Comment by gayakps** [comment]
Citizen version 2.0.27-snapshot
(build 2290)  << not lastest?

in build 2290, It occur same error too

**Comment by fullwall** [comment]
Please download build 2310 and try again.

**Comment by gayakps** [comment]
https://repo.citizensnpcs.co/net/citizensnpcs/citizensapi/

In my sight, every version is lastest
I want to divide from date so it can't that.
can you teaching what is lastest version please?

**Comment by mcmonkey4eva** [comment]
You download builds from https://ci.citizensnpcs.co/job/Citizens2/

Also that maven dependency is wrong, as it says at https://wiki.citizensnpcs.co/API you should use `<artifactId>citizens-main</artifactId>`
