### ISSUE TITLE
Can't open any gui-menu

### ISSUE THREAD

**Issue by danil20028191** [CitizensDev/Citizens2#2551]
Using latest build of PaperSpigot and Citizens

net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Вещи Дьявола", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Ценности", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Кузнец", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Механизмы", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Декорации", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Полублоки", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Блоки (2)", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Блоки (1)", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Оружейник", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Красители", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Разное", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Стёкла", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Еда", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[08:59:27 WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Зелья", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[08:59:27 WARN]:        at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[08:59:27 WARN]:        at net.kyori.adventure.text.Component.text(Component.java:588)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[08:59:27 WARN]:        at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:54)
[08:59:27 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[08:59:27 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[08:59:27 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)

**Comment by mcmonkey4eva** [comment]
Those messages are from Paper, not Citizens.

Please either fill out the issue template properly or ask on Discord @ https://discord.gg/Q6pZGSR

**Comment by danil20028191** [comment]
menus can open, but error ucures only while trying to interract with npcs

воскресенье, 16 мая 2021 г. пользователь mcmonkey4eva <
***@***.***> написал:

**Comment by CloudeLecaw** [comment]
Try Build691 it should be fixed now, this crazzy check is disabled.
