### ISSUE TITLE
New issue with kiorie on startup

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#2552]
This issue semms to be new.
We updated from paperMC670 to PaperMC686
Then this issue accours
Like you can see here https://github.com/PaperMC/Paper/issues/5659
they said we should inform you - its a "warning" instead of a paper issue
```
[07:50:07] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Barmann", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:07] [Craft Scheduler Thread - 7/INFO]: [GadgetsMenu] No update was found, you are running the latest version.
[07:50:07] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Bryn", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:07] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Sandy", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:07] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Pfarrer", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:07] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="SirRuben", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:07] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Tanja", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:07] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:07] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:08] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Stan", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:08] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Luisa", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:08] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Steven", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:08] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Rosalin", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:08] [Server thread/WARN]: net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information. Component: TextComponentImpl{content="Annemarie", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[07:50:08] [Server thread/WARN]: 	at net.kyori.adventure.text.Component.text(Component.java:588)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.EntityPlayer.<init>(EntityPlayer.java:284)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:92)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_16_R3.entity.HumanController.createEntity(HumanController.java:52)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:50:08] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:50:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1075)
[07:50:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[07:50:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[07:50:08] [Server thread/INFO]: [Citizens] 62 NPCs geladen.
```

**Comment by mcmonkey4eva** [comment]
This is purely and exclusively a Paper issue. Nothing can be done in Citizens to change that. Paper has to fix it.

**Comment by CloudeLecaw** [comment]
i attached this issue on the papersite - may u can take a word there too
https://github.com/PaperMC/Paper/issues/5659
