### ISSUE TITLE
Little Error on Startup - Citizens_2.0.28-Build2326

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#2569]
```
[07:58:13] [Server thread/WARN]: [Citizens] Task #58 for Citizens v2.0.28-SNAPSHOT (build 2326) generated an exception
java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_17_R1.entity.CraftSkeleton: method 'void <init>(org.bukkit.craftbukkit.v1_17_R1.CraftServer, net.minecraft.world.entity.monster.EntitySkeletonAbstract)' not found
	at net.citizensnpcs.nms.v1_17_R1.entity.SkeletonController$SkeletonNPC.<init>(SkeletonController.java:199) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.SkeletonController$EntitySkeletonNPC.getBukkitEntity(SkeletonController.java:114) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:43) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1252) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:436) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3143-Spigot-66f9d3c-f66c437]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

![image](https://user-images.githubusercontent.com/12080017/122001549-c5b76200-cdb0-11eb-8d78-670d31c432a3.png)
Citizens_2.0.28-Build2326

**Comment by mcmonkey4eva** [comment]
This looks like the type of issue that would resolve itself after a simple recompile - Spigot's been changing some of the NMS internals around a bit, and just recompiling has sufficed.

This seems to just be part of the process with brand new minecraft versions as of now (Spigot changed the system for how NMS updates are handled for 1.17 and will likely keep using it for future versions).

2327+ from https://ci.citizensnpcs.co/job/Citizens2/ should work with an equivalently recent Spigot build.
