### ISSUE TITLE
1.17 - Blazes fail with "unable to find valid entity superclass" exception

### ISSUE THREAD

**Issue by mrfloris** [CitizensDev/Citizens2#2578]
Going from 1.16.5 citizens to latest ci build on 1.17, during first startup I noticed this: Any tips on how to resolve this?

```
[09:55:00 WARN]: java.lang.IllegalArgumentException: unable to find valid entity superclass for class class net.citizensnpcs.nms.v1_17_R1.entity.BlazeController$BlazeNPC
[09:55:00 WARN]:     at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.registerEntityClass(NMSImpl.java:1001)
[09:55:00 WARN]:     at net.citizensnpcs.util.NMS.registerEntityClass(NMS.java:436)
[09:55:00 WARN]:     at net.citizensnpcs.npc.AbstractEntityController.<init>(AbstractEntityController.java:16)
[09:55:00 WARN]:     at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.<init>(MobEntityController.java:24)
[09:55:00 WARN]:     at net.citizensnpcs.nms.v1_17_R1.entity.BlazeController.<init>(BlazeController.java:28)
[09:55:00 WARN]:     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[09:55:00 WARN]:     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[09:55:00 WARN]:     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:55:00 WARN]:     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[09:55:00 WARN]:     at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[09:55:00 WARN]:     at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
[09:55:00 WARN]:     at java.base/java.lang.Class.newInstance(Class.java:642)
[09:55:00 WARN]:     at net.citizensnpcs.npc.EntityControllers.createForType(EntityControllers.java:20)
[09:55:00 WARN]:     at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:128)
[09:55:00 WARN]:     at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:58)
[09:55:00 WARN]:     at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56)
[09:55:00 WARN]:     at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[09:55:00 WARN]:     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[09:55:00 WARN]:     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:55:00 WARN]:     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1127)
[09:55:00 WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[09:55:00 WARN]:     at java.base/java.lang.Thread.run(Thread.java:831)
[09:55:00 WARN]: [Citizens] Task #2543 for Citizens v2.0.28-SNAPSHOT (build 2328) generated an exception
java.lang.NullPointerException: null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
    at net.citizensnpcs.npc.CitizensNPC.<init>(CitizensNPC.java:62) ~[?:?]
    at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:128) ~[?:?]
    at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:58) ~[?:?]
    at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56) ~[?:?]
    at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501) ~[?:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1127) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"a7cddc4"]
    at java.lang.Thread.run(Thread.java:831) [?:?]
```
```
paper-1.17-40.jar
Citizens-2.0.28-b2328.jar
```

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/f5a56ba8f84e28b87ec6c16368c875b8aa270b03 for Citizens build 2329+
