### ISSUE TITLE
Sentry command produces error when chunk with sentry is not loaded

### ISSUE THREAD

**Issue by AwesomeLawson** [CitizensDev/Citizens2#258]
When I run the command /sentry 221 equip none to change the equipped item for a sentry when I'm near the sentry it works.  When I run this command from a distance in the world and no other players are near it I receive the following error message: An internal error occurred while attempting to perform this command [http://gyazo.com/e46ee0eb8b8ad74e68e871416cb7f946].

I discovered this issue when the server owner sent the following exception report after I put commands into a custom plugin we use that acts like a timer:
[14:53:40 INFO]: [MassiveGates 1.1.3] CMD-Action:  sentry equip none
[14:53:40 WARN]: [MassiveGates] Task #34 for MassiveGates v1.1.3 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.8.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:90) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at com.massivecraft.massivegates.ta.ActionCmd.perform(ActionCmd.java:44) ~[?:?]
        at com.massivecraft.massivegates.Gate.trigger(Gate.java:523) ~[?:?]
        at com.massivecraft.massivegates.HourTriggingTask.triggerWorldHour(HourTriggingTask.java:73) ~[?:?]
        at com.massivecraft.massivegates.HourTriggingTask.runWorld(HourTriggingTask.java:59) ~[?:?]
        at com.massivecraft.massivegates.HourTriggingTask.run(HourTriggingTask.java:31) ~[?:?]
        at com.massivecraft.massivelag.inject.task.MassiveLagRunnable.run(MassiveLagRunnable.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: java.lang.NullPointerException
        at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:1089) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]

After some testing I was able to isolate an example of the command and run it as a player, from several hundred blocks from the sentry, and I received the following: 

Awes0meLawson issued server command: /sentry 221 equip none
[14:59:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentry v1.8.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:90) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40-internal]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-35348a5-ee6d0fa]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: java.lang.NullPointerException
        at net.aufdemrand.sentry.Sentry.onCommand(Sentry.java:1089) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-35348a5-ee6d0fa]

Thank you in advance for your time, attention, and this amazing plug-in.

**Comment by mcmonkey4eva** [comment]
Yup... that happens... the only solution would be recoding sentry to force-spawn the entity when you do a command...

here's a solution: Just be near the NPC when doing commands on it :D

Also, this is Citizens support, not Sentry support, so I'll close this (Feel free to reply down below, it's closed but not locked)

**Comment by AwesomeLawson** [comment]
"here's a solution: Just be near the NPC when doing commands on it :D"
Thanks for your reply but that's not a solution for me.  I'm using a timer plug-in to make the sentry behave differently during different times of day.

**Comment by mcmonkey4eva** [comment]
In which case, set the NPC to stay loaded, there's a Citizens config option for it and I think there's a per-NPC option too

**Comment by mcmonkey4eva** [comment]
or use a plugin like Denizen to issue force-load commands


or teleport it to spawn, edit it, teleport it back

or...

**Comment by AwesomeLawson** [comment]
Thanks for the suggestions!
