### ISSUE TITLE
1.17 Error on startup

### ISSUE THREAD

**Issue by John-H-Smith** [CitizensDev/Citizens2#2580]
After starting up my server I get this error message:

```
[16:07:47] [Server thread/ERROR]: Entity threw exception at world:-79.7502,96.0625,-2331.2162
java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.a(double, double, double, int)'
	at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.a(PlayerNavigation.java:373) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl$3.apply(NMSImpl.java:577) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl$3.apply(NMSImpl.java:1) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl$4.update(NMSImpl.java:656) ~[?:?]
	at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:73) ~[?:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:163) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:356) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:478) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:942) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:857) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:639) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:620) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
Before, on 1.16.5, all was working fine - I did no changes in config. I assume a bug with 1.17.

The output of command `/version` on my server is: **Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **Citizens version 2.0.28-SNAPSHOT (build 2328)**

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/Citizens2/commit/f5a56ba8f84e28b87ec6c16368c875b8aa270b03 for Citizens build 2329+
