### ISSUE TITLE
Could not pass PlayerinteractEntityevent

### ISSUE THREAD

**Issue by NightLife-SG** [CitizensDev/Citizens2#2581]
cant right click on npc to perform the command type in with error in console
link :https://hastebin.com/sexekepaca.apache
![image](https://user-images.githubusercontent.com/84533050/123447920-f6976280-d60c-11eb-9e5e-54d6eba66e6a.png)

**Comment by mcmonkey4eva** [comment]
```
25.06 23:23:02 [Server] ERROR Could not pass event PlayerInteractEntityEvent to Citizens v2.0.28-SNAPSHOT (build 2328)
25.06 23:23:02 [Server] INFO java.lang.IllegalStateException: zip file closed
25.06 23:23:02 [Server] INFO at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
25.06 23:23:02 [Server] INFO at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
25.06 23:23:02 [Server] INFO at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
25.06 23:23:02 [Server] INFO at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
25.06 23:23:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.jar:git-Paper-46]
25.06 23:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
25.06 23:23:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-Paper-46]
25.06 23:23:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235) ~[patched_1.17.jar:git-Paper-46]
25.06 23:23:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:121) ~[patched_1.17.jar:git-Paper-46]
25.06 23:23:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-46]
25.06 23:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:573) ~[?:?]
25.06 23:23:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
25.06 23:23:02 [Server] INFO at me.lucko.luckperms.bukkit.inject.permissible.LuckPermsPermissionAttachment.injectFakeMap(LuckPermsPermissionAttachment.java:136) ~[?:?]
```
That message `java.lang.IllegalStateException: zip file closed` usually indicates that a jar file (plugin jar or the server jar) was modified while the server was running.
In this case the error originates while LuckPerms was loading classes, so the most likely jars to have been modified would be LuckPerms, Spigot, or Citizens.
The error shouldn't repeat if you restart the server, and then be sure to not modify any jar files while the server is up.

(If you need to update a plugin or anything, shut the server all the way down, THEN change files around, THEN start it back up)
