### ISSUE TITLE
ClassCastException with WorldGuard 

### ISSUE THREAD

**Issue by bermudalocket** [CitizensDev/Citizens2#2590]
Hi, 

I just set up Citizens 2 for the first time on my development server running Paper 1.17. Everything is working great except for an issue I'm having with the `/npc path` feature that restricts wandering to within a WorldGuard region. Whenever I assign an NPC the wander waypoint provider, a ClassCastException begins to be repeatedly thrown in console.

The configuration has not been touched and can be considered fully default.

I have trimmed the logs down to everything relevant.

If this is an issue on my end, any guidance would be appreciated. Otherwise, please let me know if there's anything else I can provide.

Thanks!

---

Relevant logs (startup to pre-exception): 
https://pastebin.com/MwSHgi4H

The output of command `/version` on my server is:
```
git-Paper-68 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: f18dc1e)
```

The output of command `/version citizens` on my server is: 
```
Citizens version 2.0.28-SNAPSHOT (build 2337)
Website: http://www.citizensnpcs.co
Author: fullwall
```

WorldGuard version info:
```
> worldguard version
WorldGuard 7.0.6-SNAPSHOT
http://www.enginehub.org
----------- Platforms -----------
* Bukkit-Official (7.0.6-SNAPSHOT+2130-1cd5818)
```

WorldEdit version info:
```
> version worldedit
WorldEdit version 7.3.0-SNAPSHOT+5835-b8a9c00
```

Exception:

```
[20:36:46 WARN]: java.lang.ClassCastException: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion incompatible with com.
sk89q.worldedit.regions.Region
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.goals.WanderGoal$1.apply(WanderGoal.java:64)
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.goals.WanderGoal$1.apply(WanderGoal.java:54)
[20:36:46 WARN]:        at net.citizensnpcs.api.astar.pathfinder.MinecraftBlockExaminer.findRandomValidLocation(MinecraftBlockExami
ner.java:154)
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.goals.WanderGoal.findRandomPosition(WanderGoal.java:53)
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.goals.WanderGoal.shouldExecute(WanderGoal.java:131)
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.tree.BehaviorGoalAdapter.shouldExecute(BehaviorGoalAdapter.java:22)
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.SimpleGoalController.trySelectGoal(SimpleGoalController.java:216)
[20:36:46 WARN]:        at net.citizensnpcs.api.ai.SimpleGoalController.run(SimpleGoalController.java:188)
[20:36:46 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:490)
[20:36:46 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:348)
[20:36:46 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:478)
[20:36:46 WARN]:        at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:942)
[20:36:46 WARN]:        at net.minecraft.server.level.WorldServer$$Lambda$6701/0x00000000069f1d20.accept(Unknown Source)
[20:36:46 WARN]:        at net.minecraft.world.level.World.a(World.java:857)
[20:36:46 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:639)
[20:36:46 WARN]:        at net.minecraft.server.level.WorldServer$$Lambda$6700/0x00000000069f1a88.accept(Unknown Source)
[20:36:46 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:54)
[20:36:46 WARN]:        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:620)
[20:36:46 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1551)
[20:36:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477)
[20:36:46 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404)
[20:36:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[20:36:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:36:46 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3706/0x0000000099ea0858.run(Unknown Source)
[20:36:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by mcmonkey4eva** [comment]
Straightforward enough issue:
At https://github.com/CitizensDev/CitizensAPI/blob/622629b4db300de395cfdd32e5ad83d137e647a3/src/main/java/net/citizensnpcs/api/ai/goals/WanderGoal.java#L64
The `Region` should be `ProtectedRegion`

**Comment by mcmonkey4eva** [comment]
Should be fixed by https://github.com/CitizensDev/CitizensAPI/commit/36fcf7678847cc7dcd0fb8583e41fb3f54d8e0b5 for Citizens build 2345+ from https://ci.citizensnpcs.co/job/Citizens2/
