### ISSUE TITLE
Error 1.17

### ISSUE THREAD

**Issue by TheIntelloBox** [CitizensDev/Citizens2#2593]
[21:57:32] [Server thread/ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 10.
[21:57:32] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
[21:57:32] [Server thread/WARN]: 	at net.minecraft.nbt.NBTTagCompound.clone(NBTTagCompound.java:397)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:643)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayOutSetSlot.<init>(PacketPlayOutSetSlot.java:19)
[21:57:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:212)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:91)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:302)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[21:57:32] [Server thread/WARN]: 	at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[21:57:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[21:57:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1488)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1404)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[21:57:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:57:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:57:32] [Server thread/WARN]: [Citizens] Task #153 for Citizens v2.0.28-SNAPSHOT (build 2340) generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:643) ~[patched_1.17.jar:git-Paper-74]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:261) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:232) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:637) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:169) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.playerTick(NMSImpl.java:978) ~[?:?]
	at net.citizensnpcs.util.NMS.playerTick(NMS.java:432) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-74]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:57:32] [Server thread/ERROR]: Entity threw exception at world:1570.3476,94.0,879.0771
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:643) ~[patched_1.17.jar:git-Paper-74]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:261) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:232) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:637) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:463) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:942) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:864) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:639) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:620) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-74]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by mcmonkey4eva** [comment]
That looks like either an error with Spigot/Paper, or somehow an invalid item, either way not sourced from Citizens.
