### ISSUE TITLE
1.17.1 Problem

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#2594]
Today the MC 1.17.1 came out.
Citizens throws this mistake. You can create npc but the saved ones won't be loaded. this happens during a reload.

`[18:31:52] [Server thread/INFO]: Blueeyestar issued server command: /citizens reload
[18:31:52] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[18:31:52] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:31:52] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[18:31:52] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:31:52] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[18:31:52] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:48)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.reload(Citizens.java:387)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:57)
[18:31:52] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:31:52] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[18:31:52] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:31:52] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[18:31:52] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[18:31:52] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:31:52] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[18:31:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1133)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1126)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1110)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1039)
[18:31:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[18:31:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:31:52] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldError: bO`

`[18:26:42] [Server thread/WARN]: [Citizens] Task #6541 for Citizens v2.0.28-SNAPSHOT (build 2345) generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.setLocation(double, double, double, float, float)" because "entity" is null
	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[server.jar:3171-Spigot-610a8c0-fb556bf]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by mcmonkey4eva** [comment]
Stop flooding the issues page with this stuff.
Refer to md_5's "Expectations & Entitlement" rant https://www.spigotmc.org/threads/spigot-bungeecord-1-16-1.447405/
