### ISSUE TITLE
Might be a little help for updating to 1.17.1

### ISSUE THREAD

**Issue by CloudeLecaw** [CitizensDev/Citizens2#2596]
I know your allways updating fast :) so pls take it just as information. might it helps to see what might went wrong and might helps to fix an issue faster

```
[07:21:16] [Server thread/WARN]: [Citizens] Task #6943 for Citizens v2.0.28-SNAPSHOT (build 2345) generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.setLocation(double, double, double, float, float)" because "entity" is null
	at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[server.jar:3172-Spigot-610a8c0-99561c2]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by CoderStone** [comment]
Moving NPCs cause this error :)
[07:18:24 WARN]: [Citizens] Task #604 for Citizens v2.0.28-SNAPSHOT (build 2345) generated an exception
java.lang.IllegalAccessError: class net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation tried to access protected method 'float net.minecraft.world.entity.EntityLiving.ev()' (net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6aef1c56; net.minecraft.world.entity.EntityLiving is in unnamed module of loader 'app')
        at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.a(PlayerNavigation.java:271) ~[?:?]
        at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.l(PlayerNavigation.java:291) ~[?:?]
        at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.c(PlayerNavigation.java:519) ~[?:?]
        at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.updateNavigation(NMSImpl.java:1862) ~[?:?]
        at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:182) ~[?:?]
        at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.playerTick(NMSImpl.java:980) ~[?:?]
        at net.citizensnpcs.util.NMS.playerTick(NMS.java:432) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Purpur-1258]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1505) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Purpur-1258]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[patched_1.17.1.jar:git-Purpur-1258]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by mrfloris** [comment]
Yep, I noticed that I got an onEnable error as well in paper 1.17.1  ~ I am sure an update will come today to address some basic support for the new version which probably takes care of these. (courtesy report anyway)
```
[13:10:30 WARN]: java.lang.reflect.InvocationTargetException
[13:10:30 WARN]:     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:10:30 WARN]:     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[13:10:30 WARN]:     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:10:30 WARN]:     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:10:30 WARN]:     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:10:30 WARN]:     at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:48)
[13:10:30 WARN]:     at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[13:10:30 WARN]:     at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[13:10:30 WARN]:     at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[13:10:30 WARN]:     at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[13:10:30 WARN]:     at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[13:10:30 WARN]:     at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501)
[13:10:30 WARN]:     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[13:10:30 WARN]:     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:10:30 WARN]:     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1135)
[13:10:30 WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:10:30 WARN]:     at java.base/java.lang.Thread.run(Thread.java:831)
[13:10:30 WARN]: Caused by: java.lang.NoSuchFieldError: bO
[13:10:30 WARN]:     at net.citizensnpcs.nms.v1_17_R1.entity.VillagerController$EntityVillagerNPC.<init>(VillagerController.java:61)
[13:10:30 WARN]:     ... 17 more
[13:10:30 WARN]: [Citizens] Task #5505 for Citizens v2.0.28-SNAPSHOT (build 2345) generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.setLocation(double, double, double, float, float)" because "entity" is null
    at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:34) ~[?:?]
    at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
    at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254) ~[?:?]
    at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159) ~[?:?]
    at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
    at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:501) ~[?:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-83]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Paper-83]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1135) ~[patched_1.17.1.jar:git-Paper-83]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-83]
    at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mrfloris** [comment]
Oh, I just spotted during onEnable that it also has this:
```
[13:10:07 INFO]: [Citizens] Enabling Citizens v2.0.28-SNAPSHOT (build 2345)
[13:10:07 INFO]: [Citizens] Could not fetch NMS field bS: [[bS.
[13:10:07 INFO]: [Citizens] Could not fetch NMS field bS: [[null.
```

**Comment by CloudeLecaw** [comment]
Dont forget thr bo

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/issues/2594#issuecomment-874941949
