### ISSUE TITLE
Error that causes a crash

### ISSUE THREAD

**Issue by TheIntelloBox** [CitizensDev/Citizens2#2597]
[15:43:36] [Server thread/WARN]: [Citizens] Task #155 for Citizens v2.0.28-SNAPSHOT (build 2340) generated an exception
java.lang.IllegalAccessError: class net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation tried to access protected method 'float net.minecraft.world.entity.EntityLiving.ev()' (net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3e4389cd; net.minecraft.world.entity.EntityLiving is in unnamed module of loader 'app')
	at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.a(PlayerNavigation.java:271) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.l(PlayerNavigation.java:291) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.PlayerNavigation.c(PlayerNavigation.java:519) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.updateNavigation(NMSImpl.java:1860) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:182) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.playerTick(NMSImpl.java:978) ~[?:?]
	at net.citizensnpcs.util.NMS.playerTick(NMS.java:432) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-85]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-85]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[15:43:36] [Server thread/ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 10.
[15:43:36] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
[15:43:36] [Server thread/WARN]: 	at net.minecraft.nbt.NBTTagCompound.clone(NBTTagCompound.java:397)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:643)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayOutSetSlot.<init>(PacketPlayOutSetSlot.java:21)
[15:43:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:212)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:91)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:302)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.spawn(EventListen.java:718)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:693)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[15:43:36] [Server thread/WARN]: 	at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[15:43:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[15:43:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[15:43:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[15:43:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[15:43:36] [Server thread/WARN]: [Citizens] Task #155 for Citizens v2.0.28-SNAPSHOT (build 2340) generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:643) ~[patched_1.17.1.jar:git-Paper-85]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:160) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:289) ~[?:?]
	at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:234) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:638) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:169) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.NMSImpl.playerTick(NMSImpl.java:978) ~[?:?]
	at net.citizensnpcs.util.NMS.playerTick(NMS.java:432) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-85]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-85]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[15:43:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1568) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-85]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:643) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:323) ~[?:?]
	at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:268) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2397) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.PlayerlistTracker.updatePlayer(PlayerlistTracker.java:55) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2308) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:2053) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:2074) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:881) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:752) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:594) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[patched_1.17.1.jar:git-Paper-85]
	... 5 more
[15:43:36] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.clone()" because the return value of "java.util.Map$Entry.getValue()" is null
	at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:397) ~[?:?]
	at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:652) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.world.item.ItemStack.copy(ItemStack.java:643) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.level.ServerEntity.a(ServerEntity.java:323) ~[?:?]
	at net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:268) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:2397) ~[?:?]
	at net.citizensnpcs.nms.v1_17_R1.util.PlayerlistTracker.updatePlayer(PlayerlistTracker.java:55) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:2308) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:2053) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:2074) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:881) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:752) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:594) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-85]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-85]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/issues/2594#issuecomment-874941949
