### ISSUE TITLE
Error on 1.17.1 and half the NPCs are gone

### ISSUE THREAD

**Issue by Castiella** [CitizensDev/Citizens2#2598]
[14:01:25 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy@16d24226[
    a=[1392]
  ]

[14:01:26 WARN]: java.lang.reflect.InvocationTargetException
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:01:26 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[14:01:26 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[14:01:26 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:48)
[14:01:26 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[14:01:26 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[14:01:26 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[14:01:26 WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[14:01:26 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[14:01:26 WARN]:        at net.citizensnpcs.Citizens.reload(Citizens.java:387)
[14:01:26 WARN]:        at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:57)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:01:26 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[14:01:26 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[14:01:26 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[14:01:26 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[14:01:26 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[14:01:26 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:01:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:01:26 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[14:01:26 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2243)
[14:01:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[14:01:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2035)
[14:01:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:01:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:01:26 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[14:01:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:01:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[14:01:26 WARN]: Caused by: java.lang.NoSuchFieldError: bO
[14:01:26 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.CowController$EntityCowNPC.<init>(CowController.java:63)
[14:01:26 WARN]:        ... 43 more
[14:01:26 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.setLocation(double, double, double, float, float)" because "entity" is null
[14:01:26 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:34)
[14:01:26 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[14:01:26 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[14:01:26 WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[14:01:26 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[14:01:26 WARN]:        at net.citizensnpcs.Citizens.reload(Citizens.java:387)
[14:01:26 WARN]:        at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:57)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[14:01:26 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:01:26 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[14:01:26 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[14:01:26 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[14:01:26 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[14:01:26 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[14:01:26 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:01:26 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:01:26 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[14:01:26 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2243)
[14:01:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[14:01:26 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2035)
[14:01:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:01:26 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:01:26 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[14:01:26 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378)
[14:01:26 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265)
[14:01:26 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:01:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/issues/2594#issuecomment-874941949
