### ISSUE TITLE
[1.8.8]Citizens cause bungee scoreboard Team error

### ISSUE THREAD

**Issue by john180** [CitizensDev/Citizens2#2600]
`java.lang.IllegalArgumentException: Team CIT-e03c35f19ff1 already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
    at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:190)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:122)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)`

This problem may caused by this  PR #2544
When set `player-scoreboard-teams` to False, Everything is back to normal

- Plugin Version: 2.0.28-SNAPSHOT (build 2346)
- Server Version: spigot-1.8.8

**Comment by mcmonkey4eva** [comment]
Is this still an issue on current versions?
If so, can you please post the full `logs/latest.log` from the Spigot server with the NPCs on it, and also the relevant Bungee server?

**Comment by Ceddix** [comment]
Since one of the latest commits (probably 5dbc578fd20d0e0c5704e8272ba15fe8d1aa6865), a similar error seems to occur.
I get following error in my proxy console, when a player get near a NPC:
```
java.lang.IllegalArgumentException: Team CIT-98937821eb85 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:248) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mcmonkey4eva** [comment]
@Ceddix please post your own issue rather than bumping up this very old one
