### ISSUE TITLE
Citizen loading error in saves.yml

### ISSUE THREAD

**Issue by Perdume** [CitizensDev/Citizens2#2606]
The output of command `/version` on my server is: **Paper version git-Paper-91 (MC: 1.17.1)**
The output of command `/version citizens` on my server is: **2.0.28-SNAPSHOT (build 2345)**                                                     

```
https://github.com/CitizensDev/Citizens2/issues[02:34:36 WARN]: java.lang.reflect.InvocationTargetException
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[02:34:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[02:34:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[02:34:36 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:48)
[02:34:36 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[02:34:36 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[02:34:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[02:34:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[02:34:36 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[02:34:36 WARN]:        at net.citizensnpcs.Citizens.reload(Citizens.java:387)
[02:34:36 WARN]:        at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:57)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:34:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[02:34:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[02:34:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[02:34:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[02:34:36 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[02:34:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:34:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:34:36 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[02:34:36 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2165)
[02:34:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1976)
[02:34:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957)
[02:34:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[02:34:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[02:34:36 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[02:34:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:34:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[02:34:36 WARN]: Caused by: java.lang.NoSuchFieldError: bO
[02:34:36 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.VillagerController$EntityVillagerNPC.<init>(VillagerController.java:61)
[02:34:36 WARN]:        ... 43 more
[02:34:36 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.setLocation(double, double, double, float, float)" because "entity" is null
[02:34:36 WARN]:        at net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:34)
[02:34:36 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[02:34:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[02:34:36 WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:159)
[02:34:36 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[02:34:36 WARN]:        at net.citizensnpcs.Citizens.reload(Citizens.java:387)
[02:34:36 WARN]:        at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:57)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[02:34:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:34:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[02:34:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[02:34:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[02:34:36 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[02:34:36 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[02:34:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:34:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:34:36 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[02:34:36 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2165)
[02:34:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1976)
[02:34:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957)
[02:34:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[02:34:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[02:34:36 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[02:34:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[02:34:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[02:34:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:34:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by mcmonkey4eva** [comment]
Update https://ci.citizensnpcs.co/job/Citizens2/
