### ISSUE TITLE
IllegalStateException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#2609]
Relevant versions: 
```
>version
[10:14:04] [Server thread/INFO]: This server is running CraftBukkit version 3180-Spigot-38e6c03-ca0fe5b (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[10:14:04] [Server thread/INFO]: You are running the latest version
>version citizens
[10:14:34] [Server thread/INFO]: Citizens version 2.0.28-SNAPSHOT (build 2350)
[10:14:34] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[10:14:34] [Server thread/INFO]: Author: fullwall
>version denizen
[10:15:30] [Server thread/INFO]: Denizen version 1.2.1-SNAPSHOT (build 5662-DEV)
[10:15:30] [Server thread/INFO]: Author: The DenizenScript Team
```
The only change to the server was update of Citizens from b2349. Note that I was not trying to disable Citizens. Reverting to Citizens b2349 removed the issue.

On server startup, this occurs several times a second
```
[08:08:25] [Server thread/INFO]: [Citizens] Could not fetch NMS field classes: [[classes.
[08:08:25] [Server thread/INFO]: [Citizens] Could not fetch NMS field classes: [[null.
[08:08:25] [Server thread/WARN]: [Denizen] Task #93 for Denizen v1.2.1-SNAPSHOT (build 5662-DEV) generated an exception
java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:79) ~[?:?]
        at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:111) ~[?:?]
        at com.denizenscript.denizen.scripts.triggers.core.ProximityTrigger.lambda$onEnable$0(ProximityTrigger.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
followed eventually by
```
[08:25:08] [Server thread/ERROR]: Could not pass event PluginDisableEvent to Citizens v2.0.28-SNAPSHOT (build 2350)
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.Lenni0451.SpigotPluginManager.utils.PluginUtils.disablePlugin(PluginUtils.java:128) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.commands.subs.Disable_Sub.execute(Disable_Sub.java:42) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:89) ~[?:?]
        at net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.onCommand(PluginManager_Command.java:104) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:726) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at ch.njol.skript.Skript.dispatchCommand(Skript.java:1414) ~[?:?]
        at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:82) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:51) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88) ~[?:?]
        at ch.njol.skript.effects.Delay$1.run(Delay.java:108) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:79) ~[?:?]
        at net.citizensnpcs.api.CitizensAPI.getPlugin(CitizensAPI.java:118) ~[?:?]
        at net.citizensnpcs.EventListen.onDisable(EventListen.java:249) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1-3180.jar:3180-Spigot-38e6c03-ca0fe5b]
        ... 27 more

```

**Comment by mcmonkey4eva** [comment]
`net.Lenni0451.SpigotPluginManager.commands.PluginManager_Command.`

Never ever ever use plugin managers. They break stuff. This is an inevitable result.

**Comment by SlimeDog** [comment]
PluginManager is installed, for testing, but rarely used, and certainly not in this case. It did not cause an issue with any previous version of Citizens.

**Comment by SlimeDog** [comment]
With PluginManager uninstalled, the Denizen/CitizensAPI issue remains. Reposted [here](https://github.com/DenizenScript/Denizen/issues/2279).

**Comment by mcmonkey4eva** [comment]
Need a full server log, not just snippets.

**Comment by SlimeDog** [comment]
http://blackdog.straight8.com/drops/citizens-2609.txt

**Comment by mcmonkey4eva** [comment]
Line 2258 in your log:
```
[10:42:34] [Server thread/INFO]: [DelayJoin] Disabling DelayJoin v1.0-SNAPSHOT
[10:42:34] [Server thread/INFO]: [Citizens] Could not fetch NMS field classes: [[classes.
[10:42:34] [Server thread/INFO]: [Citizens] Could not fetch NMS field classes: [[null.
```

You have a plugin breaking / disabling itself, this causes Citizens to disable itself as well - which is a workaround for https://hub.spigotmc.org/jira/browse/SPIGOT-6621

Your options for now are:
A: Run an older Citizens build, noting that save data will go missing due to that bug.
B: Run a Spigot/Paper 1.16.5 from before May 14th
C: Remove, fix, or replace DelayJoin (and any other plugins that break like that)

Those are only needed until the workaround is improved (we have things we intend to tweak on that to reduce the chances of error-induced shutdowns looking like server shutdowns) or until Spigot fixes the bug (might help to voice support on the linked Spigot issue)

**Comment by SlimeDog** [comment]
DelayJoin disabling itself at that point is a feature.

DelayJoin does not depend on CitizensAPI. A completely unassociated plugin disabling itself should not cause CitizensAPI to go belly up. I have reverted our servers to Citizens 2.0.28-b2349 until this issue is resolved.
