### ISSUE TITLE
Couldn't look up profile properties

### ISSUE THREAD

**Issue by nowik111414** [CitizensDev/Citizens2#261]
Please help me with this error. When I remove Citizens plugin it's everythink ok. 

My PLugins list: PlugMan, FrameProtect, VoxelSniper, LorinthsRpgMobs, mcore, Vault, Multiverse-Core, Character_Stats, TopPVP, AutoMessage, EnderPearlCoolDown, MultiMOTD, JukeLoop, Block-That-Command, ProtocolLib, EssentialsKitManager, HolographicDisplays, HigherSwordEnchantments, Citizens, WorldEdit, NoCheatPlus, FarmProtect, TagAPI, MultiKill, PermissionSigns, HealthCustomizer, ArcaneEnchants, PermissionsEx, BarAPI, Bounty, RpgParty, WorldGuard, BorderGuard, AntiAura, CloudTrade, Custom_Enchantments, CoreProtect, HigherArmorEnchantments, AntiXRay, MyPet, MCCore, ClearLag, Commander, EasyAntiSpam, AutoSaveWorld, Essentials, Quests, WarpPortals, MagicSpells, Shopkeepers, LogIt, MythicMobs, EssentialsChat, SimpleRegionMarket, EssentialsProtect, EssentialsSpawn, NameTags, EchoPet, EssentialsAntiBuild, Factions, PvPManager

[08:49:06] [pool-3-thread-148/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@1096c3b5[id=2d854cc5-8e0d-4368-8b09-aa0e7c3241fa,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-139/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@1a0aa895[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-33/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@44f14e61[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-24/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@31c1db8e[id=2d854cc5-8e0d-4368-8b09-aa0e7c3241fa,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-134/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@31d2fca3[id=d553fb71-48ab-4d0a-bb2d-2eaae5aef5f0,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-128/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@64e400ef[id=d553fb71-48ab-4d0a-bb2d-2eaae5aef5f0,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-138/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@34f97ea8[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-135/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@353dfe48[id=5fffe751-dd29-4f86-bc2e-c2293d957857,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-144/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@3c4f6d32[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-120/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@3617d045[id=5fffe751-dd29-4f86-bc2e-c2293d957857,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-143/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@556a7dc1[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-131/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@426635b6[id=5fffe751-dd29-4f86-bc2e-c2293d957857,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-121/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@445061c8[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
[08:49:06] [pool-3-thread-140/WARN]: Couldn't look up profile properties for net.minecraft.util.com.mojang.authlib.GameProfile@7943b481[id=603e0d8a-f989-4803-b93b-bac2bbc1cb62,name=,properties={},legacy=false]
net.minecraft.util.com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.minecraft.util.com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher.run(HumanController.java:117) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [craftbukkit-beta-1.7.9.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by mcmonkey4eva** [comment]
Update your server, 1.8 is out already mate.

**Comment by nowik111414** [comment]
I use 1.7.9 Ro.1 plugin and I had a 1.7.9 Ro.2 Server.

Maybe problem is whit this line.
Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes

Please, help me I had 60 plugins and I'ill need update/remove all to get new server version.

**Comment by mcmonkey4eva** [comment]
This bug is only fixed by updating, sorry.
