### ISSUE TITLE
Server Crash org.bukkit.Location.checkFinite

### ISSUE THREAD

**Issue by oloflarsson** [CitizensDev/Citizens2#265]
Original Spigot Issue: https://hub.spigotmc.org/jira/browse/SPIGOT-621

```
---- Minecraft Crash Report ----
// Who set us up the TNT?
 
Time: 2/25/15 5:31 PM
Description: Ticking entity
 
java.lang.IllegalArgumentException: yaw must be finite
        at org.bukkit.Location.checkFiniteFloat(Location.java:613)
        at org.bukkit.Location.setYaw(Location.java:191)
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.getLocation(CraftEntity.java:193)
        at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:273)
        at net.citizensnpcs.npc.entity.EntityHumanNPC.s_(EntityHumanNPC.java:216)
        at net.minecraft.server.v1_8_R1.Entity.ak(Entity.java:1454)
        at net.minecraft.server.v1_8_R1.EntityLiving.ak(EntityLiving.java:1717)
        at net.minecraft.server.v1_8_R1.EntityHuman.ak(EntityHuman.java:356)
        at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1601)
        at net.minecraft.server.v1_8_R1.World.g(World.java:1578)
        at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1648)
        at net.minecraft.server.v1_8_R1.World.g(World.java:1578)
        at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1421)
        at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576)
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcmonkey4eva** [comment]
How in space did you manage to set the yaw to `infinity`?!
