### ISSUE TITLE
IllegalPluginAccessException on server shutdown

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#2653]
The output of command `/version` on my server is: 
```
>version
[09:02:20] [Server thread/INFO]: This server is running CraftBukkit version 3241-Spigot-6c1c1b2-1492826 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[09:02:20] [Server thread/INFO]: You are running the latest version
```
The output of command `/version citizens` on my server is: 
```
>version Citizens
[09:03:02] [Server thread/INFO]: Citizens version 2.0.28-SNAPSHOT (build 2369)
[09:03:02] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[09:03:02] [Server thread/INFO]: Author: fullwall
>version Sentinel
[09:03:29] [Server thread/INFO]: Sentinel version 2.3.5-SNAPSHOT (build 431)
[09:03:29] [Server thread/INFO]: Author: mcmonkey
```

Citizens/Sentinel log entries
```
[08:57:08] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.28-SNAPSHOT (build 2369)
[08:57:08] [Server thread/INFO]: [Sentinel] Loading Sentinel v2.3.5-SNAPSHOT (build 431)
[08:58:15] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.28-SNAPSHOT (build 2369)
[08:58:16] [Server thread/INFO]: [Sentinel] Enabling Sentinel v2.3.5-SNAPSHOT (build 431)
[08:58:16] [Server thread/INFO]: [Sentinel] Sentinel loading...
[08:58:16] [Server thread/INFO]: [Sentinel] Running on java version: 16.0.2
[08:58:16] [Server thread/INFO]: [Sentinel] Vault linked! Group targets will work.
[08:58:16] [Server thread/INFO]: [Sentinel] Sentinel found WorldGuard! Adding support for it!
[08:58:16] [Server thread/INFO]: [Sentinel] Sentinel loaded!
[09:00:46] [Server thread/INFO]: [Citizens] Loaded 32 NPCs.
...
[09:04:43] [Server thread/INFO]: [Sentinel] Disabling Sentinel v2.3.5-SNAPSHOT (build 431)
[09:04:43] [Server thread/INFO]: [Sentinel] Sentinel unloading...
[09:04:43] [Server thread/INFO]: [Sentinel] Sentinel unloaded!
[09:04:43] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.28-SNAPSHOT (build 2369)
[09:04:43] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[09:04:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:468)
[09:04:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:196)
[09:04:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:187)
[09:04:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:182)
[09:04:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:146)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:323)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:365)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.onDespawn(CitizensNavigator.java:143)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:92)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.despawnNPCs(CitizensNPCRegistry.java:108)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.Citizens.despawnNPCs(Citizens.java:146)
[09:04:43] [Server thread/WARN]:        at net.citizensnpcs.Citizens.onDisable(Citizens.java:292)
[09:04:43] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[09:04:43] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367)
[09:04:43] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501)
[09:04:43] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493)
[09:04:43] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.disablePlugins(CraftServer.java:445)
[09:04:43] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.stop(MinecraftServer.java:917)
[09:04:43] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.stop(DedicatedServer.java:733)
[09:04:43] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1094)
[09:04:43] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[09:04:43] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
Same with
> git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)

**Comment by mcmonkey4eva** [comment]
This error was introduced by https://github.com/CitizensDev/Citizens2/commit/79526003822d8a1cbae51c250341b2addac9a2fe#diff-4abd21f4b81f8f282be660699153ff3684a2fed11624ccbfc8564fb23d5dc2f5R323

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/Citizens2/commit/004c46ab7656094cd5438a1c8da17f7b1f6f46a9 for build 2372+ from https://ci.citizensnpcs.co/job/Citizens2/

**Comment by SlimeDog** [comment]
Confirmed fix in b2372. Thanks.
