### ISSUE TITLE
NoSuchMethodError on older MC versions

### ISSUE THREAD

**Issue by Wruczek** [CitizensDev/Citizens2#2655]
Since commit 79526003822d8a1cbae51c250341b2addac9a2fe Citizens use the chunk ticketing API, which is only available since MC 1.14.3.
Because of that, running latest build on older MC versions throws
```
java.lang.NoSuchMethodError: org.bukkit.Chunk.removePluginChunkTicket(Lorg/bukkit/plugin/Plugin;)Z
        at net.citizensnpcs.npc.ai.CitizensNavigator.updateTicket(CitizensNavigator.java:454) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.access$200(CitizensNavigator.java:42) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator$4.run(CitizensNavigator.java:326) ~[?:?]
```

Tested `Citizens v2.0.28-SNAPSHOT (build 2370)` on `PaperSpigot 1.8.8 (4c7641d)`

**Comment by mcmonkey4eva** [comment]
Fixed via https://github.com/CitizensDev/Citizens2/commit/cffb0519e0282911d1bf2aafcf8eae239ecc1f98 for Citizens build 2371+ from https://ci.citizensnpcs.co/job/Citizens2/
