### ISSUE TITLE
Error with npc type

### ISSUE THREAD

**Issue by FBDKPlus** [CitizensDev/Citizens2#2687]
### `/version` output

```txt
[11:33:01] [Server thread/INFO]: --------------------------------------------------
[11:33:01] [Server thread/INFO]: CMI 插件版本: 9.0.6.1 SqLite-> 9.0.6.2
[11:33:01] [Server thread/INFO]: CMILib: 1.0.4.2 
[11:33:01] [Server thread/INFO]: Server: Paper(373) 1.17.1-R0.1-SNAPSHOT
[11:33:01] [Server thread/INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled 
[11:33:01] [Server thread/INFO]: Modules -> 55 enabled 1 disabled: votifier
[11:33:01] [Server thread/INFO]: --------------------------------------------------
```

### `/version Citizens` output

```txt
[11:32:33] [Server thread/INFO]: =====[ Citizens v2.0.28-SNAPSHOT (build 2337) ]=====
[11:32:33] [Server thread/INFO]:      -- Author: fullwall
[11:32:33] [Server thread/INFO]:      -- Source Code: http://github.com/CitizensDev
[11:32:33] [Server thread/INFO]:      -- Website: http://www.citizensnpcs.co
[11:32:33] [Server thread/INFO]:      -- Report an issue: http://github.com/CitizensDev/Citizens2/issues
```

### Log file

https://paste.denizenscript.com/View/89772

### config.yml

https://paste.denizenscript.com/View/89773

### saves.yml

https://paste.denizenscript.com/View/89774

### Description

error with /npc type 

[11:28:19] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[11:28:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:28:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[11:28:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:28:19] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[11:28:19] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:48)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.commands.NPCCommands.tphere(NPCCommands.java:2341)
[11:28:19] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
[11:28:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:28:19] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[11:28:19] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:28:19] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:28:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1423)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1401)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1394)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1533)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1279)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:28:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[11:28:19] [Server thread/WARN]: Caused by: java.lang.NoSuchFieldError: bO
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.nms.v1_17_R1.entity.VexController$EntityVexNPC.<init>(VexController.java:47)
[11:28:19] [Server thread/WARN]: 	... 39 more
[11:28:19] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.setLocation(double, double, double, float, float)" because "<local4>" is null
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.nms.v1_17_R1.entity.MobEntityController.createEntity(MobEntityController.java:34)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:254)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.commands.NPCCommands.tphere(NPCCommands.java:2341)
[11:28:19] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
[11:28:19] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:28:19] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[11:28:19] [Server thread/WARN]: 	at Citizens.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:275)
[11:28:19] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:28:19] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:28:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2262)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2073)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2054)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1423)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1401)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1394)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1533)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1279)
[11:28:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:28:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by BehrRiley** [comment]
You're running a build of Citizens that is 61 versions behind.


Latest **Citizens** dev builds are at https://ci.citizensnpcs.co/job/Citizens2/.

Spigot releases of Citizens are available at https://www.spigotmc.org/resources/citizens.13811/.

After updating, pasting a full startup log would likely help better than a snippet of console output if you could provide that instead if the issue persists please

**Comment by BehrRiley** [comment]
I failed to mention you're also behind on your Paper version, you may benefit from updating that as well.

Latest **Paper** builds are at https://papermc.io/downloads.

**Comment by FBDKPlus** [comment]
thanks , but i don't know https://ci.citizensnpcs.co/job/Citizens2/. before ture

**Comment by FBDKPlus** [comment]
i only know in spigot download...
