### ISSUE TITLE
Villager NPC with no profession doesn't work with /npc villager --profession, works with /npc profession

### ISSUE THREAD

**Issue by WillFP** [CitizensDev/Citizens2#2692]
### `/version` output

```txt
[23:07:48 INFO]: This server is running Purpur version git-Purpur-1427 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bb5a93 on ver/1.17.1)
[23:07:48 INFO]: Previous version: git-Paper-388 (MC: 1.17.1)
```

### `/version Citizens` output

```txt
[23:07:57 INFO]: Citizens version 2.0.28-SNAPSHOT (build 2404)
[23:07:57 INFO]: Website: http://www.citizensnpcs.co
[23:07:57 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/90273

### config.yml

https://paste.denizenscript.com/View/90275

### saves.yml

https://paste.denizenscript.com/View/90276

### Description

When spawning a new Villager NPC, setting it's profession with `/npc villager profession` creates a stacktrace:
```
[23:02:27 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
[23:02:27 WARN]:        at Citizens-2.0.28-b2404.jar//net.citizensnpcs.api.command.CommandContext.getString(CommandContext.java:242)
[23:02:27 WARN]:        at Citizens-2.0.28-b2404.jar//net.citizensnpcs.nms.v1_17_R1.trait.Commands.villager(Commands.java:593)
[23:02:27 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:02:27 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[23:02:27 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:02:27 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[23:02:27 WARN]:        at Citizens-2.0.28-b2404.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[23:02:27 WARN]:        at Citizens-2.0.28-b2404.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[23:02:27 WARN]:        at Citizens-2.0.28-b2404.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[23:02:27 WARN]:        at Citizens-2.0.28-b2404.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:277)
[23:02:27 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:02:27 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[23:02:27 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[23:02:27 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2344)
[23:02:27 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2155)
[23:02:27 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2136)
[23:02:27 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[23:02:27 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[23:02:27 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[23:02:27 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
```

But /npc profession works fine. After setting the profession with `/npc profession` it works fine

**Comment by mcmonkey4eva** [comment]
Fixed by https://github.com/CitizensDev/Citizens2/commit/3da3cc2ae87c030ace003aad64c90bfdd9154329 for Citizens build 2406+ from https://ci.citizensnpcs.co/job/Citizens2/
