### ISSUE TITLE
Task #337 generated an exception

### ISSUE THREAD

**Issue by draexo** [CitizensDev/Citizens2#2704]
WARN20:43:54
[Citizens]: Task #337 for Citizens v2.0.29-SNAPSHOT (build 2420) generated an exception
Console20:43:54
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.ai.navigation.NavigationAbstract.l()'
at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.isNavigationFinished(NMSImpl.java:1676) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.nms.v1_18_R1.util.PlayerLookControl.a(PlayerLookControl.java:25) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.updateAI(EntityHumanNPC.java:507) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.updateAI(NMSImpl.java:1842) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.l(EntityHumanNPC.java:191) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.playerTick(NMSImpl.java:977) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.util.NMS.playerTick(NMS.java:450) ~[Citizens20.29alpha.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[Citizens20.29alpha.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-66]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.jar:git-Paper-66]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.jar:git-Paper-66]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-66]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-66]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-66]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-66]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mcmonkey4eva** [comment]
that Citizens build is for 1.18.1, but your Paper build is 1.18
You need to downdate Citizens or update Paper
