### ISSUE TITLE
NPC with the type "player" is not rotating

### ISSUE THREAD

**Issue by Zzeyy** [CitizensDev/Citizens2#2726]
### `/version` output

```txt
[12:22:13 INFO]: This server is running Purpur version git-Purpur-1433 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 26e5f08 on HEAD)
[12:22:13 INFO]: You are running the latest version
[12:22:13 INFO]: Previous version: git-Purpur-1171 (MC: 1.16.5)
```

### `/version Citizens` output

```txt
[12:22:02 INFO]: Citizens version 2.0.29-SNAPSHOT (build 2447)
[12:22:02 INFO]: Website: http://www.citizensnpcs.co
[12:22:02 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/91984

### config.yml

https://paste.denizenscript.com/View/91982

### saves.yml

https://paste.denizenscript.com/View/91983

### Description

I'm reporting this WARN and possibly a bug.
What happens is that when I change the NPC's type to "player" or just create one,
the NPC won't rotate it's look to the closest player but instead this pops out.
This WARN message disappears after changing the type to anything else but "player".

[12:11:12 WARN]: [Citizens] Task #191 for Citizens v2.0.29-SNAPSHOT (build 2447) generated an exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.world.entity.ai.navigation.NavigationAbstract.l()'
        at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.isNavigationFinished(NMSImpl.java:1683) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.nms.v1_18_R1.util.PlayerLookControl.a(PlayerLookControl.java:25) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.updateAI(EntityHumanNPC.java:507) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.updateAI(NMSImpl.java:1849) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.l(EntityHumanNPC.java:192) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.playerTick(NMSImpl.java:984) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.util.NMS.playerTick(NMS.java:450) ~[Citizens-2.0.29-b2447.jar:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[Citizens-2.0.29-b2447.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.jar:git-Purpur-1433]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.jar:git-Purpur-1433]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1433]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
