### ISSUE TITLE
1.12.2 catserver report errors

### ISSUE THREAD

**Issue by Shiyuku** [CitizensDev/Citizens2#2741]
### `/version` output

```txt
[05:02:40] [Server thread/WARN]: [Citizens] Task #84 for Citizens v2.0.29-SNAPSHOT (build 2466) generated an exception
net.minecraft.util.ReportedException: Ticking player
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1185) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:601) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:882) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.pathfinding.PathFinder.func_186335_a(Lnet/minecraft/pathfinding/PathPoint;Lnet/minecraft/pathfinding/PathPoint;F)Lnet/minecraft/pathfinding/Path; from class net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:40) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:29) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.b2(PlayerNavigation.java:309) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.func_179680_a(PlayerNavigation.java:254) ~[?:?]
        at net.minecraft.pathfinding.PathNavigate.func_75488_a(PathNavigate.java:87) ~[ze.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.func_75492_a(PlayerNavigation.java:78) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:512) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:509) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$5.update(NMSImpl.java:582) ~[?:?]
        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:78) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:367) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.func_70071_h_(EntityHumanNPC.java:142) ~[?:?]
        at net.minecraft.world.World.func_72866_a(World.java:2307) ~[amu.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1179) ~[?:?]
        ... 9 more
```

### `/version Citizens` output

```txt
[05:02:40] [Server thread/WARN]: [Citizens] Task #84 for Citizens v2.0.29-SNAPSHOT (build 2466) generated an exception
net.minecraft.util.ReportedException: Ticking player
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1185) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:601) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:882) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.pathfinding.PathFinder.func_186335_a(Lnet/minecraft/pathfinding/PathPoint;Lnet/minecraft/pathfinding/PathPoint;F)Lnet/minecraft/pathfinding/Path; from class net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:40) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:29) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.b2(PlayerNavigation.java:309) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.func_179680_a(PlayerNavigation.java:254) ~[?:?]
        at net.minecraft.pathfinding.PathNavigate.func_75488_a(PathNavigate.java:87) ~[ze.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.func_75492_a(PlayerNavigation.java:78) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:512) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:509) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$5.update(NMSImpl.java:582) ~[?:?]
        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:78) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:367) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.func_70071_h_(EntityHumanNPC.java:142) ~[?:?]
        at net.minecraft.world.World.func_72866_a(World.java:2307) ~[amu.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1179) ~[?:?]
        ... 9 more
```

### Log file

https://paste.denizenscript.com/View/93421

### config.yml

https://paste.denizenscript.com/View/93421

### saves.yml

https://paste.denizenscript.com/View/93421

### Description

[05:02:40] [Server thread/WARN]: [Citizens] Task #84 for Citizens v2.0.29-SNAPSHOT (build 2466) generated an exception
net.minecraft.util.ReportedException: Ticking player
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1185) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:601) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:39) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:882) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.pathfinding.PathFinder.func_186335_a(Lnet/minecraft/pathfinding/PathPoint;Lnet/minecraft/pathfinding/PathPoint;F)Lnet/minecraft/pathfinding/Path; from class net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:40) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerPathfinder.a(PlayerPathfinder.java:29) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.b2(PlayerNavigation.java:309) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.func_179680_a(PlayerNavigation.java:254) ~[?:?]
        at net.minecraft.pathfinding.PathNavigate.func_75488_a(PathNavigate.java:87) ~[ze.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.PlayerNavigation.func_75492_a(PlayerNavigation.java:78) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:512) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$4.apply(NMSImpl.java:509) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl$5.update(NMSImpl.java:582) ~[?:?]
        at net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:78) ~[?:?]
        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:172) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:367) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.func_70071_h_(EntityHumanNPC.java:142) ~[?:?]
        at net.minecraft.world.World.func_72866_a(World.java:2307) ~[amu.class:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1179) ~[?:?]
        ... 9 more

**Comment by mcmonkey4eva** [comment]
Citizens only supports Spigot and forks thereof like Paper. Forge is entirely unsupported.
