### ISSUE TITLE
Error thown on NachoSpigot

### ISSUE THREAD

**Issue by HowardZHY** [CitizensDev/Citizens2#2743]
### `/version` output

```txt
[00:55:26] [Thread-12/INFO]: This server is running NachoSpigot version git-NachoSpigot-"3f69c24" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[0;32;1mYou are running the latest version[m
```

### `/version Citizens` output

```txt
[00:55:38] [Server thread/INFO]: [0;32;1mCitizens[0;37;1m version [0;32;1m2.0.29-SNAPSHOT (build 2462)[m
```

### Log file

https://paste.denizenscript.com/View/93549

### config.yml

https://paste.denizenscript.com/View/93550

### saves.yml

https://paste.denizenscript.com/View/93551

### Profiler report

null

### Description

This error throws on server startup and sometimes randomly appears.
PS: There's 2 other bugs on Taco , Nacho and BurritoSpigot , most npc won't force chunks to load on server startup ,and NPCs(Sentinel) cannot respawn in certain places , they just respawn at the place they died.
I'm not sure these 2 bugs are related with this error , there's no console error on Taco and Burrito.

[00:55:20] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.server.v1_8_R3.ReportedException: Adding entity to track
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:141) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:64) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.World.a(World.java:1298) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1002) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.World.b(World.java:3041) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:985) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:17) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:162) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:125) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:150) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:96) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:624) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.Location.getBlock(Location.java:87) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.citizensnpcs.nms.v1_8_R3.entity.MobEntityController.createEntity(MobEntityController.java:34) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:255) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:160) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [Citizens-2.0.29-b2462.jar:?]
	at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:510) [Citizens-2.0.29-b2462.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:794) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617) [NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(EntityTracker.java:106) ~[NachoSpigot.jar:git-NachoSpigot-"3f69c24"]
	... 30 more

**Comment by fullwall** [comment]
Don't have the full error

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
