### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by HowardZHY** [CitizensDev/Citizens2#2744]
### `/version` output

```txt
[21:00:07] [Thread-15/INFO]: This server is running NachoSpigot version git-NachoSpigot-"3f69c24" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[0;32;1mYou are running the latest version[m
```

### `/version Citizens` output

```txt
[21:00:10] [Server thread/INFO]: [0;32;1mCitizens[0;37;1m version [0;32;1m2.0.29-SNAPSHOT (build 2478)[m
```

### Log file

https://paste.denizenscript.com/View/93566

### config.yml

https://paste.denizenscript.com/View/93567

### saves.yml

https://paste.denizenscript.com/View/93568

### Profiler report

null

### Description

When I upgraded citizens from b2462 to latest , messages like this
[21:00:00] [Server thread/INFO]: [Citizens] 更新时发生异常 7: null.
[21:00:00] [Server thread/WARN]: java.lang.UnsupportedOperationException
[21:00:00] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_8_R3.util.PlayerAnimationImpl.play(PlayerAnimationImpl.java:102)
[21:00:00] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.playAnimation(NMSImpl.java:736)
[21:00:00] [Server thread/WARN]: 	at net.citizensnpcs.util.NMS.playAnimation(NMS.java:461)
[21:00:00] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.updateUsingItemState(CitizensNPC.java:481)
[21:00:00] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:410)
[21:00:00] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_8_R3.entity.EntityHumanNPC.t_(EntityHumanNPC.java:405)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1887)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.g(World.java:1854)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1678)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:602)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
[21:00:00] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:617)
[21:00:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
was spamming when player join , the original log was too big to open , this latest log was tested with no player.
PS: Now I use online mode. I used offline just for building map and debug easily.

**Comment by mcmonkey4eva** [comment]
Join Discord to discuss your support-refusal due to running a cracked server - https://discord.gg/Q6pZGSR
