### ISSUE TITLE
NPE on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#2745]
```
>version
[10:03:23] [Server thread/INFO]: This server is running CraftBukkit version 3436-Spigot-699290c-1e87776 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[10:03:23] [Server thread/INFO]: You are running the latest version
```
or
```
> version
[09:45:09 INFO]: This server is running Paper version git-Paper-204 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7b8e0c3)
You are running the latest version
```

```
> version Citizens
[10:02:35] [Server thread/INFO]: Citizens version 2.0.29-SNAPSHOT (build 2480)
[10:02:35] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[10:02:35] [Server thread/INFO]: Author: fullwall
```
and every build since 2473. Build 2471 and previous are fine. No changes to configuration. Reverting to build 2471 works fine.

### Log file

https://paste.denizenscript.com/View/93578

### config.yml

https://paste.denizenscript.com/View/93579

### saves.yml

https://paste.denizenscript.com/View/93580

### Description

On server start-up, every second yields console/log error
```
[09:58:32 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
[09:58:32 WARN]:        at java.base/sun.invoke.util.ValueConversions.unboxBoolean(ValueConversions.java:108)
[09:58:32 WARN]:        at Citizens-2.0.29-b2480.jar//net.citizensnpcs.nms.v1_18_R1.util.NMSImpl.setNoGravity(NMSImpl.java:1217)
[09:58:32 WARN]:        at Citizens-2.0.29-b2480.jar//net.citizensnpcs.util.NMS.setNoGravity(NMS.java:542)
[09:58:32 WARN]:        at Citizens-2.0.29-b2480.jar//net.citizensnpcs.trait.Gravity.run(Gravity.java:38)
[09:58:32 WARN]:        at Citizens-2.0.29-b2480.jar//net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:496)
[09:58:32 WARN]:        at Citizens-2.0.29-b2480.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:361)
[09:58:32 WARN]:        at Citizens-2.0.29-b2480.jar//net.citizensnpcs.nms.v1_18_R1.entity.ParrotController$EntityParrotNPC.R(ParrotController.java:82)
[09:58:32 WARN]:        at net.minecraft.world.entity.EntityInsentient.eE(EntityInsentient.java:865)
[09:58:32 WARN]:        at net.minecraft.world.entity.EntityLiving.w_(EntityLiving.java:3264)
[09:58:32 WARN]:        at net.minecraft.world.entity.EntityInsentient.w_(EntityInsentient.java:628)
[09:58:32 WARN]:        at net.minecraft.world.entity.EntityAgeable.w_(EntityAgeable.java:154)
[09:58:32 WARN]:        at net.minecraft.world.entity.animal.EntityAnimal.w_(EntityAnimal.java:63)
[09:58:32 WARN]:        at net.minecraft.world.entity.animal.EntityParrot.w_(EntityParrot.java:193)
[09:58:32 WARN]:        at net.minecraft.world.entity.EntityLiving.k(EntityLiving.java:2914)
[09:58:32 WARN]:        at net.minecraft.world.entity.EntityInsentient.k(EntityInsentient.java:396)
[09:58:32 WARN]:        at net.minecraft.world.entity.animal.EntityPerchable.k(EntityPerchable.java:35)
[09:58:32 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1131)
[09:58:32 WARN]:        at net.minecraft.world.level.World.a(World.java:974)
[09:58:32 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:670)
[09:58:32 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
[09:58:32 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:650)
[09:58:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1608)
[09:58:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[09:58:32 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1471)
[09:58:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[09:58:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[09:58:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by fullwall** [comment]
Fixed

**Comment by SlimeDog** [comment]
Confirmed fixed, Spigot and Paper, with b2481. Thanks.
