### ISSUE TITLE
error in console when clicking on npc

### ISSUE THREAD

**Issue by 1Pootis1** [CitizensDev/Citizens2#2803]
### `/version` output

```txt
paper 1.17.1 build 409
```

### `/version Citizens` output

```txt
Citizens-2.0.29-b2553
```

### Log file

https://paste.denizenscript.com/View/96974

### config.yml

https://paste.denizenscript.com/View/96975

### saves.yml

https://paste.denizenscript.com/View/96976

### Description

The error occurs when you right click on an NPC

[12:26:57] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.29-SNAPSHOT (build 2553)
java.lang.NullPointerException: name cannot be null
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895) ~[patched_1.17.1.jar:git-Paper-409]
    at net.citizensnpcs.npc.ai.speech.CitizensSpeechFactory.getVocalChord(CitizensSpeechFactory.java:35) ~[Citizens-2.0.29-b2553.jar:?]
    at net.citizensnpcs.api.ai.speech.SimpleSpeechController.speak(SimpleSpeechController.java:33) ~[Citizens-2.0.29-b2553.jar:?]
    at net.citizensnpcs.api.ai.speech.SimpleSpeechController.speak(SimpleSpeechController.java:23) ~[Citizens-2.0.29-b2553.jar:?]
    at net.citizensnpcs.trait.text.Text.sendText(Text.java:263) ~[Citizens-2.0.29-b2553.jar:?]
    at net.citizensnpcs.trait.text.Text.onRightClick(Text.java:165) ~[Citizens-2.0.29-b2553.jar:?]
    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-409]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-409]
    at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:492) ~[Citizens-2.0.29-b2553.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor71.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-409]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2427) ~[app:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onInteraction(ServerGamePacketListenerImpl.java:2477) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[app:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2419) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[app:?]
    at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[app:?]
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
    at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
    at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
