### ISSUE TITLE
InvocationTargetException on startup

### ISSUE THREAD

**Issue by Andre601** [CitizensDev/Citizens2#2809]
### `/version` output

```txt
[13:45:16 INFO]: This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
You are running the latest version
Previous version: git-Paper-318 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
[13:45:22 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2564)
[13:45:22 INFO]: Website: http://www.citizensnpcs.co
[13:45:22 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/97377

### config.yml

https://paste.denizenscript.com/View/97378

### saves.yml

https://paste.denizenscript.com/View/97379

### Description

During Startup is Citizens printing the following exception:

```
[13:43:54 INFO]: [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2564)
[13:43:55 WARN]: java.lang.reflect.InvocationTargetException
[13:43:55 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:43:55 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:43:55 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:43:55 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:43:55 WARN]:        at Citizens.jar//net.citizensnpcs.util.NMS.giveReflectiveAccess(NMS.java:403)
[13:43:55 WARN]:        at Citizens.jar//net.citizensnpcs.util.NMS.<clinit>(NMS.java:643)
[13:43:55 WARN]:        at Citizens.jar//net.citizensnpcs.Citizens.onEnable(Citizens.java:311)
[13:43:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:43:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:43:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[13:43:55 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[13:43:55 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[13:43:55 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[13:43:55 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[13:43:55 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[13:43:55 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
[13:43:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:43:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:43:55 WARN]: Caused by: java.lang.IllegalCallerException: java.lang.reflect is not open to unnamed module @46c5ba7
[13:43:55 WARN]:        at java.base/java.lang.Module.addOpens(Module.java:836)
[13:43:55 WARN]:        ... 18 more
```

Since the latest update mentions 1.18.2 as supported version do I count this as a bug

**Comment by fullwall** [comment]
At present this isn't considered a bug, no.

**Comment by Andre601** [comment]
> At present this isn't considered a bug, no.

Would appreciate a bit more info. Why is this not considered a bug? What is the issue? How can this be fixed (IF it can be fixed)?
Just saying "Not considered a bug" and closing the issue is kind of rude...

**Comment by fullwall** [comment]
As part of updating to 1.19 I was experiencing some issues with reflection and added exception debugging (print only, this exception was already being caught). This particular exception is related to Java 16+ reflection and requires a JVM flag to clear. On testing Citizens was launching without needing this level of reflective access so for now I am monitoring. If you would like developer-level technical responses then please continue the discussion on Discord rather than Github.

**Comment by Andre601** [comment]
> As part of updating to 1.19 I was experiencing some issues with reflection and added exception debugging (print only, this exception was already being caught). This particular exception is related to Java 16+ reflection and requires a JVM flag to clear. On testing Citizens was launching without needing this level of reflective access so for now I am monitoring. If you would like developer-level technical responses then please continue the discussion on Discord rather than Github.

A simple "This was a debug message I accidentally left in the plugin" would've been enough here.

**Comment by fullwall** [comment]
That would not have been an accurate explanation.

**Comment by mcmonkey4eva** [comment]
It might be best to remain on https://ci.citizensnpcs.co/job/Citizens2/2559/ for 1.18.2 for a while to avoid any sides effects of the usual teething pains of the new Minecraft updates.
