### ISSUE TITLE
1.8 error

### ISSUE THREAD

**Issue by ProtoGhost** [CitizensDev/Citizens2#2834]
### `/version` output

```txt
[17:39:01 INFO]: This server is running CraftBukkit version git-PaperSpigot-2894af04d (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
[17:40:25 INFO]: Citizens version 2.0.27-SNAPSHOT (build 2191)
[17:40:25 INFO]: Website: http://www.citizensnpcs.co
[17:40:25 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/99342

### config.yml

https://paste.denizenscript.com/View/99343

### saves.yml

https://paste.denizenscript.com/View/99344

### Description

this error spamming in console

[17:43:31 ERROR]: [Citizens] An exception occurred while the trait profession was spawning for NPC ID 5.
[17:43:31 WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/ZombieVillager
[17:43:31 WARN]:        at net.citizensnpcs.trait.VillagerProfession.onSpawn(VillagerProfession.java:45)
[17:43:31 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:295)
[17:43:31 WARN]:        at net.citizensnpcs.EventListen.spawn(EventListen.java:714)
[17:43:31 WARN]:        at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:689)
[17:43:31 WARN]:        at net.citizensnpcs.EventListen.access$000(EventListen.java:107)
[17:43:31 WARN]:        at net.citizensnpcs.EventListen$1.run(EventListen.java:156)
[17:43:31 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[17:43:31 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[17:43:31 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[17:43:31 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[17:43:31 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[17:43:31 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[17:43:31 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by fullwall** [comment]
Fixed
