### ISSUE TITLE
Team already exists in this scoreboard

### ISSUE THREAD

**Issue by Ceddix** [CitizensDev/Citizens2#2835]
### `/version` output

```txt
Current: git-Purpur-1714 (MC: 1.19)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2632)
```

### Log file

https://paste.denizenscript.com/View/99379

### config.yml

https://pastebin.com/Yxg2zd5A

### saves.yml

https://pastebin.com/waFiuuq5

### Description

Since one of the latest commits (probably 5dbc578fd20d0e0c5704e8272ba15fe8d1aa6865), an error seems to occur.
I get following error in my **proxy console**, when a player gets near a NPC:
```
java.lang.IllegalArgumentException: Team CIT-98937821eb85 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:248) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by fullwall** [comment]
Update citizens.
