### ISSUE TITLE
Unable to spawn NPCs. Message told me to report it.

### ISSUE THREAD

**Issue by MichaelGaming12** [CitizensDev/Citizens2#2841]
[6:48:28 PM WARN] java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:162)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[6:48:28 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:546)
[6:48:28 PM WARN] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[6:48:28 PM WARN] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[6:48:28 PM WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1491)
[6:48:28 PM WARN] at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[6:48:28 PM WARN] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[6:48:28 PM WARN] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1188)
[6:48:28 PM WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[6:48:28 PM WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[6:48:28 PM WARN] [Citizens] Task #6567 for Citizens v2.0.30-SNAPSHOT (build 2657) generated an exception
[6:48:28 PM INFO] [Minecraft] [Multiverse-Inventories] First run!
[6:48:39 PM INFO] MichaelGaming12 issued server command: /npc create SMP
[6:48:39 PM WARN] java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
[6:48:39 PM WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[6:48:39 PM WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[6:48:39 PM WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[6:48:39 PM WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[6:48:39 PM WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[6:48:39 PM WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[6:48:39 PM WARN] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[6:48:39 PM WARN] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[6:48:39 PM WARN] at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[6:48:39 PM WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[6:48:39 PM WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[6:48:39 PM WARN] java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
[6:48:39 PM WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[6:48:39 PM WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[6:48:39 PM WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[6:48:39 PM WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[6:48:39 PM WARN] at Citizens-2.0.30-b2657.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[6:48:39 PM WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[6:48:39 PM WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[6:48:39 PM WARN] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[6:48:39 PM WARN] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[6:48:39 PM WARN] at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[6:48:39 PM WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[6:48:39 PM WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[6:48:39 PM WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[6:48:39 PM WARN] at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by fullwall** [comment]
Use the correct version for your server (build 2640 is the last build that supports 1.19.0)
