### ISSUE TITLE
Error while trying to create a new NPC

### ISSUE THREAD

**Issue by giorno420** [CitizensDev/Citizens2#2844]
### `/version` output

```txt
>version
[11:54:58] [Server thread/INFO]: This server is running CraftBukkit version 3553-Spigot-14a2382-ef09464 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
[11:54:58] [Server thread/INFO]: Checking version, please wait...
[11:54:59] [Thread-3062/INFO]: You are 7 version(s) behind
```

### `/version Citizens` output

```txt
>version citizens
[11:54:47] [Server thread/INFO]: Citizens version 2.0.30-SNAPSHOT (build 2660)
[11:54:47] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[11:54:47] [Server thread/INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/99765

### config.yml

https://paste.denizenscript.com/View/99766

### saves.yml

only has {} in it

### Description

While trying to do /npc create `npcname` i got an error, and after running the command the plugin send me this:
![image](https://user-images.githubusercontent.com/74859235/182841193-d5cb8756-c4a3-4929-b6bf-f2817f2ecd0e.png)

and spammed the console with this error:

```
TheGiorno issued server command: /npc2 create balls
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
at net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
at net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:831)
at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031)
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834)
at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37)
at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13)
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
at net.minecraft.server.TickTask.run(SourceFile:18)
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
at net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
at net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:831)
at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031)
at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834)
at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37)
at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13)
at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
at net.minecraft.server.TickTask.run(SourceFile:18)
at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LukasM-0812** [comment]
I have the same issue too.
![image](https://user-images.githubusercontent.com/110618911/182881471-8d22eb67-7b48-418a-bce0-2f1fe7bc3ccf.png)

**In console:**
`[14:49:23] [Server thread/INFO]: LukasM_0812 issued server command: /npc create LukasM_0812
[14:49:23] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
[14:49:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:49:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[14:49:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:49:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[14:49:23] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:49:23] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:49:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:831)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
[14:49:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:49:23] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:257)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
[14:49:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:49:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[14:49:23] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:49:23] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[14:49:23] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[14:49:23] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:49:23] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:49:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:831)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014)
[14:49:23] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
[14:49:23] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by mcmonkey4eva** [comment]
Update your server to 1.19.1, or downdate to the 1.19(.0) compatible build of Citizens: https://ci.citizensnpcs.co/job/Citizens2/2640/
