### ISSUE TITLE
Sheep Color & Cat Sitting Doesn't Work

### ISSUE THREAD

**Issue by whoshenry** [CitizensDev/Citizens2#286]
I try to do /npc sheep --color blue or any other color and nothing happens. Nothing in the console either.

Also when I try and make a Cat (ocelot) sit it doesn't work either.

**Comment by fullwall** [comment]
I think you may have entered in an incorrect color for /npc sheep. Can you try with the latest build? For the ocelot sitting, looks like there's an error in the bukkit API somewhere - still investigating.

**Comment by whoshenry** [comment]
Latest version, I get this - [07:45:51 INFO]: Henry issued server command: /npc sheep --color blue
[07:45:51 WARN]: java.lang.NullPointerException
[07:45:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftSheep.setColor(CraftSheep.java:21)
[07:45:51 WARN]:        at net.citizensnpcs.trait.SheepTrait.run(SheepTrait.java:38)
[07:45:51 WARN]:        at net.citizensnpcs.api.trait.Trait.isRunImplemented(Trait.java:38)
[07:45:51 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:111)
[07:45:51 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.getTrait(AbstractNPC.java:234)
[07:45:51 WARN]:        at net.citizensnpcs.commands.NPCCommands.sheep(NPCCommands.java:1204)
[07:45:51 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:45:51 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[07:45:51 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[07:45:51 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[07:45:51 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[07:45:51 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[07:45:51 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[07:45:51 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[07:45:51 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:45:51 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[07:45:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[07:45:51 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[07:45:51 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[07:45:51 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[07:45:51 WARN]:        at java.lang.Thread.run(Unknown Source)
>


But then when I do another color such as gray I get this - http://prntscr.com/6jvcog and the color doesn't change.

**Comment by mcmonkey4eva** [comment]
I fixed the sheep issue, excluding messages... the Ocelot issue appears to be a Bukkit-side issue.
