### ISSUE TITLE
1.19 Paper server error

### ISSUE THREAD

**Issue by apexfinity** [CitizensDev/Citizens2#2860]
yo, 
I'm running a paper server on 1.19 (not 1.19.2) and im getting this error

`[01:27:41 INFO]: apexfinity issued server command: /npc create mom
[01:27:41 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
[01:27:41 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:27:41 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:27:41 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:27:41 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[01:27:41 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:27:41 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:27:41 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[01:27:41 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[01:27:41 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[01:27:41 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[01:27:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:27:41 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:617)
[01:27:41 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:27:41 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[01:27:41 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:27:41 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[01:27:41 WARN]: 	at Citizens-2.0.30-b2665.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[01:27:41 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:27:41 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:27:41 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[01:27:41 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[01:27:41 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[01:27:41 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[01:27:41 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[01:27:41 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[01:27:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
​
`
I have installed Vault, and tried to follow a tutorial, but I keep getting this error.
Can you guys look into it?

Apexfinity

**Comment by YTJJGaming** [comment]
same issue here.

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2
