### ISSUE TITLE
NPC text editor is not working correctly since 19.2

### ISSUE THREAD

**Issue by Dave-Redisfa** [CitizensDev/Citizens2#2870]
Hello Citizens,

Since I built my 19.2 server I cannot use the in-game text editor for my npcs, of which I have almost 200. I can enter the editor, but cannot add or edit text. Attempting to do either often closes the window. In other cases nothing happens at all. I recall a similar issue some time ago, and an upgrade to the newest version fixed it. Unfortunately, I am on the newest build and it is simply not working as it used to,

There is a workaround, which requires going into the saves.yml file and editing it manually.  I do not believe I'm doing anything different than I have ever donw since the first 1.2.2 version of this server.

This is the most recent error throw:

 [Citizens] Plugin Citizens v2.0.30-SNAPSHOT (build 2673) generated an exception whilst handling conversation input
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at net.citizensnpcs.trait.text.TextBasePrompt.acceptInput(TextBasePrompt.java:35) ~[Citizens.jar:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1973) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$4.run(ServerGamePacketListenerImpl.java:2576) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BehrRiley** [comment]
Please properly use and fill out the **`Bug Report`** issue template.

**Comment by Dave-Redisfa** [comment]
No, I don't think I will. I'll just cope until you fix it.

**Comment by mcmonkey4eva** [comment]
If you don't like dealing with templates, general support is on Discord @ https://discord.gg/Q6pZGSR
