### ISSUE TITLE
Cant create npc

### ISSUE THREAD

**Issue by KB0720** [CitizensDev/Citizens2#2871]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2674)
```

### Log file

i dont have

### config.yml

https://paste.denizenscript.com/View/100885

### saves.yml

# Citizens NPC Storage  {} cant paste there

### Description

cant create npcs 
error:
[12:20:11 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:626)
[12:20:11 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:20:11 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[12:20:11 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:20:11 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[12:20:11 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:20:11 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[12:20:11 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[12:20:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[12:20:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[12:20:11 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[12:20:11 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:20:11 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:626)
[12:20:11 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:20:11 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[12:20:11 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:20:11 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[12:20:11 WARN]: 	at Citizens-2.0.30-b2674.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:305)
[12:20:11 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:20:11 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[12:20:11 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[12:20:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[12:20:11 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[12:20:11 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[12:20:11 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[12:20:11 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[12:20:11 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcmonkey4eva** [comment]
Update to 1.19.2

**Comment by KB0720** [comment]
> Update to 1.19.2

I want this version
