### ISSUE TITLE
NPE on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#2885]
### `/version` output

```txt
> version
[11:00:18 INFO]: This server is running Paper version git-Paper-142 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ef0e5a6)
You are running the latest version
```

### `/version Citizens` output

```txt
> version Citizens
[11:05:49 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2703)
[11:05:49 INFO]: Website: https://www.citizensnpcs.co
[11:05:49 INFO]: Author: fullwall
```

### Log file

https://whitedog.straight8.com/drops/log-20220914.log

### config.yml

https://whitedog.straight8.com/drops/config-20220914.yml

### saves.yml

https://whitedog.straight8.com/drops/saves-20220914.yml

### Description

On server start-up:
```
[10:50:44] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2703)
[10:50:45] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: citizensplaceholder [1.0.0]
[10:50:45] [Server thread/INFO]: [Citizens] Loaded economy handling via Vault.
[10:50:45] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.30-SNAPSHOT (build 2703) (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setTabCompleter(org.bukkit.command.TabCompleter)" because the return value of "org.bukkit.plugin.java.JavaPlugin.getCommand(String)" is null
        at net.citizensnpcs.api.command.CommandManager.registerTabCompletion(CommandManager.java:551) ~[Citizens-2.0.30-b2703.jar:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:358) ~[Citizens-2.0.30-b2703.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:50:45] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.30-SNAPSHOT (build 2703)
[10:50:45] [Server thread/WARN]: [RequiredPlugins] Citizens is a required plugin!
[10:50:45] [Server thread/INFO]: [Sentinel] Enabling Sentinel v2.7.0-SNAPSHOT (build 494)
[10:50:45] [Server thread/INFO]: [Sentinel] Sentinel loading...
[10:50:45] [Server thread/INFO]: [Sentinel] Running on java version: 18.0.2
[10:50:45] [Server thread/ERROR]: Error occurred while enabling Sentinel v2.7.0-SNAPSHOT (build 494) (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
        at org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:306) ~[Sentinel-2.7.0-b494.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-142]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-142]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-142]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 12 more
[10:50:45] [Server thread/INFO]: [Sentinel] Disabling Sentinel v2.7.0-SNAPSHOT (build 494)
[10:50:45] [Server thread/INFO]: [Sentinel] Sentinel unloading...
[10:50:45] [Server thread/INFO]: [Sentinel] Sentinel unloaded!
```
No issues with previous dev build. Same issues on Spigot.

**Comment by fullwall** [comment]
Fixed
