### ISSUE TITLE
Giving error

### ISSUE THREAD

**Issue by RADAR-G** [CitizensDev/Citizens2#2895]
### `/version` output

```txt
[09:33:34 INFO]: This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-153 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
[09:33:10 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2705)
[09:33:10 INFO]: Website: https://www.citizensnpcs.co
[09:33:10 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/101436

### config.yml

https://paste.denizenscript.com/View/101437

### saves.yml

/

### Description

when I use /npc create test I get error saying please report this error :
```
[09:39:50 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:666)
[09:39:50 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:39:50 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[09:39:50 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:39:50 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:289)
[09:39:50 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:39:50 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[09:39:50 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[09:39:50 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[09:39:50 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[09:39:50 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[09:39:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:39:50 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:666)
[09:39:50 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:39:50 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[09:39:50 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:39:50 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
[09:39:50 WARN]:        at Citizens-2.0.30-b2705.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:289)
[09:39:50 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:39:50 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[09:39:50 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[09:39:50 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[09:39:50 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[09:39:50 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[09:39:50 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[09:39:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[09:39:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
