### ISSUE TITLE
Plugin doesn't enable with large saves.yml file on 1.19.2

### ISSUE THREAD

**Issue by Frumple** [CitizensDev/Citizens2#2898]
### `/version` output

```txt
This server is running Paper version git-Paper-172 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6d63005)
You are running the latest version
Previous version: git-Paper-367 (MC: 1.18.2)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2705)
Website: https://www.citizensnpcs.co
Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/101547

### config.yml

https://paste.denizenscript.com/View/101548

### saves.yml

https://paste.denizenscript.com/View/101549

### Description

When we tried updating from Citizens build 2542 (Paper 1.18.2 build 367) to Citizens build 2705 (Paper 1.19.2 build 172), the plugin shows the following exception at startup and doesn't enable:

```
[22:57:09] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2705)
[22:57:09] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
[22:57:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:105)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[22:57:09] [Server thread/WARN]: 	at Citizens-2.0.30-b2705.jar//net.citizensnpcs.api.util.YamlStorage.load(YamlStorage.java:85)
[22:57:09] [Server thread/WARN]: 	at Citizens-2.0.30-b2705.jar//net.citizensnpcs.Citizens.createStorage(Citizens.java:153)
[22:57:09] [Server thread/WARN]: 	at Citizens-2.0.30-b2705.jar//net.citizensnpcs.Citizens.onEnable(Citizens.java:333)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[22:57:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[22:57:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[22:57:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[22:57:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1126)
[22:57:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[22:57:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:57:09] [Server thread/WARN]: Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:335)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:256)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:648)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:171)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:190)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:116)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[22:57:09] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:561)
[22:57:09] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:103)
[22:57:09] [Server thread/WARN]: 	... 16 more
[22:57:09] [Server thread/ERROR]: [Citizens] Unable to load saves, disabling...
[22:57:09] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.30-SNAPSHOT (build 2705)
```

Our saves.yml file is 3.2 MB in size with thousands of NPCs, and I can confirm it does not cause this issue on the older Citizens build 2542 with Paper 1.18.2.

As a test, I tried splitting the saves.yml into 2 halves about 1.6 MB each, and found that the latest Citizens build loads successfully with either half. I've pastebinned these files here:

saves-1st-half.yml
https://paste.denizenscript.com/View/101550

saves-2nd-half.yml
https://paste.denizenscript.com/View/101551

Is this new YAML file "limit" something that you folks (the Citizens devs) can configure/fix? Or is this more likely caused by some change in Spigot or Paper?

**Comment by mcmonkey4eva** [comment]
This is caused by a recent Paper change:
![](https://i.alexgoodwin.media/i/misc/cb6934.png)

There is likely a way to disable the limit or jack it up in code to fix this.

**Comment by Frumple** [comment]
Thanks for the reply. I've rolled back to Paper 1.19.2 build 161 and can confirm Citizens loads fine with that build.

I also came across this recently created Paper issue, where the same Paper dev confirms that the 64MB default only applies to plugins using the built-in Bukkit configuration API, and plugins using snakeyaml directly will need to make their own changes: https://github.com/PaperMC/Paper/issues/8388#issuecomment-1257152677
