### ISSUE TITLE
Error loading and create NPC

### ISSUE THREAD

**Issue by StealthDeci** [CitizensDev/Citizens2#2916]
### `/version` output

```txt
Citizens-2.0.30-b2719.jar
```

### `/version Citizens` output

```txt
Citizens-2.0.30-b2719.jar
```

### Log file

https://paste.denizenscript.com/View/102249

### config.yml

https://paste.denizenscript.com/View/102250

### saves.yml

https://paste.denizenscript.com/View/102251

### Description

Error craete NPC
[19:46:46 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:321)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:667)
[19:46:46 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[19:46:46 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:289)
[19:46:46 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:46:46 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[19:46:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940)
[19:46:46 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2474)
[19:46:46 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2245)
[19:46:46 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1386)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1363)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1356)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1334)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1219)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308)
[19:46:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:46:46 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:53)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:667)
[19:46:46 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[19:46:46 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
[19:46:46 WARN]:        at Citizens-2.0.30-b2719.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:289)
[19:46:46 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:46:46 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[19:46:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940)
[19:46:46 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2474)
[19:46:46 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2245)
[19:46:46 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1386)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1363)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1356)
[19:46:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1334)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1219)
[19:46:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308)
[19:46:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcmonkey4eva** [comment]
You need 1.19.2, not 1.19(.0)
