### ISSUE TITLE
Stacktrace on NPC creation

### ISSUE THREAD

**Issue by Catzy44** [CitizensDev/Citizens2#2921]
build b2729
trying to /npc create xxxx
```
[04:49:43 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:339)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:105)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:52)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:51)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:259)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:667)
[04:49:43 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:49:43 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[04:49:43 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:49:43 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
[04:49:43 WARN]:        at Citizens-2.0.30-b2729.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:289)
[04:49:43 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:49:43 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:49:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[04:49:43 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[04:49:43 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[04:49:43 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:49:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:49:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[04:49:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[04:49:43 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[04:49:43 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[04:49:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mcmonkey4eva** [comment]
Update your server.
If confused, ask for support on Discord @ https://discord.gg/Q6pZGSR
