### ISSUE TITLE
NoSuchMethodError: EntityHumanNPC.ex() -> Unable to create NPCs

### ISSUE THREAD

**Issue by Phantom1092** [CitizensDev/Citizens2#2934]
### `/version` output

```txt
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2759)
```

### Log file

https://paste.denizenscript.com/View/103399

### config.yml

https://paste.denizenscript.com/View/103398

### saves.yml

https://paste.denizenscript.com/View/103401

### Description

I was trying to create an npc via /npc create RandomName. After that, it throws the error in the console and the same error on reload/restart of the server:

[09:54:24 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ex()'
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:340)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:109)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:52)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:48)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:275)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:169)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[09:54:24 WARN]:        at Citizens.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:567)
[09:54:24 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[09:54:24 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[09:54:24 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1135)
[09:54:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[09:54:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:54:24 WARN]: [Citizens] Task #12 for Citizens v2.0.30-SNAPSHOT (build 2759) generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "<local4>" is null
        at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:358) ~[Citizens.jar:?]
        at net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:109) ~[Citizens.jar:?]
        at net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:52) ~[Citizens.jar:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:48) ~[Citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:275) ~[Citizens.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:169) ~[Citizens.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[Citizens.jar:?]
        at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:567) ~[Citizens.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-81]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1135) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Please tell me, if I did something wrong or if you guys messed sth up

**Comment by Phantom1092** [comment]
found answer
