### ISSUE TITLE
NPC CREATE PROBLEM!!

### ISSUE THREAD

**Issue by ismamilahi** [CitizensDev/Citizens2#2940]
[16:22:07 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.ai.attributes.AttributeMapBase net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.ey()'
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:306)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:102)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:52)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:258)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:615)
[16:22:07 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:22:07 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:22:07 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:22:07 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:304)
[16:22:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:22:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:22:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[16:22:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[16:22:07 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[16:22:07 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[16:22:07 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[16:22:07 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2294)
[16:22:07 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[16:22:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:22:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1445)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:22:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:22:07 WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.attributes.AttributeModifiable.a(double)" because "range" is null
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:324)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.nms.v1_19_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:102)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.nms.v1_19_R1.entity.HumanController.createEntity(HumanController.java:52)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:258)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:615)
[16:22:07 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:22:07 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[16:22:07 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:22:07 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[16:22:07 WARN]:        at Citizens-2.0.30-b2577.jar//net.citizensnpcs.Citizens.onCommand(Citizens.java:304)
[16:22:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:22:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:22:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
[16:22:07 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[16:22:07 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[16:22:07 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:305)
[16:22:07 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:289)
[16:22:07 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2294)
[16:22:07 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[16:22:07 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[16:22:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[16:22:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1445)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1173)
[16:22:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[16:22:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcmonkey4eva** [comment]
Please either fill out the issue template properly, or ask on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel

**Comment by ismamilahi** [comment]
> Please either fill out the issue template properly, or ask on Discord @ https://discord.gg/Q6pZGSR in the `#citizens` channel

ok
