### ISSUE TITLE
Console spam regarding player navigation

### ISSUE THREAD

**Issue by Jazzkuh** [CitizensDev/Citizens2#2945]
### `/version` output

```txt
Current: git-Purpur-1860 (MC: 1.19.3)*
Previous: git-Purpur-1826 (MC: 1.19.2)
* You are running the latest version
```

### `/version Citizens` output

```txt
Citizens v2.0.30-SNAPSHOT (build 2804)
```

### Log file

https://paste.denizenscript.com/View/103817

### config.yml

https://paste.denizenscript.com/View/103819

### saves.yml

https://paste.denizenscript.com/View/103818

### Description

Happens right when the server is done loading, my guess is it has something to do with player navigation. It is just spamming the console with the following error:

```
[11:38:00] [Server thread/INFO]: [Citizens] Exception while updating 6: Cannot invoke "net.minecraft.util.profiling.GameProfilerFiller.a(String)" because the return value of "net.minecraft.world.level.World.ad()" is null.
[11:38:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.profiling.GameProfilerFiller.a(String)" because the return value of "net.minecraft.world.level.World.ad()" is null
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.PlayerNavigation.a(PlayerNavigation.java:229)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.PlayerNavigation.a(PlayerNavigation.java:220)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.PlayerNavigation.supercreatePath(PlayerNavigation.java:492)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.PlayerNavigation.a(PlayerNavigation.java:188)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.PlayerNavigation.a(PlayerNavigation.java:374)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.NMSImpl.lambda$getTargetNavigator$2(NMSImpl.java:661)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.util.NMSImpl$2.update(NMSImpl.java:739)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.npc.ai.MCNavigationStrategy.update(MCNavigationStrategy.java:84)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:180)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:446)
[11:38:00] [Server thread/WARN]: 	at Citizens-2.0.30-b2804.jar//net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.l(EntityHumanNPC.java:506)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.a(WorldServer.java:1280)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.world.level.World.a(World.java:965)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.lambda$tick$6(WorldServer.java:754)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.a(WorldServer.java:734)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1562)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:477)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1422)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[11:38:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[11:38:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by fullwall** [comment]
Fixed in newer build
