### ISSUE TITLE
CustomEntityRegistry no longer accepts intrusive holders

### ISSUE THREAD

**Issue by datatags** [CitizensDev/Citizens2#2951]
### `/version` output

```txt
This server is running Paper version git-Paper-343 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f3eb2c7)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-328 (MC: 1.19.3)
```

### `/version Citizens` output

```txt
[15:28:42 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2816)
[15:28:42 INFO]: Website: https://www.citizensnpcs.co
[15:28:42 INFO]: Author: fullwall
```

### Log file

https://pastebin.com/6Lx8mSht

### config.yml

https://pastebin.com/ZQwXenbW

### saves.yml

https://pastebin.com/8Qw8P4sN

### Description

Like in #2947, I'm developing a plugin that registers custom entities through the registry. Until 1.19.3, (has to do with commit d44cebdcfd71eb6673c7e9f8eccb98ca18e0870d?) I was able to register entities (when Citizens was present or not) with [this code](https://github.com/datatags/UltraCosmetics/blob/6b1c80950aa153bd3a45dfd358ba703a03b799dc/v1_19_R2/src/main/java/be/isach/ultracosmetics/v1_19_R2/customentities/CustomEntities.java#L43-L107). But with recent builds of Citizens, I can no longer register custom entities, and I get this error:
```
[15:28:35 WARN]: java.lang.IllegalStateException: This registry can't create intrusive holders
[15:28:35 WARN]:        at net.minecraft.core.RegistryMaterials.f(RegistryMaterials.java:369)
[15:28:35 WARN]:        at Citizens-2.0.30-b2816.jar//net.citizensnpcs.nms.v1_19_R2.util.CustomEntityRegistry.createIntrusiveHolder(CustomEntityRegistry.java:
200)
[15:28:35 WARN]:        at Citizens-2.0.30-b2816.jar//net.citizensnpcs.nms.v1_19_R2.util.CustomEntityRegistry.f(CustomEntityRegistry.java:153)
[15:28:35 WARN]:        at net.minecraft.world.entity.EntityTypes.<init>(EntityTypes.java:327)
[15:28:35 WARN]:        at net.minecraft.world.entity.EntityTypes.<init>(EntityTypes.java:319)
[15:28:35 WARN]:        at net.minecraft.world.entity.EntityTypes$Builder.a(EntityTypes.java:783)
[15:28:35 WARN]:        at UltraCosmetics-3.0-DEV-b3b.jar//be.isach.ultracosmetics.v1_19_R2.customentities.CustomEntities.registerEntity(CustomEntities.java:1
10)
...
```
I see MyPet works around this by scanning for the real registry wrapped by Citizens' registry and operating on that instead. So my question is, is this an issue I need to work around myself, or is this considered a Citizens bug? It seems like it would be more friendly to accept registrations through the normal NMS methods, like it did previously. Thanks!

**Comment by fullwall** [comment]
Try the new build

**Comment by datatags** [comment]
Looks like that fixed it, thank you!
