### ISSUE TITLE
Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

### ISSUE THREAD

**Issue by spookymgmt** [CitizensDev/Citizens2#2974]
### `/version` output

```txt
Pufferfish-54 Git 15538a9 1.19.3
```

### `/version Citizens` output

```txt
2.0.30-SNAPSHOT Build 2880
```

### Log file

https://mclo.gs/hNwK00y

### config.yml

https://paste.denizenscript.com/View/105022

### saves.yml

https://paste.denizenscript.com/View/105023

### Description

```
[11:08:21] [Netty Epoll Server IO #4/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[11:08:21] [Netty Epoll Server IO #4/WARN]: Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[11:08:21] [Netty Epoll Server IO #4/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(51) + length(1) exceeds writerIndex(51): PooledUnsafeDirectByteBuf(ridx: 51, widx: 51, cap: 256)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaBackwards-4.5.2-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:146)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:60)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ViaVersion-4.5.2-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:38)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at eGlow 3.2.1 1.9.4-1.19.3 (1).jar//me.MrGraycat.eGlow.Util.Packets.PipelineInjector$1.write(PipelineInjector.java:92)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at FartherViewDistance-9.7.4 (1).jar//xuan.cat.fartherviewdistance.code.branch.v19.Branch_19_Minecraft$1.write(Branch_19_Minecraft.java:109)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib (1).jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:08:21] [Netty Epoll Server IO #4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
```

1. At random times, this above error will occur. It seems like it's always caused by a bedrock player.

2. When a player triggers this error, NOBODY can join the server until the player who triggered it leaves the server.

3. In the provided log file, you can see the error started at 11:01:46 (I say this because it's the first time in the log you see players joining and instantly disconnecting. Here's what I mean.

[11:01:46] [Server thread/INFO]: [+] _YoddieBear
[11:01:46] [Server thread/INFO]: [✖] _YoddieBear
[11:02:10] [Server thread/INFO]: + NEW PinedaMC
[11:02:10] [Server thread/INFO]: [✖] PinedaMC

4. When a bedrock player causes the malformed packet, there is NO ERROR in the logs. 
5. Once a java player joins, the actual error is displayed in the console. From above, we can see that a malformed packet was sent sometime just before 11:01:46

This is the most recent player connection to the server that it wasn't flawed.

[10:59:30] [Server thread/INFO]: [+] _UnhookedSauce31

The malformed packet had to have happened sometime between 10:59:30 and 11:01:46

HOWEVER, distinct commands were ran in this time. Why does this matter? It shows it's most likely not a plugin with a specific command causing the issue.

JUICY PART

6. As mentioned earlier, once the player who caused / received / sent the malformed packet leaves the server, everything goes back to normal. With this information,

[11:11:01] [Server thread/INFO]: [✖] _MobileUsers1

This player left the server at 11:11:01, as soon as he left, player connections went back to normal. Problem fixed.

Now lets look at all the logs by this player while being online.

	Line 27651: [10:59:23] [Server thread/INFO]: [+] _MobileUsers1
	Line 27655: [10:59:26] [Craft Scheduler Thread - 2180 - mcMMO/INFO]: [mcMMO] Creating new data for player: _MobileUsers1
	Line 29987: [11:07:17] [Server thread/INFO]: _MobileUsers1 issued server command: /rtp
	Line 29999: [11:07:24] [Server thread/INFO]: _MobileUsers1 issued server command: /wild world
	Line 31233: [11:08:06] [Server thread/INFO]: zwartenacht123 issued server command: /tpa _MobileUsers1
	Line 31246: [11:08:20] [Server thread/INFO]: _MobileUsers1 issued server command: /tpaccept
	Line 31728: [11:09:53] [Server thread/INFO]: _MobileUsers1 issued server command: /hub
	Line 31741: [11:09:59] [Server thread/INFO]: _MobileUsers1 issued server command: /hub
	Line 31742: [11:10:05] [Server thread/INFO]: _MobileUsers1 issued server command: /spawn
	Line 31752: [11:10:17] [Server thread/INFO]: _MobileUsers1 issued server command: /lobby

7. He was at my servers spawn when this malformed packet was sent / received. The only plugins available at my spawn, that could be sending him packets are Citizens, DecentHolograms, and crazycrates, and world guard.

I've been having this error since 1.19.3 viaversion released, and during that time I wasn't using decentholograms, meaning it comes down to Citizens and Crazycrates.

Crazycrates doesn't touch PLAYER_INFO or PLAYER_INFO_UPDATE which leads us to... Citizens.

Please look into this, I'm loosing a lot of sleep over it. Thanks.

**Comment by mcmonkey4eva** [comment]
That is either a Geyser issue, or ViaVersion.

**Comment by spookymgmt** [comment]
![Discord_J5HcsurNRw](https://user-images.githubusercontent.com/78775526/210864992-0b2e5a2e-cf9e-4347-903b-5c9dbaf5e6ba.png)
The issue isn't geyser. The issue isn't viaversion. It's citizens.

**Comment by Camotoy** [comment]
It's probably a ViaVersion error. Seeing as 1.19.3 Java players are fine, that means that unless they aren't getting these same packets, the encoding on the packets are correct. Via is probably seeing these packets and is unsure on how to parse them correctly.
