### ISSUE TITLE
NPE in `AStarNavigationStrategy` since updating to 1.19.3 Citizens build 2891

### ISSUE THREAD

**Issue by Blitheness** [CitizensDev/Citizens2#2978]
### `/version` output

```txt
Paper 1.19.3 #378 (Behind a BungeeCord proxy)
```

### `/version Citizens` output

```txt
2.0.30 #2891
```

### Log file

Server startup excerpt: https://paste.denizenscript.com/View/105503

### config.yml

https://paste.denizenscript.com/View/105501

### saves.yml

https://paste.denizenscript.com/View/105502.txt

### Description

I recently updated from 1.19 to 1.19.3 and bumped Citizens from build 2640 to build 2891.

Now my console is being spammed with null pointer exceptions for a select few NPCs several times per second, but without a stack trace for me to figure out why:
<details>
<pre>
[00:30:00 INFO]: [Citizens] Exception while updating 4,154: null.
[00:30:00 WARN]: java.lang.NullPointerException
[00:30:00 INFO]: [Citizens] Exception while updating 4,160: null.
[00:30:00 WARN]: java.lang.NullPointerException
[00:30:00 INFO]: [Citizens] Exception while updating 4,548: null.
[00:30:00 WARN]: java.lang.NullPointerException
[00:30:00 INFO]: [Citizens] Exception while updating 4,155: null.
</pre>
</details>

I have attached `saves.yml` - I am wondering if anybody can spot what might be wrong? The file hasn't been changed manually, and has been used for several years.

The affected NPCs have pathfinding configured, but when errors are spewing into the console, the NPCs do not move.

I set `debug: true` in `config.yml` to try and get a more helpful exception, however it has so far not provided a stack trace _(Edit: See towards the end for a useful exception)_:

<details>
<pre>
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,472: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,153: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,160: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,155: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Respawning all NPCs at [56,16] due to org.bukkit.event.world.EntitiesLoadEvent@72e9af08
[00:45:16 INFO]: [Citizens] Removing respawns of 1905{Nurse, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1905{Nurse, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1905{Nurse, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@72e9af08 at [56,16]
[00:45:16 INFO]: [Citizens] Removing respawns of 2054{Barista Maestro, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 2054{Barista Maestro, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 2054{Barista Maestro, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@72e9af08 at [56,16]
[00:45:16 INFO]: [Citizens] Removing respawns of 2053{Barista, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 2053{Barista, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 2053{Barista, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@72e9af08 at [56,16]
[00:45:16 INFO]: [Citizens] Respawning all NPCs at [60,15] due to org.bukkit.event.world.EntitiesLoadEvent@11da962b
[00:45:16 INFO]: [Citizens] Removing respawns of 1856{John, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1856{John, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1856{John, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@11da962b at [60,15]
[00:45:16 INFO]: [Citizens] Removing respawns of 3877{Officer, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 3877{Officer, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 3877{Officer, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@11da962b at [60,15]
[00:45:16 INFO]: [Citizens] Respawning all NPCs at [60,16] due to org.bukkit.event.world.EntitiesLoadEvent@750d25b9
[00:45:16 INFO]: [Citizens] Removing respawns of 1863{Dentist, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1863{Dentist, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1863{Dentist, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@750d25b9 at [60,16]
[00:45:16 INFO]: [Citizens] Removing respawns of 1862{Gardener, PLAYER} due to SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1862{Gardener, PLAYER} SpawnReason.CHUNK_LOAD
[00:45:16 INFO]: [Citizens] Spawned 1862{Gardener, PLAYER} during org.bukkit.event.world.EntitiesLoadEvent@750d25b9 at [60,16]
[00:45:16 INFO]: [Citizens] Exception while updating 4,472: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,153: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,160: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,155: null.
[00:45:16 WARN]: java.lang.NullPointerException
[00:45:16 INFO]: [Citizens] Exception while updating 4,472: null.
</pre>
</details>

I got this too, but I am unsure if it is related to the issue causing my server log to fill up with NPEs:
<details>
<pre>
[00:48:04 INFO]: [Citizens] Stored 3938{Railway Staff, PLAYER} for respawn from NPCNeedsRespawnEvent
[00:48:04 INFO]: [Citizens] Retrying spawn of 3939{Hermione, PLAYER} later, SpawnReason.RESPAWN. Was loaded false is loaded false
[00:48:04 INFO]: [Citizens] Stored 3939{Hermione, PLAYER} for respawn from NPCNeedsRespawnEvent
[00:48:04 INFO]: [Citizens] Removing respawns of 3942{Librarian, VILLAGER} due to SpawnReason.RESPAWN
[00:48:04 INFO]: [Citizens] Spawned 3942{Librarian, VILLAGER} SpawnReason.RESPAWN
[00:48:04 INFO]: [Citizens] Removing respawns of 3941{Librarian, VILLAGER} due to SpawnReason.RESPAWN
[00:48:04 INFO]: [Citizens] Spawned 3941{Librarian, VILLAGER} SpawnReason.RESPAWN
[00:48:04 WARN]: java.lang.Exception: CITIZENS CHUNK LOAD DEBUG [76,-501]
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.EventListen.loadNPCs(EventListen.java:180)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.EventListenChunk.onEntitiesLoad(EventListenChunk.java:18)
[00:48:04 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor343.execute(Unknown Source)
[00:48:04 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:48:04 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:48:04 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:48:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
[00:48:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1921)
[00:48:04 WARN]:        at io.papermc.paper.world.ChunkEntitySlices.callEntitiesLoadEvent(ChunkEntitySlices.java:151)
[00:48:04 WARN]:        at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:917)
[00:48:04 WARN]:        at net.minecraft.world.level.chunk.Chunk.onChunkLoad(Chunk.java:868)
[00:48:04 WARN]:        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1311)
[00:48:04 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050)
[00:48:04 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034)
[00:48:04 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919)
[00:48:04 WARN]:        at net.minecraft.server.level.ChunkProviderServer.s(ChunkProviderServer.java:583)
[00:48:04 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:1005)
[00:48:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:48:04 WARN]:        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:451)
[00:48:04 WARN]:        at net.minecraft.world.level.World.a(World.java:501)
[00:48:04 WARN]:        at net.minecraft.world.level.World.a_(World.java:779)
[00:48:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.block.CraftBlock.getType(CraftBlock.java:229)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.nms.v1_19_R2.entity.MobEntityController.createEntity(MobEntityController.java:41)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.AbstractEntityController.create(AbstractEntityController.java:24)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:297)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:180)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[00:48:04 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:606)
[00:48:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[00:48:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[00:48:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1114)
[00:48:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[00:48:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:48:04 INFO]: [Citizens] Removing respawns of 3940{Librarian, VILLAGER} due to SpawnReason.RESPAWN
[00:48:04 INFO]: [Citizens] Spawned 3940{Librarian, VILLAGER} SpawnReason.RESPAWN
[00:48:04 INFO]: [Citizens] Retrying spawn of 3944{Gina, PLAYER} later, SpawnReason.RESPAWN. Was loaded false is loaded false
[00:48:04 INFO]: [Citizens] Stored 3944{Gina, PLAYER} for respawn from NPCNeedsRespawnEvent
[00:48:04 INFO]: [Citizens] Retrying spawn of 3943{Vince Chancellier, PLAYER} later, SpawnReason.RESPAWN. Was loaded false is loaded false
[00:48:04 INFO]: [Citizens] Stored 3943{Vince Chancellier, PLAYER} for respawn from NPCNeedsRespawnEvent
</pre>
</details>

💁‍♂️<mark>Ah ha!</mark> I've found something:
<details>
<pre>
[00:51:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:51:49 INFO]: [Citizens] Exception while updating 4,153: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null.
[00:51:49 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.AStarNavigationStrategy.update(AStarNavigationStrategy.java:111)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:199)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:481)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.l(EntityHumanNPC.java:498)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1211)
[00:51:49 WARN]:        at net.minecraft.world.level.World.a(World.java:918)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$6(WorldServer.java:731)
[00:51:49 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:711)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1535)
[00:51:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[00:51:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:51:49 INFO]: [Citizens] Exception while updating 4,153: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null.
[00:51:49 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.AStarNavigationStrategy.update(AStarNavigationStrategy.java:111)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:199)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:481)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.l(EntityHumanNPC.java:498)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1211)
[00:51:49 WARN]:        at net.minecraft.world.level.World.a(World.java:918)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$6(WorldServer.java:731)
[00:51:49 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:711)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1535)
[00:51:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[00:51:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:51:49 INFO]: [Citizens] Exception while updating 4,153: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null.
[00:51:49 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.AStarNavigationStrategy.update(AStarNavigationStrategy.java:111)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:199)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:481)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.l(EntityHumanNPC.java:498)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1211)
[00:51:49 WARN]:        at net.minecraft.world.level.World.a(World.java:918)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$6(WorldServer.java:731)
[00:51:49 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:711)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1535)
[00:51:49 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:440)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[00:51:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[00:51:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
</pre>
</details>

```log
[00:51:49 INFO]: [Citizens] Exception while updating 4,153: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null.
[00:51:49 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.toLocation(org.bukkit.World)" because "this.vector" is null
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.AStarNavigationStrategy.update(AStarNavigationStrategy.java:111)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:199)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:481)
[00:51:49 WARN]:        at Citizens-2.0.30-b2891.jar//net.citizensnpcs.nms.v1_19_R2.entity.EntityHumanNPC.l(EntityHumanNPC.java:498)
[00:51:49 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1211)
```

Possibly related:
- ffac34f734ab42ff6a959e2f0144a4001b108ed6 On 5 Jan 2023 there was a change to `update()` upon creating a new instance of `AStarPlanner`, the method of getting an NPC's location changed from `npc.getStoredLocation()` to `npc.getEntity().getLocation(NPC_LOCATION)`.
- https://github.com/CitizensDev/Citizens2/commit/ffef42efb76d1442341adaa3b3b69b005d971739 Another change that could have affected how `vector` is set

**Comment by Blitheness** [comment]
Thank you very much for looking into this and fixing it, much appreciated
