### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Regomy** [CitizensDev/Citizens2#2979]
### `/version` output

```txt
his server is running Reaper version git-Reaper-"1454595" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:02:43 INFO]: You are 23 version(s) behind
```

### `/version Citizens` output

```txt
[17:56:37 INFO]: Citizens version 2.0.30-SNAPSHOT (build 2858)
[17:56:37 INFO]: Website: https://www.citizensnpcs.co
[17:56:37 INFO]: Author: fullwall
```

### Log file

1

### config.yml

1

### saves.yml

1

### Profiler report

1

### Description

[17:52:31 ERROR]: [Citizens] Error retrieving entity from ID: ProtocolLib error? Suppressing further exceptions unless debugging.
[17:52:31 WARN]: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={ type exactly class net.minecraft.server.v1_12_R1.Entity }}
[17:52:31 WARN]: at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
[17:52:31 WARN]: at com.comphenix.protocol.injector.EntityUtilities.lambda$getEntity$0(EntityUtilities.java:126)
[17:52:31 WARN]: at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[17:52:31 WARN]: at com.comphenix.protocol.injector.EntityUtilities.getEntity(EntityUtilities.java:116)
[17:52:31 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:404)
[17:52:31 WARN]: at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:145)
[17:52:31 WARN]: at net.citizensnpcs.ProtocolLibListener.access$200(ProtocolLibListener.java:37)
[17:52:31 WARN]: at net.citizensnpcs.ProtocolLibListener$2.onPacketSending(ProtocolLibListener.java:100)
[17:52:31 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[17:52:31 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[17:52:31 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[17:52:31 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[17:52:31 WARN]: at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[17:52:31 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[17:52:31 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[17:52:31 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[17:52:31 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.writePacket(NetworkManager.java:319)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:245)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:231)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1223)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:322)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:431)
[17:52:31 WARN]: at net.citizensnpcs.nms.v1_12_R1.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:56)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:265)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerChunk.sendChunk(PlayerChunk.java:179)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:77)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:418)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerList.d(PlayerList.java:421)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:744)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[17:52:31 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:52:31 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:867)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:788)
[17:52:31 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678)
[17:52:31 WARN]: at java.lang.Thread.run(Thread.java:748)
[17:52:43 WARN]: java.lang.NullPointerException
[17:52:43 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$hideClickableEntities$9(Hologram.java:612)
[17:52:43 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1259)
[17:52:43 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.hideClickableEntities(Hologram.java:612)
[17:52:43 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.hide(Hologram.java:568)
[17:52:43 WARN]: at eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:89)
[17:52:43 WARN]: at eu.decentsoftware.holograms.api.holograms.HologramManager.tick(HologramManager.java:61)
[17:52:43 WARN]: at eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[17:52:43 WARN]: at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[17:52:43 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:52:43 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:52:43 WARN]: at java.lang.Thread.run(Thread.java:748)
[17:52:44 WARN]: java.lang.NullPointerException
[17:52:44 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$hideClickableEntities$9(Hologram.java:612)
[17:52:44 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1259)
[17:52:44 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.hideClickableEntities(Hologram.java:612)
[17:52:44 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.hide(Hologram.java:568)
[17:52:44 WARN]: at eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:89)
[17:52:44 WARN]: at eu.decentsoftware.holograms.api.holograms.HologramManager.tick(HologramManager.java:61)
[17:52:44 WARN]: at eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[17:52:44 WARN]: at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[17:52:44 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:52:44 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:52:44 WARN]: at java.lang.Thread.run(Thread.java:748)
[17:52:45 WARN]: java.lang.NullPointerException
[17:52:45 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.lambda$hideClickableEntities$9(Hologram.java:612)
[17:52:45 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1259)
[17:52:45 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.hideClickableEntities(Hologram.java:612)
[17:52:45 WARN]: at eu.decentsoftware.holograms.api.holograms.Hologram.hide(Hologram.java:568)
[17:52:45 WARN]: at eu.decentsoftware.holograms.api.holograms.HologramManager.updateVisibility(HologramManager.java:89)
[17:52:45 WARN]: at eu.decentsoftware.holograms.api.holograms.HologramManager.tick(HologramManager.java:61)
[17:52:45 WARN]: at eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
[17:52:45 WARN]: at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[17:52:45 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:52:45 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:52:45 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by mcmonkey4eva** [comment]
Closing due to refusal to provide required information.
