### ISSUE TITLE
errer

### ISSUE THREAD

**Issue by Regomy** [CitizensDev/Citizens2#2980]
### `/version` output

```txt
This server is running Reaper version git-Reaper-"1454595" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:34:05 INFO]: You are 23 version(s) behind
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2858)
```

### Log file

1

### config.yml

1

### saves.yml

1

### Profiler report

https://spark.lucko.me/VQs72QmX6L

### Description

[Citizens] Error retrieving entity from ID: ProtocolLib error? Suppressing further exceptions unless debugging.
[21:31:19 WARN]: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={ type exactly class net.minecraft.server.v1_12_R1.Entity }}
[21:31:19 WARN]: at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:352)
[21:31:19 WARN]: at com.comphenix.protocol.injector.EntityUtilities.lambda$getEntity$0(EntityUtilities.java:126)
[21:31:19 WARN]: at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[21:31:19 WARN]: at com.comphenix.protocol.injector.EntityUtilities.getEntity(EntityUtilities.java:116)
[21:31:19 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:404)
[21:31:19 WARN]: at net.citizensnpcs.ProtocolLibListener.getNPCFromPacket(ProtocolLibListener.java:145)
[21:31:19 WARN]: at net.citizensnpcs.ProtocolLibListener.access$200(ProtocolLibListener.java:37)
[21:31:19 WARN]: at net.citizensnpcs.ProtocolLibListener$2.onPacketSending(ProtocolLibListener.java:100)
[21:31:19 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[21:31:19 WARN]: at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[21:31:19 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547)
[21:31:19 WARN]: at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521)
[21:31:19 WARN]: at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99)
[21:31:19 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571)
[21:31:19 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472)
[21:31:19 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43)
[21:31:19 WARN]: at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.writePacket(NetworkManager.java:319)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:245)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:231)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1223)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:322)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:431)
[21:31:19 WARN]: at net.citizensnpcs.nms.v1_12_R1.util.PlayerlistTrackerEntry.updatePlayer(PlayerlistTrackerEntry.java:56)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:220)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:1397)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2386)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInSettings.a(PacketPlayInSettings.java:35)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInSettings.a(PacketPlayInSettings.java:5)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[21:31:19 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[21:31:19 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:867)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:788)
[21:31:19 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678)
[21:31:19 WARN]: at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by tal5** [comment]
You already opened the exact same issue (#2979) and it got closed because you didn't provide the required information.
Please follow the issue template and provide all the necessary information, consider also asking for support on Discord @ https://discord.gg/Q6pZGSR
