### ISSUE TITLE
BUG ERROR PIZDEC BLYAT POMOGITE YZHE

### ISSUE THREAD

**Issue by Regomy** [CitizensDev/Citizens2#2983]
### `/version` output

```txt
This server is running Reaper version git-Reaper-"1454595" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.30-SNAPSHOT (build 2858)
[13:22:23 INFO]: Website: https://www.citizensnpcs.co
[13:22:23 INFO]: Author: fullwall
```

### Log file

1

### config.yml

1

### saves.yml

1

### Profiler report

1

### Description

[13:20:42 WARN]: java.lang.NullPointerException
[13:20:42 WARN]: at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1015)
[13:20:42 WARN]: at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:908)
[13:20:42 WARN]: at net.citizensnpcs.api.util.Messaging.convertLegacyCodes(Messaging.java:121)
[13:20:42 WARN]: at net.citizensnpcs.api.util.Messaging.parseComponents(Messaging.java:158)
[13:20:42 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.init(AbstractNPC.java:107)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPC.init(CitizensNPC.java:66)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPCRegistry.create(CitizensNPCRegistry.java:52)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:71)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:57)
[13:20:42 WARN]: at net.citizensnpcs.trait.HologramTrait.createHologram(HologramTrait.java:90)
[13:20:42 WARN]: at net.citizensnpcs.trait.HologramTrait.onSpawn(HologramTrait.java:202)
[13:20:42 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:141)
[13:20:42 WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:119)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:382)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:313)
[13:20:42 WARN]: at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:394)
[13:20:42 WARN]: at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:750)
[13:20:42 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:20:42 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:20:42 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:20:42 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:20:42 WARN]: at net.citizensnpcs.api.command.CommandManager.executeCommand(CommandManager.java:187)
[13:20:42 WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:97)
[13:20:42 WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:228)
[13:20:42 WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:348)
[13:20:42 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:20:42 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150)
[13:20:42 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1514)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1317)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[13:20:42 WARN]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[13:20:42 WARN]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:867)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:788)
[13:20:42 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678)
[13:20:42 WARN]: at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mcmonkey4eva** [comment]
blocking due to spam
