### ISSUE TITLE
Paper 1.19.2 Cannot be used

### ISSUE THREAD

**Issue by MySoulcutting** [CitizensDev/Citizens2#2991]
### `/version` output

```txt
[12:51:40 ERROR]: [Citizens] v2.0.30-SNAPSHOT (build 2915) 与 Minecraft v1_19_R1不兼容 - 尝试升级或降级Citizens, 正在禁用。
[12:51:40 INFO]: [Citizens] Disabling Citizens v2.0.30-SNAPSHOT (build 2915)

//English 
[12:51:40 ERROR]: [Citizens] v2.0.30-SNAPSHOT (build 2915) is incompatible with Minecraft v1_19_R1-an attempt was made to upgrade or downgrade Citizens, which is being disabled.
```

### `/version Citizens` output

```txt
> citizens version
[12:59:06 WARN]: Unexpected exception while parsing console command "citizens version"
org.bukkit.command.CommandException: Cannot execute command 'citizens' in plugin Citizens v2.0.30-SNAPSHOT (build 2915) - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```

### Log file

not log

### config.yml

not config

### saves.yml

not save

### Description

I think it's only compatible with 1.19R2.
Not compatible with 1.19R1

**Comment by mcmonkey4eva** [comment]
Correct, you need 1.19.3
