### ISSUE TITLE
Plugin dose not work 

### ISSUE THREAD

**Issue by NaysKutzu** [CitizensDev/Citizens2#3020]
```java
[22:05:16 INFO]: [Citizens] Enabling Citizens v2.0.31-SNAPSHOT (build 3095)
[22:05:16 WARN]: Enabled plugin with unregistered PluginClassLoader Citizens v2.0.31-SNAPSHOT (build 3095)
[22:05:16 INFO]: [Citizens] Loading external libraries
[22:05:16 ERROR]: [Citizens] Citizens implementation changed, disabling plugin.
[22:05:16 INFO]: [Citizens] Disabling Citizens v2.0.31-SNAPSHOT (build 3095)
[22:05:16 ERROR]: Error occurred while enabling Citizens v2.0.31-SNAPSHOT (build 3095) (Is it up to date?)
java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:168) ~[?:?]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:112) ~[?:?]
        at net.citizensnpcs.api.util.Translator.getDefaultBundleProperties(Translator.java:188) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.api.util.Translator.populateDefaults(Translator.java:236) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.api.util.Translator.getDefaultResourceBundle(Translator.java:209) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.api.util.Translator.getDefaultBundle(Translator.java:67) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.api.util.Translator.<init>(Translator.java:45) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.api.util.Translator.setInstance(Translator.java:252) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.Citizens.setupTranslator(Citizens.java:547) ~[Citizens-2.0.31-b3095.jar:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:379) ~[Citizens-2.0.31-b3095.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by eldiosx** [comment]
x2

**Comment by mcmonkey4eva** [comment]
ask on Discord @ https://discord.gg/Q6pZGSR
