### ISSUE TITLE
1.20.1An error will be reported

### ISSUE THREAD

**Issue by welove69** [CitizensDev/Citizens2#3030]
### `/version` output

```txt
1.20.1
```

### `/version Citizens` output

```txt
Build #3133 And Build #3127
```

### Log file

https://paste.denizenscript.com/View/111360

### config.yml

default

### saves.yml

default

### Description

An error will be reported

[15:16:56 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@c9a7701
[15:16:56 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
[15:16:56 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:16:56 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:16:56 WARN]:        at 【NPC】Citizens-2.0.32-b3127.jar//net.citizensnpcs.EventListen.lambda$registerKnockbackEvent$5(EventListen.java:724)
[15:16:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:16:56 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[15:16:56 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[15:16:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[15:16:56 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[15:16:56 WARN]:        at net.minecraft.world.entity.Entity.push(Entity.java:2175)
[15:16:56 WARN]:        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1366)
[15:16:56 WARN]:        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2284)
[15:16:56 WARN]:        at net.minecraft.server.network.PlayerConnection$6.a(PlayerConnection.java:2971)
[15:16:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[15:16:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[15:16:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2893)
[15:16:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[15:16:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[15:16:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[15:16:56 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:16:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:16:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[15:16:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[15:16:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1452)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[15:16:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:16:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcmonkey4eva** [comment]
Closing as you did not provide the required logs and related files.
