### ISSUE TITLE
Warn 

### ISSUE THREAD

**Issue by Distolfix** [CitizensDev/Citizens2#3031]
### `/version` output

```txt
15:38:32 INFO]: This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
```

### `/version Citizens` output

```txt
[15:38:43 INFO]: Citizens version 2.0.32-SNAPSHOT (build 3133)
[15:38:43 INFO]: Website: https://www.citizensnpcs.co
[15:38:43 INFO]: Author: fullwall
```

### Log file

https://paste.denizenscript.com/View/111370

### config.yml

https://paste.denizenscript.com/View/111372

### saves.yml

https://paste.denizenscript.com/View/111373

### Description

[15:37:34 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@229c8724
[15:37:34 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
[15:37:34 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:37:34 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:37:34 WARN]:        at Citizens-2.0.32-b3133.jar//net.citizensnpcs.EventListen.lambda$registerKnockbackEvent$6(EventListen.java:724)
[15:37:34 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:37:34 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[15:37:34 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[15:37:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[15:37:34 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[15:37:34 WARN]:        at net.minecraft.world.entity.Entity.push(Entity.java:2034)
[15:37:34 WARN]:        at net.minecraft.world.entity.projectile.EntityArrow.a(EntityArrow.java:419)
[15:37:34 WARN]:        at net.minecraft.world.entity.projectile.IProjectile.a(IProjectile.java:214)
[15:37:34 WARN]:        at net.minecraft.world.entity.projectile.IProjectile.preOnHit(IProjectile.java:205)
[15:37:34 WARN]:        at net.minecraft.world.entity.projectile.EntityArrow.preOnHit(EntityArrow.java:296)
[15:37:34 WARN]:        at net.minecraft.world.entity.projectile.EntityArrow.l(EntityArrow.java:232)
[15:37:34 WARN]:        at net.minecraft.world.entity.projectile.EntityTippedArrow.l(EntityTippedArrow.java:112)
[15:37:34 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1226)
[15:37:34 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$6(WorldServer.java:734)
[15:37:34 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[15:37:34 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:711)
[15:37:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1548)
[15:37:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:450)
[15:37:34 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1399)
[15:37:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1176)
[15:37:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[15:37:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
