### ISSUE TITLE
Floods Console with error

### ISSUE THREAD

**Issue by twist3d99** [CitizensDev/Citizens2#3034]
### `/version` output

```txt
1.20.1
api version 1.20.1-R0.1-SNAPSHOT
```

### `/version Citizens` output

```txt
2.0.32-snapshot (build 3135)
```

### Log file

https://paste.denizenscript.com/View/111507

### config.yml

https://paste.denizenscript.com/View/111508

### saves.yml

https://paste.denizenscript.com/View/111509

### Description

Keeps flooding my server with errors.

[21:39:32 WARN]: java.lang.IllegalArgumentException: java.lang.ClassCastException@56d142d1
[21:39:32 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
[21:39:32 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:39:32 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[21:39:32 WARN]:        at Citizens.jar//net.citizensnpcs.EventListen.lambda$registerKnockbackEvent$5(EventListen.java:724)
[21:39:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:39:32 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:39:32 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:39:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[21:39:32 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:39:32 WARN]:        at net.minecraft.world.entity.Entity.push(Entity.java:2120)
[21:39:32 WARN]:        at net.minecraft.world.entity.projectile.EntityArrow.a(EntityArrow.java:419)
[21:39:32 WARN]:        at net.minecraft.world.entity.projectile.IProjectile.a(IProjectile.java:196)
[21:39:32 WARN]:        at net.minecraft.world.entity.projectile.IProjectile.preOnHit(IProjectile.java:187)
[21:39:32 WARN]:        at net.minecraft.world.entity.projectile.EntityArrow.preOnHit(EntityArrow.java:296)
[21:39:32 WARN]:        at net.minecraft.world.entity.projectile.EntityArrow.l(EntityArrow.java:232)
[21:39:32 WARN]:        at net.minecraft.world.entity.projectile.EntityTippedArrow.l(EntityTippedArrow.java:112)
[21:39:32 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:1352)
[21:39:32 WARN]:        at net.minecraft.world.level.World.a(World.java:919)
[21:39:32 WARN]:        at net.minecraft.server.level.WorldServer.lambda$tick$12(WorldServer.java:872)
[21:39:32 WARN]:        at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
[21:39:32 WARN]:        at net.minecraft.server.level.WorldServer.a(WorldServer.java:852)
[21:39:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1543)
[21:39:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[21:39:32 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[21:39:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[21:39:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[21:39:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

[21:50:20 ERROR]: [Shopkeepers] Shopkeeper 17: Error during ticking!
java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:92) ~[Citizens.jar:?]
        at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:132) ~[Citizens.jar:?]
        at com.nisovin.shopkeepers.shopobjects.citizens.SKCitizensShopObject.getNPC(SKCitizensShopObject.java:195) ~[Shopkeepers-2.16.5.jar:?]
        at com.nisovin.shopkeepers.shopobjects.citizens.SKCitizensShopObject.onTick(SKCitizensShopObject.java:664) ~[Shopkeepers-2.16.5.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.AbstractShopkeeper.onTick(AbstractShopkeeper.java:1584) ~[Shopkeepers-2.16.5.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.AbstractShopkeeper.tick(AbstractShopkeeper.java:1540) ~[Shopkeepers-2.16.5.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.ticking.ShopkeeperTicker.tickShopkeeper(ShopkeeperTicker.java:274) ~[Shopkeepers-2.16.5.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.nisovin.shopkeepers.shopkeeper.ticking.ShopkeeperTicker.tickShopkeepers(ShopkeeperTicker.java:244) ~[Shopkeepers-2.16.5.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.ticking.ShopkeeperTicker.access$200(ShopkeeperTicker.java:21) ~[Shopkeepers-2.16.5.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.ticking.ShopkeeperTicker$ShopkeeperTickTask.run(ShopkeeperTicker.java:235) ~[Shopkeepers-2.16.5.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-31]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-31]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-31]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mcmonkey4eva** [comment]
Update, this was already fixed https://ci.citizensnpcs.co/job/Citizens2/
