### ISSUE TITLE
Can not set double field net.citizensnpcs.trait.text.Text.range to java.lang.String

### ISSUE THREAD

**Issue by Blueeyestar** [CitizensDev/Citizens2#3049]
### `/version` output

```txt
Paper version git-Paper-170 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 39953cf)
Previous version: git-Paper-169 (MC: 1.20.1)
```

### `/version Citizens` output

```txt
[07:23:30 INFO]: Citizens version 2.0.32-SNAPSHOT (build 3199)
>....
[07:23:30 INFO]: Website: https://www.citizensnpcs.co
>....
[07:23:30 INFO]: Author: fullwall
```
```
[06:59:10 INFO]: Citizens version 2.0.32-SNAPSHOT (build 3200)
>....
[06:59:10 INFO]: Website: https://www.citizensnpcs.co
>....
[06:59:10 INFO]: Author: fullwall
```

### Log file

https://pastebin.com/x2YjBPSH

### config.yml

https://pastebin.com/pNNjC394

### saves.yml

https://pastebin.com/5tFZKWuh

### Description

With Citizens Version 3199/3200 we get an error from Citizens every time we load it.
```

[07:15:26] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set double field net.citizensnpcs.trait.text.Text.range to java.lang.String
[07:15:26] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[07:15:26] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[07:15:26] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeDoubleFieldAccessorImpl.set(UnsafeDoubleFieldAccessorImpl.java:110)
[07:15:26] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:799)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.api.persistence.PersistenceLoader$PersistField.set(PersistenceLoader.java:134)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.api.persistence.PersistenceLoader.deserialise(PersistenceLoader.java:276)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.api.persistence.PersistenceLoader.load(PersistenceLoader.java:514)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.api.npc.AbstractNPC.loadTraitFromKey(AbstractNPC.java:395)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.api.npc.AbstractNPC.load(AbstractNPC.java:373)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:180)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[07:15:26] [Server thread/WARN]: 	at Citizens-2.0.32-b3199.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:632)
[07:15:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:15:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[07:15:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1111)
[07:15:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[07:15:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[07:15:26] [Server thread/INFO]: [Citizens] 1 NPCs geladen.
```

**Comment by fullwall** [comment]
Update to new build
