### ISSUE TITLE
I have some trouble with citizen plugin.

### ISSUE THREAD

**Issue by enesmio** [CitizensDev/Citizens2#3052]
[00:36:01] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.32-SNAPSHOT (build 3203) (Is it up to date?)
java.lang.RuntimeException: Failed to download library 'ch.ethz.globis.phtree:phtree:2.6.2'
at clib.net.byteflux.libby.LibraryManager.downloadLibrary(LibraryManager.java:382) ~[?:?]
at clib.net.byteflux.libby.LibraryManager.loadLibrary(LibraryManager.java:442) ~[?:?]
at net.citizensnpcs.Citizens.loadMavenLibraries(Citizens.java:304) ~[?:?]
at net.citizensnpcs.Citizens.onEnable(Citizens.java:379) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
at java.lang.Thread.run(Thread.java:1623) ~[?:?]

This is my eror code. But Im already using spigot 1.20 current version and current version of citizen (Citizens-2.0.32-b3203) Here is my all logs: https://paste.denizenscript.com/View/115188
Can anyone help me ? Im so tired of this error.

**Comment by enesmio** [comment]
https://paste.denizenscript.com/View/115188

**Comment by mcmonkey4eva** [comment]
Closing due to not following the issue template, consider asking on Discord  https://discord.gg/Q6pZGSR  instead
