### ISSUE TITLE
Citizens2 ( Citizens-2.0.33-b3331) not compatible on paper-1.20.1-196.jar server

### ISSUE THREAD

**Issue by Shade-emry** [CitizensDev/Citizens2#3098]
### `/version` output

```txt
paper version git-paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
```

### `/version Citizens` output

```txt
https://paste.denizenscript.com/View/120673



   citizens version.bukkit.command.CommandException: Cannot execute command
Buk Come d.COmmand ention: Cannot execute command eite c piu in citin
in plugin Citizens v2.0.33-SNAPSHOT (build 3331) - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(Plug inCommand.java:37) ~[paper-api-1.20.1-RO. 1-SNASHOT. Jar: 2) at org.bukkit.command.SimpleCommandMap.dispatch (SimpleCommandMap. java: 155) ~ [paper-ap1-1.20. 1-RO. 1-SNAPSHOT. jars?] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
~[paper-1.20.1.jar:git-Paper-196]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchServerCommand (CraftServer-java:972)
~ [paper-1.20.1.jar:git-Paper-196]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.1.jar:git-Paper-1961
at net.minecraft-server.dedicated. Dedicatedserver. tickerattserve.ave -Joar-2. 1-Sar 9.20Paner-18-Paper -1961
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java: 1393)
at net.minecraft.server.MinecraftServer.runServer (MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196] at net minecraft.server.MinecraftServer. lambda$spin$0 (MinecraftServer.java:317)[paper-1.20.1.jar:git-Paper-196] at java. lang. Thread. run (Thread.java: 1583) ~[3:7]
```

### Log file

https://paste.denizenscript.com/View/120670

### config.yml

https://paste.denizenscript.com/View/120671

### saves.yml

https://paste.denizenscript.com/View/120672

### Description

when trying to install an v1_20_r1 it will not install.

when trying to install the current stable build, It disables the plugin.

**Comment by fullwall** [comment]
Update to 1.20.4
