### ISSUE TITLE
ClassCastException and NoClassDefFoundError

### ISSUE THREAD

**Issue by ImYenil** [CitizensDev/Citizens2#3100]
### `/version` output

```txt
[10:17:38 INFO]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
[01:45:15 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3350)
[01:45:15 INFO]: Website: https://www.citizensnpcs.co
[01:45:15 INFO]: Authors: fullwall
```

### Log file

https://paste.denizenscript.com/View/120778

### config.yml

https://paste.denizenscript.com/View/120779

### saves.yml

https://paste.denizenscript.com/View/120780

### Description

An error occurs when clicking on an NPC

**Comment by fullwall** [comment]
Try new build

**Comment by ImYenil** [comment]
> Try new build

still doesn't fix

**Comment by ImYenil** [comment]
this issue still doesn't fix
https://pastebin.com/EU11yW3y

**Comment by ImYenil** [comment]
and on disable citizens 
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getStorageContents()[Lorg/bukkit/inventory/ItemStack;
        at net.citizensnpcs.api.trait.trait.Inventory.saveContents(Inventory.java:187) ~[?:?]
        at net.citizensnpcs.api.trait.trait.Inventory.save(Inventory.java:167) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC.save(AbstractNPC.java:418) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.save(CitizensNPC.java:212) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.store(SimpleNPCDataStore.java:82) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.storeAll(SimpleNPCDataStore.java:88) ~[?:?]
        at net.citizensnpcs.Citizens.storeNPCs(Citizens.java:556) ~[?:?]
        at net.citizensnpcs.Citizens.despawnNPCs(Citizens.java:189) ~[?:?]
        at net.citizensnpcs.Citizens.onDisable(Citizens.java:350) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:415) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:408) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:338) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:464) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:668) ~[Hypickle-Server-1.8.8-R0.1-SNAPSHOT.jar:git-Carbon-unknown]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]

**Comment by fullwall** [comment]
That's a completely different error. I'm not sure why but it seems related to your weird server fork.

**Comment by ImYenil** [comment]
> That's a completely different error. I'm not sure why but it seems related to your weird server fork.

I get the same error even if I use paper

**Comment by fullwall** [comment]
Can you try with new build

**Comment by ImYenil** [comment]
> Can you try with new build

[13:11:50 WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/AbstractHorse
[13:11:50 WARN]:        at net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:210)
[13:11:50 WARN]:        at net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:73)
[13:11:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:392)
[13:11:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:360)
[13:11:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:435)
[13:11:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:297)
[13:11:50 WARN]:        at am.mher.cosmetics.Or_YqvM.cy21m$S.spawn(Unknown Source)
[13:11:50 WARN]:        at am.mher.cosmetics.HFR8lvt.hIiOzaP.spawn(Unknown Source)
[13:11:50 WARN]:        at am.mher.cosmetics.KhkN31q.c$t94ve.bG0SCYV(Unknown Source)
[13:11:50 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[13:11:50 WARN]:        at am.mher.cosmetics.KhkN31q.c$t94ve.q75$2Ks(Unknown Source)
[13:11:50 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[13:11:50 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:351)
[13:11:50 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:804)
[13:11:50 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:387)
[13:11:50 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:734)
[13:11:50 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:631)
[13:11:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834) this issue doesn't fix when i use new build

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Cracks
