### ISSUE TITLE
Bug report from "[ModelEngine-4.0.5"

### ISSUE THREAD

**Issue by XiaoYu5530s** [CitizensDev/Citizens2#3108]
### `/version` output

```txt
This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)
```

### `/version Citizens` output

```txt
Citizend version 2.0.33-SNAPSHOT (build 3372)
```

### Log file

https://paste.denizenscript.com/View/121407

### config.yml

https://paste.denizenscript.com/View/121409

### saves.yml

https://paste.denizenscript.com/View/121411

### Description

[01:58:18] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WorldGuard v7.0.8+33cdb4a
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "org.bukkit.entity.EntityType.getName()" is null
	at com.fastasyncworldedit.bukkit.adapter.IBukkitAdapter.adapt(IBukkitAdapter.java:346) ~[FastAsyncWorldEdit-Bukkit-2.9.2-SNAPSHOT-708.jar:?]
	at com.fastasyncworldedit.bukkit.adapter.IDelegateBukkitImplAdapter.adapt(IDelegateBukkitImplAdapter.java:271) ~[FastAsyncWorldEdit-Bukkit-2.9.2-SNAPSHOT-708.jar:?]
	at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:395) ~[FastAsyncWorldEdit-Bukkit-2.9.2-SNAPSHOT-708.jar:?]
	at com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatureSpawn(WorldGuardEntityListener.java:623) ~[worldguard-bukkit-7.0.8-dist.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor77.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:759) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:664) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1514) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1422) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1417) ~[?:?]
	at com.ticxo.modelengine.v1_19_R3.entity.EntityHandlerImpl.lambda$createHitbox$1(EntityHandlerImpl.java:268) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.api.utils.promise.Promise.lambda$thenRunSync$0(Promise.java:102) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.api.utils.promise.AbstractPromise.lambda$thenApplySync$4(AbstractPromise.java:75) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.api.utils.promise.LegacyPromise.executeSync(LegacyPromise.java:25) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.api.utils.promise.AbstractPromise.lambda$thenApplySync$5(AbstractPromise.java:75) ~[ModelEngine-4.0.5.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
	at com.ticxo.modelengine.api.utils.promise.AbstractPromise.thenApplySync(AbstractPromise.java:75) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.api.utils.promise.Promise.thenRunSync(Promise.java:101) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.v1_19_R3.entity.EntityHandlerImpl.createHitbox(EntityHandlerImpl.java:267) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.bone.behavior.SubHitboxImpl.onApply(SubHitboxImpl.java:61) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.bone.ModelBoneImpl.addBoneBehavior(ModelBoneImpl.java:289) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.ActiveModelImpl.generateModel(ActiveModelImpl.java:196) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.ModeledEntityImpl.addModel(ModeledEntityImpl.java:177) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.model.ModeledEntityImpl.load(ModeledEntityImpl.java:294) ~[ModelEngine-4.0.5.jar:?]
	at com.ticxo.modelengine.core.citizens.ModelTrait.onSpawn(ModelTrait.java:69) ~[ModelEngine-4.0.5.jar:?]
	at net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:386) ~[Citizens-[NPC創建].jar:?]
	at net.citizensnpcs.npc.CitizensNPC$1.accept(CitizensNPC.java:354) ~[Citizens-[NPC創建].jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:429) ~[Citizens-[NPC創建].jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:185) ~[Citizens-[NPC創建].jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[Citizens-[NPC創建].jar:?]
	at net.citizensnpcs.Citizens.reload(Citizens.java:464) ~[Citizens-[NPC創建].jar:?]
	at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CitizensHook.forceRespawnAllCustomEntitiesNPCs(SourceFile:121) ~[ItemsAdder_3.4.1c.jar:?]
	at dev.lone.itemsadder.Core.OtherPlugins.Citizens.CitizensHook.reload(SourceFile:62) ~[ItemsAdder_3.4.1c.jar:?]
	at ia.m.ax.a(SourceFile:436) ~[ItemsAdder_3.4.1c.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at ia.m.kO.a(SourceFile:68) ~[ItemsAdder_3.4.1c.jar:?]
	at ia.m.I.c(SourceFile:2419) ~[ItemsAdder_3.4.1c.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by fullwall** [comment]
Not a Citizens error. Try asking FAWE/ModelEngine
