### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#3112]
### /version
```
> version
[09:50:13 INFO]: This server is running Paper version git-Paper-484 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4445d23)
You are running the latest version
Previous version: git-Paper-483 (MC: 1.20.4)
```

### /version Citizens
```
> version Citizens
[09:50:31 INFO]: Citizens version 2.0.33-SNAPSHOT (build 3392)
[09:50:31 INFO]: Website: https://www.citizensnpcs.co
[09:50:31 INFO]: Author: fullwall
```

### Log file

Not relevant, but available if requested

### config.yml
https://paste.denizenscript.com/View/122016

### saves.yml

Not relevant, but available if requested

### Description

```
[09:41:29] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set double field net.citizensnpcs.trait.text.Text.range to java.lang.String
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleDoubleFieldAccessorImpl.set(MethodHandleDoubleFieldAccessorImpl.java:136)
[09:41:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader$PersistField.set(PersistenceLoader.java:132)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader.deserialise(PersistenceLoader.java:273)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader.load(PersistenceLoader.java:507)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.AbstractNPC.loadTraitFromKey(AbstractNPC.java:359)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.AbstractNPC.load(AbstractNPC.java:341)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:180)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:590)
[09:41:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:41:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[09:41:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1142)
[09:41:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:41:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[09:41:29] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set double field net.citizensnpcs.trait.text.Text.range to java.lang.String
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleDoubleFieldAccessorImpl.set(MethodHandleDoubleFieldAccessorImpl.java:136)
[09:41:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader$PersistField.set(PersistenceLoader.java:132)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader.deserialise(PersistenceLoader.java:273)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader.load(PersistenceLoader.java:507)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.AbstractNPC.loadTraitFromKey(AbstractNPC.java:359)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.AbstractNPC.load(AbstractNPC.java:341)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:180)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:590)
[09:41:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:41:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[09:41:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1142)
[09:41:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:41:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[09:41:29] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set double field net.citizensnpcs.trait.text.Text.range to java.lang.String
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[09:41:29] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.MethodHandleDoubleFieldAccessorImpl.set(MethodHandleDoubleFieldAccessorImpl.java:136)
[09:41:29] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Field.java:836)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader$PersistField.set(PersistenceLoader.java:132)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader.deserialise(PersistenceLoader.java:273)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.persistence.PersistenceLoader.load(PersistenceLoader.java:507)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.AbstractNPC.loadTraitFromKey(AbstractNPC.java:359)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.AbstractNPC.load(AbstractNPC.java:341)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:180)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[09:41:29] [Server thread/WARN]: 	at Citizens-2.0.33-b3392.jar//net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:590)
[09:41:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:41:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[09:41:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1142)
[09:41:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[09:41:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by fullwall** [comment]
The logs and saves are both very relevant

**Comment by SlimeDog** [comment]
On subsequent restart(s), the error is no longer generated. Perhaps the config was rewritten with acceptable values?
