### ISSUE TITLE
Missing Kyori library

### ISSUE THREAD

**Issue by SlimeDog** [CitizensDev/Citizens2#3118]
### `/version` output

```txt
> version
[11:09:45 INFO]: This server is running Paper version git-Paper-53 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 5729b29)
You are running the latest version
```

### `/version Citizens` output

```txt
> version Citizens
[11:09:29 INFO]: Citizens version 2.0.34-SNAPSHOT (build 3416)
[11:09:29 INFO]: Website: https://www.citizensnpcs.co
[11:09:29 INFO]: Author: fullwall
```

### Log file

See below

### config.yml

N/A

### saves.yml

N/A

### Description

```
[10:37:38] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.34-SNAPSHOT (build 3416)
[10:37:38] [Server thread/INFO]: [Citizens] Loading external libraries
[10:37:39] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.34-SNAPSHOT (build 3416) (Is it up to date?)
java.lang.RuntimeException: Failed to download library 'net.kyori:adventure-platform-bukkit:4.3.3-SNAPSHOT'
        at Citizens-2.0.34-b3416.jar/clib.net.byteflux.libby.LibraryManager.downloadLibrary(LibraryManager.java:382) ~[Citizens-2.0.34-b3416.jar:?]
        at Citizens-2.0.34-b3416.jar/clib.net.byteflux.libby.LibraryManager.loadLibrary(LibraryManager.java:442) ~[Citizens-2.0.34-b3416.jar:?]
        at Citizens-2.0.34-b3416.jar/net.citizensnpcs.Citizens.loadMavenLibraries(Citizens.java:305) ~[Citizens-2.0.34-b3416.jar:?]
        at Citizens-2.0.34-b3416.jar/net.citizensnpcs.Citizens.onEnable(Citizens.java:375) ~[Citizens-2.0.34-b3416.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-53]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-53]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-53]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-53]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[10:37:39] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.34-SNAPSHOT (build 3416)
```

**Comment by fullwall** [comment]
Make sure your server can access this url: https://s01.oss.sonatype.org/content/repositories/snapshots/net/kyori/adventure-platform-bukkit/4.3.3-SNAPSHOT/adventure-platform-bukkit-4.3.3-20240507.021326-6.jar

**Comment by SlimeDog** [comment]
I have now configured NetworkInterceptor to allow downloads from `s01.oss.sonatype.org`. Thanks.
