### ISSUE TITLE
Cannot invoke "net.citizensnpcs.api.npc.NPC.getEntity()" because "this.hologram" is null

### ISSUE THREAD

**Issue by IAISI** [CitizensDev/Citizens2#3139]
### `/version` output

```txt
Running latest paper 1.21 with Sakura patches on top of it
```

### `/version Citizens` output

```txt
> ver Citizens
[12:17:41 INFO]: Citizens version 2.0.35-SNAPSHOT (build 3494)
[12:17:41 INFO]: Website: https://www.citizensnpcs.co
[12:17:41 INFO]: Author: fullwall
```

### Log file

N/A

### config.yml

N/A

### saves.yml

N/A

### Description

```
com.destroystokyo.paper.exception.ServerSchedulerException: Task #2127644 for Citizens v2.0.35-SNAPSHOT (build 3494) generated an exception
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:486)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "net.citizensnpcs.api.npc.NPC.getEntity()" because "this.hologram" is null
	at Citizens.jar//net.citizensnpcs.trait.HologramTrait$InteractionVehicleRenderer.onSeenByPlayer(HologramTrait.java:637)
	at Citizens.jar//net.citizensnpcs.EventListen.lambda$onNPCLinkToPlayer$4(EventListen.java:478)
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
	... 6 more
```

Latest release on SpigotMc is working fine, we actually tried dev builds cause I saw there are some changes to name handling and depending on the amount of NPCs, Hologram trait could cause lag (updating text using legacy serializer too often), so was hopping this was removed...

Since I'm already here, there's one other thing that might be worth considering...

I terms of performance, I was wondering if this could be skipped altogether if setProtected is set to true for NPC: https://github.com/CitizensDev/Citizens2/blob/c8f6e4f4ec39c6758fc69ffccc20115356f2b851/v1_21_R1/src/main/java/net/citizensnpcs/nms/v1_21_R1/entity/EntityHumanNPC.java#L232

**Comment by mcmonkey4eva** [comment]
closing due to refusal to provide required information
