### ISSUE TITLE
java.lang.IllegalArgumentException: BODY is not valid for players

### ISSUE THREAD

**Issue by ZoruaFox** [CitizensDev/Citizens2#3142]
### `/version` output

```txt
This server is running Leaf version 1.20.6-DEV-ver/1.20.6@f0e36a8 (2024-07-04T12:39:59Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
* You are running the latest version
Previous version: 1.20.6-2233-0d6766e (MC: 1.20.6)
```

### `/version Citizens` output

```txt
Citizens version 2.0.35-SNAPSHOT (build 3496)
```

### Log file

Unnecessary

### config.yml

Unnecessary

### saves.yml

Unnecessary

### Profiler report

Unnecessary

### Description

We believe in a [recent update](https://github.com/CitizensDev/Citizens2/commit/57df21d13b4ff43e06ea02ad610c0c5e8f677931), Citizen handled some logic incorrectly:
```
[10:04:43 INFO]: [Citizens] 更新时发生异常 1: BODY is not valid for players!.
[10:04:43 WARN]: java.lang.IllegalArgumentException: BODY is not valid for players!
[10:04:43 WARN]:        at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.getItem(CraftInventoryPlayer.java:171)
[10:04:43 WARN]:        at Citizens-2.0.35-b3496.jar//net.citizensnpcs.api.trait.trait.Equipment.run(Equipment.java:184)
[10:04:43 WARN]:        at Citizens-2.0.35-b3496.jar//net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:538)
[10:04:43 WARN]:        at Citizens-2.0.35-b3496.jar//net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:478)
[10:04:43 WARN]:        at Citizens-2.0.35-b3496.jar//net.citizensnpcs.nms.v1_20_R4.entity.EntityHumanNPC.tick(EntityHumanNPC.java:359)
[10:04:43 WARN]:        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1445)
[10:04:43 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$9(ServerLevel.java:923)
[10:04:43 WARN]:        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42)
[10:04:43 WARN]:        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:903)
[10:04:43 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:514)
[10:04:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by mcmonkey4eva** [comment]
Try the new dev build @ https://ci.citizensnpcs.co/job/Citizens2/ (3497+), might be fixed
