### ISSUE TITLE
NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R2/boss/CraftBossBar

### ISSUE THREAD

**Issue by kangarko** [CitizensDev/Citizens2#3164]
### `/version` output

```txt
This server is running AdvancedSlimePaper version 1.21.1-16392-paper_upstream@ba950ec (2024-10-21T16:24:13Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.36-SNAPSHOT (build 3602)
```

### Log file

not applicable

### config.yml

not applicable

### saves.yml

not applicable

### Description

Hello!

Since the latest build, it appears to be crashing during server start on 1.21.1.

```
24.10 16:20:36 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R2/boss/CraftBossBar
24.10 16:20:36 [Server] INFO at Citizens-2.0.36-b3602.jar/net.citizensnpcs.nms.v1_21_R2.util.NMSImpl.<clinit>(NMSImpl.java:2694) ~[Citizens-2.0.36-b3602.jar:?]
24.10 16:20:36 [Server] INFO at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
24.10 16:20:36 [Server] INFO at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
24.10 16:20:36 [Server] INFO at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
24.10 16:20:36 [Server] INFO at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
24.10 16:20:36 [Server] INFO at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at Citizens-2.0.36-b3602.jar/net.citizensnpcs.api.util.SpigotUtil.lambda$getMinecraftPackage$1(SpigotUtil.java:171) ~[Citizens-2.0.36-b3602.jar:?]
24.10 16:20:36 [Server] INFO at Citizens-2.0.36-b3602.jar/net.citizensnpcs.api.util.SpigotUtil.getMinecraftPackage(SpigotUtil.java:176) ~[Citizens-2.0.36-b3602.jar:?]
24.10 16:20:36 [Server] INFO at Citizens-2.0.36-b3602.jar/net.citizensnpcs.Citizens.onEnable(Citizens.java:322) ~[Citizens-2.0.36-b3602.jar:?]
24.10 16:20:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
24.10 16:20:36 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:211) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
24.10 16:20:36 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:642) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:591) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
24.10 16:20:36 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
24.10 16:20:36 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R2.boss.CraftBossBar
24.10 16:20:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
24.10 16:20:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
24.10 16:20:36 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
24.10 16:20:36 [Server] INFO ... 21 more
24.10 16:20:36 [Server] INFO [Citizens] Disabling Citizens v2.0.36-SNAPSHOT (build 3602)
```

Everything was working fine a few builds ago and we kept using our setup for over a month with no changes.

Thanks for looking into this.

**Comment by SNWCreations** [comment]
Latest build is for 1.20.3. Please upgrade your server first.

**Comment by kangarko** [comment]
Did you mean 1.21.3? Why is 1.21.1 unsupported already?

Thanks,.

**Comment by SNWCreations** [comment]
> Did you mean 1.21.3? Why is 1.21.1 unsupported already?
> 
> Thanks,.

Yes 1.21.3 sorry for my mis-spell. Citizens only give support for the last patch version of a major Minecraft version as devs can't support many MC version at same time.

**Comment by kangarko** [comment]
Oh, I am sorry I missed that!

I spotted versions down to [v1_8_R3](https://github.com/CitizensDev/Citizens2/tree/master/v1_8_R3) so I thought it's still supported.

On behalf of my users and the community, I would kindly request at least supporting 1.21.1 because it's still extremely early, and we don't even have stable [paper](https://papermc.io/downloads/paper) builds yet.

However, I respect your decision and the time you have available.

Thanks,
Matej

**Comment by SNWCreations** [comment]
We should thank fullwall and everyone who contributed to this.
We can just wait Paper to follow up. Stable builds will come.
Old support modules still exist but at a minimum level of maintainence (small bugfixes only) just for some devs so they could fork the repo and do their own work to keep old versions work.

**Comment by mcmonkey4eva** [comment]
The last build for 1.21.1 is https://ci.citizensnpcs.co/job/Citizens2/3598/

**Comment by kangarko** [comment]
Thank you for the info!
