### ISSUE TITLE
Incompatibility with iDisguise Plugin

### ISSUE THREAD

**Issue by WinPhan254** [CitizensDev/Citizens2#317]
I use Minecraft 1.8.3 with Spigot. This plugin works perfect on its own, however, it does not work with the iDisguise plugin. If I try to /npc create to create an NPC in the Citizens plugin, and I have iDisguise installed also, it causes a Disconnect. However, it doesn't happen if I set my disguise *with iDisguise). Only using Citizens (with iDisguise) does this.  I tested it over and over and determined they are incompatible together. Is this something you can fix? I also posted this in a ticket on the iDisguise page.

Here's the logs:
 [20:52:27 INFO]: WinPhan254 issued server command: /npc create winphan254
 [20:52:27 WARN]: java.lang.NullPointerException
 [20:52:27 WARN]:        at de.robingrether.idisguise.management.DisguiseManager.isDisguised(DisguiseManager.java:169)
 [20:52:27 WARN]:        at de.robingrether.idisguise.management.ChannelHandler.write(ChannelHandler.java:38)
 [20:52:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
 [20:52:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
 [20:52:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
 [20:52:27 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
 [20:52:27 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
 [20:52:27 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
 [20:52:27 WARN]:        at net.minecraft.server.v1_8_R2.NetworkManager$4.run(NetworkManager.java:198)
 [20:52:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
 [20:52:27 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
 [20:52:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
 [20:52:27 WARN]:        at java.lang.Thread.run(Unknown Source)
 [20:52:27 WARN]: java.nio.channels.ClosedChannelException
 [20:52:27 WARN]: java.nio.channels.ClosedChannelException
 [20:52:27 WARN]: java.nio.channels.ClosedChannelException
 [20:52:27 WARN]: java.nio.channels.ClosedChannelException
 [20:52:27 INFO]: WinPhan254 lost connection: Internal Exception: java.lang.NullPointerException
 [20:52:27 INFO]: WinPhan254 left the game.

**Comment by mcmonkey4eva** [comment]
That looks like a problem on iDisguise's end.

**Comment by WinPhan254** [comment]
Yeah, that's why I posted this there first.
