### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Newwings** [CitizensDev/Citizens2#324]
Error in Denizen 
````
[21:47:41 WARN]: [Denizen] Task #146262 for Denizen v0.9.6-SNAPSHOT (build 1573) generated an exception
java.lang.IllegalStateException: getBukkitEntity() called on a non-living NPC
        at net.citizensnpcs.api.npc.AbstractNPC.getBukkitEntity(AbstractNPC.java:184) ~[?:?]
        at net.aufdemrand.denizen.npc.traits.HealthTrait$1.run(HealthTrait.java:159) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c136710-350cb99]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-c136710-350cb99]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-c136710-350cb99]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
```
Shoud be opened in Denizen not Citizens, sorry.

**Comment by mcmonkey4eva** [comment]
Why are you giving the health trait to an NPC that is not alive?

**Comment by Newwings** [comment]
I used npc ```create sdd --type Minecart```. How do I remove tht health trait from an NPC?

**Comment by mcmonkey4eva** [comment]
If it got added somehow `/trait health` - it shouldn't have been added unless a script added it though.

**Comment by Newwings** [comment]
If I use /trait health on the Minecart NPC it returnes ```Removed health successfully```. It is possible to destroy the NPC-Minecart through damaging it. I fixed this problem with a world script of denizen:
```
NoDestroy:
type: world
events:
        on player damages n@137:
            - run Ord_Autohaus_Abholen
            - determine cancelled
        on player enters n@137:
            - run Ord_Autohaus_Abholen
            - determine cancelled
```

**Comment by mcmonkey4eva** [comment]
@fullwall it looks like NPC minecarts are damageable, according to the above? ^

-- Tested and confirmed that.

**Comment by agenttylo** [comment]
i have this error
can some one help me with it
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet

**Comment by mcmonkey4eva** [comment]
@fullwall Have you had any chance to look into this?

**Comment by fullwall** [comment]
@mcmonkey4eva they are but shouldn't it be covered by the damageable metadata?

**Comment by mcmonkey4eva** [comment]
@fullwall They're damageable from the start, `/npc create miney --type minecart` - IE, before you set any metadata values or do any commands or anything. The default mode is non-damageable for all other NPC types.

**Comment by fullwall** [comment]
Does it work with the latest build?
