### ISSUE TITLE
Error with citizens and worlguard 6.0 and sentry?

### ISSUE THREAD

**Issue by jpell1221** [CitizensDev/Citizens2#326]
Cannot use on damage event for skript?

[08:24:38] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to Skript v2.1.2
java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
	at ch.njol.skript.hooks.regions.WorldGuardHook.getRegionsAt_i(WorldGuardHook.java:195) ~[?:?]
	at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:94) ~[?:?]
	at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:158) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:471) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.teleport(CraftEntity.java:200) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:398) [citizens-2.0.13-SNAPSHOT.jar:?]
	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:423) [citizens-2.0.13-SNAPSHOT.jar:?]
	at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:1022) [sentry.jar:?]
	at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:128) [sentry.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:204) [citizens-2.0.13-SNAPSHOT.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:119) [citizens-2.0.13-SNAPSHOT.jar:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) [citizens-2.0.13-SNAPSHOT.jar:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:295) [citizens-2.0.13-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:600) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit_dev_3116.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]

**Comment by mcmonkey4eva** [comment]
That's a Skript error, not Citizens.

Also, Denizen Script > Skript all the way.
