### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by JcTehPiggy** [CitizensDev/Citizens2#366]
This is the message it leaves in Console:

[21:25:18 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[21:25:18 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[21:25:18 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[21:25:18 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[21:25:18 WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
[21:25:18 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:25:18 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:25:18 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:25:18 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[21:25:18 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[21:25:18 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[21:25:18 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[21:25:18 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[21:25:18 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:25:18 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:25:18 WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[21:25:18 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:25:18 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[21:25:18 WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[21:25:18 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:25:18 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[21:25:18 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[21:25:18 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[21:25:18 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:25:18 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:25:18 WARN]: 	... 28 more

**Comment by mcmonkey4eva** [comment]
You're running the wrong version of Citizens2 -> get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by JcTehPiggy** [comment]
Thanks @mcmonkey4eva
