### ISSUE TITLE
NPCs not being created? Help!

### ISSUE THREAD

**Issue by XxScrewshotxX** [CitizensDev/Citizens2#387]
Here is the error message I get:
[09:09:46 WARN]: java.lang.NullPointerException
[09:09:46 WARN]:        at de.robingrether.idisguise.management.DisguiseManager.
isDisguised(DisguiseManager.java:177)
[09:09:46 WARN]:        at de.robingrether.idisguise.management.ChannelHandler.w
rite(ChannelHandler.java:45)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
Write(AbstractChannelHandlerContext.java:658)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(
AbstractChannelHandlerContext.java:716)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:706)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:741)
[09:09:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush
(DefaultChannelPipeline.java:895)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(Abstra
ctChannel.java:240)
[09:09:46 WARN]:        at net.minecraft.server.v1_8_R2.NetworkManager$4.run(Net
workManager.java:198)
[09:09:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.ru
nAllTasks(SingleThreadEventExecutor.java:380)
[09:09:46 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:357)
[09:09:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[09:09:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:09:46 WARN]: java.lang.NullPointerException
[09:09:46 WARN]:        at de.robingrether.idisguise.management.DisguiseManager.
isDisguised(DisguiseManager.java:177)
[09:09:46 WARN]:        at de.robingrether.idisguise.management.ChannelHandler.w
rite(ChannelHandler.java:45)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
Write(AbstractChannelHandlerContext.java:658)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(
AbstractChannelHandlerContext.java:716)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:706)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:741)
[09:09:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush
(DefaultChannelPipeline.java:895)
[09:09:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(Abstra
ctChannel.java:240)
[09:09:46 WARN]:        at net.minecraft.server.v1_8_R2.NetworkManager$4.run(Net
workManager.java:198)
[09:09:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.ru
nAllTasks(SingleThreadEventExecutor.java:380)
[09:09:46 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:357)
[09:09:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[09:09:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:09:47 WARN]: java.lang.NullPointerException
[09:09:47 WARN]:        at de.robingrether.idisguise.management.DisguiseManager.
isDisguised(DisguiseManager.java:177)
[09:09:47 WARN]:        at de.robingrether.idisguise.management.ChannelHandler.w
rite(ChannelHandler.java:45)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
Write(AbstractChannelHandlerContext.java:658)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(
AbstractChannelHandlerContext.java:716)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:706)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:741)
[09:09:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush
(DefaultChannelPipeline.java:895)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(Abstra
ctChannel.java:240)
[09:09:47 WARN]:        at net.minecraft.server.v1_8_R2.NetworkManager$4.run(Net
workManager.java:198)
[09:09:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.ru
nAllTasks(SingleThreadEventExecutor.java:380)
[09:09:47 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:357)
[09:09:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[09:09:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[09:09:47 WARN]: java.lang.NullPointerException
[09:09:47 WARN]:        at de.robingrether.idisguise.management.DisguiseManager.
isDisguised(DisguiseManager.java:177)
[09:09:47 WARN]:        at de.robingrether.idisguise.management.ChannelHandler.w
rite(ChannelHandler.java:45)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invoke
Write(AbstractChannelHandlerContext.java:658)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(
AbstractChannelHandlerContext.java:716)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:706)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeA
ndFlush(AbstractChannelHandlerContext.java:741)
[09:09:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush
(DefaultChannelPipeline.java:895)
[09:09:47 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(Abstra
ctChannel.java:240)
[09:09:47 WARN]:        at net.minecraft.server.v1_8_R2.NetworkManager$4.run(Net
workManager.java:198)
[09:09:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.ru
nAllTasks(SingleThreadEventExecutor.java:380)
[09:09:47 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.ja
va:357)
[09:09:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.
run(SingleThreadEventExecutor.java:116)
[09:09:47 WARN]:        at java.lang.Thread.run(Unknown Source)

The problem is that when I do /npc create <name> it does not create an npc, however it does say the npc has been created. I have been having this problem for 2 days and nothing has come up. I have the latest npcs version and the latest craftbukkit but it still doesn't work. Please help, thanks.

**Comment by Talamar1** [comment]
None of those errors have anything to do with Citizen, looks like DisguiseManager is broken, go fix that.

**Comment by XxScrewshotxX** [comment]
so disguisemanager is the reason citizens won't be created?

**Comment by Talamar1** [comment]
I would imagine, since none of these errors are Citizen related.

**Comment by XxScrewshotxX** [comment]
ok
thanks

**Comment by XxScrewshotxX** [comment]
That worked, thank you
