### ISSUE TITLE
Please Report These Error ( While Creating NPC )

### ISSUE THREAD

**Issue by 1Mido** [CitizensDev/Citizens2#394]
WhenEver I create an npc it says : Please Report These Error [ See Console ]
java.lang.NoClassdefFoundError:net/minecraft/server/v_1_8_R1/packet

Version :  2.0.14 (alpha 1 for MC 1.8.1)

Console : 
2015-05-26T08:55:34.903047704Z >
[08:55:34 WARN]: 	... 28 more
2015-05-26T08:55:34.902972332Z >
[08:55:34 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-05-26T08:55:34.902900409Z >
[08:55:34 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-05-26T08:55:34.902829207Z >
[08:55:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
2015-05-26T08:55:34.902739497Z >
[08:55:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
2015-05-26T08:55:34.902660499Z >
[08:55:34 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
2015-05-26T08:55:34.902593076Z >
[08:55:34 WARN]: 	at java.lang.Thread.run(Thread.java:745)
2015-05-26T08:55:34.902527768Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
2015-05-26T08:55:34.902453678Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
2015-05-26T08:55:34.902368620Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
2015-05-26T08:55:34.902295846Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712)
2015-05-26T08:55:34.902187943Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
2015-05-26T08:55:34.902108880Z >
[08:55:34 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2015-05-26T08:55:34.902035577Z >
[08:55:34 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2015-05-26T08:55:34.901961592Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
2015-05-26T08:55:34.901884433Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
2015-05-26T08:55:34.901803386Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
2015-05-26T08:55:34.901704148Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
2015-05-26T08:55:34.901622121Z >
[08:55:34 WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
2015-05-26T08:55:34.901539668Z >
[08:55:34 WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
2015-05-26T08:55:34.901438641Z >
[08:55:34 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
2015-05-26T08:55:34.899287183Z >
[08:55:34 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2015-05-26T08:55:34.899234154Z >
[08:55:34 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
2015-05-26T08:55:34.899167436Z >
[08:55:34 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
2015-05-26T08:55:34.899121577Z >
[08:55:34 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
2015-05-26T08:55:34.899078795Z >
[08:55:34 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
2015-05-26T08:55:34.899018558Z >
[08:55:34 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:483)
2015-05-26T08:55:34.898970930Z >
[08:55:34 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-05-26T08:55:34.898922415Z >
[08:55:34 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-05-26T08:55:34.898867162Z >
[08:55:34 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-05-26T08:55:34.898841557Z >
[08:55:34 WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
2015-05-26T08:55:34.898771122Z >
[08:55:34 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
2015-05-26T08:55:34.898711160Z >
[08:55:34 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
2015-05-26T08:55:34.898654536Z >
[08:55:34 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
2015-05-26T08:55:34.898613187Z >
[08:55:34 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
2015-05-26T08:55:34.776261532Z >
[08:55:34 INFO]: Mido_ issued server command: /npc create smith 12 12 12

**Comment by fullwall** [comment]
You are using a version of Citizens which is too old for your Spigot version.

**Comment by 1Mido** [comment]
my spigot is 1.8 ? and i am using 1.8.1

**Comment by mcmonkey4eva** [comment]
Your spigot is 1.8.3 actually.

Get the relevant Citizens version here: http://wiki.citizensnpcs.co/Versions

**Comment by ZoeZoe-MP3** [comment]
I am using the minehut server hosting, and now my Citizens stop working out of the blue... when I restart my server... Now I am getting this error called http://java.lang.NoClassDefFoundError.
I would love some help lol, I am not good with these kinda things.

**Comment by mcmonkey4eva** [comment]
@ZoeZoe-MP3 You've replied to a random issue from 2015. Open a new issue to report a problem.
