### ISSUE TITLE
An important aid request of plugin citizens

### ISSUE THREAD

**Issue by darcking** [CitizensDev/Citizens2#397]
hello,
I have a problem with the pluging Citizens it does not work how can I succeed to make it work
help me do the six months that pluging not work with me
I hope you will help me thank you

**Comment by Archious** [comment]
What citizens versions are u using?
posts your console error too.

**Comment by Morphan1** [comment]
If only I could read this.

**Comment by darcking** [comment]
hellos,
here is the error happens:


[15:02:43] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R3/Entity [15:02:43] [Server thread/WARN]: at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:111) [15:02:43] [Server thread/WARN]: at net.citizensnpcs.resources.npclib.NPCManager.register(NPCManager.java:136) [15:02:43] [Server thread/WARN]: at net.citizensnpcs.commands.BasicCommands.create(BasicCommands.java:218) [15:02:43] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [15:02:43] [Server thread/WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [15:02:43] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [15:02:43] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:606) [15:02:43] [Server thread/WARN]: at net.citizensnpcs.resources.sk89q.CommandsManager.executeMethod(CommandsManager.java:254) [15:02:43] [Server thread/WARN]: at net.citizensnpcs.resources.sk89q.CommandsManager.execute(CommandsManager.java:146) [15:02:43] [Server thread/WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:145) [15:02:43] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [15:02:43] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) [15:02:43] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:957) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:818) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:47) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:157) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.ServerConnection.c(SourceFile:134) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:667) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [15:02:43] [Server thread/WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [15:02:43] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_6_R3.Entity [15:02:43] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) [15:02:43] [Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) [15:02:43] [Server thread/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:425) [15:02:43] [Server thread/WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:358) [15:02:43] [Server thread/WARN]: ... 24 more

**Comment by Morphan1** [comment]
You're using a Minecraft 1.6.X (1.6.4? Where even did you find that) version of Citizens2 on a 1.7.10 server.
If you want to upgrade Citizens2 to your version, get it from http://wiki.citizensnpcs.co/Versions
Any problems that occur on such old builds will most likely not be helped.

**Comment by darcking** [comment]
hello thanks to you it finally walking to thank you I would like to offer you a grade on my minecraft server but is in French I'm doing not so bad in English but stp accept this gift from me
m1.minecraft-illimity.com:25458

**Comment by mcmonkey4eva** [comment]
Please do not advertise your server here. We're here to help you get things running, not play on your server.

Glad to hear everything's now working. Closing on the assumption that this is accurate. If it is not, please leave a message below and we will reopen.
