### ISSUE TITLE
Spigot 1.8.3

### ISSUE THREAD

**Issue by Richard333** [CitizensDev/Citizens2#400]
Upon booting up the sever I get this error:

[02:10:31] [Server thread/WARN]: [Citizens] Task #52 for Citizens v2.0.14-SNAPSHOT (build 1212) generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56) ~[?:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:295) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-1d14d5f-ba32592]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:718) [server.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [server.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [server.jar:git-Spigot-1d14d5f-ba32592]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [server.jar:git-Spigot-1d14d5f-ba32592]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[server.jar:git-Spigot-1d14d5f-ba32592]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-1d14d5f-ba32592]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_45]
	... 11 more

Upon trying to create a Npc it gives me this error:

[02:10:58] [Server thread/INFO]: Richard333 issued server command: /npc
[02:11:02] [Server thread/INFO]: Richard333 issued server command: /npc create Steve
[02:11:02] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:324)
[02:11:02] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:11:02] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:11:02] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:11:02] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[02:11:02] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[02:11:02] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:11:02] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[02:11:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[02:11:02] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[02:11:02] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[02:11:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[02:11:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:11:02] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[02:11:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[02:11:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[02:11:02] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:11:02] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:11:02] [Server thread/WARN]: 	... 28 more

I'm using citizens 2.0.14 on a Spigot 1.8.3 build.

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens. http://wiki.citizensnpcs.co/Versions

**Comment by Richard333** [comment]
Thank you for giving me a link to the newer versions.
