### ISSUE TITLE
1.8.7/1.8.6- Citizens2 fails/console spam

### ISSUE THREAD

**Issue by brooklynstarr** [CitizensDev/Citizens2#419]
In 1.8.7 or 1.8.6, I get the following two errors spammed on the console; Citizens does not function:

[14:51:31] [Server thread/ERROR]: [Citizens] An exception occurred while the trait particles was spawning for NPC ID 258.
[14:51:31] [Server thread/WARN]: java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getBukkitEntity()Lorg/bukkit/entity/LivingEntity;
[14:51:31] [Server thread/WARN]: 	at net.aufdemrand.denizen.npc.traits.ParticlesTrait.onSpawn(ParticlesTrait.java:114)
[14:51:31] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:220)
[14:51:31] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:125)
[14:51:31] [Server thread/WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[14:51:31] [Server thread/WARN]: 	at net.citizensnpcs.Citizens$2.run(Citizens.java:295)
[14:51:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:51:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[14:51:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
[14:51:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[14:51:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[14:51:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[14:51:31] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

And

[14:52:42] [Server thread/ERROR]: [Citizens] An exception occurred while the trait health was spawning for NPC ID 214.
[14:52:42] [Server thread/WARN]: java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getBukkitEntity()Lorg/bukkit/entity/LivingEntity;
[14:52:42] [Server thread/WARN]: 	at net.aufdemrand.denizen.npc.traits.HealthTrait.setHealth(HealthTrait.java:219)
[14:52:42] [Server thread/WARN]: 	at net.aufdemrand.denizen.npc.traits.HealthTrait.onSpawn(HealthTrait.java:150)
[14:52:42] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:220)
[14:52:42] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.HumanController$SkinFetcher$1.run(HumanController.java:270)
[14:52:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[14:52:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[14:52:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726)
[14:52:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[14:52:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[14:52:42] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[14:52:42] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

-workaround-

Using 1.8.6 with build 1239 solves the issue.

Let me know if you need more info.

Thanks!

**Comment by mcmonkey4eva** [comment]
Update Denizen to latest dev build from http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/

**Comment by brooklynstarr** [comment]
That did it. I've bookmarked the page so I can try from there if I'm having any other issues.

Thanks!
