### ISSUE TITLE
I Have This Problem

### ISSUE THREAD

**Issue by stelioshah** [CitizensDev/Citizens2#425]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:122) ~[?:?]
at net.aufdemrand.sentry.Sentry.getSentry(Sentry.java:295) ~[?:?]
at net.aufdemrand.sentry.SentryListener.entteleportevent(SentryListener.java:82) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_55

**Comment by mcmonkey4eva** [comment]
Acquire the correct versions of your Citizens-related plugins here: http://wiki.citizensnpcs.co/Versions
