### ISSUE TITLE
Citizens Creating NPC Error

### ISSUE THREAD

**Issue by boomboompower** [CitizensDev/Citizens2#427]
Whenever I do /npc create {name} I get this error in the console:
If anyone could help, it would be great.

[16:07:51] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
[16:07:51] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:07:51] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:07:51] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:07:51] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[16:07:51] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[16:07:51] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:07:51] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:07:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[16:07:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632)
[16:07:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405)
[16:07:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369)
[16:07:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[16:07:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[16:07:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:07:51] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[16:07:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[16:07:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:07:51] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:07:51] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:07:51] [Server thread/WARN]: 	... 21 more

**Comment by mcmonkey4eva** [comment]
Acquire the correct versions of your Citizens-related plugins here: http://wiki.citizensnpcs.co/Versions

**Comment by boomboompower** [comment]
So I need all 4 of these plugins for it to work?

**Comment by mcmonkey4eva** [comment]
No.

**Comment by boomboompower** [comment]
Tested, still does not work. I get the same error.
