### ISSUE TITLE
Citizens wont load on spigot 1.8.3

### ISSUE THREAD

**Issue by LegendOfzLink** [CitizensDev/Citizens2#429]
Hi! I am currently using spigot 1.8.3 and am using the citizens build 1.8.3. I keep on getting this error!
(Note i do not have any other citizens plugins)
[01:51:39] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.15-SNAPSHOT (build 1230)
[01:51:39] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.15-SNAPSHOT (build 1230) (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method "net.citizensnpcs.api.CitizensAPI.setImplementation(Lnet/citizensnpcs/api/CitizensPlugin;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, net/citizensnpcs/Citizens, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, net/citizensnpcs/api/CitizensAPI, have different Class objects for the type net/citizensnpcs/api/CitizensPlugin used in the signature
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:257) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:286) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by mcmonkey4eva** [comment]
You... have Citizens twice or a copy of the API downloaded or something. I don't know what you did but you did it very wrong.

**Comment by LegendOfzLink** [comment]
thats weird.
Ill check

**Comment by Kaladial** [comment]
[17:56:45] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1244) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R3/CraftServer
	at net.citizensnpcs.util.Util.getMinecraftRevision(Util.java:78) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:260) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R3.CraftServer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	... 13 more

i have same with spigot 1.8.3
can you help us?
pls ;)

mfg kala

**Comment by mcmonkey4eva** [comment]
@Kaladial Wrong version of C2 downloaded, acquire the correct version here: http://wiki.citizensnpcs.co/Versions

**Comment by conetopia** [comment]
Citizens Config
advanced:
  check-minecraft-version: true
Needs to be false
