### ISSUE TITLE
Build #1244 Does not load on Spigot 1.8.3

### ISSUE THREAD

**Issue by Stuperfied** [CitizensDev/Citizens2#433]
Got simply there was an error loading this plugin
[08:49:54] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1244)
[08:49:54] [Server thread/INFO]: Creating file: config.yml
[08:49:54] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1244) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R3/CraftServer
	at net.citizensnpcs.util.Util.getMinecraftRevision(Util.java:78) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:260) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:746) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R3.CraftServer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8_server.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 25 more
[08:49:54] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.7.19

**Comment by mcmonkey4eva** [comment]
That build is for 1.8.7. Get the correct version here: http://wiki.citizensnpcs.co/Versions

**Comment by Stuperfied** [comment]
Oh ok. Im using 1222 now and it works. Will update to 1230 later.

**Comment by mcmonkey4eva** [comment]
Cause Bukkit does not include an NPC API, we built entirely our own directly on top of Mojang's internal server (NMS) code. We use Bukkit solely to allow inter-operability with other plugins, not for any actual functionality.

Sponge promises to make it possible for us to not do this though, so let's hope that comes true.
