### ISSUE TITLE
Trouble using /npc create

### ISSUE THREAD

**Issue by ChaseThis** [CitizensDev/Citizens2#436]
I am having trouble using the /npc create command. When I execute this CMD, it says to check console and this is what console is saying:

`
[18:27:07 INFO]: Chase_This issued server command: /npc create Chase_This
[18:27:08 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Pa
cket
[18:27:08 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:92)
[18:27:08 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[18:27:08 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[18:27:08 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:320)
[18:27:08 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[18:27:08 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[18:27:08 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[18:27:08 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[18:27:08 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:154)
[18:27:08 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:90)
[18:27:08 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:178)
[18:27:08 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[18:27:08 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[18:27:08 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[18:27:08 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCo
mmand(CraftServer.java:646)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnection.handleC
ommand(PlayerConnection.java:1137)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnection.a(Playe
rConnection.java:972)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(Packe
tPlayInChat.java:1)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.
run(SourceFile:13)
[18:27:08 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[18:27:08 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile
:60)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.A(Minecr
aftServer.java:710)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.A(Dedica
tedServer.java:368)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.z(Minecr
aftServer.java:651)
[18:27:08 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(Mine
craftServer.java:554)
[18:27:08 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:27:08 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.serv
er.v1_8_R1.Packet
[18:27:08 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:91)
[18:27:08 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:86)
[18:27:08 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:27:08 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:27:08 WARN]:        ... 28 more
>

`

**Comment by mcmonkey4eva** [comment]
Wrong version. http://wiki.citizensnpcs.co/Versions

**Comment by ChaseThis** [comment]
Forgot to mention that I have tried the newest version for 1.8.6 and that does not work, it says [Citizens]: ERROR "Is it up to date?" then disables Citizens from running, when i type /pl and see my plugins, I see Citizens in Red and all other plugins are in Green. Keep in mind, I am running a 1.8.x server and my version supports 1.8.1 and lower blocks. Sorry for not mentioning that, but I do hope that this will help out this investigation.

**Comment by mcmonkey4eva** [comment]
We build for 1.8.7 - update your server

**Comment by ChaseThis** [comment]
I just updated my server to 1.8.7 Spigot and downloaded the latest build and It says this in console:

[ERROR]: [Citizens] v2.0.16-SNAPSHOT (build 1239) is not compatible wit
h Minecraft v1.8.7 - try upgrading or downgrading Citizens. Disabling.

**Comment by mcmonkey4eva** [comment]
That's like 15 builds behind. Get the latest dev build from the link above.
