### ISSUE TITLE
I got this error after NPC death

### ISSUE THREAD

**Issue by BorowskiKamil** [CitizensDev/Citizens2#457]
[00:01:21 ERROR]: Could not pass event EntityDeathEvent to Citizens v2.0.16-SNAPSHOT (build 1247)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:377) [spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:370) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:876) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityTameableAnimal.die(SourceFile:185) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityWolf.damageEntity(EntityWolf.java:213) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1328) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6d16e64-b105298]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6d16e64-b105298]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:209) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6d16e64-b105298]
        ... 23 more

**Comment by Talamar1** [comment]
Try updating to latest, there were some patches made to despawning NPCs.

**Comment by BorowskiKamil** [comment]
Still got this:
[18:50:34 ERROR]: Could not pass event EntityDeathEvent to Citizens v2.0.16-SNAPSHOT (build 1251)
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:377) [spigot.jar:git-Spigot-6d16e64-b105298]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:370) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:876) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityTameableAnimal.die(SourceFile:185) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityWolf.damageEntity(EntityWolf.java:213) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1328) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6d16e64-b105298]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-6d16e64-b105298]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-6d16e64-b105298]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException

**Comment by mcmonkey4eva** [comment]
```at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:209) ~[?:?]```
Corresponds to https://github.com/CitizensDev/Citizens2/blob/master/src/main/java/net/citizensnpcs/EventListen.java#L209
... which is a `}`
Which I'm fairly sure can't throw an error.
Sooooooooo....

**Comment by Talamar1** [comment]
You stopped pasting the second one at the NPE error, but the lines AFTER that have the actual error in Citizens, please paste the added log lines.  We need the ones that start with 
'''
at net.citizensnpcs.

**Comment by BorowskiKamil** [comment]
There is a problem with location, I think.
<code>Caused by: java.lang.NullPointerException
        at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:219) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6d16e64-b105298]
        ... 23 more</code>

**Comment by mcmonkey4eva** [comment]
You now have an NPE on
`npc.data().remove(NPC.SCOREBOARD_FAKE_TEAM_NAME_METADATA);`
Which... also can't throw an NPE.
