### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by AzenoX** [CitizensDev/Citizens2#461]
I cannot create npc :

[19:59:19 INFO]: AzenoX issued server command: /npc create 1vs1
[19:59:19 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Pa
cket
[19:59:19 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:92)
[19:59:19 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[19:59:19 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[19:59:19 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:320)
[19:59:19 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[19:59:19 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[19:59:19 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[19:59:19 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[19:59:19 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:154)
[19:59:19 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:90)
[19:59:19 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:178)
[19:59:19 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[19:59:19 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[19:59:19 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[19:59:19 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCo
mmand(CraftServer.java:642)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleC
ommand(PlayerConnection.java:1135)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(Playe
rConnection.java:970)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(Packe
tPlayInChat.java:1)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.
run(SourceFile:13)
[19:59:19 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[19:59:19 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtil
s.java:19)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:714)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:367)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:653)
[19:59:19 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:556)
[19:59:19 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:59:19 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.serv
er.v1_8_R1.Packet
[19:59:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:91)
[19:59:19 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:86)
[19:59:19 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[19:59:19 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[19:59:19 WARN]:        ... 28 more
>

**Comment by Talamar1** [comment]
What build of Cit are you on?

**Comment by mcmonkey4eva** [comment]
The wrong one. Can get the correct one here: http://wiki.citizensnpcs.co/Versions
