### ISSUE TITLE
Citizen close my server

### ISSUE THREAD

**Issue by keliann123** [CitizensDev/Citizens2#477]
Hello, i'm sorry if i'm bad in english, i'm from belgium ^^
So, i want to make some clone for my minecraft 1.7.10 server, so then i instal it and i see with the command /pl he's in red (he don't work) i see we can convert the file, i tryied it but i have an error 500 when i start to convert, please help me, thanks ^^ !

**Comment by mcmonkey4eva** [comment]
You can find the correct version of the plugin here: http://wiki.citizensnpcs.co/Versions

**Comment by keliann123** [comment]
Hello, when i create a NPC the server stop, and it say : Server closed

**Comment by keliann123** [comment]
I paste you the error

**Comment by keliann123** [comment]
[17:11:44] [Server thread/INFO]: [Citizens] Loaded 1 NPCs.
[17:11:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking entity
 at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1649]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
 at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
 at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
 at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[minecraft_server.jar:git-Spigot-1649]
 ... 4 more
[17:11:44] [Server thread/ERROR]:  Cause of unexpected exception was
java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
 at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
 at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
 at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [minecraft_server.jar:git-Spigot-1649]
 at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Spigot-1649]
[17:11:44] [Server thread/ERROR]: This crash report has been saved to: /home/keliann123/server_24922/./crash-reports/crash-2015-08-08_17.11.44-server.txt

**Comment by BlackCoyote** [comment]
Welke versie van citizens gebruik je?
Which version of citizens do you use?

**Comment by keliann123** [comment]
I downloaded the version about this comment : 
 mcmonkey4eva commented 17 hours ago

You can find the correct version of the plugin here: http://wiki.citizensnpcs.co/Versions
I taked it and it's closing my server

**Comment by keliann123** [comment]
I taked the plugin for 1.7.10 server

**Comment by mcmonkey4eva** [comment]
You grabbed the wrong version ~ you probably have the 1.8 protocol hack

http://wiki.citizensnpcs.co/Versions

**Comment by keliann123** [comment]
I taked the 1.7.10 version, it's the same problem :/  I dont know if i'm bad to download or not, have you skype ? Or i can take a vidéo and upload it and after i send you the vidéo but it's doesn't work :/

**Comment by mcmonkey4eva** [comment]
If you're not going to read replies, you're not going to get help :)
