### ISSUE TITLE
have an issue with the lastest dev build of citizens

### ISSUE THREAD

**Issue by GeForcez** [CitizensDev/Citizens2#494]
hi all can you take a look at this i'm running 1.8.8 spigot and lastest dev version of citizens also lastest dev version of denizen and sentry
EDIT: version of citizens build(1253)
         tried it with 1252 and seems a problem with one of my npc's its skin is gone but it was also an npc with denizen or sentry because its only that npc that lost its skin the rest is fine oh and in 1252 all works fine only the skin of that one npc is gone. EDIT2: skin came back after reload.

``` java
[00:11:34 WARN]: [Citizens] Task #37 for Citizens v2.0.16-SNAPSHOT (build 1253) generated an exception
java.lang.NullPointerException: data cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[spigot.jar:git-Spigot-fdc1440-53f
ac9f]
        at net.citizensnpcs.api.npc.SimpleMetadataStore.checkPrimitive(SimpleMetadataStore.java:15) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleMetadataStore.setPersistent(SimpleMetadataStore.java:86) ~[?:?]
        at net.citizensnpcs.api.npc.AbstractNPC$1.setPersistent(AbstractNPC.java:64) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.setNPCSkinData(Skin.java:227) ~[?:?]
        at net.citizensnpcs.npc.skin.Skin.apply(Skin.java:154) ~[?:?]
        at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:86) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:186) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:132) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:295) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-fdc1440-53f
ac9f]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.
jar:git-Spigot-fdc1440-53fac9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-fdc1440-53fac
9f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac
9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac
9f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53f
ac9f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
```

**Comment by GeForcez** [comment]
1252 works fine see edit above :D trying to get you more info from this error :dancer:

**Comment by fullwall** [comment]
The error is fixed but a new bug is there.
@JCThePants when the plugin is reloaded the skin does not reload, even if you set the skin again to the same name. Also, the -p option of /npc skin is not implemented. The old behavior was to reload the skin on every start up and only cache the skin if -p was used. This is for when people change their skins etc.

**Comment by JCThePants** [comment]
@fullwall I'll have a fix ready sometime tomorrow

**Comment by GeForcez** [comment]
thx guys you are so awesome and really fast in replying :D
