### ISSUE TITLE
When I do /npc create.

### ISSUE THREAD

**Issue by ManUtdPlaysMC** [CitizensDev/Citizens2#504]
[08:31:26 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[08:31:26 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[08:31:26 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[08:31:26 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[08:31:26 WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:320)
[08:31:26 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:31:26 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[08:31:26 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:31:26 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[08:31:26 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[08:31:26 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[08:31:26 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[08:31:26 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[08:31:26 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:31:26 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:31:26 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[08:31:26 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[08:31:26 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[08:31:26 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[08:31:26 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[08:31:26 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[08:31:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[08:31:26 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[08:31:26 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[08:31:26 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[08:31:26 WARN]: 	... 28 more

**Comment by mcmonkey4eva** [comment]
Wrong Citizens version -> http://wiki.citizensnpcs.co/Versions
