### ISSUE TITLE
Java error on server shutdown

### ISSUE THREAD

**Issue by Talamar1** [CitizensDev/Citizens2#517]
```
[17:58:26 INFO]: [Citizens] Disabling Citizens v2.0.16-SNAPSHOT (build 1260)
[17:58:26 WARN]: java.lang.NullPointerException
[17:58:26 WARN]:        at net.aufdemrand.denizen.npc.traits.SittingTrait.onDespawn(SittingTrait.java:45)
[17:58:26 WARN]:        at net.citizensnpcs.Citizens.despawnNPCs(Citizens.java:110)
[17:58:26 WARN]:        at net.citizensnpcs.Citizens.onDisable(Citizens.java:249)
[17:58:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[17:58:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[17:58:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[17:58:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[17:58:26 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
[17:58:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
[17:58:26 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:592)
[17:58:26 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mcmonkey4eva** [comment]
This is a Denizen issue; please report it there.
