### ISSUE TITLE
Errors happens after Start up of server

### ISSUE THREAD

**Issue by DeadIntermediate** [CitizensDev/Citizens2#547]
I am getting errors when everytime I start up the server.

Here is the Pastebin: http://pastebin.com/rTf9ihrg#1005

The error code starts at: 808 to 997

**Comment by mcmonkey4eva** [comment]
```
[21:18:30] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at com.dsh105.echopet.api.pet.Pet.getCraftPet(Pet.java:82) ~[?:?]
        at com.dsh105.echopet.api.pet.Pet.getLocation(Pet.java:87) ~[?:?]
```

I wasn't aware we were the EchoPet support page?

**Comment by fullwall** [comment]
EchoPet problem, also EchoPet doesn't use Citizens so not related to Citizens there either.
