### ISSUE TITLE
NullPointerException on spawning a Player

### ISSUE THREAD

**Issue by NomNuggetNom** [CitizensDev/Citizens2#570]
The following code:
```
NPCRegistry register = CitizensAPI.getNPCRegistry();
NPC npc = register.createNPC(EntityType.PLAYER, "NomNuggetNom");
npc.spawn(l);
```

Results in the following error:
```
[05:48:28 ERROR]: java.lang.NullPointerException
[05:48:28 ERROR]:     at io.netty.channel.DefaultChannelConfig.setRecvByteBufAllocator(DefaultChannelConfig.java:290)
[05:48:28 ERROR]:     at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:74)
[05:48:28 ERROR]:     at io.netty.channel.DefaultChannelConfig.<init>(DefaultChannelConfig.java:70)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.network.EmptyChannel.<init>(EmptyChannel.java:14)
[05:48:28 ERROR]:     at net.citizensnpcs.util.NMS.initNetworkManager(NMS.java:423)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.network.EmptyNetworkManager.<init>(EmptyNetworkManager.java:12)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:220)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:78)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[05:48:28 ERROR]:     at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:186)
```

I'm using version 2.0.16-SNAPSHOT build 1277 with Spigot version 1.8.8. When I change the `EntityType` to be `EntityType.COW`, it works fine. In fact, I haven't found anything else that is broken.

**Comment by fullwall** [comment]
Very odd... the error seems to be from Netty (someone setting an incorrect default byte buf allocator?) but it could be a spigot version issue.

**Comment by mcmonkey4eva** [comment]
@NomNuggetNom are you still having trouble after updating to latest versions?

**Comment by fullwall** [comment]
I looked into this but seemed to be a Netty version mismatch as the code line numbers were different and nothing I could find sets the default byte buf allocator.

**Comment by NomNuggetNom** [comment]
It's very likely that. What version of netty do you guys run?

**Comment by fullwall** [comment]
@NomNuggetNom - we don't include netty at all, so it would be from another source.

**Comment by fullwall** [comment]
Is this still an issue?

**Comment by NomNuggetNom** [comment]
@fullwall Yes, it is. Using build 1297. Same error. I need to figure out what version of netty I should be using, as we're just using the latest possible, which is where the problem is arising.

**Comment by mcmonkey4eva** [comment]
@NomNuggetNom ... you... use the netty that comes with Spigot, not your own... normally...

**Comment by NomNuggetNom** [comment]
@mcmonkey4eva Yes, I know, but we don't use the normal Spigot.

**Comment by mcmonkey4eva** [comment]
@NomNuggetNom we're limited in what we can do for you. If you're not running Spigot, you're not running what we build for. Can you replicate this error in a real-Spigot test environment?

**Comment by NomNuggetNom** [comment]
@mcmonkey4eva I'm going to switch our netty version back to whatever Spigot comes with, once I figure out what that is. If I still have an error, I'll switch to a clean Spigot build to test.

**Comment by NomNuggetNom** [comment]
Downgrading netty (to version `4.1.0.Beta6`) fixed it
