### ISSUE TITLE
CitizensAPI not work!

### ISSUE THREAD

**Issue by KokeCacao** [CitizensDev/Citizens2#576]
I do put [Citizens] in the plugin.yml in my own plugin. And I do use CitizensAPI when I was coding! I do put the Cityzens.jar in my server. But it still says that : 

[18:43:00] [Server thread/ERROR]: Error occurred while enabling test v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
	at com.xxxx.test.Main.onEnable(Main.java:240) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1649]
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-1649]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1649]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	... 12 more

I am using 1.7 procotal hack, and the version of Citizens.jar is 1.7.9 (load correctly)
What should I do ?

**Comment by mcmonkey4eva** [comment]
First, update your server to latest 1.8.8 if you expect support...

**Comment by KokeCacao** [comment]
Jesus, my own laptop can not support OpenGL in 1.8...
Oh, maybe I should change a new one as soon as possible...
But, thank you...
