### ISSUE TITLE
Any Solution Of "Error occurred while enabling Citizens v2.0.16-SNAPSHOT"

### ISSUE THREAD

**Issue by RIGHTXD** [CitizensDev/Citizens2#580]
[22:55:59 INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1277)
[22:55:59 ERROR]: Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1277) (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/InputStream;)V
        at net.citizensnpcs.api.util.Translator.populateDefaults(Translator.java:276) ~[?:?]
        at net.citizensnpcs.api.util.Translator.getDefaultResourceBundle(Translator.java:245) ~[?:?]
        at net.citizensnpcs.api.util.Translator.getDefaultBundle(Translator.java:65) ~[?:?]
        at net.citizensnpcs.api.util.Translator.<init>(Translator.java:43) ~[?:?]
        at net.citizensnpcs.api.util.Translator.setInstance(Translator.java:301) ~[?:?]
        at net.citizensnpcs.Citizens.setupTranslator(Citizens.java:398) ~[?:?]
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:258) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[craftbukkit.jar:git-Spigot-1642]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Spigot-1642]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [craftbukkit.jar:git-Spigot-1642]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [craftbukkit.jar:git-Spigot-1642]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [craftbukkit.jar:git-Spigot-1642]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [craftbukkit.jar:git-Spigot-1642]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [craftbukkit.jar:git-Spigot-1642]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [craftbukkit.jar:git-Spigot-1642]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [craftbukkit.jar:git-Spigot-1642]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [craftbukkit.jar:git-Spigot-1642]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1642]

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens for your Spigot version. Update one or downdate the other. http://wiki.citizensnpcs.co/Versions

**Comment by RIGHTXD** [comment]
I install all version one by one, but none of version are right...

**Comment by mcmonkey4eva** [comment]
Don't install all of them; install the correct one.

**Comment by RIGHTXD** [comment]
I know =.=
I just install a new version to the server
When it can't work, i change it to the other version
but none of version can work

**Comment by mcmonkey4eva** [comment]
What error does the /correct version/ give?

**Comment by RIGHTXD** [comment]
[22:55:59 INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1277)
[22:55:59 ERROR]: Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1277) (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/InputStream;)V
at net.citizensnpcs.api.util.Translator.populateDefaults(Translator.java:276) ~[?:?]
at net.citizensnpcs.api.util.Translator.getDefaultResourceBundle(Translator.java:245) ~[?:?]
at net.citizensnpcs.api.util.Translator.getDefaultBundle(Translator.java:65) ~[?:?]
at net.citizensnpcs.api.util.Translator.(Translator.java:43) ~[?:?]
at net.citizensnpcs.api.util.Translator.setInstance(Translator.java:301) ~[?:?]
at net.citizensnpcs.Citizens.setupTranslator(Citizens.java:398) ~[?:?]
at net.citizensnpcs.Citizens.onEnable(Citizens.java:258) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[craftbukkit.jar:git-Spigot-1642]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Spigot-1642]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [craftbukkit.jar:git-Spigot-1642]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [craftbukkit.jar:git-Spigot-1642]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [craftbukkit.jar:git-Spigot-1642]
at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [craftbukkit.jar:git-Spigot-1642]
at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [craftbukkit.jar:git-Spigot-1642]
at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [craftbukkit.jar:git-Spigot-1642]
at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [craftbukkit.jar:git-Spigot-1642]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [craftbukkit.jar:git-Spigot-1642]
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1642]

**Comment by mcmonkey4eva** [comment]
That is not the correct version.

**Comment by RIGHTXD** [comment]
if i change other version,
it will show that it is too old ( or too new)

**Comment by Fortifier42** [comment]
What exact version of spigot are you running?

**Comment by mcmonkey4eva** [comment]
Well get the one that doesn't do that. I guarantee at least one will. And it's not the version you're currently trying.

**Comment by RIGHTXD** [comment]
oh... I know what happen now... thank you...

**Comment by End3rDNZ** [comment]
Ami me sale esto :C Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1267) (Is it up to date?)

**Comment by ixRaGe** [comment]
same here the plugin just fine but it keep spamming the error
