### ISSUE TITLE
Error spam in log. (Exception during update 30)

### ISSUE THREAD

**Issue by Romuux** [CitizensDev/Citizens2#589]
Hi, 

Since any month my server is run with citizens 2 without any problem.
Since today i see massive error in my log like this :

[16:04:33] [Server thread/INFO]: [Citizens] Exception pendant la mise-à-jour 30 : no implementation set.
[16:04:33] [Server thread/WARN]: java.lang.IllegalStateException: no implementation set
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:70)
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:103)
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.trait.LookClose.findNewTarget(LookClose.java:58)
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.trait.LookClose.run(LookClose.java:98)
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:416)
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:275)
[16:04:33] [Server thread/WARN]: at net.citizensnpcs.npc.entity.EntityHumanNPC.t_(EntityHumanNPC.java:289)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.World.g(World.java:1582)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:04:33] [Server thread/WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:04:33] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)

What i have test :

Stop and restart server.
Take the LAST build of Citizens (v2.0.16-snap (build 1290)

Nothing change, any idea ?
Thank :)

**Comment by fullwall** [comment]
Looking into it.

**Comment by fullwall** [comment]
Could you please post your full log on pastie.org and link it here?

**Comment by Romuux** [comment]
Hi,

thank for your fast reply, du to size of my log the PasteBin is limited i have used my FTP for add my log on PHP files reader.

http://dark-mine.com/latest.log

Here you can see ALL part of my log, nothing touch is original file ;)

**Comment by mcmonkey4eva** [comment]
That's a pretty old build. Can you replicate on a recent one: http://ci.citizensnpcs.co/job/Citizens2/1290/ ?

**Comment by fullwall** [comment]
Please try it with build #1291 - it seems to be a problem with reloading (and possibly with another plugin). Looks like the wrong CitizensAPI class is being used.

**Comment by Romuux** [comment]
I encounter a problems with my provider, I can not restarted my server ...
I would give you the result with the new version of "Citizens" as soon as my server is online.

**Comment by Romuux** [comment]
Hi , i'm finally back for news, so i have finally access to my server , i have use the version :
http://ci.citizensnpcs.co/job/Citizens2/1291/

All is now work and no spam, thank to all for your help !
