### ISSUE TITLE
???Citizens + Multiverse Clash???

### ISSUE THREAD

**Issue by Jadeng47** [CitizensDev/Citizens2#595]
This Error Keeps appearing on My console: Plz at least tell me if I need to open a ticket at multiverse.

12:14:25 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:385) [Citizens.jar:?]
	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:411) [Citizens.jar:?]
	at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:1022) [sentry.jar:?]
	at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:128) [sentry.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:235) [Citizens.jar:?]
	at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128) [Citizens.jar:?]
	at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179) [Citizens.jar:?]
	at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32) [Citizens.jar:?]
	at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:222) [Citizens.jar:?]
	at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:118) [Citizens.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:680) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [minecraft_server.jar:git-Bukkit-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-Bukkit-18fbb24]
	... 22 more
[12:14:25 ERROR]: Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [minecraft_server.jar:git-Bukkit-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:385) [Citizens.jar:?]
	at net.citizensnpcs.api.npc.AbstractNPC.teleport(AbstractNPC.java:411) [Citizens.jar:?]
	at net.citizensnpcs.api.ai.TeleportStuckAction.run(TeleportStuckAction.java:40) [Citizens.jar:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:234) [Citizens.jar:?]
	at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:139) [Citizens.jar:?]
	at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268) [Citizens.jar:?]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.t_(EntityHumanNPC.java:339) [Citizens.jar:?]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1420) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1398) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1269) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:560) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:727) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [minecraft_server.jar:git-Bukkit-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [minecraft_server.jar:git-Bukkit-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-Bukkit-18fbb24]
	... 21 more

Thank You For Reading

**Comment by Fortifier42** [comment]
Yeah thats a Multiverse error.

> Caused by: java.lang.NullPointerException at
> com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198) ~[?:?]
