### ISSUE TITLE
Fatal error when creating an NPC?

### ISSUE THREAD

**Issue by cjunekim** [CitizensDev/Citizens2#601]
Have a look at the following error in the client side. I don't see any error on the server's log.

The steps I took to produce the following were: (w/ MC 1.8.8 and 1.8.9)

1) In a clean setup, started the most recent spigot : CraftBukkit version git-Spigot-db6de12-07c3001 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) and the most recent Citizens v2.0.16-SNAPSHOT (build 1297)
2) entered the following to the chat line : /npc create superman
3) see the error on the client side log:

In addition to that, after some NPC operations, when I login to a world with NPCs, I see the same errors on the client side.

[21:31:09] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_66]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_66]
    at g.a(SourceFile:45) [1.8.9.jar:?]
    at ave.av(SourceFile:881) [1.8.9.jar:?]
    at ave.a(SourceFile:325) [1.8.9.jar:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at bcy.a(SourceFile:301) ~[1.8.9.jar:?]
    at fp.a(SourceFile:75) ~[1.8.9.jar:?]
    at fp.a(SourceFile:16) ~[1.8.9.jar:?]
    at fh$1.run(SourceFile:13) ~[1.8.9.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_66]
    at g.a(SourceFile:44) ~[1.8.9.jar:?]
    ... 11 more

**Comment by fullwall** [comment]
Are you running a modded client? It's hard to debug client errors as they are obfuscated.

**Comment by fullwall** [comment]
Seems to be related to the tab list.

**Comment by cjunekim** [comment]
I am running a vanilla client, without any mods.

**Comment by seema84** [comment]
yes, thats the same null error as the tablist problem

**Comment by mcmonkey4eva** [comment]
@seema84 because we have no equipment at all for dealing with clientside issues. We don't touch the client in our work. And the client is an obfuscated mess of overcomplicated code.
Combine that with the lead dev being much too busy to try to learn how to deal with that mess just to solve this one issue that not many people have had...

**Comment by mcmonkey4eva** [comment]
Redirect this issue to #1360
