### ISSUE TITLE
asynchronous entity remove error

### ISSUE THREAD

**Issue by sami37** [CitizensDev/Citizens2#603]
Hello everyone,

I am coming today because i got little problem with my plugin.
I am making a simple buy/tp/sell plugin for bodyguard citizens/sentry plugin.

I do successfull what i need but, i got confronted to a little problem when a player buy a bodyguard then sell then rebuy. The problem is when player set skin on NPC after the buy method.
I has create a gui where player can do the action with 3 buttons Buy / Tp / Sell.
Step 1 :If player Buy a bodyguard a type a name into chat, the plugin put the skin of the typed player name.
Step 2 : Next if the same player sell him bodyguard and redo step 1 it give me an error and skin is not apply.

Error code :
```
[16:53:39] [Async Chat Thread - #0/WARN]: java.lang.IllegalStateException: Asynchronous entity remove!
[16:53:39] [Async Chat Thread - #0/WARN]:     at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.minecraft.server.v1_8_R3.World.removeEntity(World.java:1116)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:527)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.citizensnpcs.npc.entity.HumanController.remove(HumanController.java:134)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:87)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:127)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.citizensnpcs.npc.skin.SkinPacketTracker.notifySkinChange(SkinPacketTracker.java:99)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.citizensnpcs.npc.entity.EntityHumanNPC.setSkinName(EntityHumanNPC.java:301)
[16:53:39] [Async Chat Thread - #0/WARN]:     at com.DarkMine.PNJGui.PNJGui.skin(PNJGui.java:215)
[16:53:39] [Async Chat Thread - #0/WARN]:     at com.DarkMine.PNJGui.PNJGui.onPlayerChat(PNJGui.java:236)
[16:53:39] [Async Chat Thread - #0/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:53:39] [Async Chat Thread - #0/WARN]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at java.lang.reflect.Method.invoke(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:53:39] [Async Chat Thread - #0/WARN]:     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:53:39] [Async Chat Thread - #0/WARN]:     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:53:39] [Async Chat Thread - #0/WARN]:     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022)
[16:53:39] [Async Chat Thread - #0/WARN]:     at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[16:53:39] [Async Chat Thread - #0/WARN]:     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at java.util.concurrent.FutureTask.run(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:53:39] [Async Chat Thread - #0/WARN]:     at java.lang.Thread.run(Unknown Source)
```

Skin code :
```
public void skin(NPC npc, String name, Player player) {
        String skinName = name;
        try{
            player.sendMessage(String.format("The name : ' %s ' has been set to your bodyguard", name));
            npc.data().set(NPC.PLAYER_SKIN_UUID_METADATA, name);
        } catch (Exception e) {
            player.sendMessage(String.format("The name : ' %s ' has not been resolved. Your skin has been set to your bodyguard", player.getName()));
            npc.data().set(NPC.PLAYER_SKIN_UUID_METADATA, player.getName());
        }
        npc.data().set(NPC.PLAYER_SKIN_USE_LATEST, false);
        if (npc.isSpawned()) {
            SkinnableEntity skinnable = NMS.getSkinnable(npc.getEntity());
            if (skinnable != null) {
Line 215                skinnable.setSkinName(skinName);
            }
        }else {
            Location loc = new Location(player.getWorld(), player.getLocation().getBlockX(), player.getLocation().getBlockY(), player.getLocation().getBlockZ());
            npc.spawn(loc);
            SkinnableEntity skinnable = NMS.getSkinnable(npc.getEntity());
            if (skinnable != null) {
                skinnable.setSkinName(skinName);          
            }
        }
    }
```
Line 215 :
skinnable.setSkinName(skinName);
onPlayerChat code :

```
   @EventHandler
    public void onPlayerChat(AsyncPlayerChatEvent evt){
        Player player = evt.getPlayer();
          if (MyList.contains(player.getUniqueId())) {
            NPCRegistry npcRegistry = CitizensAPI.getNPCRegistry();
            try {
                NPC npc = npcRegistry.getByUniqueId(AssociatedNPC.get(player.getUniqueId())); 
                if(npc != null){
                    skin(npc, evt.getMessage(), player);
                    evt.setCancelled(true);
                }
           } catch (Exception e) {
               e.printStackTrace();
          }
            MyList.remove(player.getUniqueId());
        }
    }
```
Line 236 :
skin(npc, evt.getMessage(), player);
Creating code :
```
    class SpawnNPC implements Runnable
    {
        private Player player;
     
        public SpawnNPC(Player p)
        {
            player = p;
        }
     
        public void run()
        {
			NPC spawnNPC = CitizensAPI.getNPCRegistry().createNPC(player.getType(), player.getName() + "'s bodyguard");
			spawnNPC.spawn(player.getLocation());
			spawnNPC.getTrait(Owner.class).setOwner(player.getName(), player.getUniqueId());
			spawnNPC.getTrait(SkinLayers.class);
			spawnNPC.getTrait(SentryTrait.class);
			UUID myuuid = player.getUniqueId();
	    	UUID npcuuid = spawnNPC.getUniqueId();
			player.getLocation().getBlockX();
			player.getLocation().getBlockY();
			player.getLocation().getBlockZ();
			
	    	AssociatedNPC.put(myuuid, npcuuid);
			economy.withdrawPlayer(player, BuyPrice);
			SentryInstance inst = spawnNPC.getTrait(SentryTrait.class).getInstance();
			inst.setGuardTarget(player.getName(), true);
			
			Equipment equipTrait = spawnNPC.getTrait(Equipment.class);
			ItemStack diamondsword = new ItemStack(Material.DIAMOND_SWORD, 1);
			ItemStack IRONHelmet = new ItemStack(Material.IRON_HELMET, 1);
			ItemStack IRONChest = new ItemStack(Material.IRON_CHESTPLATE, 1);
			ItemStack IRONPants = new ItemStack(Material.IRON_LEGGINGS, 1);
			ItemStack IRONBoots = new ItemStack(Material.IRON_BOOTS, 1);
			
			equipTrait.set(0, diamondsword);
			equipTrait.set(1, IRONHelmet);
			equipTrait.set(2, IRONChest);
			equipTrait.set(3, IRONPants);
			equipTrait.set(4, IRONBoots);
				
			PutInlist(player);
			
			player.sendMessage(String.format("%sPlease type a player name to get him skin to your bodyguard !", ChatColor.GREEN));
			player.sendMessage(String.format("%sYour new money amount is "+ economy.getBalance(player)+" !", ChatColor.GREEN));
       }
    } 
```
EventHandler for InventoryGui :
``` 
	@EventHandler
	public void onInventoryClick(InventoryClickEvent event) {
		if(!ChatColor.stripColor(event.getInventory().getName()).equalsIgnoreCase("Gestion guard"))
			return;
		Player player = (Player) event.getWhoClicked();
		event.setCancelled(true);

		NPCRegistry npcRegistry = CitizensAPI.getNPCRegistry();
		NPC npc = null;
        try {
   			npc = npcRegistry.getByUniqueId(AssociatedNPC.get(player.getUniqueId()));    
        } catch (Exception e) {
            e.printStackTrace();
    	}
		if(event.getCurrentItem() == null || event.getCurrentItem().getType() == Material.AIR || !event.getCurrentItem().hasItemMeta()){
			player.closeInventory();
			return;
		}
		int x, y, z;
		x = player.getLocation().getBlockX();
		y = player.getLocation().getBlockY();
		z = player.getLocation().getBlockZ();
		switch(event.getCurrentItem().getType()) {
		case DOUBLE_PLANT:
			if(economy != null)
			{
				if(economy.getBalance(player) >= BuyPrice){
					if(npc == null){
				        Bukkit.getScheduler().scheduleSyncDelayedTask(PNJGui.getPlugin(PNJGui.class), new SpawnNPC(player));
					}else
					{
						player.sendMessage(String.format("%sYou allready got bodyguard or we are not able to create new bodyguard !", ChatColor.DARK_RED));
					}
				}else{
					player.sendMessage(String.format("%sYou don't get enough money !", ChatColor.DARK_RED));					
				}
			}
			else{
				player.sendMessage(String.format("%sYou can't buy bodyguard because there is no economy !", ChatColor.DARK_RED));					
			}
			player.closeInventory();
			break;
        default:
            player.closeInventory();
            break;
        }
    }
```

Delete method:
```
class delNPC implements Runnable
{
    private NPC targetLoc;
    NPCRegistry npcRegistry = CitizensAPI.getNPCRegistry();

    public delNPC(NPC npc)
    {
        targetLoc = npc;
    }

    public void run()
    {
        targetLoc.data().remove(NPC.PLAYER_SKIN_UUID_METADATA);
        targetLoc.removeTrait(SentryTrait.class);
        targetLoc.removeTrait(SkinLayers.class);
        targetLoc.removeTrait(Owner.class);
        npcRegistry.deregister(targetLoc);
        targetLoc.destroy();
    }
}
```
I had try to use delayedtaskremove and direct remove but the result is the same, something is missing but i don't know what, any of you could help me?
The problem occur when i try to type a second time the same skin.

Thanks for any help.
Ps: sorry for my english :)

**Comment by mcmonkey4eva** [comment]
Why are you using Async code for... anything in minecraft ever?

`PlayerChatEvent` (The sync version) is a lot safer for 90% of cases. Minecraft wasn't designed for Async at all and it was a mistake for them to include it for chat imo.

You're running into one of the basic textbook problems with this setup.

**Comment by sami37** [comment]
Sorry I solved my problem using Runnable class
