### ISSUE TITLE
Citizens

### ISSUE THREAD

**Issue by Blamo27** [CitizensDev/Citizens2#642]
[Citizens] Task #361573 for Citizens v2.0.16-SNAPSHOT (build 1292) generated an exception 
java.lang.IllegalArgumentException: Cannot measure distance between world and pvpbox

> Can you fix this ?

**Comment by mcmonkey4eva** [comment]
Update to latest -> http://ci.citizensnpcs.co/job/Citizens2/

**Comment by Blamo27** [comment]
[13:09:41] [Server thread/WARN]: [Citizens] Task #2622433 for Citizens v2.0.16-SNAPSHOT (build 1303) generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and PVP

**Comment by fullwall** [comment]
Please provide the full exception

**Comment by Blamo27** [comment]
Yes

[15:19:21] [Server thread/WARN]: [Citizens] Task #3703922 for Citizens v2.0.16-SNAPSHOT (build 1303) generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and pvpbox
    at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.citizensnpcs.npc.skin.SkinPacketTracker.updateNearbyViewers(SkinPacketTracker.java:189) ~[?:?]
    at net.citizensnpcs.npc.skin.SkinPacketTracker$1.run(SkinPacketTracker.java:114) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-d3e0b6f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by fullwall** [comment]
Should be fixed in latest build?
