### ISSUE TITLE
npc right click event

### ISSUE THREAD

**Issue by dpheonix68** [CitizensDev/Citizens2#684]
using latest dev hyper merchant build 26 and citizens2 build 1319 getting this error randomly  with shops. once it happens it doesnt go away. 

[09:02:42] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.17-SNAPSHOT (build 1319)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:386) [citizens-2.0.17-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1524) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_73]
	at java.lang.Short.parseShort(Unknown Source) ~[?:1.8.0_73]
	at java.lang.Short.parseShort(Unknown Source) ~[?:1.8.0_73]
	at regalowl.hyperconomy.inventory.HItemStack.<init>(HItemStack.java:49) ~[?:?]
	at regalowl.hyperconomy.tradeobject.BasicTradeObject.getItem(BasicTradeObject.java:705) ~[?:?]
	at regalowl.hyperconomy.tradeobject.BasicTradeObject.getItemStack(BasicTradeObject.java:709) ~[?:?]
	at grokswell.hypermerchant.ShopMenu.loadPage(ShopMenu.java:192) ~[?:?]
	at grokswell.hypermerchant.ShopMenu.<init>(ShopMenu.java:115) ~[?:?]
	at grokswell.hypermerchant.HyperMerchantTrait.onRightClick(HyperMerchantTrait.java:367) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor529.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-2dc26f3-4a8818c]
	... 23 more

**Comment by fullwall** [comment]
Hyperconomy is trying to load something around item numbers and has no data instead of data for something. This is an issue with hyperconomy/hypermerchant, not citizens.

**Comment by dpheonix68** [comment]
ok good to hear. that mod hasn't been updated in 5 months so ill post error there thank you
