### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Pandaism** [CitizensDev/Citizens2#686]
Before I start, I am on build 1336, with the latest version of minecraft. I did:
NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.PLAYER, player.getDisplayName());

The error NoClassDefFoundError was found on this line of code

I also did the /npc create command in game and receive the same message by without my line code since i commented it out

===============================
code error
`[19:58:48 ERROR]: Could not pass event PlayerQuitEvent to NeverLogOff v1.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.PlayerList.disconnect(PlayerList.java:384) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1012) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.NetworkManager.handleDisconnection(NetworkManager.java:317) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:175) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:815) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.npc.EntityControllers
	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:95) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40) ~[?:?]
	at com.spigot.pandaism.nlo.Handler.LogOffHandler.onLogOff(LogOffHandler.java:42) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
	... 12 more`

/npc create error
`[19:52:08 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.npc.EntityControllers
[19:52:08 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:95)
[19:52:08 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[19:52:08 WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[19:52:08 WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:359)
[19:52:08 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:52:08 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:52:08 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:52:08 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:52:08 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[19:52:08 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[19:52:08 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[19:52:08 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[19:52:08 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:52:08 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:52:08 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:52:08 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:52:08 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
[19:52:08 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
[19:52:08 WARN]: 	at java.lang.Thread.run(Thread.java:745)`

Along with this error there is but i am assuming the citizens team is working on the potions so it's not bothering me atm
`[19:57:53 WARN]: [Citizens] Task #4 for Citizens v2.0.17-SNAPSHOT (build 1336) generated an exception
java.lang.NoSuchFieldError: LINGERING_POTION
	at net.citizensnpcs.npc.EntityControllers.<clinit>(EntityControllers.java:130) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:95) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56) ~[?:?]
	at net.citizensnpcs.Citizens$2.run(Citizens.java:296) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]`

**Comment by mcmonkey4eva** [comment]
Are you sure you're on latest Spigot build? Please update that and re-test to be sure.

**Comment by Pandaism** [comment]
Ah oh i made a stupid mistake and was several spigot version behind because I forgot to update
