### ISSUE TITLE
could not pass world unload event (from multiverse)

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#687]
`unloaded a world (with npc's in it) to test something else, and this happened when i ran "/mv remove [Adventure]"
`
Link to server log & Citizens config if relevant (using e.g. hastebin.com) 

```
[09:00:05] [Server thread/ERROR]: Could not pass event WorldUnloadEvent to Citizens v2.0.17-SNAPSHOT (build 1332)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.unloadWorld(CraftServer.java:967) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.unloadWorld(CraftServer.java:943) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorldFromBukkit(WorldManager.java:558) [Multiverse-Core-2.5%20b717.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorld(WorldManager.java:368) [Multiverse-Core-2.5%20b717.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorld(WorldManager.java:358) [Multiverse-Core-2.5%20b717.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.removeWorldFromConfig(WorldManager.java:307) [Multiverse-Core-2.5%20b717.jar:?]
	at com.onarandombox.MultiverseCore.commands.RemoveCommand.runCommand(RemoveCommand.java:36) [Multiverse-Core-2.5%20b717.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5%20b717.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5%20b717.jar:?]
	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5%20b717.jar:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:906) [Multiverse-Core-2.5%20b717.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at net.citizensnpcs.EventListen.storeForRespawn(EventListen.java:517) ~[?:?]
	at net.citizensnpcs.EventListen.onWorldUnload(EventListen.java:481) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-23e921f-8b69bdd]
	... 23 more
```
Minecraft & Citizens version if relevant
```
git-Spigot-23e921f-8b69bdd (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
Citizens version 2.0.17-SNAPSHOT (build 1332)
Multiverse-Core version 2.5-b717
Multiverse-NetherPortals version 2.5-b708
```

minor issue, but should be patched :)

**Comment by fullwall** [comment]
Fixed in latest version (when it builds).
