### ISSUE TITLE
Create Npc Error

### ISSUE THREAD

**Issue by AuthMe** [CitizensDev/Citizens2#697]
Only installed Npc Plugins, and no any change, just use command: npc create NpcName.
Server: PaperSpigot 1.9 lastest version.
Java: 8u74.
```
[10:52:03 INFO]:
>version
[10:52:06 INFO]: This server is running Paper version git-Paper-459 (MC: 1.9) (I
mplementing API version 1.9-R0.1-SNAPSHOT)
[10:52:06 INFO]: Checking version, please wait...
[10:52:09 INFO]: You are 75 version(s) behind
[11:07:42 INFO]: UUID of player Steve is 5627dd98-e6be-3c21-b8a8-e92344183641
[11:07:43 INFO]: Steve[/127.0.0.1:58157] logged in with entity id 0 at ([world]-
8.92500001192093, 85.0, 13.541345731796348)
[11:08:38 INFO]: Steve issued server command: /npc
[11:08:40 INFO]: Steve issued server command: /npc create a
[11:08:40 WARN]: java.lang.NoSuchFieldError: LINGERING_POTION
[11:08:40 WARN]:        at net.citizensnpcs.npc.EntityControllers.<clinit>(Entit
yControllers.java:130)
[11:08:40 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:95)
[11:08:40 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[11:08:40 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[11:08:40 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:376)
[11:08:40 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[11:08:40 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[11:08:40 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[11:08:40 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:08:40 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[11:08:40 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[11:08:40 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[11:08:40 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[11:08:40 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:45)
[11:08:40 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:146)
[11:08:40 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCo
mmand(CraftServer.java:662)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1367)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(Playe
rConnection.java:1179)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:5)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.
run(SourceFile:13)
[11:08:40 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:08:40 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile
:45)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(Minecr
aftServer.java:775)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(Dedica
tedServer.java:404)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(Minecr
aftServer.java:714)
[11:08:40 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(Mine
craftServer.java:613)
[11:08:40 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:08:43 INFO]: Steve issued server command: /npc
[11:08:50 INFO]: Steve issued server command: /npc create
[11:08:54 INFO]: Steve issued server command: /npc create test
[11:08:54 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.
citizensnpcs.npc.EntityControllers
[11:08:54 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:95)
[11:08:54 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[11:08:54 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[11:08:54 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:376)
[11:08:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[11:08:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[11:08:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[11:08:54 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:08:54 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[11:08:54 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[11:08:54 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[11:08:54 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[11:08:54 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:45)
[11:08:54 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:146)
[11:08:54 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCo
mmand(CraftServer.java:662)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1367)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(Playe
rConnection.java:1179)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:5)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.
run(SourceFile:13)
[11:08:54 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:08:54 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile
:45)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(Minecr
aftServer.java:775)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(Dedica
tedServer.java:404)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(Minecr
aftServer.java:714)
[11:08:54 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(Mine
craftServer.java:613)
[11:08:54 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:09:02 INFO]: Steve issued server command: /npc create test test
[11:09:02 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.
citizensnpcs.npc.EntityControllers
[11:09:02 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:95)
[11:09:02 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[11:09:02 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[11:09:02 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:376)
[11:09:02 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[11:09:02 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[11:09:02 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[11:09:02 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:09:02 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[11:09:02 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[11:09:02 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[11:09:02 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[11:09:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:45)
[11:09:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:146)
[11:09:02 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCo
mmand(CraftServer.java:662)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1367)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(Playe
rConnection.java:1179)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:5)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.
run(SourceFile:13)
[11:09:02 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:09:02 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile
:45)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(Minecr
aftServer.java:775)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(Dedica
tedServer.java:404)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(Minecr
aftServer.java:714)
[11:09:02 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(Mine
craftServer.java:613)
[11:09:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[11:09:04 INFO]: Steve issued server command: /npc create test
[11:09:04 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.
citizensnpcs.npc.EntityControllers
[11:09:04 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:95)
[11:09:04 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[11:09:04 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[11:09:04 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:376)
[11:09:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[11:09:04 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[11:09:04 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[11:09:04 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:09:04 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[11:09:04 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[11:09:04 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[11:09:04 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[11:09:04 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:45)
[11:09:04 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:146)
[11:09:04 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCo
mmand(CraftServer.java:662)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1367)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(Playe
rConnection.java:1179)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:5)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.
run(SourceFile:13)
[11:09:04 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:09:04 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile
:45)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(Minecr
aftServer.java:775)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(Dedica
tedServer.java:404)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(Minecr
aftServer.java:714)
[11:09:04 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(Mine
craftServer.java:613)
[11:09:04 WARN]:        at java.lang.Thread.run(Unknown Source)
>li
[11:09:16 INFO]: Unknown command. Type "/help" for help.
>list
[11:09:18 INFO]: There are 1/100 players online:
[11:09:18 INFO]: Steve
[11:09:19 INFO]: Steve issued server command: /npc create
[11:09:21 INFO]: Steve issued server command: /npc create a
[11:09:21 WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.
citizensnpcs.npc.EntityControllers
[11:09:21 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:95)
[11:09:21 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[11:09:21 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[11:09:21 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:376)
[11:09:21 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[11:09:21 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[11:09:21 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[11:09:21 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[11:09:21 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:152)
[11:09:21 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
[11:09:21 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:175)
[11:09:21 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[11:09:21 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:45)
[11:09:21 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:146)
[11:09:21 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCo
mmand(CraftServer.java:662)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:1367)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(Playe
rConnection.java:1179)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:45)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(Packe
tPlayInChat.java:5)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.
run(SourceFile:13)
[11:09:21 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[11:09:21 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile
:45)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(Minecr
aftServer.java:775)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(Dedica
tedServer.java:404)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(Minecr
aftServer.java:714)
[11:09:21 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(Mine
craftServer.java:613)
[11:09:21 WARN]:        at java.lang.Thread.run(Unknown Source)
>
```

**Comment by mcmonkey4eva** [comment]
Please use latest builds of (real, not paper) Spigot alongside latest Citizens builds from http://ci.citizensnpcs.co/job/Citizens2/

**Comment by AuthMe** [comment]
@mcmonkey4eva But PaperSpigot is a High performance Spigot fork, API is very same like Spigot, I think this is a bug.

**Comment by mcmonkey4eva** [comment]
@AuthMe I state again: Update to the latest builds of things for functionality.

We can't be expected to support outdated software.

**Comment by Morphan1** [comment]
@mcmonkey4eva I'm assuming since he's using illegally modified clients to play on his server (judging by the logs - Steve is most definitely not his username and the uuid next to it is v3, which implies that it is for an offline mode server (also see http://ideone.com/A28jCy)), this means he doesn't have enough money to buy the game or even a reasonable VPS that could host normal Spigot. 
Cut him some slack! He doesn't have time to deal with your "bug"s or "negligence"!

*DISCLAIMER: it's just a prank bro*

**Comment by AuthMe** [comment]
@Morphan1 So I am in the off-line testing is also illegal? What makes you think I'm not genuine users?
Besides, feedback ISSUES Is must also be genuine users? Who rules this f*cking things? You? Hehe.

**Comment by AuthMe** [comment]
@mcmonkey4eva I use lastest Citizens.

**Comment by sourcepowered** [comment]
@Morphan1 So if he is not mojang's users, he can't feedback the Issus here and just let bug go? Very funny. :)

**Comment by fullwall** [comment]
The bug is from using an incorrect version of Citizens with your Spigot version. Either downgrade Citizens or upgrade Spigot.

**Comment by mcmonkey4eva** [comment]
@sourcepowered Plugin developers for the Citizens team are the ones with `Citizens - NPCs for Bukkit! member` on the right across from their name.
