### ISSUE TITLE
Not sure whats going on

### ISSUE THREAD

**Issue by NomzHD** [CitizensDev/Citizens2#702]
[17:43:31] [Server thread/INFO]: NomzHD issued server command: /npc create test
[17:43:31] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/Packet
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:95)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:376)
[17:43:31] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:43:31] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:43:31] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:43:31] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[17:43:31] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[17:43:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:43:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:43:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[17:43:31] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:43:31] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[17:43:31] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[17:43:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:43:31] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.Packet
[17:43:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[17:43:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[17:43:31] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[17:43:31] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:43:31] [Server thread/WARN]: 	... 28 more

I have been attempting to install Citizens 2, Denizen, Quests, and Sentry to my server. My server versions is minecraft v1.8.8, and the plugins are all their most recent versions.

Another thing worth mentioning, is the installation of those four plugins has caused another unrelated plugin to cease working. RPG items v 3.3. Here is the error report for that, below, since they are related issues. 

Error occurred while enabling RPG_Items v3.3 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 1
	at think.rpgitems.data.Locale.loadLocaleStream(Locale.java:168) ~[?:?]
	at think.rpgitems.data.Locale.reloadLocales(Locale.java:146) ~[?:?]
	at think.rpgitems.data.Locale.<init>(Locale.java:68) ~[?:?]
	at think.rpgitems.data.Locale.init(Locale.java:215) ~[?:?]
	at think.rpgitems.Plugin.onEnable(Plugin.java:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [minecraft_server.jar:git-Spigot-ea179b3-6e0120a]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by mcmonkey4eva** [comment]
You must either use older plugin versions or a new server version.

**Comment by NomzHD** [comment]
Alright well I downgraded the plugin to what is listed as the appropriate version for 1.8.8. I now receive THIS error.

http://pastebin.com/rPUNfwsX

**Comment by mcmonkey4eva** [comment]
You're presently running 1.8.3, not 1.8.8
