### ISSUE TITLE
Chests size

### ISSUE THREAD

**Issue by seema84** [CitizensDev/Citizens2#730]
Spigot 1.9.2 ->

[20:36:20 ERROR]: [Citizens] An exception occurred while the trait inventory was spawning for NPC ID 70.
[20:36:20 WARN]: java.lang.IllegalArgumentException: Chests must have a size that is a multiple of 9!
[20:36:20 WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[20:36:20 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createInventory(CraftServer.java:1534)
[20:36:20 WARN]: 	at org.bukkit.Bukkit.createInventory(Bukkit.java:942)
[20:36:20 WARN]: 	at net.citizensnpcs.api.trait.trait.Inventory.onSpawn(Inventory.java:73)
[20:36:20 WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:244)
[20:36:20 WARN]: 	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:141)
[20:36:20 WARN]: 	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[20:36:20 WARN]: 	at net.citizensnpcs.Citizens$2.run(Citizens.java:296)
[20:36:20 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:36:20 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:36:20 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[20:36:20 WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[20:36:20 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[20:36:20 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[20:36:20 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Xenmai** [comment]
Can you please tell us what's causing this? From that warning I'd say you're trying to make a NPC inventory of an invalid size. If I'm not mistaken, inventories must have sizes that are a multiple of 9. So 27 works, but 30 doesn't.

**Comment by seema84** [comment]
I dont know ... i think this i a Quest NPC. After Update Spigot i get this Error.
(https://www.spigotmc.org/resources/quests.3711/)

**Comment by mcmonkey4eva** [comment]
Update to latest Citizens -> http://ci.citizensnpcs.co/job/Citizens2/ -> this was patched recently.

**Comment by seema84** [comment]
I use the latest Build #1349

**Comment by mcmonkey4eva** [comment]
... I guess the patch didn't work then.

What type of NPC was spawned to cause this error?

**Comment by seema84** [comment]
EntityHorse and Villager

**Comment by fullwall** [comment]
Fixed

**Comment by seema84** [comment]
thanks

**Comment by seema84** [comment]
pls reopen

**Comment by PsychoLynx** [comment]
Can confirm: not fixed

**Comment by fullwall** [comment]
Saves.yml?

**Comment by ThemInspectors** [comment]
I have this issue Here's my saves.yml http://pastebin.com/FLK07TFs

**Comment by ThemInspectors** [comment]
And I Believe all the NPCs that are villagers are causing it

**Comment by seema84** [comment]
I have no problems with the latest Builds now.
