### ISSUE TITLE
Duplicate Citizens Start Error 

### ISSUE THREAD

**Issue by Dy1an362** [CitizensDev/Citizens2#760]
MINECRAFT 1.8.8
CITIZENS 2.0.16-SNAPSHOT 1267
RELEVANT: leaderheads

DESCRIPTION:
Having 2 (or more) of NPCs with the same name cause non-plugin-breaking Start-up errors that are generally annoying.
```
Leaderheads configuration:
# This is the configuration file where you can change the name tags of the NPCs created by Citizens.


# Name tags of the non-player NPCs.
# The number defines the rank in the leaderboard
# These name tags can be any length

npc-name-tag:
  '1': '&6&l#{number} &b{name}'
  '2': '&6&l#{number} &b{name}'
  '3': '&6&l#{number} &b{name}'
  '4': '&6&l#{number} &b{name}'
  '5': '&6&l#{number} &b{name}'
  '6': '&6&l#{number} &b{name}'
  '7': '&6&l#{number} &b{name}'
  '8': '&6&l#{number} &b{name}'
  '9': '&6&l#{number} &b{name}'
  '10': '&6&l#{number} &b{name}'
  
# Names of the player NPC's.
# The number defines the rank in the leaderboard
# The length of these name tags is maximum 16 characters (without color codes)

player-name-tag:
  '1': ''
  '2': ''
  '3': ''
  '4': ''
  '5': ''
  '6': ''
  '7': ''
  '8': ''
  '9': ''
  '10': ''
  
# Version of the config
# Do NOT change this
config-version: 1
```
```
[01:12:32 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@10d4ee[id=3435bb75-dd30-4fa7-ac86-1167b396b4f5,name=playername,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
        at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:70) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:1) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.TileEntitySkull$3.run(TileEntitySkull.java:172) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
```

**Comment by mcmonkey4eva** [comment]
Try running this more recent version of Citizens -> http://ci.citizensnpcs.co/job/Citizens2/1308/
That error basically just says "The machine your server runs on is looking up player skins too often" either because you have too many NPCs/human skulls in use, or because you share a machine with too many other servers.
The more recent build should, if nothing else, hide the error.

**Comment by RobiRami** [comment]
I'd like to add tot this that more recent versions of Leaderheads disable the logger of this error so you won't be annoyed by it. Furthermore, Leaderheads now also uses Citizens to retreive skulls, so no more useless requests to the Mojang servers will be done.
