### ISSUE TITLE
dont work with FTB infiniti evold

### ISSUE THREAD

**Issue by GiuseppeGroth** [CitizensDev/Citizens2#796]
In this issue, please include:
```
[17:05:44] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1267)
[17:05:44] [Server thread/INFO]: Creating file: config.yml
[17:05:44] [Thread-24/WARN]: Exception in thread "Thread-24" 
[17:05:44] [Thread-24/WARN]: java.lang.NoSuchMethodError: guava10.com.google.common.io.Resources.asByteSource(Ljava/net/URL;)Lguava10/com/google/common/io/ByteSource;
[17:05:44] [Thread-24/WARN]: 	at net.citizensnpcs.api.util.Translator$SaveResource.run(Translator.java:153)
[17:05:44] [Thread-24/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:05:44] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.16-SNAPSHOT (build 1267) (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R3/CraftServer
	at net.citizensnpcs.util.Util.getMinecraftRevision(Util.java:78) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:262) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1566.UNOFFICIAL]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R3.CraftServer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:394) ~[PluginClassLoader.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1566.UNOFFICIAL]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
	... 13 more

```
http://dev.bukkit.org/bukkit-plugins/citizens/files/52-2-0-16-beta-1-for-mc-1-8-8/

FTB Inviniti evolfd 
17:10:05 CONSOLE: [INFO] This server is running Cauldron version 1.7.10-1566.UNOFFICIAL (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

can you send me please a working version from Citizens and builder pls

**Comment by mcmonkey4eva** [comment]
https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar
