### ISSUE TITLE
[BUG] Error on startup

### ISSUE THREAD

**Issue by elFlashor** [CitizensDev/Citizens2#809]
Minecraft/server version: Spigot 1.9.2
Citizens version: Citizens_v2.0.17-SNAPSHOT (build 1316)

On server startup, the following error is displayed in the console:

java.lang.Throwable: Unexpected NavigationListener add
[19:47:47 WARN]:        at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
[19:47:47 WARN]:        at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
[19:47:47 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
[19:47:47 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
[19:47:47 WARN]:        at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[19:47:47 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[19:47:47 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
[19:47:47 WARN]:        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:138)
[19:47:47 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59)
[19:47:47 WARN]:        at net.citizensnpcs.Citizens$2.run(Citizens.java:296)
[19:47:47 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:47:47 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:47:47 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[19:47:47 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:47:47 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[19:47:47 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[19:47:47 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
Update to latest relevant version: http://wiki.citizensnpcs.co/Versions

**Comment by elFlashor** [comment]
This indeed fixed the issue, thank you.
That list is very handy and would deserve to be put forward much more often!
That is the very first time I see it although I have been operating and updating Citizens for quite a long time...
