### ISSUE TITLE
Authlib

### ISSUE THREAD

**Issue by exZerry** [CitizensDev/Citizens2#835]
What is the point in connecting twice to Auth server at NMS.java
Why don't just use server's auth?

**Comment by mcmonkey4eva** [comment]
Er... where do you see that happening twice?

**Comment by exZerry** [comment]
Well right here (line 203):
URL url = HttpAuthenticationService.constantURL("https://sessionserver.mojang.com/session/minecraft/profile/"
                + UUIDTypeAdapter.fromUUID(profile.getId()));

Shouldn't it use server's auth? Because at first there comes POST request from the server, and then your plugin requests it again with GET.

**Comment by exZerry** [comment]
But the server uses the same GET request at YggdrasilMinecraftSessionService.java
`protected GameProfile fillGameProfile(GameProfile profile, boolean requireSecure) {
 try {
 URL url = HttpAuthenticationService.constantURL("..." + UUIDTypeAdapter.fromUUID(profile.getId()));
}
}`

**Comment by exZerry** [comment]
Which is why it successfully fetches profile, but it does not fetch profile properties.

**Comment by exZerry** [comment]
It receives such data from my server
{
			"id":"505b3cb2e3b5353697d32bd2960d9554","name":"ZeroTwoFour","properties":
			[
			{
				"name":"textures","value":"CgkJewoJCQkidGltZXN0YW1wIjoiMTQ2NzAzMDI0MiIsInByb2ZpbGVJZCI6IjUwNWIzY2IyZTNiNTM1MzY5N2QzMmJkMjk2MGQ5NTU0IiwicHJvZmlsZU5hbWUiOiJaZXJvVHdvRm91ciIsInRleHR1cmVzIjoKCQkJewoJCQkJCgkJICAgICAgICAiU0tJTiI6CgkJCQl7CgkJCQkJInVybCI6Imh0dHA6Ly9hcHAuZXh6ZXJyeS5jb20vbGxtYy9NaW5lY3JhZnRTa2lucy9aZXJvVHdvRm91ci5wbmciCgkJCQl9CgkJCX0KCQl9"
			}
			]
		}

And the response of a plugin is:

[15:24:05] [Server thread/WARN]: [Citizens] Task #63 for Citizens v2.0.19-SNAPSHOT (build 1374) generated an exception
java.lang.NullPointerException: data cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at net.citizensnpcs.api.npc.SimpleMetadataStore.checkPrimitive(SimpleMetadataStore.java:15) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleMetadataStore.setPersistent(SimpleMetadataStore.java:86) ~[?:?]
	at net.citizensnpcs.api.npc.AbstractNPC$1.setPersistent(AbstractNPC.java:65) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.setNPCSkinData(Skin.java:315) ~[?:?]
	at net.citizensnpcs.npc.skin.Skin.apply(Skin.java:106) ~[?:?]
	at net.citizensnpcs.npc.skin.SkinPacketTracker.updateViewer(SkinPacketTracker.java:218) ~[?:?]
	at net.citizensnpcs.npc.skin.SkinUpdateTracker$1.run(SkinUpdateTracker.java:338) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:697) [craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:646) [craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:550) [craftbukkit-1.10-R0.1-SNAPSHOT-latest.jar:git-Bukkit-9af379f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by exZerry** [comment]
Well after configuring JSON a little bit, the server does receive profile properties, but it ends up on this error:

Fetched profile 505b3cb2-e3b5-3536-97d3-2bd2960d9554 for player ZeroTwoFour
Profile lookup for player 'ZeroTwoFour' failed: Cannot contact authentication server

Although the auth server is up and running.
Skins are enabled on players, but not on citizens.

**Comment by fullwall** [comment]
I will check to see if Yggdrasil has changed - the reason we copy their GET request is because the original can silently catch an error without letting us know about it.

**Comment by fullwall** [comment]
From the sounds of things you are reimplementing Yggdrasil? It hasn't changed so there must be an error in your implementation somewhere.
