### ISSUE TITLE
Big WARN spam when i create NPC

### ISSUE THREAD

**Issue by HaloTrial** [CitizensDev/Citizens2#846]
**I use spigot 1.9 server and citizens 2.0.17 (alpha 1 for MC 1.9) (build 1316)
I create an NPC and the console writes this. (why?)**
CONSOLE:
[16:00:03 INFO]: HaloTrial issued server command: /npc create HaloTrial
[16:00:03 WARN]: java.lang.Throwable: Unexpected NavigationListener add
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
[16:00:03 WARN]:        at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
[16:00:03 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
[16:00:03 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
[16:00:03 WARN]:        at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[16:00:03 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[16:00:03 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
[16:00:03 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:407)
[16:00:03 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:00:03 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:00:03 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:00:03 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:00:03 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[16:00:03 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[16:00:03 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[16:00:03 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[16:00:03 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:00:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:00:03 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[16:00:03 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:00:03 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[16:00:03 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[16:00:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:00:05 WARN]: java.lang.Throwable: Unexpected NavigationListener add
[16:00:05 WARN]:        at net.minecraft.server.v1_9_R1.NavigationListener.a(NavigationListener.java:16)
[16:00:05 WARN]:        at net.citizensnpcs.util.nms.PlayerNavigation.<init>(PlayerNavigation.java:51)
[16:00:05 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.initialise(EntityHumanNPC.java:261)
[16:00:05 WARN]:        at net.citizensnpcs.npc.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:84)
[16:00:05 WARN]:        at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:82)
[16:00:05 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:35)
[16:00:05 WARN]:        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:192)
[16:00:05 WARN]:        at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:128)
[16:00:05 WARN]:        at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:179)
[16:00:05 WARN]:        at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32)
[16:00:05 WARN]:        at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:222)
[16:00:05 WARN]:        at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:118)
[16:00:05 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:00:05 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[16:00:05 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[16:00:05 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:00:05 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[16:00:05 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[16:00:05 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by mcmonkey4eva** [comment]
YOu're running an older build for 1.9, you can grab a more recent one off of http://wiki.citizensnpcs.co/Versions
