### ISSUE TITLE
ShulkerBullet Cast Exception

### ISSUE THREAD

**Issue by Cutiemango** [CitizensDev/Citizens2#872]
I used /npc type Shulker_bullet command, and it poped out these errors.

[19:32:18] [Server thread/WARN]: java.lang.ClassCastException: net.citizensnpcs.npc.entity.nonliving.ShulkerBulletController$ShulkerBulletNPC cannot be cast to org.bukkit.entity.Arrow
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.nonliving.ShulkerBulletController.getBukkitEntity(ShulkerBulletController.java:27)
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.entity.nonliving.ShulkerBulletController.getBukkitEntity(ShulkerBulletController.java:20)
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.getEntity(CitizensNPC.java:115)
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:197)
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.setEntityController(CitizensNPC.java:173)
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.setBukkitEntityType(CitizensNPC.java:160)
[19:32:18] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.type(NPCCommands.java:1847)
... more

Spigot version: 1.10.2
Citizens version: Citizens v2.0.19-SNAPSHOT (build 1374)

**Comment by fullwall** [comment]
Fixed
