### ISSUE TITLE
ConcurrentException :v

### ISSUE THREAD

**Issue by alekso56** [CitizensDev/Citizens2#896]
Bug report:
[19:18:25 WARN]: [Citizens] Task #2117 for Citizens v2.0.19-SNAPSHOT (build 1374) generated an exception
net.minecraft.server.v1_10_R1.ReportedException: Ticking player
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_101]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.EntityTracker.a(EntityTracker.java:207) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.EntityPlayer.F(EntityPlayer.java:1107) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.EntityLiving.tickPotionEffects(EntityLiving.java:554) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.citizensnpcs.npc.entity.EntityHumanNPC.m(EntityHumanNPC.java:283) ~[?:?]
        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.World.g(World.java:1604) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:51) ~[?:?]
        ... 7 more

This also happens in the newest build, except the server crashes completely
This server is running CraftBukkit version git-Spigot-1e4dd71-5e5cf84 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by fullwall** [comment]
Does the latest build help?

**Comment by alekso56** [comment]
[17:56:19] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:794) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_101]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_101]
	at net.minecraft.server.v1_10_R1.EntityTracker.a(EntityTracker.java:253) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.PlayerChunk.b(PlayerChunk.java:138) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.PlayerChunkMap.flush(PlayerChunkMap.java:188) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:257) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:783) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	... 4 more
[17:56:19] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_101]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_101]
	at net.minecraft.server.v1_10_R1.EntityTracker.a(EntityTracker.java:253) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.PlayerChunk.b(PlayerChunk.java:138) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.PlayerChunkMap.flush(PlayerChunkMap.java:188) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:257) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:783) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by fullwall** [comment]
I think this is related to another plugin, not Citizens.
