### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tymop** [CitizensDev/Citizens2#916]
Hello, this is a Bug report
Versions:
Minecraft : 1.10.2
Spigot : git-Spigot-f9671b8-48b88ed (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

this is an error which appears when a user try to create a NPC :+1: 

```
[01:15:35 INFO]: tymop issued server command: /npc create Garde_1 --trait sentry
[01:15:35 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/World
[01:15:35 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[01:15:35 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
[01:15:35 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:110)
[01:15:35 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:468)
[01:15:35 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:15:35 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:15:35 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:15:35 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:15:35 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[01:15:35 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[01:15:35 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[01:15:35 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
[01:15:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[01:15:35 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[01:15:35 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[01:15:35 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:15:35 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[01:15:35 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[01:15:35 WARN]:        at java.lang.Thread.run(Thread.java:745)
[01:15:35 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.World
[01:15:35 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[01:15:35 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[01:15:35 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[01:15:35 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[01:15:35 WARN]:        ... 28 more
```

**Comment by DevIPv2** [comment]
Downgrade the plug-in

**Comment by willies952002** [comment]
```
[01:15:35 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/World
[01:15:35 WARN]:        at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
[01:15:35 WARN]:        at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
...
```
For starters, these kind of errors are meant to happen. It prevents code written for older versions of minecraft, where the mappings were different, from executing with unknown outcomes.

Secondly, this isn't a Citizens 2 bug.

After some research and seeing who was developing the plugin that was having the issue, I would recommend looking into getting [this](https://github.com/mcmonkey4eva/Sentinel/) (recommended [here](https://github.com/mcmonkey4eva/Sentry/blob/master/README.md))

**Comment by tymop** [comment]
Thanks a lot.
Sorry for the bug report which is not on your side.


2016-09-11 5:15 GMT+02:00 mcmonkey <notifications@github.com>:

**Comment by DevIPv2** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/83b4761f7a",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Sepp is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
