### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Kurimatzu** [CitizensDev/Citizens2#917]
[10:11:22 INFO]: [Citizens] Exception while updating 79: null.

[10:11:22 WARN](java.lang.NullPointerException):        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:278)
[10:11:22 WARN](java.lang.NullPointerException):        at net.citizensnpcs.nms.v1_10_R1.entity.EntityHumanNPC.m(EntityHumanNPC.java:309)
[10:11:22 WARN](java.lang.NullPointerException):        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1738)
[10:11:22 WARN](java.lang.NullPointerException):        at net.minecraft.server.v1_10_R1.World.g(World.java:1713)
[10:11:22 WARN](java.lang.NullPointerException):        at net.citizensnpcs.nms.v1_10_R1.util.NMSImpl.tick(NMSImpl.java:835)
[10:11:22 WARN](java.lang.NullPointerException):        at net.citizensnpcs.util.NMS.tick(NMS.java:246)
[10:11:22 WARN](java.lang.NullPointerException):        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[10:11:22 WARN](java.lang.NullPointerException):        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[10:11:22 WARN](java.lang.NullPointerException):        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[10:11:22 WARN](java.lang.NullPointerException):        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:781)
[10:11:22 WARN](java.lang.NullPointerException):        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[10:11:22 WARN](java.lang.NullPointerException):        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[10:11:22 WARN](java.lang.NullPointerException):        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[10:11:22 WARN](java.lang.NullPointerException):        at java.lang.Thread.run(Unknown Source)

Minecraft 1.1.0 + Citizens Last version

**Comment by fullwall** [comment]
Can you try with the latest version? That stack trace seems old.
