### ISSUE TITLE
EntityDamageByEntity Event

### ISSUE THREAD

**Issue by tharvoil** [CitizensDev/Citizens2#927]
I'm seeing this spammed repeatedly in my console, it seems to be when my "guards" are attacked by skeletons. Running build 1417 and spigot 1.10.2.

```
29.09 18:29:51 [Server] ERROR Could not pass event EntityDamageByEntityEvent to Citizens v2.0.20-SNAPSHOT (build 1417)
29.09 18:29:51 [Server] INFO ... 24 more
29.09 18:29:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
29.09 18:29:51 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
29.09 18:29:51 [Server] INFO at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
29.09 18:29:51 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.whenAttacksHappened(SentinelTrait.java:289) ~[?:?]
29.09 18:29:51 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_10_R1.entity.CraftArrow cannot be cast to org.bukkit.entity.LivingEntity
29.09 18:29:51 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:799) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.World.g(World.java:1604) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1629) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityTippedArrow.m(EntityTippedArrow.java:68) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityArrow.m(EntityArrow.java:193) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityArrow.a(EntityArrow.java:285) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityPlayer.damageEntity(EntityPlayer.java:500) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity(EntityHuman.java:772) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityHuman.damageEntity0(EntityHuman.java:847) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1238) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:604) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:572) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_latest.jar:git-Spigot-570526c-75a8885]
29.09 18:29:51 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_latest.jar:git-Spigot-570526c-75a8885]
```

**Comment by mcmonkey4eva** [comment]
Update Sentinel: http://ci.citizensnpcs.co/job/Sentinel/

if the error persists after an update, report to https://github.com/mcmonkey4eva/Sentinel/issues
