### ISSUE TITLE
Citizens 2 on a MCPC Plus forge bukkit server

### ISSUE THREAD

**Issue by Angelimar** [CitizensDev/Citizens2#958]
Hey guys please help me with my issue i have a movie to do and i installed animated horses mod for server on ----> mcpc plus 1.7.2 - R0.3 - forge 1022 <---- server.
1. I tried installing 2.0.11 alpha 1 for mc 1.7.2 

[https://dev.bukkit.org/bukkit-plugins/citizens/files/39-2-0-11-alpha-1-for-mc-1-7-2/](url)

2 then i tried installing 2.0.11 alpha 2 for mc. 1.7.2 

[https://dev.bukkit.org/bukkit-plugins/citizens/files/40-2-0-11-alpha-2-for-mc-1-7-2/](url)

3 and finally tried installing 2.0.11 for mc 1.7.x 

[https://dev.bukkit.org/bukkit-plugins/citizens/files/41-2-0-11-for-mc-1-7-x/](url)

Yes i have both java 8 and java 7 installed and running properly.
Every time i joined the server and typed the -->  /npc create John <-- command i got this message 

--> Please report this error (see console)
 java.lang.NoClassDefFoundError: 
org/bukkit/craftbukkit/v1.7_R1/CraftWorld <---

And the error in the console looks like this:

[18:16:26] [Server thread/INFO]: Angelimar issued server command: /npc create John
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R1/CraftWorld
        at net.citizensnpcs.npc.entity.HumanController.createEntity(HumanController.java:28)
        at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:36)
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:161)
        at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:360)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
        at net.citizensnpcs.Citizens.onCommand(Citizens.java:246)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:199)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:546)
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1313)
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1129)
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:78)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:207)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:966)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:416)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:796)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:660)
        at java.lang.Thread.run(Unknown Source)

Guys please help me i beg you!

**Comment by mcmonkey4eva** [comment]
If you switch to MCPC 1.7.10, we got https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar available. Otherwise, not able to run it.

**Comment by Morphan1** [comment]
Alternatively, if you can't switch to 1.7.10, we got https://www.dropbox.com/s/mcm7g1gmyb6f820/citizens-2.0.11-1.7.2-Cauldron-B1.jar available.

Remember both of these builds are unofficial and that we don't offer support for them.

**Comment by Angelimar** [comment]
None of the solutions worked for me but thank you for help guys.
