### ISSUE TITLE
Spigot 1.11 crash with citizens 2.0.21-SNAPSHOT (build 1425)

### ISSUE THREAD

**Issue by Capri205** [CitizensDev/Citizens2#970]
Hi. Upgraded our server today which has 18 NPC's, but the server crashes when you move into a chunk that contains an NPC or goes into an endless error loop when interacting with existing NPC's. At the moment as soon as we join the server it crashes immediately because the last place we were was next to an NPC. Server works fine if we remove the saves.yml and create entirely new NPC's, but will not work with our existing saves.yml. I have tried creating a new config and then putting back the saves.yml also, but no luck.

Can you confirm if there's any work we need to do on existing saves.yml for this to work?

Using latest spigot build: This server is running CraftBukkit version git-Spigot-16c940b-eed13ca (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[16:03:08] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.21-SNAPSHOT (build 1425)

Thanks

`[15:44:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking player
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.l(PlayerNavigation.java:427) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.updateNavigation(NMSImpl.java:1341) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:129) ~[?:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1652) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.World.g(World.java:1627) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.WorldServer.l(WorldServer.java:658) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1421) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        ... 4 more
[15:44:21] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at net.citizensnpcs.nms.v1_11_R1.util.PlayerNavigation.l(PlayerNavigation.java:427) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.updateNavigation(NMSImpl.java:1341) ~[?:?]
        at net.citizensnpcs.nms.v1_11_R1.entity.EntityHumanNPC.A_(EntityHumanNPC.java:129) ~[?:?]
        at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1652) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.World.g(World.java:1627) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.WorldServer.l(WorldServer.java:658) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1421) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[15:44:21] [Server thread/ERROR]: This crash report has been saved to: Minecraft/./crash-reports/crash-2016-11-19_15.44.21-server.txt
`

**Comment by mcmonkey4eva** [comment]
There might be an error with MOVING NPCs - there definitely was one in the first few builds of Citizens for 1.11...

**Comment by Capri205** [comment]
Yes. The ones with a path seems to be the problem. If I restore the saves.yml from a backup and get the server to start clean, then I can approach a moving NPC but as soon as I interact with it the plugin generates endless errors liket his in the log:

`[16:50:05] [Server thread/WARN]: [Citizens] Task #50 for Citizens v2.0.21-SNAPSHOT (build 1425) generated an exception
net.minecraft.server.v1_11_R1.ReportedException: Ticking player
        at net.citizensnpcs.nms.v1_11_R1.util.NMSImpl.tick(NMSImpl.java:881) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:253) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-eed13ca]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
[16:50:05] [Server thread/INFO]: Negative index in crash report handler (0/10)
`

**Comment by fullwall** [comment]
Latest build should fix this.

**Comment by Capri205** [comment]
That has indeed fixed the problem. Thanks for the quick turnaround. Greatly appreciated.
