### ISSUE TITLE
Villager NPCs crashing the server

### ISSUE THREAD

**Issue by Brokkonaut** [CitizensDev/Citizens2#972]
When I have at least one villager NPC the next next chunkloading that tries to load some villagers crashes the server:

`[02:38:45 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
        at net.minecraft.server.v1_11_R1.EntityVillager$1.a(EntityVillager.java:194) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.c(SourceFile:62) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:40) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.TileEntityMobSpawner$2.a(SourceFile:63) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.c(SourceFile:62) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:40) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.ChunkRegionLoader$1.a(ChunkRegionLoader.java:267) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.c(SourceFile:62) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:40) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.DataConverterManager.a(SourceFile:33) ~[patched_1.11.jar:git-Paper-925]
        at net.minecraft.server.v1_11_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:88) ~[patched_1.11.jar:git-Paper-925]
        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:23) ~[patched_1.11.jar:git-Paper-925]
        at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:16) ~[patched_1.11.jar:git-Paper-925]
        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150) ~[patched_1.11.jar:git-Paper-925]
        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95) ~[patched_1.11.jar:git-Paper-925]
        at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85) ~[patched_1.11.jar:git-Paper-925]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

We did some investigation and found out that the reason is, that EntityList.getKey(EntityVillager.class) is null. Somehow the citizens plugin is breaking that data.

CItizens: Citizens v2.0.21-SNAPSHOT (build 1426)
Paper: git-Paper-925 (MC: 1.11)

**Comment by fullwall** [comment]
It seems like from your stacktrace that this is a Villager mob spawner that has a bad NBTTagCompound? Not sure where you're getting EntityList.getKey from as I have been unable to find it in the code.

This is the relevant code:
`if ((EntityTypes.getName(EntityVillager.class).equals(new MinecraftKey(nbttagcompound.getString("id")))) && (nbttagcompound.hasKeyOfType("Offers", 10)))`

I have verified that EntityTypes.getName does not return null so the mob spawner's NBTTagCompound is null. As to why that is it could be Citizens, it could be a corrupted file - I have been unable to reproduce this. If you could get a list of steps to make the corrupted mob spawner that would be great.

**Comment by Lbleu** [comment]
Same Citizens and paper version here, if I have any NPC with the villager type whenever I move around the map and generate a new chunk it crashes the server. 
After crashing, if I try to log in again without deleting player data from the world folder it will crash the server everytime I try to log in.

**Comment by Brokkonaut** [comment]
No we tested that. I had a custom build to check what is null and it was EntityTypes.getName(EntityVillager.class) (sorry, I mistyped it in the first post), not nbttagcompound.

This was the change that stopped the server from crashing: https://gist.github.com/Zbob750/ec18b998bbefadce4e90658283fadda3

Without Citizens i can run the server without crashes and with citizens it crashed immediately. I could reproduce the crashes on a test server with a map generated in 1.10 where I had just the citizens plugin, created one villager citizen and one normal villager (using /summon) in 1.10, then updated the server and citizens to 1.11 and the server immediately crashes when it tries to load the chunk. 

When i generate a new map in 1.11 it does not crash - probably because it does not want to convert anything.

Two more stacktraces from my testing (with just the citizens plugin, nothing else:
http://pastebin.com/raw/tLBeQ24j
http://pastebin.com/raw/bbbRshp0`

**Comment by fullwall** [comment]
Hmmm... I think it must be to do with the initial upgrade process from 1.10 to 1.11.

**Comment by Brokkonaut** [comment]
I have no idea, I don't know that much about the servers internals to say what exactly goes wrong, but I created a test file: http://www.mediafire.com/file/4tkg4g1arkp7tlf/Villager.zip
This includes Citizens build 1426 + a configuration with a villager npc and a player npc and a world generated in 1.10. Start a server with this (tested with recent spigot and paper), join the server and walk a bit around until the server crashes..
If you remove the citizens plugin you can start the server and walk around without any crashes.

**Comment by fullwall** [comment]
Thanks, I'll take a look.

**Comment by fullwall** [comment]
Try latest build.

**Comment by Brokkonaut** [comment]
Thanks, we had no more crashes since the update, so I think it works :)
