### ISSUE TITLE
Right Click on NPC generates error

### ISSUE THREAD

**Issue by brooklynstarr** [CitizensDev/Citizens2#995]
Currently using Minecraft 1.11. Tried both Paper and Spigot. Today's update generated an error where I can no longer right click on my shop npc's. Also fails with blacksmith and any other NPC's for that matter. I tried to go back several builds (both Citizens and Spigot) and the error still persists, and I only updated Spigot & Citizens.

Seems like updating permanently broke something. I also tried using a developmental version of Denizens. I cannot use my shop keepers.

Here is a copy of the error:

[22:34:39] [Server thread/ERROR]: Could not pass event NPCRightClickEvent to Citizens v2.0.21-SNAPSHOT (build 1445)
org.bukkit.event.EventException
	at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:80) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.jar:git-Paper-953]
	at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414) [citizens-2.0.21-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:63) [MassiveLag.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1556) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-953]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-953]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_111]
	at java.lang.Short.parseShort(Unknown Source) ~[?:1.8.0_111]
	at java.lang.Short.parseShort(Unknown Source) ~[?:1.8.0_111]
	at regalowl.hyperconomy.inventory.HItemStack.<init>(HItemStack.java:49) ~[?:?]
	at regalowl.hyperconomy.tradeobject.BasicTradeObject.getItem(BasicTradeObject.java:718) ~[?:?]
	at regalowl.hyperconomy.tradeobject.BasicTradeObject.getItemStack(BasicTradeObject.java:722) ~[?:?]
	at grokswell.hypermerchant.ShopMenu.loadPage(ShopMenu.java:193) ~[?:?]
	at grokswell.hypermerchant.ShopMenu.<init>(ShopMenu.java:116) ~[?:?]
	at grokswell.hypermerchant.HyperMerchantTrait.onRightClick(HyperMerchantTrait.java:366) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:63) ~[?:?]
	... 24 more

**Comment by mcmonkey4eva** [comment]
That's a HyperMerchant/HyperConomy error.
You'll have to contact them about that one.

**Comment by brooklynstarr** [comment]
I get the same when it errors out on blacksmith as well.. OK. Tried non hypermerchants and interestingly only one worked.. she sells flowers. Non hypermerchants seem to work. OK, will work in that direction. Thanks.

**Comment by brooklynstarr** [comment]
OK.. I updated Hyperconomy one . version from .975.6 to .975.7. Also had to restore the db from a backup. Now blacksmith works and a few more shopkeeper npc's, but not all of them. I suspect it might have to do with what the seller is selling, so I'll investigate in that direction. You can go ahead and close this- appreciate the help, now I'm off in the right direction.

**Comment by brooklynstarr** [comment]
Hi, just wanted to FYI this, the latest build of HyperMerchant permanently fixed this annoying issue.

Thanks.
